### ISSUE TITLE
Provide a way to provide build scripts for unsupported distros

### ISSUE THREAD

**Issue by madsl** [systemd/mkosi#101]
It would be awesome if mkosi could be made distribution agnostic! What if there were a distro option called "custom"? So that when invoking mkosi with an option like "--distribution=custom", you have to add some mandatory options like e.g. --image-devel-script and --image-final-script which both points to scripts that does the caching and package managing manually?

I just stumbled upon this project, so I do not yet have a full overview how many steps that would need to have a custom script to make this work. I just thought I should throw this suggestion out to get any input before trying to create a patch :)

**Comment by luntik2012** [comment]
also, please, provide a way to remove system from the internet

**Comment by fsateler** [comment]
Why not simply add support for your distro to mkosi?

**Comment by madsl** [comment]
Lennart has already added most of the distributions already that has a straight-forward predefined way to install a base system, but not all distributions are like that. The use case might be doing something custom with yocto or buildroot, maybe OpenWRT, or even Gentoo. To code support for all these different ways of putting together a distro seems futile, so a better solution might be to provide a easy way to hook in scripts so you can define these targets yourself...

**Comment by poettering** [comment]
so what about this: if a distribution is selected that we do not know about right now, we look for a file `mkosi.distribution-<name>` in the local directory, and if it exists and is executable we invoke that for installing the distribution.

That said, I think add support for better known distros such as yocto or Gentoo directly would make a ton of sense, hence I'd suggest to submit patches for them directly.

**Comment by madsl** [comment]
The mkosi.distribution-<name> solutions sounds perfect!

I agree that it would be best to have proper distro support in mkosi too, but I guess that'll we have a lot of bikeshedding before us if mkosi should be made aware of all the sets of config files needed to build images for source based distros...

I think the best way is to begin with the mkosi.distribution-<name>-solution anyway, the scripts needed to add support that way could be a base for further support work! I'll make sure to share my scripts in that regard at least :)

**Comment by dteleguin** [comment]
Hi Lennart @poettering, are you interested in Mageia Linux support?

We are nearing Mageia 6 release now, with one of its highlights being native DNF support out of the box. Hence, the process shouldn't be much different for Fedora. However, we have systemd 230. Will mkosi operation still be possible, maybe in some limited manner?

If positive, I can contribute a patch for mkosi + Mageia RPM package.

**Comment by lucaswerkmeister** [comment]
@dteleguin mkosi v2+ requires systemd v233+ for systemd-nspawn’s `--overlay=+…::…` feature (see #88; introduced in cd2f1519e52d1279f65b24cf59fb6b1dcaeba8f2).

**Comment by dteleguin** [comment]
@lucaswerkmeister seems like `--overlay=...` option is activated if and only if the ReadOnly mode is chosen. I think we can safely add support for Mageia - anyway, mkosi will be included into Mageia in the next stable release only.

On Mageia 6 (stable), mkosi will still work with a non-critical limitation (no support for ReadOnly).

**Comment by dteleguin** [comment]
Also I think we can emulate `--overlay=+...::...` with `mkdir` + `mount -t overlay` + `rmdir`, but I think it's an overkill.

**Comment by poettering** [comment]
@dteleguin i figure adding support for generating mageia images would be good to have. The less intrusive the patch the more welcome it is though ;-)

Maybe in the long run we should split out all per-distro support into separate .py files, to keep the per-distro hacks in the main program minimal.

**Comment by dteleguin** [comment]
@poettering #112 
It's truly minimal and mostly copypaste. Though I hate copypaste, I didn't dare to start refactoring :) but I'm afraid we'll have to face it sooner or later, especially when adding CentOS (which is IMHO way more popular in the cloud than Fedora). The code is almost identical, with the exception of repositories configuration, package list, GPG keys handling etc. Remember this comment, one day we'll come up with classes & inheritance & other OOP stuff :)

**Comment by DaanDeMeyer** [comment]
We have `--distribution=none` support now, in which case the rootfs has to be populated via the `SkeletonTrees=` or `BaseTrees=` settings, or via a prepare script, so let's close this issue.
