### ISSUE TITLE
Drop CentOS 7 support?

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#1041]
We have quite a bit of custom code to deal with CentOS 7 because it doesn't support systemd-boot/systemd-stub. Do we want to support it until it's EOL? It's trivial to run mkosi from source so users that still need centos 7 can always clone the repo and checkout the version 13 branch in order to still be able to build centos 7 images.

**Comment by keszybz** [comment]
Dunno, I think that most of us don't care at all. I guess the one downvote above signifies that there's at least one user. I think it'd be reasonalbe to drop this if we manage to land the big refactoring. It's one thing to carry existing code, and another to reimplement it.

**Comment by keszybz** [comment]
Done in #1152.
