### ISSUE TITLE
Allow running qemu as an unprivileged user

### ISSUE THREAD

**Issue by jre21** [systemd/mkosi#1076]
The man page suggests that `mkosi qemu` can be run as an unprivileged user under some circumstances:

> This command must be executed as root unless the image already exists and -f is not specified.

but in practice mkosi's [sudo check](https://github.com/systemd/mkosi/blob/e2681d2adbaabe1065f7cff307368d0ff0d69bb5/mkosi/__init__.py#L126) prevents this.

On my machine (Arch Linux with Wayland/Sway), qemu fails to start if invoked through sudo (with the message `Authorization required, but no authorization protocol specified`), but after removing `Verb.qemu` from the sudo check in a local checkout of the source code I was able to build an image (as root) and run it with `mkosi qemu` as my normal user.  There are clearly limitations in running qemu as an unprivileged user (setting up netdev requires root, for example), but it seems to be working well enough that I'd prefer if the qemu verb were removed from the sudo check.

I only discovered mkosi a few days ago and had never delved very deeply into qemu's workings beforehand, so it's quite possible there are potential dangers with this setup I'm not aware of.  If so, I can understand the desire to limit the tool to known-working configurations.  But given the indication from the docs, I wanted to see if this was something the maintainers would be willing to enable.

**Comment by jre21** [comment]
I've sorted out the `xhost` workaround to run qemu through sudo.  I would still prefer to have the option of running without sudo when not testing features that require root privileges.

**Comment by behrmann** [comment]
It's a bit tricky, because `qemu` implies `build` if the image has not been built yet and we need root for a lot of things we do. We'll happily review patches!
