### ISSUE TITLE
Visibility into failing 'Workspace command' - kernel-install

### ISSUE THREAD

**Issue by stellarhopper** [systemd/mkosi#1079]
On some systems/configurations, I see the following error:

```
dracut: dracut: creation of /efi/440477aa75c346638759186e063f90d8/5.19.0-rc3/initrd failed
‣ Error: Workspace command kernel-install add 5.19.0-rc3 /lib/modules/5.19.0-rc3/vmlinuz returned non-zero exit code 1.
```

Interestingly, copying the vmlinuz file in the expected location under lib/modules via the skeleton tree in mkosi.extra/ worked for Fedora Workstation, but this continues to fail in Fedora server.

Is there a way (`debug=<flag>` perhaps?) to get more visibility into what it was trying to run and how it failed, or the shell output from that command or something?

**Comment by DaanDeMeyer** [comment]
We have a --debug flag. You could add a "kernel-install" option to that and add --verbose to the kernel-install call when that is set
