### ISSUE TITLE
running `# mkosi` fails on ext4 filesystem with chattr +C

### ISSUE THREAD

**Issue by erickj** [systemd/mkosi#108]
When I run `# mkosi` it fails with output:

    subprocess.CalledProcessError: Command '['chattr', '+C', '/home/erick/kvms/images/.mkosi-mzuvrf7o']' returned non-zero exit status 1

If I try to make tmp directory and run `chattr` manually I get:

    # chattr +C .mkfoo-rex28
    chattr: Operation not supported while setting flags on .mkfoo-rex28

It seems ext4 doesn't support cow (C) attribute?

    $ man ext4
       The ext2, ext3, and ext4 filesystems support setting the following file attributes  on  Linux  systems  using  the
       chattr(1) utility:

       a - append only
       A - no atime updates
       d - no dump
       D - synchronous directory updates
       i - immutable
       S - synchronous updates
       u - undeletable
       In addition, the ext3 and ext4 filesystems support the following flag:
       j - data journaling
       Finally, the ext4 filesystem also supports the following flag:
       e - extents format

Commenting out the call to `chattr +C` in the mkosi script builds an image successfully.

Context:

    02:34:56 [root@lenobot:/home/erick/kvms/images] 
    $ mount | grep /home
    /dev/sda3 on /home type ext4 (rw,relatime,seclabel,data=ordered)

    02:35:10 [root@lenobot:/home/erick/kvms/images] 
    $ rpm -q mkosi
    mkosi-1-1.fc25.noarch

    02:35:47 [root@lenobot:/home/erick/kvms/images] 
    $ mkosi
    DISTRIBUTION:
    Distribution: fedora
    Release: 25
    
    OUTPUT:
    Output Format: raw_gpt
    Output: /home/erick/kvms/images/image.raw
    Output Checksum: n/a
    Output Signature: n/a
    Output nspawn Settings: n/a
    XZ Compression: no
    
    PACKAGES:
    Packages: none
    With Documentation: no
    Package Cache: none
    Extra Trees: none
    Build Script: none
    Build Sources: /home/erick/kvms/images
    Build Packages: none
    nspawn Settings: none
    
    PARTITIONS:
    Bootable: no
    Root Partition: 1.0G
    Swap Partition: (disabled)
    ESP: (disabled)
    /home Partition: (disabled)
    /srv Partition: (disabled)
    
    VALIDATION:
    Checksum: no
    Sign: no
    GPG Key: default
    Password: default
    ‣ Detaching namespace...
    ‣ Detaching namespace complete.
    ‣ Setting up package cache...
    ‣ Setting up package cache /home/erick/kvms/images/.mkosi-y87uw8fg completed.
    ‣ Setting up temporary workspace.
    ‣ Temporary workspace in /var/tmp/mkosi-h_htd1ma is now set up.
    ‣ Creating partition table...
    Traceback (most recent call last):
    File "/bin/mkosi", line 1657, in <module>
    main()
    File "/bin/mkosi", line 1653, in main
    build_stuff(args)
    File "/bin/mkosi", line 1613, in build_stuff
    raw, tar = build_image(args, workspace, run_build_script=False)
    File "/bin/mkosi", line 1542, in build_image
    raw = create_image(args, workspace.name)
    File "/bin/mkosi", line 124, in create_image
    subprocess.run(["chattr", "+C", f.name], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
    File "/usr/lib64/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['chattr', '+C', '/home/erick/kvms/images/.mkosi-mzuvrf7o']' returned non-zero exit status 1

**Comment by erickj** [comment]
hmmm... it looks like this was fixed quite a while ago with https://github.com/systemd/mkosi/pull/38

it looks like the version of `mkosi` is just 8 months old, https://admin.fedoraproject.org/pkgdb/package/rpms/mkosi/

**Comment by erickj** [comment]
@keszybz you seem to be the maintainer in Fedora? (https://admin.fedoraproject.org/pkgdb/packager/zbyszek/) is there a way I can update `mkosi` via dnf to a newer version?

can the package be updated to v2 or v3?

**Comment by poettering** [comment]
@erickj can you file a bug about the fedora package on rhbz? let'sleave this issue tracker for upstream issues only.

That said, it appears the v2 packages are already there:

https://koji.fedoraproject.org/koji/packageinfo?packageID=23248

Closing this hence.
