### ISSUE TITLE
Support using aria2c to speed up package manager downloads

### ISSUE THREAD

**Issue by sarthakag12** [systemd/mkosi#1102]
Currently, mkosi uses apt-get to install the packages: https://github.com/systemd/mkosi/blob/main/mkosi/__init__.py#L2682

Can the time it takes to install the packages be reduced if we use apt-fast instead of apt-get?
I'm not sure if this has been investigated before. I would be happy to take it up, if not.

**Comment by DaanDeMeyer** [comment]
We're not going to take a dependency on an extra shell script in mkosi. If I look at apt-fast, it mostly seems to configure apt to use aria2c to speed up downloads. I wouldn't mind investigating whether we can (optionally) use aria2c to speed up downloads, so I'll rename the issue to reflect that.

**Comment by DaanDeMeyer** [comment]
Let's close this, usage of aria2c is likely best achieved by overriding apt-get somehow
