### ISSUE TITLE
Support for RHEL

### ISSUE THREAD

**Issue by nick123pig** [systemd/mkosi#1103]
Thoughts on including actual RHEL8 as a supported distribution? I could add the support, but before I start down adding this code, I want to make sure it won't be rejected due to the more complicated licensing/testing.

**Comment by keszybz** [comment]
RHEL8 should be very similar to CentOS… (Or should that be "CentOS should be very similar to RHEL" :) ). So I think it's totally fine to add. We might not be able to test RHEL directly, but as long as the differences from CentOS are just some repository paths and names, this should be OK.

**Comment by DaanDeMeyer** [comment]
We have RHEL UBI support now, still keeping this open until we add actual RHEL support as well

**Comment by keszybz** [comment]
RHEL support was added in #1968.
