### ISSUE TITLE
mkosi booting debian instance in emergency mode

### ISSUE THREAD

**Issue by cerebro1** [systemd/mkosi#1108]
```
[ TIME ] Timed out waiting for device v-gpt\x2dauto\x2droot.device.
[DEPEND] Dependency failed for systemd-fsck-root.service.
[DEPEND] Dependency failed for sysroot.mount.
[DEPEND] Dependency failed for initrd-root-fs.target.
[DEPEND] Dependency failed for initrd-parse-etc.service.
[DEPEND] Dependency failed for initrd-root-device.target.
[  OK  ] Stopped systemd-ask-password-console.path.
[  OK  ] Stopped target basic.target.
[  OK  ] Reached target initrd-fs.target.
[  OK  ] Stopped target sysinit.target.
[  OK  ] Started emergency.service.
[  OK  ] Reached target emergency.target.

Generating "/run/initramfs/rdsosreport.txt"


Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.


Press Enter for maintenance
(or press Control-D to continue): 
```

**Comment by behrmann** [comment]
@cerebro1 Thanks for the report! Could you maybe add the invocation or config file used to generate the error (i.e. what version of Debian were you targetting) and with what version of mkosi it was produced on what kind of host system? The `/run/initramfs/rdsosreport.txt` might also be helpful.

**Comment by DaanDeMeyer** [comment]
@behrmann This is from the systemd repository, @cerebro1 didn't include the default config files that are included with the systemd repo.

We should add a `cat` command or so to print all the configs used to stdout

**Comment by behrmann** [comment]
Ah, my bad. I vaguely remembered the name from the systemd PR list, but didn't make the connection.

> We should add a `cat` command or so to print all the configs used to stdout

Ah, I just had the same idea :) Although I'd rather call it `bugreport-info` or something like that and include some host info and mkosi version

**Comment by cerebro1** [comment]
I think it's my bad... 
Forgive my newbie knowledge in this field.
I built the image using -d option
mkosi -d debian but while booting the image, I didn't pass the distribution option and name.
```mkosi qemu```
What I could conclude here then if the base OS is different, then while booting also we need to pass the distribution since it is not self detecting from the image available that which OS it is. 
Feel free to close if this not a bug and it's somewhere mentioned in some manpage that i missed to read. It would be good if this could be mentioned of not already present

**Comment by DaanDeMeyer** [comment]
Let's close the issue, since it was just an issue of not specifying the correct option
