### ISSUE TITLE
LGTM.com to be retired by end of November

### ISSUE THREAD

**Issue by mcassaniti** [systemd/mkosi#1120]
See https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

**Comment by poettering** [comment]
I guess we can close this now that #1186 is merged? or is anything left to do? @behrmann @DaanDeMeyer @mrc0mmand

**Comment by mrc0mmand** [comment]
Nope, this is all done, the LGTM integration for this repo is disabled. Once https://github.com/systemd/python-systemd/pull/121 is merged I'll remove the LGTM app from the systemd org completely, as it's the last repo remaining.
