### ISSUE TITLE
Distribution=rawhide doesn't use the correct distribution

### ISSUE THREAD

**Issue by davide125** [systemd/mkosi#1156]
When using `Distribution=rawhide` I get:
```
‣ Warning: Assuming rawhide is version 36 — You may specify otherwise with --release=rawhide-<version>
```
That should be version 38, not 36, but ideally we wouldn't hardcode this.

**Comment by DaanDeMeyer** [comment]
Agreed, I'm not sure how we can automatically figure out the last release though. /etc/pki/rpm-gpg doesn't seem to contain a symlink to the key for the latest release

**Comment by DaanDeMeyer** [comment]
Nvm, found a rawhide key link in there, we can use that
