### ISSUE TITLE
Value of --output-split-root (and others) ignored

### ISSUE THREAD

**Issue by pyfisch** [systemd/mkosi#1177]
Given the command `sudo mkosi -f --split-artifacts --output=spam --output-split-root=eggs` I expect that a file with the name "eggs" containing the root partition is created in the output directory. However the name "eggs" is ignored and the three output files are "spam", "spam.manifest" and "spam.root.raw". The last one should be named "eggs".

In `load_args` the arguments `output_split_root`, `output_split_verity`, `output_split_verity_sig` and `output_split_kernel` are always overwritten. 

https://github.com/systemd/mkosi/blob/46c3e8b2fc97f4124e1cb3b55e33a055426380a7/mkosi/__init__.py#L6462-L6469

**Comment by DaanDeMeyer** [comment]
We migrated to systemd-repart which now handles this, so let's close this issue
