### ISSUE TITLE
RFE: Support building images with signed PCR policies

### ISSUE THREAD

**Issue by poettering** [systemd/mkosi#1180]
It would be great to support building OS images with signed PCR policies in mkosi.

With https://github.com/systemd/systemd/pull/24351 and https://github.com/systemd/systemd/pull/24458 there's now support in systemd for TPM2 based disk encryption policies that bind the unsealed keys to the booted kernel image. And if the boot image locks the root fs via verity then this transiently means that you can build OS images now that can have encrypted file systems that can be unlocked in unattended scenarios via TPM2 in a way that strictly requires that OS image (or any other signed by the same key pair) to unlock it.

I think this is quite a major step ahead: secure encryption by default without requiring interactivity. This I am sure should become the default for servers and iot devices sooner or later, and probably even for desktops (as this means we can boot up without interactivity and have encrypted storage already accessible *before* login, so that only the actual act of logging in will require interactivity).

Implementing this would probably require change things so that dracut doesn't do the objcopy to merge the seperate parts into a unified kernel image anymore. Instead we should do that in mkosi ourselves, and do a simple `systemd-measure sign` call before, with pretty much the same parameters.

The linked PRs have man pages with examples for this.

I will prep more docs soon, but the man pages should be enough already to get things started.

I'll eventually hack this up myself for mkosi, but would love if somebody interest of course would beat me to it ;-)

**Comment by poettering** [comment]
(moving the objcopy call out of dracut and into mkosi is probably also nice to support alternative initrd generators, like the arch one or the debian one?)

**Comment by DaanDeMeyer** [comment]
We already do the objcopy out of dracut these days btw

**Comment by DaanDeMeyer** [comment]
> (moving the objcopy call out of dracut and into mkosi is probably also nice to support alternative initrd generators, like the arch one or the debian one?)

I tried, but these don't run systemd in the initrd by default, and we definitely want that, so we're still using dracut for now.

**Comment by behrmann** [comment]
On Fri, Sep 09, 2022 at 12:33:29PM -0700, Daan De Meyer wrote:
> I tried, but these don't run systemd in the initrd by default, and we definitely want that, so we're still using dracut for now.
> 

At least mkinitcpio can be made to, not sure about initramfs-tools.
