### ISSUE TITLE
"mkosi qemu" should automatically start swtpm and expose it

### ISSUE THREAD

**Issue by poettering** [systemd/mkosi#1191]
It's 2022, and VMs really should come with TPMs just working.

hence, I think we should unconditionally run swtpm in the background when "mkosi qemu" is invoked.

This means forking off swtpm before invoking qemu, with a command line such as:

```
swtpm socket --tpm2 --tpmstate dir="$TPM_STATE" --ctrl type=unixio,path="$TPM_STATE/sock"
```

(with some temporary dir in $TPM_STATE)

And then invoke qemu with `-chardev socket,id=chrtpm,path=$TPM_STATE/sock -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0` added to the command line.

After qemu exits we can remove $TPM_STATE again.

**Comment by behrmann** [comment]
Haven't tested this, but hacked up a quick way of what this might look like in #1192. Is that the direction you imagine?

**Comment by poettering** [comment]
Ah, eh, after posting this, I also started working on this, see #1193...

That one definitely works, I have tested the systemd TPM stuff with it.

**Comment by behrmann** [comment]
No worries. :) Having something that's already tested to work is worth more than a sketch.
