### ISSUE TITLE
mkosi genkey fails

### ISSUE THREAD

**Issue by baaa-sh** [systemd/mkosi#1207]
I just discovered mkosi genkey... excellent.

...only it doesn't work:

```
[baaash@delta ~]$ sudo mkosi genkey
[sudo] password for baaash:
‣ Generating secure boot keys rsa:2048 for CN 'mkosi of baaash'.

The keys will expire in 730 days (Thursday 26. September 2024).
Remember to roll them over to new ones before then.

Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 36, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 27, in main
    run_verb(a)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 8390, in run_verb
    generate_secure_boot_key(args)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 8317, in generate_secure_boot_key
    os.execvp(cmd[0], cmd)
  File "/usr/lib64/python3.10/os.py", line 574, in execvp
    _execvpe(file, args)
  File "/usr/lib64/python3.10/os.py", line 616, in _execvpe
    raise last_exc
  File "/usr/lib64/python3.10/os.py", line 607, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory

```
It's looking for something there... what?  that isn't exactly clear to me.

looking at the function statements where it's choking:

```
def execvpe(file, args, env):
    """execvpe(file, args, env)

    Execute the executable file (which is searched for along $PATH)
    with argument list args and environment env, replacing the
    current process.
    args may be a list or tuple of strings. """
    _execvpe(file, args, env)

__all__.extend(["execl","execle","execlp","execlpe","execvp","execvpe"])

def _execvpe(file, args, env=None):
    if env is not None:
        exec_func = execve
        argrest = (args, env)
    else:
        exec_func = execv
        argrest = (args,)
        env = environ

    if path.dirname(file):
        exec_func(file, *argrest)
        return
    saved_exc = None
    path_list = get_exec_path(env)
    if name != 'nt':
        file = fsencode(file)
        path_list = map(fsencode, path_list)
    for dir in path_list:
        fullname = path.join(dir, file)
        try:
            exec_func(fullname, *argrest)
        except (FileNotFoundError, NotADirectoryError) as e:
            last_exc = e
        except OSError as e:
            last_exc = e
            if saved_exc is None:
                saved_exc = e
    if saved_exc is not None:
        raise saved_exc
    raise last_exc
```

extra details... 

My path:
```
[baaash@delta ~]$ echo $PATH
/home/baaash/.cargo/bin:/home/baaash/.nvm/versions/node/v18.8.0/bin:/usr/bin:/usr/local/bin:/home/baaash/.local/bin:/home/baaash/bin
```
mkosi version:
```
[baaash@delta ~]$ mkosi --version
mkosi 13
```
python version:
```
baaash@delta ~]$ python --version
Python 3.10.7
```
python binary location:
```
baaash@delta ~]$ which python3
/usr/bin/python3
```
Kernel version:
```
[baaash@delta ~]$ uname -r
5.19.11-200.fc36.x86_64
```

**Comment by behrmann** [comment]
`FileNotFoundError: [Errno 2] No such file or directory` means that the first argument of the call to `execvp` could not be found. In this case this is the `openssl` binary. Either your distribution doesn't put it in any of the paths in your `PATH` (maybe `/usr/sbin` or the like) or you don't have it installed.

**Comment by DaanDeMeyer** [comment]
@behrmann Can we adapt the genkey to use run() instead of exec? We'd have better error reporting if we did that

**Comment by behrmann** [comment]
Sure, there's no really deep reason for this using `execvp`. Back then we `exec`ed into nspawn on the `shell` verb, I think, and I thought this made sense, since mkosi's job at this point was done, but there's really nothing preventing us from just calling `run` on this now.

**Comment by baaa-sh** [comment]
> `FileNotFoundError: [Errno 2] No such file or directory` means that the first argument of the call to `execvp` could not be found. In this case this is the `openssl` binary. Either your distribution doesn't put it in any of the paths in your `PATH` (maybe `/usr/sbin` or the like) or you don't have it installed.

oh my gosh this was it. how silly of me. 

thank you.

**Comment by poettering** [comment]
(one of those days we should replace the openssl callout here by just using python-cryptography. I mean, we might as well make the dep official and universal, it's always going to be more crypto we have to add, never going to become less)

**Comment by DaanDeMeyer** [comment]
> (one of those days we should replace the openssl callout here by just using python-cryptography. I mean, we might as well make the dep official and universal, it's always going to be more crypto we have to add, never going to become less)

I was hoping we'd get to a point where we just pass the key around to systemd tools and don't do anything with it ourselves so we can get rid the cryptography module again.
