### ISSUE TITLE
mkosi should probably touch `/usr/lib/clock-epoch` during build

### ISSUE THREAD

**Issue by poettering** [systemd/mkosi#1218]
It would probably make sense of mkosi would touch /usr/lib/clock-epoch late during image building.

It's mtime is used by PID1 during boot to bump the clock if it is before that timestamp. It is helpful on systems lacking a working clock to at least get into territory where time makes sense at all. 

PID 1 will bump the clock via a built-in timestamp selected at RPM/DEB built-time anyway. But touching this file from mkosi would be a good idea, since of course image builders just take the distro built packages and then package them up anew, and thus at a later point in time.

We should probably do this always, unconditionally. And if the SOURCE_DATE_EPOCH env var is set during mkosi invocation use it for setting the mtime of that file. (as per https://reproducible-builds.org/docs/source-date-epoch/)

**Comment by DaanDeMeyer** [comment]
Should we put this in systemd-firstboot instead?

**Comment by keszybz** [comment]
> Should we put this in systemd-firstboot instead?

I like this idea. `systemd-firstboot --reset --root=…`. I guess the option should take a list of opt-in/opt-out steps to do: `--reset=hostname` or `--reset=no-hostname,no-epoch`.
