### ISSUE TITLE
Incompatible image name with `machinectl`

### ISSUE THREAD

**Issue by netzego** [systemd/mkosi#1224]
The generated image name when used with `mkosi.version` is incompatible to `machinectl`. `mkosi` uses an `_` (underscore) as delimiter which is not allowed in valid hostnames. If one copies an image `image_0.1.raw` to `/var/lib/machines` and attempt to start it via `machinectl start image_0.1` an error occurs: `Invalid machine name image_0.1.`.

Starting the image via `systemd-nspawn` works, and `machinectl list` shows that nspawn simply discard the invalid character. So the name of that machine/image would be `image0.1`.

When using `mkosi boot` the hostname (`/etc/hostname`) of that machine is used by `machinectl` -- which is fine, imo.

Any how, i consider this as a naming inconvenience but not a *bug*. So feel free to *just* notice and close this issue. Thanks for this neat tool!

**Comment by keszybz** [comment]
Hmm, shouldn't `machined` and `nspawn` ignore `_*` in image names? It seems a bit of a bummer to have this incompatibility. @poettering, opinions?

**Comment by DaanDeMeyer** [comment]
Fixed by #1739
