### ISSUE TITLE
systemd-networkd: Permission Denied in (Debian) subvol

### ISSUE THREAD

**Issue by iam-TJ** [systemd/mkosi#1235]
I'm not sure if this a transient issue due to recent changes but reporting it just in case whilst using the current git HEAD (`5dc93b1`).

Based on comparing with a manual `debootstrap` install of the same set of packages, I *think* `mkosi` is setting restrictive permissions on the container's `/etc/  /etc/systemd/ /etc/systemd/network/` directories too tight. Symptoms when starting a freshly created `subvol` of Debian Bullseye were the network not being configured with the host showing the slave bridge interface as `LOWERLAYERDOWN`.

Inside the container the `systemd-networkd` log showed some strange reports about **Permission Denied**
```
Oct 22 12:47:58 lineage-builder systemd[1]: Starting Network Service...
Oct 22 12:47:58 lineage-builder systemd-networkd[28]: Failed to increase receive buffer size f
or general netlink socket, ignoring: Operation not permitted
Oct 22 12:47:58 lineage-builder systemd-networkd[28]: Failed to open configuration file '/etc/systemd/netw
orkd.conf': Permission denied
Oct 22 12:47:58 lineage-builder systemd-networkd[28]: Failed to parse configuration file: Perm
ission denied
Oct 22 12:47:58 lineage-builder systemd-networkd[28]: host0: DHCP4 CLIENT: Failed to set IAID+DUID: Permis
sion denied
Oct 22 12:47:58 lineage-builder systemd-networkd[28]: host0: Failed
Oct 22 12:47:58 lineage-builder systemd-networkd[28]: Could not process new link message, igno
ring: Permission denied
Oct 22 12:47:58 lineage-builder systemd-networkd[28]: Enumeration completed
Oct 22 12:47:58 lineage-builder systemd[1]: Started Network Service.
```
I eventually tracked it down to the `systemd-network` user/group (that the process `systemd-networkd` operates as) being denied due to very strict permissions on the directories mentioned (No traverse permission for `other`):
```
# namei -l /etc/systemd/networkd.conf                                                                       
f: /etc/systemd/networkd.conf                                                                                                     
drwxr-xr-x root root /                                                                                                            
drwxr-x--- root root etc                                                                                                          
drwxr-x--- root root systemd                                                                                                      
-rw-r--r-- root root networkd.conf

# namei -l /etc/systemd/network                                                                             
f: /etc/systemd/network                                                                                                           
drwxr-xr-x root root /                                                                                                            
drwxr-x--- root root etc                                                                                                          
drwxr-x--- root root systemd                                                                                                      
drwxr-x--- root root network
```
I used `debootstrap` to create an equivalent root-fs and that has more relaxed permissions:
```
$ namei -l test02-manual/etc/systemd/network{d.conf,}
f: test02-manual/etc/systemd/networkd.conf
drwxr-xr-x root root test02-manual
drwxr-xr-x root root etc
drwxr-xr-x root root systemd
-rw-r--r-- root root networkd.conf
f: test02-manual/etc/systemd/network
drwxr-xr-x root root test02-manual
drwxr-xr-x root root etc
drwxr-xr-x root root systemd
drwxr-xr-x root root network
```
I'm not quite sure where/how the tightend permissions were applied, but the manual solution was, from inside the container:
```
chmod +X /etc /etc/systemd
chown :systemd-network /etc/systemd/networkd.conf
chown -R :systemd-network /etc/systemd/network
```
Without the change to `/etc/systemd/network` the interface would be brought up but the configuration would not be applied - it'd use the default configuration from `/usr/lib/systemd/network/80-container-host0.network` rather than the intended `/etc/systemd/network/host0.network`.

**Comment by behrmann** [comment]
I don't right away see where these permissions come from, since there's only one place where we explicitly set `750` as mode and that's not it. Actually, with the `--netdev` option we explicitly set `755` for `/etc/systemd` and `/etc/systemd/network`.

The changing of the group of `networkd.conf` and `/etc/systemd/network` is not needed, though, as they have owner `root:root` on a regular system.

Generally, it would be great if you could provide the input you encountered the problem with, preferably as a minimal example.

**Comment by iam-TJ** [comment]
I wish I'd looked a little deeper before reporting it - user problem! *blush*
I've got a skeleton that adds the network files - oops!
```
$ namei -l mkosi.skeleton/etc/systemd/network/host0.network 
f: mkosi.skeleton/etc/systemd/network/host0.network
drwxr-x--- tj tj mkosi.skeleton
drwxr-x--- tj tj etc
drwxr-x--- tj tj systemd
drwxr-x--- tj tj network
-rw-r----- tj tj host0.network
```
Sorry for the noise!
