### ISSUE TITLE
pacman cache not working with directory output

### ISSUE THREAD

**Issue by lucasdemarchi** [systemd/mkosi#124]
When running mkosi with directory output pacstrap ends up doing a bind mount of the root directory which effectively removes the ability to use the package cache we set up. The line in pacstrap is here:
https://github.com/falconindy/arch-install-scripts/blob/master/common#L82

I'm not sure why pacstrap is doing that. @falconindy ?

Since pacstrap is a thin layer over pacman dealing with mountpoints, cache, etc, maybe mkosi could just use pacman directory?

**Comment by lucaswerkmeister** [comment]
This is the same problem that #116 fixes, isn’t it?

**Comment by lucasdemarchi** [comment]
Oh... there's a pending PR for that. Yes, it is. Thanks.

**Comment by willemw12** [comment]
This issue closed but not fixed.

[Here](https://github.com/willemw12/mkosi/commit/a59b472d04fe88482a963e4cc79f63747a772d2e) is a fix for mkosi.

The workspace root is mounted, unmounted and deleted when needed. The fix should be compatible with any output format.

**Comment by poettering** [comment]
@willemw12 please submit any fixes as PR so that we can review/merge them

**Comment by willemw12** [comment]
@poettering: created PR https://github.com/systemd/mkosi/pull/222.

**Comment by gdiscry** [comment]
Note that with falconindy/arch-install-scripts@232784ec5607383feb805c60d628e7fdda9c2b0e, pacstrap does not bind mount the root anymore if it's a simple directory.

Still waiting for a release however.

**Comment by willemw12** [comment]
A fix in pacstrap instead of mkosi would be preferred.

**Comment by gdiscry** [comment]
According to falconindy/arch-install-scripts#32, a release might come this weekend.
