### ISSUE TITLE
RFE: add another hook script, that can install python/perl/php packages, i.e. those not covered by RPM/DEB

### ISSUE THREAD

**Issue by lucasdemarchi** [systemd/mkosi#125]
Some python packages are not provided by distros but are rather installed via pip and friends.  I think the same apply for npm but I don't use it so don't really know.

How would be the proper way to install them on the image?
1) Package them on the distro: it'd be good, but the chances of getting outdated packages is high since the python packages are controlled by upstream
2) Have a PythonPackages section in the config and --python-packages switch that will a) add the corresponding pip package for the distro and install them after the normal distro packages are installed
3) Use a prefix for packages: pip:pymavlink, for example, would install pymavlink using pip; pip2:pymavlink would install pymavlink using pip2. There could be a key in the configuration to tell what command to use to install packages with each external package manager, like:  ExternalPackageManager = pip:'pip install {}'

Thoughts?

**Comment by fsateler** [comment]
Isn't `postinst build` suitable for this? I'm not sure mkosi should gain knowledge of every lang-specific package manager out there...

**Comment by lucasdemarchi** [comment]
@fsateler I thought I had tried that and it was not working.... but now looking at the code it seems it should rather do.  I'll take a look again.

**Comment by poettering** [comment]
@lucasdemarchi did that work for you?

so the problem with "postinst" is that it runs as the last step of building an image. i figure you need the python modules much earlier, right?

I figure this means we'd have to add a new type of script: "mkosi.pkginstall" or so, which runs after the RPM/DEB phase, right before we run the build script. The result of that would be included in the cached image for incremental mode.

Anyway, do you still need this? I sympathize with a new hook script for this, so if this still is useful to you, let's go for it.

**Comment by fthiery** [comment]
I use the postinst for this and it works pretty good; what took me a while to understand, is that you need to enable networking for pip to work.

```
[Packages]
WithNetwork=yes
```
However, i agree that a way to add custom packages (in my case, prebuilt arch AUR packages) could be nice; right now i have a mkosi.extra/extra-packages/ folder, and my postinst contains the following:

```
# Install custom packages
echo "Installing custom Arch packages"
find /extra-packages/ -iname *.pkg.tar.xz -exec pacman -U --noconfirm {} \;
echo "Removing /extra-packages"
rm -rf /extra-packages
```
Having an mkosi.packages **folder** instead of my hack could be interesting.

**Comment by lucasdemarchi** [comment]
@poettering a long time later I saw your question... I don't think I need this anymore. postinst using "WithNetwork = yes" I think worked for me. I'm not exactly sure what I needed at the time.  I agree it would be nice to have a mkosi.pkginstall, but we need to start documenting where each hook is called out since it's becoming messy.

**Comment by lucasdemarchi** [comment]
I closed, but thinking again. I'll leave it open as a "nice to have".

**Comment by DaanDeMeyer** [comment]
We have this now with mkosi.prepare
