### ISSUE TITLE
KERNEL_INSTALL_BYPASS=1 issue

### ISSUE THREAD

**Issue by leifliddy** [systemd/mkosi#1263]
I'm attempting to build these Fedora 37 configs (on a Fedora 36 system)
https://github.com/leifliddy/asahi-fedora-usb/blob/main/mkosi.default
https://github.com/leifliddy/asahi-fedora-builder/blob/main/mkosi.default

And am running into this issue when running `mkosi`
```
  Running scriptlet: kernel-core-6.1.0-0.rc3.asahi1.1.fc37.aarch64                                            335/335 
kernel-install: Skipping execution because KERNEL_INSTALL_BYPASS=1
```
Setting `KERNEL_INSTALL_BYPASS` to `0` in  `mkosi/__init__.py` solves the issue  
```
run(cmdline, env=dict(KERNEL_INSTALL_BYPASS="0"))
```
I'm wondering why that wasn't occurring when I was building out the Fedora 36 config (on a Fedora 36 system).   
Also, what is the proper solution or workaround for this?

Update: 
This issue also happens when attempting to build a Fedora 37 config on a Fedora 37 system.

**Comment by behrmann** [comment]
`KERNEL_INSTALL_BYPASS` is a variable to skip `kernel-install` if it's run somewhere, where you can't change that it's being invoked, but where you can change the environment. Apparently the `kernel-core` started setting it, although I have no idea why. 

I guess the right way to counteract this would be to set `KERNEL_INSTALL_BYPASS=0` in mkosi, but first I'd like to understand why it was set in the first place. @keszybz do you have any idea?

**Comment by DaanDeMeyer** [comment]
We set this because we run kernel-install manually later anyway so to avoid building the initrd twice we disable kernel-install execution as part of running dnf.

**Comment by leifliddy** [comment]
It's not the log message that's the issue, it's that kernel-install never seems to be run and I'm left with a boot partition that looks like this:
```[root@fedora boot]# ll
total 16
drwx------. 1 root root 14 Nov  8 12:47 efi
drwx------. 1 root root 24 Nov  8 12:46 grub2
drwxr-xr-x. 1 root root 14 Nov  8 12:46 loader
lrwxrwxrwx. 1 root root 57 Nov  8 12:46 symvers-6.1.0-0.rc3.asahi1.1.fc37.aarch64.gz -> /lib/modules/6.1.0-0.rc3.asahi1.1.fc37.aarch64/symvers.gz
```
What is meant by ` we run kernel-install manual later anyway`?   
Because that doesn't seem to be happening here. 
Do my configs need to be adjusted in some way?    
I've building these configs since the beginning of the year without any issues. 
So something has changed recently....I'm just not sure what.

**Comment by behrmann** [comment]
Just to be clear: before https://github.com/leifliddy/asahi-fedora-usb/commit/b13846c34105ee7795f5469fc7556451da10e080 you can build a bootable image and starting with that commit you can't?

**Comment by DaanDeMeyer** [comment]
We only run kernel-install if `Bootable=yes`. Since it's disabled in your config, kernel-install isn't getting executed. I assume you set `Bootable=no` because you need grub instead of systemd-boot. I would set `Bootable=yes` and override systemd-boot with grub later. Although from systemd-boot v252 onwards it should also be work properly on aarch64 so you might not need grub anymore.

**Comment by leifliddy** [comment]
\> Just to be clear: before https://github.com/leifliddy/asahi-fedora-usb/commit/b13846c34105ee7795f5469fc7556451da10e080 you can build a bootable image and starting with that commit you can't?
I'm not trying to build a bootable image, but I need the kernel installed.   
The kernel was being installed up until a week or so ago (I run this quite often for testing).   
I think maybe what's happened is that `mkosi` was updated. 

\> I would set Bootable=yes and override systemd-boot with grub later. 
Interesting, I'll try that. Also I've tested out systemd-boot and it works fine. I should probably transition over to that at some point...

**Comment by leifliddy** [comment]
I originally set `Bootable=no` because mkosi would throw these aarch64 efi errors.

**Comment by leifliddy** [comment]
If I set `bootable=yes` I get this
```
‣ Error: Directory, subvolume, tar, cpio, and plain squashfs images cannot be booted.
```
Is there a way I can override that kernel-install setting without having to manually modify the python library?

**Comment by behrmann** [comment]
>  I'm not trying to build a bootable image, but I need the kernel installed. The kernel was being installed up until a week or so ago (I run this quite often for testing). I think maybe what's happened is that `mkosi` was updated.

We did release v14 twelve days ago, so that might be a reason, but the `KERNEL_INSTALL_BYPASS=1` was included in v13 as well. Which version of mkosi are you running anyway?

**Comment by leifliddy** [comment]
I'm on v14 now.

**Comment by DaanDeMeyer** [comment]
> ‣ Error: Directory, subvolume, tar, cpio, and plain squashfs images cannot be booted.

How are you running mkosi? This error should only trigger if you're trying to run the built image in qemu

**Comment by leifliddy** [comment]
\>How are you running mkosi? This error should only trigger if you're trying to run the built image in qemu
I'm running it on an aarch64 system (macbook m1 air running Fedora). There's no qemu involved.

**Comment by leifliddy** [comment]
ahhhh, the reason I couldn't create a bootable image before was that I had ```Format=directory```

Anyways, I completely overhauled this project to create a bootable image (that's then transferred to a usb/external drive)
https://github.com/leifliddy/asahi-fedora-usb
