### ISSUE TITLE
Consider adding a fallback for nspawn's rootidmap

### ISSUE THREAD

**Issue by jre21** [systemd/mkosi#1265]
After updating to systemd 252, my mkosi builds started failing with errors like

```
Failed to map ids for bind mount /home/jre2718/src/mkosi-images/mkosi.workspace/glfx9oa4/root/root/src: Operation not permitted
```

I eventually tracked this down to systemd-nspawn's `rootidmap` flag, added in #1151 (mkosi runs correctly if I unconditionally set `idmap_opt = ""` in the two places where it's defined).  I think there's something a bit odd with my system (more on that below), but it would be nice to do one of the following:

1.  Test whether the source directory's containing filesystem supports idmapped mounts and if so, drop the `rootidmap` flag.
2.  Add a configuration option to disable the idmap behavior.

If the first option is doable, that would obviously give the cleaner user experience, although I'm not sure what a clean test would look like.

As to why my setup might be weird: my home directory is a luks/btrfs volume managed by systemd-homed, with ext4 as the underlying root filesystem.  With some experimentation, I found that I could mount a directory on the root filesystem with idmap, but anything under my homedir fails.  I also tried manually replicating the homed setup by creating a scratch file on my root filesystem, opening it as a luks volume, and creating a fresh btrfs filesystem in the new volume.  This new btrfs filesystem was mountable with idmap.  So either something in homed itself is interfering with idmap, or my home directory's filesystem is in an old enough version of the format to be incompatible.

To be honest, I hadn't encountered idmap before today, so I'm not sure what else to check while debugging, but at the very least it seems like checking the systemd-nspawn version isn't enough to guarantee that it's safe to use idmap in bind mounts.

**Comment by behrmann** [comment]
Since `idmap_opt` is set for you I gather you are running systemd 252. Can you also tell us what kernel and mkosi versions you are running on what distro?

**Comment by jre21** [comment]
One additional data point here: if I mount my home directory manually (losetup + cryptsetup + mount) instead of through systemd-homed, then I can bind-mount it into a container with rootidmap, so the failure case is specifically an interaction of homed and idmap.

**Comment by qdeslandes** [comment]
As you've been able to run `systemd-nspawn` with `rootidmap`, I assume your system supports it. 

Regarding fixes in case `rootidmap` wouldn't work on any given system:
- Detecting whether it's supported is not easy, see [`testsuite-13.sh`](https://github.com/systemd/systemd/blob/main/test/units/testsuite-13.sh#L77).
- Adding an option to disable it would be faster (`--no-rootidmap`).

Is `systemd-homed` using ID mapping to make the home directory portable?

**Comment by qdeslandes** [comment]
> Is `systemd-homed` using ID mapping to make the home directory portable?

Seems like [it is](https://github.com/systemd/systemd/blob/main/src/home/homework-mount.c#L240).

**Comment by behrmann** [comment]
Ah, and currently they're not stackable? Probably we need a some check then to not use id mapping if there filesystem is already id-mapped?

**Comment by qdeslandes** [comment]
ID mappings are "stackable", but it depends on which UID is mapped to the underlying filesystem. I would expect this to work transparently with `homed`, but apparently it doesn't. I'd have to (find time to) investigate further.

**Comment by qdeslandes** [comment]
@jre21 Could you try #1270 ? You should be able to disabled `rootidmap` using `--idmap=no`.

**Comment by jre21** [comment]
That code works.  Which section of mkosi.conf will it land in?

**Comment by DaanDeMeyer** [comment]
We removed --idmap in favor of unprivileged mkosi so let's close this issue
