### ISSUE TITLE
Attempts to write to *.roothash.p7s or *.usrhash.p7s twice

### ISSUE THREAD

**Issue by jheretic** [systemd/mkosi#1274]
Running a build with both `Verity=signed` and `SplitArtifacts=yes` causes the build to fail at the last step with the following error:
```
FileExistsError: [Errno 17] File exists: '/home/user/src/build/mkosi.output/arch~rolling/.mkosi-rae4hbks' -> '/home/user/src/build/mkosi.output/arch~rolling/archetype_2022.11.13-1.root.roothash.p7s'
```
This appears to be because both `link_output_split_verity_sig` and `link_output_root_hash_p7s_file` attempt to write to the same path, namely `*.roothash.p7s` (or `*.usrhash.p7s` when using `UsrOnly`). It is not clear to me whether both of these functions are meant to write the same contents, but if they do one solution could be to disable one of those functions when both `Verity=signed` and `SplitArtifacts=yes`.

**Comment by behrmann** [comment]
Thanks for the report! I think this functionality will change soonish™, since it will be moved to using systemd-repart. 

From the top of my head I'm not sure whether both will write the same content, but maybe you could give this a quick test and patch one of the output to a different name, as to compare them. If the contents are the same it should be a trivial fix, that we can push in between now and switching to repart.

**Comment by jheretic** [comment]
Thanks for the quick response! It seems that one is a binary blob and the other a JSON blob, containing signature data, for example (just test data):
```
{"rootHash": "b40bde7e7b0cba15f1397d79c94555ea9fb14d7917bda19b68d8c261d5c7630a", "certificateFingerprint": "6c24eda00c92adf561782cb1b538f7fdd308b04be7a045b3d9dc4605b5be0d09", "signature": "MIIBkgYJKoZIhvcNAQcCoIIBgzCCAX8CAQExDzANBglghkgBZQMEAgEFADALBgkqhkiG9w0BBwExggFaMIIBVgIBATAvMBcxFTATBgNVBAMMDG1rb3NpIG9mIG4wbgIUS4gj92KTwWrpzESs5LWf4BaPSEswDQYJYIZIAWUDBAIBBQAwDQYJKoZIhvcNAQEBBQAEggEAuKlK2jqD8WF5Bug/cxfW2fe53ESexOqRH90yH0Mu4N233e4BEs2cexbYFUV34cabAz1LCX95MyaqqRJU5cE3lp9eYkn0OpsG4AmJcXxbBXbnOMyIEWqavRQmTuGtqpjTerg/qgLZzw3iQBnxy0HPuACDHN1s0mlUNUlrLQIcRKt4D41BnN6rCNCTmMeLtUDDyFNXj7utpKlWivc2WLCXqINYh/bJEFN2wxHXB5hKlV1VGt36pgXC7pYmSyZ8Ov0sI922E7TxfV8F0laehfs0Uvf/hcWf+ITPKoC1kq2HKSj+gYEi2WpQu0tE+Ws8n81NM8fsMqA9C5UZqJzy7m12Hw=="}%
```
Presumably one is meant to be written to a standalone file, and the other is meant to be written to a partition. Perhaps the appropriate one could be written to `*.verity.p7s` instead?

The systemd-repart work sounds interesting, is there anywhere that's being documented or discussed, or what the timeframe is likely to be?

**Comment by DaanDeMeyer** [comment]
See https://github.com/systemd/mkosi/issues/1228, should be done within a few months at most

**Comment by jheretic** [comment]
Thank you! Looks like a cool direction to take things. In the meantime, @behrmann I created a simple PR to rename one of the output files so that there is no longer a conflict.

**Comment by DaanDeMeyer** [comment]
We migrated to systemd-repart which now handles all of this so let's close the issue
