### ISSUE TITLE
rpmdb migration is still broken

### ISSUE THREAD

**Issue by coling** [systemd/mkosi#1286]
Hi,

8650beb790004b816380c3bf8af5f2b781fd84af proposed to fix building a Fedora 36 image from Fedora 35 but in turn breaks the opposite, building an "older" distro from Fedora 36.

It seems that after 8650beb790004b816380c3bf8af5f2b781fd84af I can no longer use Fedora 36 to build images for older RPM distros (e.g. RHEL 8 or similar) if my image installs the rpm command (which might be needed to install custom repos and do further package management in mkosi.prepare)

The rpm package itself owns the files in /var/lib/rpm/ and thus if your image installs the rpm package, these files will exist but as we're installing using the host's rpm which populate <image>/usr/lib/sysimage/rpm instead, these files will be blank. 

8650beb790004b816380c3bf8af5f2b781fd84af then _preserves_ these blank files rather than migrating the *actual* files from /usr/lib/sysimage/rpm/

I have a code snippet that runs in mkosi.prepare which does the migration manually (and does some chcon stuff for selinux resigning which is also a (separate) issue which crops up with a compat symlink solution - a full directory move is actually required without tweaking rules).

I'm wondering what the best solution here is? Back out all migration code and just leave it up to the mkosi.prepare? Perhaps have a few helper "macros" we ship to do the migrations easily and can be injected into prepare scripts? Or a bunch of command line options for rpmdb migration that covers different scenarios, or at least one that disables it so we can do our own magic? WDYT?

Col

**Comment by behrmann** [comment]
Damn this whack-a-mole. 

I'd lean towards just not doing any migrating in mkosi, since we've always been breaking one use-case or the the other, and just ship common snippets as separate scriptlets in the tree, maybe in a `contrib/` directory that packagers could ship in `/usr/share/systemd/mkosi/contrib` or such and that people can copy into their prepare scripts.

**Comment by coling** [comment]
> I'd lean towards just not doing any migrating in mkosi, since we've always been breaking one use-case or the the other, and just ship common snippets as separate scriptlets in the tree, maybe in a `contrib/` directory that packagers could ship in `/usr/share/systemd/mkosi/contrib` or such and that people can copy into their prepare scripts.

Yeah probably most sensible. I won't be able to do a patch this week, so feel free if you're keen, otherwise I will hopefully be able to do something next week.

FWIW, this is my mkosi.prepare code for Fedora 36+ host with "legacy" rpm image (possibly with selinux installed on host):

```
if [ -x /usr/bin/rpm -a -d /usr/lib/sysimage/rpm ]; then
  echo "Migrating Fedora 36+ RPM DB to legacy location"
  echo "  Note: rpm will function inside image, but not outside from host"
  rm -rf /var/lib/rpm
  mv /usr/lib/sysimage/rpm /var/lib/
  if [ -x /usr/bin/chcon ]; then
    # Fix selinux context
    chcon -R -u system_u -t rpm_var_lib_t /var/lib/rpm
  fi
  rpm --rebuilddb --define "_db_backend bdb" || exit 1
fi
```
