### ISSUE TITLE
--secureboot is broken when --incremental is used

### ISSUE THREAD

**Issue by kerneis-anssi** [systemd/mkosi#1288]
Steps to reproduce:
```
mkosi genkey
echo '#!/bin/sh' > mkosi.build
chmod u+x mkosi.build
mkosi --incremental -d fedora -r 37 -b --secure-boot
```

Expected result: bootloader and combined  kernel+initrd boot files are signed in final image.
Actual result:  /usr/lib/systemd/boot/efi/systemd-bootx64.efi is signed in pre-inst image, but nothing else is (and in particular kernel+initrd boot file in final image is not).

Root cause: `secure_boot_sign` is called in many different steps, often as a no-op due to various conditions guarding its execution. The only step where it is expected to sign files in `/efi` is towards the very end, right after the call to `install_unified_kernel` in `__init__.py`. However, if `--installed` is passed, the `cached` variable will always be true at this stage, even during the first run. Note that `install_unified_kernel` acts regardless of the value of `cached`, and so should `secure_boot_sign`.

Solution: it's unclear to me whether taking caching into account is ever useful. If it is useful in the case of signing the bootloader, then the following line should unconditionally set `cached=False`: https://github.com/systemd/mkosi/blob/1c9a6ac5d1729e7797f8a1a4f1a1475c7a2795cf/mkosi/__init__.py#L5960
Otherwise, the `cached` parameter and its use should be discarded from `secure_boot_sign` altogether.

**Comment by DaanDeMeyer** [comment]
Already fixed in #1276
