### ISSUE TITLE
Building custom bootloader

### ISSUE THREAD

**Issue by boliboli123** [systemd/mkosi#1297]
Hello,

First of all, I'm not sure if this is the right forum for general questions so please let me know if there is a mailing list that I have missed.

I'm trying to add UEFI Grub bootloader to my image but I'm not sure how to proceed.

I read in this thread that grub is no longer supported:
https://github.com/systemd/mkosi/issues/348

One of the comments mentioned that you can create a custom boot partition.

From the V14 Release notes that is also mentioned:

`` To generate BIOS images you can use any version of mkosi up to mkosi 13 or the new --bios-size option. This can be used to add a BIOS boot partition of the specified size on which grub (or any other bootloader) can be installed with the help of mkosi's script support (depending on your needs most likely mkosi.postinst or mkosi.finalize). This method can also be used for other EFI bootloaders that mkosi intentionally does not support. ``

But I could not find any information about this option and how to use it.

Can anyone point me in the right direction for learning how to implement this?

much appreciated!

**Comment by DaanDeMeyer** [comment]
Unfortunately I don't have the time to figure out how to set this up, if you figure out how to do it, we'd accept a PR to add documentation so others can benefit. For now let's close the issue as its more of a question
