### ISSUE TITLE
mkosi should be made compatible with a host with SELinux enabled

### ISSUE THREAD

**Issue by sourcejedi** [systemd/mkosi#130]
[RHBZ#1374427](https://bugzilla.redhat.com/show_bug.cgi?id=1374427) equally affects `mkosi`.  `mkosi` was written, in part, for testing modifications to systemd.  But this issue means systemd's HACKING instructions do not work, on a default Fedora install.

`mkosi` does not request installation of selinux support in images, and [deliberately disables it](https://github.com/systemd/mkosi/blob/40df6a3acbcdb26d40471109fa2a53c15dd113e3/mkosi#L2494).  This seems correct when using `mkosi` to develop systemd or any other software.  Any modification to systemd could fail, until the downstream distribution updates their SELinux policy to support it.

However `dnf` still tries to assign SELinux labels to the installed files.  When running the image the labels cause SELinux transitions, e.g. when running `passwd`.  We don't want this, and it causes failures.  This behaviour of `dnf --installroot` under SELinux was included in the above report.  Sadly this did not elicit any suggestion of how to use `dnf --installroot` and get _consistent_ SELinux labels, let alone disable the labelling as `mkosi` would want.

When a user creates a Fedora image using `dnf`, they can very simply work around the issue using `restorecon` or possibly `fixfiles`.  The `mkosi` tool could do something similar.  The files in the image could be relabelled using `chcon unconfined_u:object_r:unlabeled_t:s0 -R`.  `unlabeled_t` is the value shown for files which have no context xattr.  This might be desirable, to avoid unnecessary differences between images generated on systems with SELinux enabled v.s. disabled.  (Or it could use `default_t`, the label assigned when you create a new directory underneath `/`).

Assigning labels is only possible on the system which has SELinux configured.  Therefore this needs to be done conditionally, and not from inside a container.  Without SELinux (e.g inside a container):

```
-bash-4.4# chcon unconfined_u:object_r:unlabeled_t:s0 / 
chcon: invalid context: 'unconfined_u:object_r:unlabeled_t:s0': No such file or directory
```

In theory, at least the `unconfined_u:object_r:` part is policy-specific.  As is the ability for "unconfined" processes to access `unlabeled_t` files without interference.  So this is not a universal solution for any SELinux policy.  However it should make mkosi usable on popular Linux systems and the SELinux reference policy.

## Specific failure

```
$ rpm -q mkosi
mkosi-2-1.fc26.noarch
```

1. `mkosi`
2. `systemd-nspawn -b -i image.raw`  # oops, I need to set a root password to log in
3. `systemd-nspawn -i image.raw`
4. `passwd`

```
-bash-4.4# passwd
passwd: Can not identify you!
-bash-4.4# passwd -u root
passwd: Unknown user name 'root'.
```

AVC denial:

* SELinux is preventing passwd from read access on the file passwd.
* Source Context                unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023
* Target Context                system_u:object_r:unlabeled_t:s0

```
-bash-4.4# ls -Z /etc/passwd
system_u:object_r:unlabeled_t:s0 /etc/passwd
-bash-4.4# ls -Z /usr/bin/passwd
system_u:object_r:passwd_exec_t:s0 /usr/bin/passwd
```

**Comment by doverride** [comment]
An -Z and -L is needed just like with nspawn, but in this case one needs some other aspects as well.

My fork has some very ugly hacks to make it "work" with my selinux security policy. Its a really dirty hack since i hard code identifiers. and shutil.copy2() all over the place and do other bad things, but it does give some ideas as to what is needed.

https://github.com/DefenSec/mkosi

**Comment by poettering** [comment]
I sympathize with the issue, but given that I am not an SELinux guru I am not sure I can fix this. I'd be happy to review and merge a patch adding this however.

**Comment by ValdikSS** [comment]
As far as I understand, there are 'standard' SELinux policies which modern RedHat/Fedora utilities use: https://github.com/containers/container-selinux
It requires installation on host.

**Comment by ValdikSS** [comment]
@poettering, should mkosi generate context-less tar archive if SELinux is not supported currently? Right now I have to add "--xattrs-exclude=security.selinux" to tar arguments (in make_tar function). Could this be made configurable?

**Comment by ValdikSS** [comment]
@DaanDeMeyer, please reopen the issue. The merged code is a workaround, not a proper SELinux compatibility.

**Comment by sourcejedi** [comment]
Sorry, I don't know.  If I was still using it, it wouldn't bother me because I don't leave SELinux in enforcing mode anymore.  So the following is an unreliable guess, based on old memories:

In order to follow `systemd/docs/HACKING.md` on a default Fedora, the "workaround" approach would be great, if it was generalized to work on disk images.  But if instead, "properly relabel" means you set up all the Fedora SELinux labels, that means you're testing against your current SELinux policy.  Whereas I thought you were supposed to hack in blissful ignorance, and let Fedora fix any policy that breaks downstream.

I only remember using nspawn.  It looks like you could use qemu instead, and if you need to you can use `--kernel-command-line=enforcing=0`.  In that case "proper" labels could be better, so long as you know the trick.

**Comment by martinetd** [comment]
I *think* it's related? On a somewhat up to date fedora 37 I tried to run mkosi (main branch) from the systemd (main branch) and fedora install fails with a bunch of
```
Error in <unknown> scriptlet in rpm package tree
error: setexecfilecon: (/bin/sh, rpm_script_t) Read-only file system
error: Plugin selinux: hook scriplet_fork_post failed
warning: %transfiletriggerin(systemd-251.14-2.fc37.x86_64) scriptlet failed, exit status 126
```
for a bunch of packages.

Running `setenforce 0` seems to fix the issue, so I guess it's not a mkosi/systemd bug but a selinux-policies problem on fedora37 that might already be fixed in a more recent version... I'll just pretend I didn't see this and someone with an up to date fedora can perhaps confirm if they stumble into it (the error didn't come up on a search anywhere, so at least it'll be documented as a policy problem now)

**Comment by keszybz** [comment]
`selinux=0` was removed from the default option set in 2d851ec26f4b312360da82851498de5f52740ec0 and relabelling was added in cdef7ba19d4e85cfe4df0d27336d7950a42bb0da. So I think that's it from the mkosi side. Maybe there should be some selinux policy changes, but that'd need to be handled elsewhere.

**Comment by DaanDeMeyer** [comment]
I was still going to try and find the time to verify that we can run properly from systems with selinux in enforcing mode

**Comment by DaanDeMeyer** [comment]
So running latest mkosi from a F39 VM with selinux doesn't seem to trigger any denials. So since we properly relabel the images themselves and denials while building images should be handled by the selinux policy, let's close this issue.
