### ISSUE TITLE
RFE: Support setting hostname, locale and timezone

### ISSUE THREAD

**Issue by dteleguin** [systemd/mkosi#131]
At the moment, generated image ends up with the following settings:
- hostname: localhost
This comes from `/etc/hostname` which belongs to systemd RPM and contains "localhost" (however may be specific to my distro, Mageia). If the image is used as a systemd-nspawn bootable container, this static hostname prevents the transient hostname (= machine name) to be set correctly (as of systemd-230). Hence, the hostname may need to be set for VMs and to be _unset_ for containers;
- locale: (not set)
- timezone: inherited from the build machine (?)

It would be nice to have an ability to configure this all on the image building stage. However, this can be tricky, since `hostnamectl`/`localectl`/`timedatectl` all require running systemd inside the image.

**Comment by dteleguin** [comment]
Of course this could be solved by manipulating `/etc/hostname`, `/etc/locale.conf` and `/etc/localtime` from a `mkosi.postinst` script, or even installing a first-run script into the image. Feel free to close if insignificant/irrelevant.

**Comment by dteleguin** [comment]
I have just noticed #105, so the hostname part seems to be dealt with already. I think setting timezone and locale could be implemented in a similar manner.

**Comment by poettering** [comment]
I'd probably add explicit support for setting the hostname, but I am not sure about /etc/locale.conf, as mkosi.extra/ appears fully sufficient to cover that, and similar for /etc/localtime. 

@dteleguin would mkosi.extra/ suffice for you? If yes, we can close this and leave #105 for the hostname thing.

**Comment by dteleguin** [comment]
@poettering yep I'm OK with that, closing the issue
