### ISSUE TITLE
Running mkosi build gives error unrecognized arguments

### ISSUE THREAD

**Issue by rayzorben** [systemd/mkosi#1339]
Just doing a simple `mkosi` and getting

`mkosi: error: unrecognized arguments: --chown=no --idmap=no`

I am running Arch and installed via git `yay -S mkosi-git`.

**Comment by DaanDeMeyer** [comment]
Those options were removed, I assume you have them set in a config file somewhere

**Comment by rayzorben** [comment]
Thanks, didn't realize there could be a .conf file to add those in, fixed.
