### ISSUE TITLE
Failed to create bootable Ubuntu image on Arch

### ISSUE THREAD

**Issue by Aloxaf** [systemd/mkosi#1368]
mkosi version: d13ff85610c6fb01a2fff0a8187729ebe4a05595

## log
```bash
> sudo python -m mkosi -d ubuntu -t disk -b -o image.raw
...
...
‣   Generating initramfs images…
/usr/lib/kernel/install.d/50-depmod.install: line 34: exec: depmod: not found
/etc/kernel/install.d/50-mkosi-dpkg-reconfigure-dracut.install: 20: dpkg-reconfigure: not found
/boot/initrd.img-5.15.0-60-generic does not exist, not installing an initrd
‣ Error: "kernel-install add 5.15.0-60-generic /boot/vmlinuz-5.15.0-60-generic" returned non-zero exit code 254.
```

**Comment by behrmann** [comment]
Thanks for the report! Which version of Ubuntu were you running this on?

On Debian `dpkg-reconfigure` is part of the `debconf` package. Could you check whether the problem persists if you add `debconf` to the list of installed packages?

**Comment by DaanDeMeyer** [comment]
This is going to be caused because we propagate the PATH from the host into the container which doesn't include sbin on Arch.

**Comment by behrmann** [comment]
Ah, my bad, read it the other way 'round.

**Comment by Aloxaf** [comment]
> This is going to be caused because we propagate the PATH from the host into the container which doesn't include sbin on Arch.

Thanks for your explanation! It works well after adding `/sbin` and `/usr/lib/systemd` (needed by ukify) to PATH.

**Comment by DaanDeMeyer** [comment]
This should be fixed in mkosi itself, can you test #1369 and see if it fixes the issue without modifying your own PATH?

**Comment by Aloxaf** [comment]
@DaanDeMeyer It works well now after the patch!

**Comment by ineu** [comment]
This is broken again in mkosi 26, as described here: https://github.com/systemd/mkosi/discussions/4059

Downgrading the mkosi package in Arch from 26 to 25 fixes the depmod problem

**Comment by Taxrosdev** [comment]
This does appear to be broken again on upgrade.

**Comment by manut** [comment]
I ran into the same issue on Debian/sid: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1133276 - either pick the patch from there on top of v26 or add /usr/sbin to $PATH
