### ISSUE TITLE
opensuse: bad URL

### ISSUE THREAD

**Issue by reverendhomer** [systemd/mkosi#137]
Hi, I tried to make an opensuse image under fedora 26 and got this error message:

```
Download (curl) error for 'https://download.opensuse.org/update/tumbleweed/repodata/repomd.xml':
Error code:  Bad URL
Error message: Protocol "http" not supported or disabled in libcurl
```

mkosi from git master. How can I fix that?

**Comment by poettering** [comment]
Hmm, very weird... does curl work on the cmdline?

**Comment by reverendhomer** [comment]
Yup
```
λ curl https://download.opensuse.org/update/tumbleweed/repodata/repomd.xml
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://download.opensuse.org/repositories/openSUSE:/Factory:/Update/standard/repodata/repomd.xml">here</a>.</p>
<hr>
<address>Apache/2.2.34 (Linux/SUSE) Server at download.opensuse.org Port 443</address>
</body></html>

```

**Comment by poettering** [comment]
Hmm @fbuihuu any idea about this one, given that this is in the opensuse code?

**Comment by keszybz** [comment]
I suspect this is caused by the redirect to plain http from an https URL.

**Comment by fbuihuu** [comment]
It seems that curl(1) doesn't like such redirection anymore.

There seems to be some WIP to stop redirecting https to http, see https://github.com/openSUSE/mirrorbrain/issues/3 but for the time being we could fix that simply by using http:// for the mirrors as there seems to be no additional value in https:// (the rpms are signed by gpg keys already, so is the repodata
