### ISSUE TITLE
fail to build ubuntu image on 22.04

### ISSUE THREAD

**Issue by photoszzt** [systemd/mkosi#1372]
I'm using the ubuntu packaged version of mkosi version 12. I'm using a minimal mkosi.default to test:
```
[Distribution]
Distribution=ubuntu
Release=jammy

[Partitions]
RootSize=12G
ESPSize=512M

[Output]
Format=raw_gpt
Bootable=yes
Output=root.img

[Contents]
WithNetwork=yes

[Packages]
Packages=
  ubuntu-minimal
  net-tools

[Validation]
Password=root
```
I'm building the image with command: sudo -E mkosi -i -f --autologin build
The following error appears:
```
tune2fs 1.46.5 (30-Dec-2021)

This operation requires a freshly checked filesystem.

Please run e2fsck -f on the filesystem.

‣  (Detaching /dev/loop0)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/mkosi/__main__.py", line 32, in <module>
    main()
  File "/usr/lib/python3/dist-packages/mkosi/__main__.py", line 26, in main
    run_verb(a)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 7809, in run_verb
    manifest = build_stuff(args)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 7227, in build_stuff
    image = build_image(args, root, manifest=manifest, do_run_build_script=False, cleanup=True)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 6948, in build_image
    refresh_file_system(args, dev, cached)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 859, in refresh_file_system
    run(["tune2fs", "-U", "random", dev], stdin=subprocess.DEVNULL)
  File "/usr/lib/python3/dist-packages/mkosi/backend.py", line 699, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['tune2fs', '-U', 'random', '/dev/loop0p2']' returned non-zero exit status 1.
```

**Comment by DaanDeMeyer** [comment]
Please only report issues against the latest commit on the main branch. We don't support older releases.

**Comment by photoszzt** [comment]
@DaanDeMeyer Sure. But the most recent version doesn't have valid documentation. My current config file works in version 5 and 12 but not anymore on 14. The man page still said gpt_ext4 is a valid output format while it gives me error. I had to go to look at the code to figure out what's supported. I'm fine to explore this way but it's not very helpful for any end user to properly use this tool. Also root-size and esp-size are also not recognized now while man page still documents them.

**Comment by photoszzt** [comment]
Ok, saw the News.md.

**Comment by DaanDeMeyer** [comment]
Where are you getting the man page from? I just updated the man page bundled with the repo to include the latest changes. For the latest docs, look at the mkosi.md markdown file in the repository.

Note that systemd v253 is required to run the latest mkosi and there have been quite a few breaking changes.

**Comment by photoszzt** [comment]
I was looking at the source code's man page. Ubuntu 22.04 is bundled with systemd 249. I don't want to upgrade systemd and mess with my os.

**Comment by photoszzt** [comment]
I think I will just use the previous version of mkosi. Main is not usable for me for my current setup.

**Comment by septatrix** [comment]
I also could observe this error with v14 though not deterministically. Just now it occured after invoking a `-i -ff` build after a previous `-i -f` build and IIRC the previous instance where I had this happen might have been the same situation.

Simply running the build again, however, has always resolved the issue for now. I currently cannot try v15 as I think that requires systemd v254 now which I do not have.
