### ISSUE TITLE
ext4 images generated on newer hosts may not be bootable

### ISSUE THREAD

**Issue by medhefgo** [systemd/mkosi#1378]
I just stumbled upon this while testing a systemd mkosi run of centos8 on a up-to-date arch host.

The image builds fine, but fails inside the initrd when booting in qemu:
```
Mar 09 13:39:46 localhost systemd[1]: Starting systemd-fsck-root.service...
Mar 09 13:39:46 localhost systemd-fsck[368]: /dev/sda2 has unsupported feature(s): FEATURE_C12
Mar 09 13:39:46 localhost systemd-fsck[368]: e2fsck: Get a newer version of e2fsck!
Mar 09 13:39:46 localhost systemd-fsck[368]: root-x86-64: ********** WARNING: Filesystem still has errors **********
Mar 09 13:39:46 localhost systemd-fsck[366]: fsck failed with exit status 12.
Mar 09 13:39:46 localhost systemd[1]: systemd-fsck-root.service: Main process exited, code=exited, status=1/FAILURE
Mar 09 13:39:46 localhost systemd[1]: systemd-fsck-root.service: Failed with result 'exit-code'.
Mar 09 13:39:46 localhost systemd[1]: Failed to start systemd-fsck-root.service.
```

The issue is that newer userspace tools may use fs features not supported by older tools/kernels of the target image. Coincidentally, I just read this https://lwn.net/Articles/923969/ where it was suggested that the image should be created in a chroot by the userspace tools of the generated image for best support.

**Comment by behrmann** [comment]
Yeah, I thought we might run into this issue sooner or later when reading the article. 

Using two step process to build the image with the same distro as would later run was discussed before, but it's not been pursuit really. Does the also mentioned `tune2fs` trick from the article work? If so that would be a good intermediate solution.
