### ISSUE TITLE
Debian/Ubuntu: usrmerge package not found

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/mkosi#14]
sudo mkosi -d debian -r jessie -o ...

> ...
> E: Couldn't find these debs: usrmerge
> ...

The reason for this error is very simple: `usrmerge` isn’t in jessie, only in stretch (testing) and sid (unstable) so far. It would be very convenient if `mkosi` detected this condition and either removed `usrmerge` from the package list (probably not what you want for “legacy-free images”) or printed a better error message than the current double stack trace (“Debian releases other than ‘testing’ and ‘unstable’ are unsupported at the moment”).

**Comment by stefan-it** [comment]
See also ongoing discussion about the `usrmerge` package [here](https://github.com/systemd/mkosi/pull/7#discussion_r77798517) and [here](https://github.com/fsateler/mkosi/commit/3656ae181c052a5f0b22456d364ed9dc4c40854b) :)

**Comment by stefan-it** [comment]
The `usrmerge` package was removed with 893397862b27d4d4526d4fdac90197b74d53f6ea (see more explanation on #17) so I guess we can close here :)

**Comment by lucaswerkmeister** [comment]
Yeah, sounds like it :)
