### ISSUE TITLE
Only parse configuration files suffixed with ".conf" in dropin directories

### ISSUE THREAD

**Issue by nikandfor** [systemd/mkosi#1406]
I've encountered crash when run `mkosi` command. The problem was it tried to parse `.*.swp` file in `conf.d` directory. I opened config on server, vim created its file, I got python traceback.

Maybe filter out hidden files here?
https://github.com/systemd/mkosi/blob/beee070079e057b83cc8cae791e7b140f6f4b005/mkosi/__init__.py#L2108

**Comment by DaanDeMeyer** [comment]
We should only parse config files suffixed with .conf
