### ISSUE TITLE
rootfs directory acl issue

### ISSUE THREAD

**Issue by leifliddy** [systemd/mkosi#1409]
This issue pertains to the main branch and occurs when building an image on Fedora 37 and 38 systems. 

Given the following `mkosi` configuration
https://github.com/leifliddy/asahi-fedora-usb/blob/main/mkosi.default

There's an issue with the  `mkosi.rootfs` directory that gets created.

That directory and every directory that recursively appears beneath it has this 
`u:root:rwx` acl set on it. 

```
[root@fedora usb]# getfacl mkosi.rootfs
# file: mkosi.rootfs
# owner: root
# group: root
user::r-x
user:root:rwx
group::r-x
mask::rwx
other::r-x
```

```
[root@fedora usb]# ll mkosi.rootfs
total 80
dr-xr-xr-x+ 1 root root    0 Jan 19 01:00 afs
lrwxrwxrwx. 1 root root    7 Jan 19 01:00 bin -> usr/bin
dr-xr-xr-x+ 1 root root  564 Mar 26 19:54 boot
drwxr-xr-x+ 1 root root    0 Mar 26 19:51 dev
drwxr-xr-x+ 1 root root 2412 Mar 26 19:55 etc
...
```

This issue is related to a PR that was merged on Feb 9. 
I think it's this one:
https://github.com/systemd/mkosi/commit/fdecbf74e9d8a9b1e1c32e4c16b15d7be07fdf5a
```
It's difficult to test -- because if I install mkosi at that `fdecbf..` commit, I run into this error. 
  File "/root/.local/lib/python3.11/site-packages/mkosi/run.py", line 199, in <listcomp>
    cmdline = [os.fspath(x) for x in cmdline]
               ^^^^^^^^^^^^
```

Update:
If I attempt to build to build an image as a non-root user
Then the `mkosi.rootfs` dir will inexplicably be owned by this `524288` uid
```
dr-xrwxr-x+ 1     524288     524288   166 Mar 26 23:18 mkosi.rootfs
```

```
[leif.liddy@fedora usb]$ ls -la mkosi.rootfs
total 80
dr-xrwxr-x+ 1     524288     524288  166 Mar 26 23:18 .
drwxr-xr-x. 1 leif.liddy leif.liddy  224 Mar 26 23:19 ..
dr-xrwxr-x+ 1     524288     524288    0 Jan 19 01:00 afs
lrwxrwxrwx. 1     524288     524288    7 Jan 19 01:00 bin -> usr/bin
dr-xrwxr-x+ 1     524288     524288  564 Mar 26 23:19 boot
drwxrwxr-x+ 1     524288     524288    0 Mar 26 23:17 dev
drwxrwxr-x+ 1     524288     524288 2412 Mar 26 23:19 etc
drwxrwxr-x+ 1     524288     524288   20 Jan 19 01:00 home
...
```

And the following acl gets set 
```
[leif.liddy@fedora usb]$ getfacl mkosi.rootfs
# file: mkosi.rootfs
# owner: 524288
# group: 524288
user::r-x
user:leif.liddy:rwx
group::r-x
mask::rwx
other::r-x
```

Also, I'm only using the main branch as this commit hasn't been merged into a release yet https://github.com/systemd/mkosi/pull/1264/commits/41d1c2a1fbe2a42be8f21c912298944ecbb31e01

Perhaps you guys would consider creating a new release within the next few months.

**Comment by DaanDeMeyer** [comment]
#1410 has been merged so closing this issue. The ACLs are not added by default anymore.

**Comment by DaanDeMeyer** [comment]
> Perhaps you guys would consider creating a new release within the next few months.

I've still got more breaking changes in the pipeline so I want to wait until all those are done before doing a new release.

**Comment by leifliddy** [comment]
Got it, thanks!
