### ISSUE TITLE
Make `--install-recommends` configurable

### ISSUE THREAD

**Issue by Natureshadow** [systemd/mkosi#1419]
The distribution scripts default hard-coded to not installing recommended dependencies.

While this is a sane default, it should be configurable with an option, probably separately for the build and final images.

**Comment by behrmann** [comment]
I'm not sure I would consider Debian's recommends sensible, but there's little that can be done on that front. :)

You can configure this via a config file in `/etc/apt` via `mkosi.skeleton` and change the file later with scripts. 

Could you check whether that works for you? This would be much preferable to adding an option for that, since this is very specific to certain package managers and doesn't generalise well.

**Comment by DaanDeMeyer** [comment]
> You can configure this via a config file in /etc/apt via mkosi.skeleton and change the file later with scripts.

This doesn't work, we only consider apt config files in our own custom location.

**Comment by Natureshadow** [comment]
> You can configure this via a config file in /etc/apt via mkosi.skeleton and change the file later with scripts.

I could. But as the issue says, the behaviour is hard-coded. mkosi always passes `--no-install-recommends` on the command-line, overriding any configuration files.

**Comment by DaanDeMeyer** [comment]
We can just add an option for this, I think it makes sense to have. We can have values yes, no, build and final and default to no. Would be happy to review a patch for this.

**Comment by iam-TJ** [comment]
Just been bitten by this. Project configurations that worked fine until now break during build because (on Debian/Ubuntu) `systemd` is no longer installed, only `libsystemd0`,  and failing (fortunately else I'd not have known) when `mkosi.postinst` tries to do `systemctl enable systemd-networkd`:
```
...
‣   Setting root password
‣   Copying in extra file trees…
‣   Running kernel-install…
‣   Running postinstall script…
/root/postinst: line 9: systemctl: command not found
‣ "/root/postinst final" returned non-zero exit code 127.
```

**Comment by gdiscry** [comment]
> Just been bitten by this. Project configurations that worked fine until now break during build because (on Debian/Ubuntu) `systemd` is no longer installed, only `libsystemd0`, and failing (fortunately else I'd not have known) when `mkosi.postinst` tries to do `systemctl enable systemd-networkd`:

mkosi always used `--no-install-recommends` and I'm not sure that debootstrap installs systemd.

If I remember correctly, mkosi <15 would force the installation of a few packages, such as `systemd`, `udev`, `dbus` and others based on the configuration (filesystem tools, `systemd-networkd`…).

It looks like mkosi 15 takes a minimalist approach to the packages installed by default and requires the needed packages to be listed explicitly.

**Comment by iam-TJ** [comment]
Yes; I think the move to`DistributionInstaller` is responsible; prior to that `install_debian_or_ubuntu()` had a short `extra` list of packages on top of whatever `debootstrap` installed.

I'm using the new `mkosi.conf.d` fragments and `Match` architecture to break up the package lists and conditionally including fragments based on a combination of `Distribution=` and `PathExists=`  and creating the fragment lists from the package priorities `required` and `important` from each distro:
```
for priority in required important; do awk '/^Package/{P=$2} /^Priority:.*'${priority}'/{print P}' /var/lib/dpkg/status | tr \\n , > packages-$(lsb_release --short --id)-${priority}.conf; done
```
These get rationalised and broken down into several purpose-specific `conf` fragments - e.g. packages to support hardware (`systemd-udev, fdisk`) are not required in containers. Fragments then use the `Match` clauses to do e.g.`PathExists=../match/devices`  and  ` touch ./match/devices` will trigger it.

**Comment by DaanDeMeyer** [comment]
Note that you can use apt search patterns in `Packages`, so you can add `?priority(required)` to `Packages` to install all required packages.

**Comment by iam-TJ** [comment]
@DaanDeMeyer  Thanks for pointing that out! I can combine that with lists of packages NOT to install. That will reduce the chance of missing packages in future releases that are added to the priorities.

**Comment by DaanDeMeyer** [comment]
With the newly added --package-manager-tree option, you can add apt config dropins to override mkosi's default of not installing recommended dependencies.
