### ISSUE TITLE
Update documentation inside repo

### ISSUE THREAD

**Issue by nameOfUser0236** [systemd/mkosi#1443]
The documentation inside this repo: [mkosi.md](https://github.com/systemd/mkosi/blob/779484101987048b820b07a6111bcb0e8d5ebc1d/mkosi.md) and to a lesser extent [man/mkosi.1](https://github.com/systemd/mkosi/blob/779484101987048b820b07a6111bcb0e8d5ebc1d/man/mkosi.1) are outdated, including most of the [Partitions] section among other things. The full manual exists (on archlinux at least), however it is not linked to from this repo, creating a source of confusion.

**Comment by DaanDeMeyer** [comment]
Fixed by #1287
