### ISSUE TITLE
Versioning of configuration and executable

### ISSUE THREAD

**Issue by iam-TJ** [systemd/mkosi#1482]
There has been quite a bit of change in the configuration file options and semantics recently. Two changes that come to mind are the `mkosi.default` -> `mkosi.conf` change (I appreciate there is backwards compatibility for this) and the more invasive reversal of the `mkosi.conf.d`  ordering and logic (due to `[Match]` and sub-directories named after `Distribution=` now being processed regardless.

For projects that include mkosi configuration and are likely to be built on a wide range of distributions with different packaged releases of `mkosi` it would be helpful to have a way to provide a single set of configuration files that can gracefully cope with older versions of `mkosi` whilst still harnessing the latest functionality for those with latest release or using a build from `HEAD¬ - possibly via the `zipapp`.

It would be useful to add some kind of version-check sanity to avoid unexpected issues for existing configurations.

One option would be an addition to the `Match` semantics
```
[Match]
MkosiVersionFirst=
MkosiVersionLast=
```
with the defaults for each being `0` and "whatever version the executable is"

This would allow coping with the loss of deprecated or changed functionality as well as harnessing latest functionality that hasn't made it into distributions yet.

That might be overkill though, so a project-wide stamp file `mkosi.version` with `MkosiVersion=` is a simpler alternative but much less useful to projects using `mkosi`.

It would also help if the version reported by builds from `HEAD`  (or any commit following a tagged release) reported something else other than the last released version. As in right now, building a `zipapp` from `HEAD` still reports `mkosi 14` but its behaviour changes breaks existing project configuration drop-in file parsing due to ordering. Something like `mkosi 15~dev` might be sufficient.

This last would be useful without any configuration file versioning. Build scripts that call `mkosi --version` could determine if the project configuration is compatible.

**Comment by DaanDeMeyer** [comment]
The goal is to try and keep backwards compatibility starting from the next release so we're not going to implement something like this due to the overhead involved.
