### ISSUE TITLE
[Match] multiple Distribution= with OR

### ISSUE THREAD

**Issue by iam-TJ** [systemd/mkosi#1483]
Whilst re-writing several project configurations to work with the `[Match]` semantics and having fragments for both Debian and Ubuntu I realised `Packages=`  and `BuildPackages=` has to be duplicated in both despite being the same. That made me wish I could do:
```
[Match]
Distribution=debian
Distribution=ubuntu
```
or
```
[Match]
Distribution=debian ubuntu
```
and a logical OR would be applied to the multiple names.

**Comment by DaanDeMeyer** [comment]
Makes perfect sense. I'd go for something like this:

```
[Match]
Distribution=debian|ubuntu
```

Will happily accept a PR for this. should be trivial to implement.

**Comment by iam-TJ** [comment]
I already started experimenting but thought using existing list semantics (space separated) rather than introducing an operator would be preferred.

**Comment by DaanDeMeyer** [comment]
We should add `config_make_list_matcher()` which mimicks `config_make_list_parser()` but splits the value based on the configured delimiter, and passes each value to the provided match function and if any match, it returns True, otherwise False.

**Comment by iam-TJ** [comment]
That makes sense.
