### ISSUE TITLE
btrfs subvol: ReadOnly no longer possible due to repart

### ISSUE THREAD

**Issue by iam-TJ** [systemd/mkosi#1484]
Just hit this whilst converting project configurations to v15 style:
```
$ mkosi --debug="" --distribution=debian summary 
‣ Error: Unknown setting ReadOnly

$ cat mkosi.conf.d/95-output.conf 
[Output]
Format=subvolume
ReadOnly=true
```

**Comment by DaanDeMeyer** [comment]
I think subvolume is broken in general. Haven't had time to fix it.

But yes, `ReadOnly=` does not exist anymore. Please use a finalize script to mark the subvolume read-only instead.
