### ISSUE TITLE
Debian/Ubuntu: dbus not installed

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/mkosi#15]
`debootstrap` does not install `dbus`, probably because it only installs required dependencies of the `--include`d packages (`systemd` recommends `dbus`, but doesn’t require it). This means that the new image can’t be controlled with `machinectl shell` or `machinectl login`.

**Comment by stefan-it** [comment]
What do you think about adding the `libpam-systemd` [package](https://packages.debian.org/de/sid/libpam-systemd), too? Seems to be also a suggested package (for `systemd`) and I install it all the time when I build a new Debian based container.

**Comment by lucaswerkmeister** [comment]
Sounds good, would you like me to add it to #16?

**Comment by stefan-it** [comment]
Yes, that would be great!
