### ISSUE TITLE
Support for reading configs from TAR archive

### ISSUE THREAD

**Issue by Winterhuman** [systemd/mkosi#1505]
Using `tar` to archive all the configs together works, but it requires extracting the contents to a directory before `mkosi` can read it (as far as I understand), which is a bit messy if the configs are meant to be ephemeral.

**Comment by DaanDeMeyer** [comment]
Can you expand? Do you want the entire config including extra trees and such stored in a tar?

**Comment by Winterhuman** [comment]
Yep, pretty much everything you can configure with `mkosi` in one TAR file

**Comment by DaanDeMeyer** [comment]
So we have `--include` now which can be used to include extra configuration from arbitrary directories. This would allow you to extract the tar to an ephemeral directory and then include it with --include and remove the directory afterwards.

I don't see us adding support for this directly in mkosi as it seems like a rather niche use case, so I'm going to close this one as not planned.
