### ISSUE TITLE
Adding xbootldr partition breaks UKI generation

### ISSUE THREAD

**Issue by MariusSchiffer** [systemd/mkosi#1544]
I created mkosi.repart definitions including an ESP and a  XBOOTLDR partition.  
However, after generation of UKIs by mkosi, they are completely absent from both the ESP (/efi, with `CopyFiles=/efi:/`) and XBOOTLDR (/boot with `CopyFiles=/boot:/`).

Side note here: ukify is invoked with `/boot/EFI/Linux` as output directory (which is still correct for my goal), however this of course does not exist on the XBOOTLDR. I added a mkdir before invocation of ukify.  
bootctl also needs `/efi` as `SYSTEMD_ESP_PATH`.

My goal is split generation of partitions as I will distribute them separately for A/B updates.  
ESP should contain only sd-boot, XBOOTLDR should contain UKIs. sd-boot can load UKIs from XBOOTLDR.
This means that I can include XBOOTLDR with kernel images in the A/B scheme (using the automount flag) and only leave out the ESP.

Versions: main branch mkosi and systemd from today.

**Comment by DaanDeMeyer** [comment]
Should be fixed now if you build the latest systemd-repart from source
