### ISSUE TITLE
btrfs not found in PATH

### ISSUE THREAD

**Issue by 4nd3r** [systemd/mkosi#1559]
Using main branch on Debian Sid.

I don't have `btrfs` installed, but `mkosi` still wants to use it.

```
$ mkosi -t tar -o test
‣ Removing output files…
‣ Building default image
‣ btrfs not found in PATH.
```

Workaround is to add `--use-subvolumes no`.

Documentation says:
> If `auto`, missing btrfs or failures to create subvolumes are ignored.

But `auto` has no effect. Should it be the default?

**Comment by DaanDeMeyer** [comment]
Can you try https://github.com/systemd/mkosi/pull/1560?

**Comment by 4nd3r** [comment]
You're fast.

Yes, #1560 fixes this.
