### ISSUE TITLE
Running mkosi in jenkins environment

### ISSUE THREAD

**Issue by BakermanLP** [systemd/mkosi#156]
Hello there,

I just wanted to ask, if it is possible to build images via mkosi in jenkins. My first tries ended in a problem with "Detaching namespace" while running in a chroot environment. 

My setup is at the moment a running Ubuntu 17.04 workstation, there is a folder with the Ubuntu 17.10 base (same architecture). In this environment I can chroot and install mkosi with "apt-get install mkosi". But running without any command line arguments the above error occure

```
\u2023 Detaching namespace...
mount: /: not mount point or bad option.
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 2764, in <module>
    main()
  File "/usr/bin/mkosi", line 2759, in main
    init_namespace(args)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/bin/mkosi", line 128, in init_namespace
    subprocess.run(["mount", "--make-rslave", "/"], check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['mount', '--make-rslave', '/']' returned non-zero exit status 32.
```
Is this in any way possible? 

Thanks for reading

Michael (aka BakermanLP)

**Comment by poettering** [comment]
mkosi needs a pretty recent distro with systemd-nspawn. It needs write access to cgroupfs, to /dev/loop and namespacing. I can't really answer you whether your system and Jenkins provide that. It's probably something to inquire the Jenkins community about.

Sorry that I can't be more helpful on this.

**Comment by BakermanLP** [comment]
Ok, Thanks for reading.

Am Di., 10. Okt. 2017, 11:49 schrieb Lennart Poettering <
notifications@github.com>:
