### ISSUE TITLE
bootctl not found in PATH

### ISSUE THREAD

**Issue by 4nd3r** [systemd/mkosi#1561]
Using main branch on Debian Sid.

When building Ubuntu image with `-p systemd`, `mkosi` wants to use `bootctl`, which I don't have installed.

```
$ mkosi -t tar -o test -p systemd -d ubuntu
```

Same time Debian builds without `bootctl` just fine.

**Comment by DaanDeMeyer** [comment]
Pushed another commit onto https://github.com/systemd/mkosi/pull/1560 that should fix this
