### ISSUE TITLE
Allow installing another kernel than mainline on Arch

### ISSUE THREAD

**Issue by fthiery** [systemd/mkosi#157]
On Arch, the latest kernel is always installed, it would be nice to install at least another official variant (linux-hardened, linux-lts, linux-zen)

**Comment by fthiery** [comment]
Here is the PR if anyone is interested
https://github.com/systemd/mkosi/pull/158

**Comment by fedelibre** [comment]
As #158 has been merged, this issue should be closed, shouldn't?

**Comment by fthiery** [comment]
Indeed !
