### ISSUE TITLE
Improve architecture handling

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#1588]
Lots of cruft around this:

- Debian has its own architecture list and our mapping to that isn't complete I think
- I don't even know what architecture specs we're following in mkosi
- There's EFI architectures and we have a map to those as well so that we can find the right stub to pass to ukify. We can't rely on ukify's auto detection logic because it doesn't have a --root argument. Ideally ukify would learn --root and we could drop the EFI architectures map completely
- We don't set the repart root partition GUID correctly when building for a foreign architecture. Even if we do this in mkosi, it doesn't fix the case when users have custom repart files because we can't fix the architecture for those. Maybe we should add a way to override the architecture that the architecture independent partition uuid names resolve to so that we can set the architecture from mkosi itself.

**Comment by bluca** [comment]
We also should add aliasing at least here and there (eg: repart for the config files), and at least one cross-build test to ensure we don't regress

**Comment by DaanDeMeyer** [comment]
Fixed by the recent PRs around architecture handling
