### ISSUE TITLE
Uki and `.vmlinuz` signatures differ

### ISSUE THREAD

**Issue by Cornelicorn** [systemd/mkosi#1589]
Following https://github.com/systemd/mkosi/commit/85d8342e974e5537529ea959b4e405fa330467b9, the signatures between the `.vmlinuz` output and the kernel image inside the UKI differ.
The kernel inside the UKI is signed by the mkosi secureboot keys, the `.vmlinuz` output is not.

Since only UEFI hosts are supported with systemd-boot, I don't see why the split out kernel is needed after all, but I guess it should then work the same way as the UKI.

**Comment by behrmann** [comment]
I guess it would make sense to drop the split out stuff, since it can be easily obtained with an objdump from the UKI in a finalize script

**Comment by DaanDeMeyer** [comment]
This is intended to be there, It's useful to allow booting it's there to allow booting cpios in qemu directly without needing a UKI or rootfs.

**Comment by DaanDeMeyer** [comment]
Should be trivial to sign the vmlinuz as well if needed.
