### ISSUE TITLE
Verity setup not working for Ubuntu

### ISSUE THREAD

**Issue by MariusSchiffer** [systemd/mkosi#1612]
I'm building a Ubuntu Jammy image with a verity partition added in repart.
Roothash is also correctly included in the UKI commandline. Boot fails by timeout waiting for `/dev/mapper/root`.  
I checked the partition GUIDs with the roothash.

Systemd's veritysetup is also started correctly, but `/dev/mapper/root` never appears. Besides the following logs, I can't find more information on what's going wrong.

`systemd-veritysetup@root` is running:
`/lib/systemd/systemd-veritysetup attach root /dev/disk/by-partuuid/954172df-ee9a-aab2-d90a-0ab162ee6bc5 /dev/disk/by-partuuid/a6a77ede-951f-ad19-f0f9-4df0d7266a93 954172dfee9aaab2d90a0ab162ee6bc5a6a77ede951fad19f0f94df0d7266a93`

Log:
```
Jun 06 09:04:30 localhost systemd-fstab-generator[119]: Using verity root device /dev/mapper/root.
Jun 06 09:04:30 localhost systemd[1]: Created slice Slice /system/systemd-veritysetup.
Jun 06 09:04:37 localhost kernel: device-mapper: verity: sha256 using implementation "sha256-generic"
```

The same issue appears when using a Ubuntu Focal image with systemd and mkosi main branch from today.
I'm not sure if this is a systemd or mkosi issue. (For both images, I'm using mkosi main branch)

What else could I look at?

Used mkosi.conf:
```
[Distribution]
Distribution=ubuntu
Release=jammy
Repositories=main,restricted,jammy-updates
Architecture=x86-64

[Output]
Format=disk
OutputDirectory=mkosi.output
CacheDirectory=mkosi.cache
RepartDirectories=mkosi.repart
ImageId=hypervisor
SplitArtifacts=yes
Bootable=yes

[Validation]
VerityKey=mkosi.key
VerityCertificate=mkosi.crt

[Content]
Packages=systemd
     linux-generic
     cryptsetup-bin
```

Repart files:
```
[Partition]
Type=esp
Format=vfat
CopyFiles=/efi:/
SizeMinBytes=1024M
SizeMaxBytes=1024M
```
```
[Partition]
Type=root
Format=ext4
CopyFiles=/
Minimize=guess
Verity=data
VerityMatchKey=root
```
```
[Partition]
Type=root-verity
Verity=hash
VerityMatchKey=root
SizeMinBytes=300M
SizeMaxBytes=300M
```
```
[Partition]
Type=srv
Format=ext4
CopyFiles=/srv:/
SizeMinBytes=2G
```

**Comment by DaanDeMeyer** [comment]
You need dmsetup in the initrd, it's not included by default in the initrd mkosi generates by default. Check the mkosi setup in the systemd repo for more info on how to make this work
