### ISSUE TITLE
Creating Ubuntu image fails with `sh: line 1: exec: apt-get: not found`

### ISSUE THREAD

**Issue by paulmenzel** [systemd/mkosi#1617]
I just got the latest changes for mkosi, and previously working commands fail now.

```
$ debootstrap --version # actually 1.0.128
debootstrap $(VERSION)
$ git log --oneline --no-decorate -1
b082259 Install dmsetup in the initrd on Debian/Ubuntu
$ pip install .
$ ~/.local/bin/mkosi --version
mkosi 14
$ sudo ~/.local/bin/mkosi --distribution ubuntu -r focal --bootable --output-dir /dev/shm/foobar qemu --debug
‣ Removing output files…
‣ Building default image
ERROR: not a btrfs filesystem: /dev/shm/.mkosi.tmpaxm7xpub
‣  Mounting image…
‣   Installing Ubuntu
sh: line 1: exec: apt-get: not found
‣ "apt-get update" returned non-zero exit code 127.
```

Is it because of merge/pull request https://github.com/systemd/mkosi/pull/1442 requiring apt-get, which my distribution does not have?

**Comment by behrmann** [comment]
> Is it because of merge/pull request https://github.com/systemd/mkosi/pull/1442 requiring apt-get, which my distribution does not have?

Indeed. We stopped doing debootstrap in favour of bootstrapping ourselves with apt, since it allowed to streamline the bootstrapping for all distributions such that the package manager is only invoked from the outside. Unfortunately this means, that if your distribution does not provide `apt-get`, you will have to build it (and `dpkg` from source).

**Comment by paulmenzel** [comment]
The merge/pull request just talks about some mysterious hack.

Sounds like a regression to me to require the more heavy weight apt-get which requires more dependencies to be built.

**Comment by DaanDeMeyer** [comment]
This is not something that we're going to revert. We've decided to run package managers on the host system instead of inside the image as it brings a ton of advantages. Please get your distribution to package apt instead.
