### ISSUE TITLE
Support multiple kernel versions with image version

### ISSUE THREAD

**Issue by MariusSchiffer** [systemd/mkosi#1631]
When setting an image version, the same name is used for the UKI filename for multiple kernel versions.

See here: https://github.com/systemd/mkosi/blob/5616f28505a00dfe58793fadfa81919446024596/mkosi/__init__.py#L880-L881

**Comment by DaanDeMeyer** [comment]
Yeah that's a bug, can you file a PR to put the kernel version in the name?
