### ISSUE TITLE
Support building an initrd using a build script

### ISSUE THREAD

**Issue by mcassaniti** [systemd/mkosi#1645]
If the option `Initrds=` is set to a nonexistent file then mkosi will rightfully complain. It is ideal however to build an initrd using the build script and then use the initrd after the fact. Now it could be argued that building an initrd as an entirely separate build process and then running mkosi a second time would work, but that does add some complexity.

I wanted to get some feedback before posting up a PR.

**Comment by DaanDeMeyer** [comment]
mkosi already supports building an initrd itself, can you list the issues you have with the auto-generated initrd? I would prefer making that work properly rather than adding another way to build initrds.

**Comment by DaanDeMeyer** [comment]
Also, we have mkosi.presets if you need to run mkosi multiple times, check the systemd repo for an example on how we use that to build the initrd in a separate step before using it in the final image

**Comment by mcassaniti** [comment]
Is there any documentation on presets? I'm sure it's a great feature but I really don't understand it. Perhaps by way of example?

Am I correct in saying that it is a way to chain mkosi runs together so one output (like a base installation) can be used for another (like a system extension build)?

I'm wanting to use dracut for my initrd image mainly for the reduction in size on Ubuntu.

**Comment by DaanDeMeyer** [comment]
> Is there any documentation on presets? I'm sure it's a great feature but I really don't understand it. Perhaps by way of example?

> Am I correct in saying that it is a way to chain mkosi runs together so one output (like a base installation) can be used for another (like a system extension build)?

https://github.com/systemd/mkosi/pull/1644 adds some documentation on presets. You can also look at the systemd repo for a practical example. The gist of it is that presets allow specifying multiple mkosi configs that get built in alphanumerical order and that the later configs can depend on outputs from the earlier configs.

This can be used to first build an initrd to use in the final image or to first build a base layer and then build system extensions against that base layer.

> I'm wanting to use dracut for my initrd image mainly for the reduction in size on Ubuntu.

So with presets you can build a custom initrd that you can trim as much as you want to get a similar size initrd as dracut produces. Specifically the --kernel-modules-include and --kernel-modules-exclude options can be used to trim the kernel modules that are included in the initrd. For everything else `RemoveFiles=` can be used to remove more stuff if needed.

**Comment by mcassaniti** [comment]
I'll close this one out and make use of presets, even if that means I build using dracut in one of those.
