### ISSUE TITLE
SignExpectedPCR should only be turned on if a TPM is present.

### ISSUE THREAD

**Issue by Cornelicorn** [systemd/mkosi#1657]
This option makes `ukify` call `systemd-measure sign`, which in it's manpage says

> Note that a TPM2 device must be available for this signing to take place, even though the result is not tied to any TPM2 device or its state.

This makes mkosi builds fail with the default settings if `systemd-measure` is available but no TPM module is installed (VMs without tpm emulation or older hardware).

**Comment by DaanDeMeyer** [comment]
The latest version of systemd-measure doesn't need a TPM anymore to sign PCRs, so I'd suggest just updating to the latest version of systemd-measure from git until v254 is released.

**Comment by Cornelicorn** [comment]
Yes, sorry. With the systemd git version I used, that still didn't work and the upstream manpage still says that `systemd-measure` needs a TPM2 device.
