### ISSUE TITLE
Tree copy fails if build produces local files to folders that are a symbolic link (e.g. /lib > /usr/lib on Arch)

### ISSUE THREAD

**Issue by fthiery** [systemd/mkosi#166]
My build script installs files into /root/dest/lib/firmware, and mkosi crashes in that case.

```
\u2023 Running build script...
...
Copy file /lib/firmware/fw.bin to /root/dest/lib/firmware/fw.bin
...
\u2023 Running build script complete.
\u2023 Copying in build tree...
cp: cannot overwrite non-directory '/var/tmp/mkosi-qs39r9yw/root/lib' with directory '/var/tmp/mkosi-qs39r9yw/dest/lib'
\u2023 Unmounting Package Cache...
...
\u2023 Detaching image file complete.
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 3072, in <module>
    main()
  File "/usr/bin/mkosi", line 3068, in main
    build_stuff(args)
  File "/usr/bin/mkosi", line 3020, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=False)
  File "/usr/bin/mkosi", line 2871, in build_image
    install_build_dest(args, workspace.name, run_build_script, for_cache)
  File "/usr/bin/mkosi", line 1512, in install_build_dest
    enumerate_and_copy(os.path.join(workspace, "dest"), os.path.join(workspace, "root"))
  File "/usr/bin/mkosi", line 1430, in enumerate_and_copy
    subprocess.run(["cp", "--reflink=auto", "--recursive", "--no-dereference", "--preserve=all", "--no-target-directory", source, dest], check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cp', '--reflink=auto', '--recursive', '--no-dereference', '--preserve=all', '--no-target-directory', '/var/tmp/mkosi-qs39r9yw/dest', '/var/tmp/mkosi-qs39r9yw/root']' returned non-zero exit status 1.
```

To reproduce, use the following as mkosi.build script:

```
mkdir -p /root/dest/lib/
echo "test" > /root/dest/lib/testfile
```

**Comment by fthiery** [comment]
Adding some debug shows that cp refuses to copy into lib because (at least on arch) /lib is a symlink to /usr/lib:
```
Copy /var/tmp/mkosi-kktbf0bs/dest to /var/tmp/mkosi-kktbf0bs/root
[cp running]
/var/tmp/mkosi-kktbf0bs/root/lib: symbolic link to usr/lib
```

**Comment by fthiery** [comment]
Since https://github.com/systemd/mkosi/pull/134 cp is used ; cp is apparently not supporting this case (https://superuser.com/questions/534790/cp-into-destination-hierarchy-with-symbolic-link) and someone suggests using rsync instead of cp.

`    subprocess.run(["cp", "--reflink=auto", "--recursive", "--no-dereference", "--preserve=all", "--no-target-directory", source, dest], check=True)
`

**Comment by fthiery** [comment]
On arch, any file installed to /bin, /lib, /lib64 or /sbin would fail at copy time
```
lrwxrwxrwx   1 root root     7 26 mars   2017 bin -> usr/bin
lrwxrwxrwx   1 root root     7 26 mars   2017 lib -> usr/lib
lrwxrwxrwx   1 root root     7 26 mars   2017 lib64 -> usr/lib
lrwxrwxrwx   1 root root     7 26 mars   2017 sbin -> usr/bin
```

**Comment by fthiery** [comment]
I came up with the following rsync option set, but i'm not sure it matches cp's --no-target-directory argument:
`    subprocess.run(["rsync", "--recursive", "--keep-dirlinks", "--perms", "--group", "--specials", source, dest], check=True)
`

**Comment by fthiery** [comment]
The above works only if a trailing slash is added to the source (https://serverfault.com/questions/529287/rsync-creates-a-directory-with-the-same-name-inside-of-destination-directory)

**Comment by lucasdemarchi** [comment]
I think this is solved, right?

**Comment by fthiery** [comment]
I'm not sure, my commit was not merged i think. Sorry, i'm not using mkosi anymore.

**Comment by lucasdemarchi** [comment]
There is an internal cp implementation that is being used now. I will give this a test and close if it works. Thanks

**Comment by DaanDeMeyer** [comment]
Let's close this as we haven't been using cp for a while now. This should be fixed in master.
