### ISSUE TITLE
Add specifier support when parsing configuration files

### ISSUE THREAD

**Issue by MariusSchiffer** [systemd/mkosi#1664]
I'm currently using a setup similar to the presets in the main systemd repository. I would like to output to a directory specified on the command line, as in my case the repository directory should not be written to.

The relative paths used for `BaseTrees` would not work then.  
Example:  
Preset base with `OutputDirectory=../../mkosi.output` (or no directory set)
Preset initrd with `BaseTrees=../../mkosi.output/base`

Call mkosi with `mkosi --output-directory=/tmp/mkosi.output`

A workaround for me here is calling the preset manually with the `--base-tree=/tmp/mkosi.output/base`, which gets unwieldy with several presets.

A possible solution I see is adding a PathsRelativeTo similar to what repart has, or calling `.format(output_directory=)` on these paths so one can use `BaseTrees={output}/base`

**Comment by DaanDeMeyer** [comment]
We should probably add specifier support. I'd also like to more easily allow specifying paths relative to the top level directory mkosi was invoked from.
