### ISSUE TITLE
mkosi API (interop with languages)

### ISSUE THREAD

**Issue by malt3** [systemd/mkosi#1683]
Users of mkosi may want to create images from a programming language (python, go, ...) and want to set configuration options or flags for mkosi.
Should mkosi do one of the following?:

- expose bindings for other languages
- expose a (somewhat) stable config format (at least add a version field to the config and ensure stability for a given version)
- expose an additional config input (json or similar) that can be used to interact with mkosi

In my opinion, the last two options are more scalable, easier to integrate and should be preferred.
Let me know if this is something that you would like to see implemented in mkosi and what a preferred implementation may look like.
I would be happy to work on this to provide some kind of api between mkosi and Go to create OS images.

**Comment by DaanDeMeyer** [comment]
For API I'd just use the CLI arguments tbh. Bindings definitely seems way more effort than value. Same with supporting another configuration format. The rest is about being backwards compatible. At one point we will be, but I cannot give any timeline on when.

**Comment by malt3** [comment]
That's a fair viewpoint. For my purposes, serializing a config file is more ergonomic and type safe but I'm fine with doing this on my own and staying up to date with changes regarding the config file format. Feel free to reopen this in the future if you want to document/implement ways how other (build) tools should interact with mkosi.
