### ISSUE TITLE
Cannot run images built with mkosi 14 on older hosts (e.g. Rocky 8.6)

### ISSUE THREAD

**Issue by coling** [systemd/mkosi#1702]
Sorry to open this up, but just run into an issue with this commit.

If you build e.g. a rocky image and run it on rocky 8.6, this change prevents the image from booting with the following error:
```
[root@development-container-host ~]# systemd-nspawn --read-only -i image.raw 
Spawning container platform on image.raw .
Press ^] three times within 1s to kill container.
Failed to read machine ID from container image: Invalid argument
```

This is just getting a shell, but same issue booting it.

Reverting this change and just having an empty machine-id file allows it to boot fine.

Note I'm running a quite old systemd on the host: systemd-239-58.el8.x86_64 where systemd-239-74.el8_8.2.x86_64 is the latest so I should see if the newer runtime helps but I don't see anything specific in the changelog.

My image build host is Fedora 38.

_Originally posted by @coling in https://github.com/systemd/mkosi/issues/1118#issuecomment-1652041123_

**Comment by DaanDeMeyer** [comment]
Yeah this is unfortunate but I don't think we're going to change this. This is a bug in older versions of systemd-nspawn. I would suggest backporting the systemd fix for this to make this work.

**Comment by coling** [comment]
I contemplated adding support for ```MachineId=``` (i.e. setting a blank machine id) but to be honest, it's a one liner in the ```mkosi.finalize``` to work around it so hardly worth spending the effort on it.

I'll close this ticket, but hopefully might help someone else from banging their head against a wall!
