### ISSUE TITLE
Add extended support for configuring the partition layout used by mkosi

### ISSUE THREAD

**Issue by fthiery** [systemd/mkosi#172]
I was hoping to use the home partition to grow it with resize2fs, but that's not going to happen if the home partition is inserted before the root partition.

```
Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048          526335   256.0 MiB   EF00  ESP System Partition
   2          526336          731135   100.0 MiB   8302  Home Partition
   3          731136         7024606   3.0 GiB     8304  Root Partition
```

**Comment by lucasdemarchi** [comment]
Maybe we could receive the partition table as an argument and we give that to sfdisk? That way we the user could customize how the partitions are created, but we need to add code to ensure we have the required partitions in place.

**Comment by poettering** [comment]
@lucasdemarchi i was thinking that maybe we should read "mkosi.sfdisk" if it exists and use it instead.

**Comment by DaanDeMeyer** [comment]
These days we'd probably want to do his with systemd-repart once we adopt it.

**Comment by DaanDeMeyer** [comment]
Going to close this one in favor of #866 since they're kinda similar and probably have the same solution
