### ISSUE TITLE
Support overriding default values for options

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#1761]
For each supported option, we should introduce a variant that allows modifying the default value for that option if none is set explicitly. For example, for `Architecture=` we'd have `DefaultArchitecture=` and idem for other options. This would allow configuring global defaults for presets that can be overridden individually per preset if needed. This would allow configuring the default architecture for all images and sysexts built from a set of presets, except for the tools tree image which would use `Architecture=native` to make sure it always uses the host architecture.

**Comment by Cornelicorn** [comment]
Maybe presets could instead override settings given by `mkosi.conf` and `mkosi.conf.d` outside of the workspace? Then the default architecture could be set in `mkosi.conf` and in the tools tree preset `mkosi.conf` `Architecture=native` could be set.

So CLI overrides Preset overrides general config.

**Comment by DaanDeMeyer** [comment]
This doesn't work because we need to be able to set general defaults in the global config. A good example is the distribution to build. For a bunch of use cases, you want to be able to configure the distro to use globally in mkosi.conf, and then match on it in the individual presets to install individual presets. If we parse the presets first and then the global config, that becomes impossible.

**Comment by mcassaniti** [comment]
Closed via #1829?
