### ISSUE TITLE
"Could not resolve host" error when running build or postinst scripts

### ISSUE THREAD

**Issue by fedelibre** [systemd/mkosi#178]
I must add a package which is not available in debian stretch repository, namely guile-1.8 (but it would be available in unstable and oldstable repositories).
Don't know what's the recommended way to do this in mkosi. I don't think mkosi allows to install a single package from a different repository (pinning).

So I tried downloading and compiling from source using mkosi.build or mkosi.postinst scripts, but in both cases I got a DNS error:

```
‣ Running build script...
Cloning into 'guile'...
fatal: unable to access 'https://git.savannah.gnu.org/git/guile.git/': Could not resolve host: git.savannah.gnu.org
```

Here's the script:

```
#!/bin/sh
#git clone git://git.savannah.gnu.org/guile.git
git clone https://git.savannah.gnu.org/git/guile.git
cd guile
git checkout branch_release-1-8
./autogen.sh
./configure --disable-error-on-warning --prefix=/opt/guile-1.8
make
make install
```

Thanks in advance for your help

**Comment by fsateler** [comment]
Did you try using the `--with-network` parameter? This can be specified in the `mkosi.default` file in the `[Packages]` section.

**Comment by fedelibre** [comment]
Yes, adding this option fixed the problem:

```
[Packages]
WithNetwork=yes
```

I'm still a bit unsure if I should put this in the build or postinst script.
IIUC build script is better, since only the files generated will be copied to the final image, while the source will be deleted. Is it correct?

**Comment by fsateler** [comment]
Correct, I think the build stage is better.
