### ISSUE TITLE
add "mkosi qemu" which is like "mkosi boot" or "mkosi shell", but invokes qemu the right way on the built image

### ISSUE THREAD

**Issue by poettering** [systemd/mkosi#179]
if we have "mkosi boot" now, we also should have "mkosi qemu"

**Comment by fsateler** [comment]
Unfortunately that requires knowing where the OVMF files are, and that varies by distro...

**Comment by poettering** [comment]
yeah, that really sucks. But I figure we could look for it at a few common places...

**Comment by dteleguin** [comment]
I think per-distro defaults + cmdline option and config key to override should do the trick.
It's `/usr/share/edk2/ovmf-x64/` for Mageia BTW.

**Comment by poettering** [comment]
An implementation for this is waiting in #180.
