### ISSUE TITLE
Build fails if host does not have /etc/gshadow

### ISSUE THREAD

**Issue by malt3** [systemd/mkosi#1792]
From my research, `/etc/gshadow` seems to be entirely optional. Both openSUSE and NixOS do not create `/etc/gshadow`.

This code expects gshadow to exist on the host and bind mounts `/dev/null` -> `/etc/gshadow` in bubblewrap if the path does not exist in the sysroot we are building:

https://github.com/systemd/mkosi/blob/9ae416df714cc87efad876b076ca10b677ed7036/mkosi/run.py#L338-L353

If `/etc/gshadow` does not exist on the host, bubblewrap first needs to create it before bind mounting it. This fails, since we do not have permissions to write to `/etc`.

A possible fix is to add `--tmpfs /etc` to the bwrap arguments and add all paths from the host as bind mounts (except for `/etc/passwd`,  `/etc/group`, `/etc/shadow`, `/etc/gshadow`). This way, we have permissions to create the mount for `/dev/null` -> `/etc/gshadow`.
Alternatively, we can maybe skip the bind mount if the file doesn't exist on the host?

Would you be interested in a PR that implements either the tmpfs mount for `/etc` or one that skips the mount if the file doesn't exist on the host?

**Comment by DaanDeMeyer** [comment]
Let's just skip the mount if it doesn't exist on the host. gshadow isn't terribly important and I'm pretty sure we'll still get what we want even without it mounted.
