### ISSUE TITLE
The Match section is not inherited into presets from a base drop-in

### ISSUE THREAD

**Issue by mcassaniti** [systemd/mkosi#1801]
Perhaps this isn't something that we want to support, but the following does not work at present:

* A base configuration
* An override with a match section in the base directory as a drop-in. I'm using `PathExists = mkosi.repart` to set some options.
* A configuration in a preset directory. The preset has a directory mkosi.repart

The other option is some symlinks, but it would be nice to have this inherited.

Example tree layout:
```
mkosi.conf
mkosi.conf.d/
mkosi.conf.d/repart-settings.conf
mkosi.presets/
mkosi.presets/00-my-image/
mkosi.presets/00-my-image/mkosi.conf
mkosi.presets/00-my-image/mkosi.repart/
mkosi.presets/00-my-image/mkosi.repart/...
```

**Comment by DaanDeMeyer** [comment]
RepartDirectories= is a list setting. so we'll append to it when we find more then one. What you could do is the following

```
[Match]
PathExists=mkosi.repart

[Output]
RepartDirectories=mkosi.repart,!*
```

This will pick up mkosi.repart/ from the top level directory if it exists and exclude any other repart directories from being added.

**Comment by mcassaniti** [comment]
This might explain a bit. None of these settings are set in the base configuration.

```
$ cat mkosi.conf.d/repart-settings.conf
# If mkosi.repart exists then build a disk image with a signed checksum

[Match]
PathExists = mkosi.repart

[Output]
Format         = disk
CompressOutput = xz

[Validation]
Checksum = yes
Sign     = yes
Key      = ...
```

**Comment by DaanDeMeyer** [comment]
They don't have to be set, but if you don't set `RepartDirectories=`, we will pick up every mkosi.repart/ directory and use them all. So if you only want the top level one to be used, you have to add `!*` to make sure that any later ones do not get added

**Comment by mcassaniti** [comment]
What I want to have happen is for the settings shown above in `repart-settings.conf` to be applied to any presets that have a directory of mkosi.repart present.

**Comment by DaanDeMeyer** [comment]
Yeah no that's not supported. Please use symlinks for that scenario

**Comment by mcassaniti** [comment]
Do we want to support anything like this, say with something like `mkosi.overrides` that operate similar to match?

**Comment by DaanDeMeyer** [comment]
Not without a very good use case, config parsing is already complex as it is. For sharing configuration between presets, presets seem like a good enough option
