### ISSUE TITLE
--output behaves inconsistently with directories

### ISSUE THREAD

**Issue by davide125** [systemd/mkosi#1824]
Running something like `mkosi --distribution fedora --release 38 --architecture x86-64 --format directory --output x64` works just fine, but using `--output /tmp/x64` (or any other fully qualified path) instead fails with `‣ /tmp/x64 is not a valid filename`.

**Comment by DaanDeMeyer** [comment]
--output only configures the filename. --output-directory configures the output directory. Maybe we should rename --output to --output-name or so?

**Comment by davide125** [comment]
`--output-directory foo` works, but that's the _enclosing_ directory, so if you only pass that and don't pass output your tree ends up under `foo/image`. There doesn't seem to be a straightforward way to just say "put a tree under /foo/bar" which is what I want here.

**Comment by DaanDeMeyer** [comment]
That would be done using `--output-directory foo --output bar`. The reasoning behind this is that you can have multiple outputs so it felt more natural to split the output prefix (`--output`) and the output directory (`--output-directory`) into separate options. The other thing is that you generally end up reusing the output directory with different output prefixes when doing presets. But maybe we should look into translating output when given as a path into a separate directory and prefix automatically.

**Comment by davide125** [comment]
> But maybe we should look into translating output when given as a path into a separate directory and prefix automatically.

Yeah I think that would be nice. I understand the current behavior now, but for a user that's not familiar with it and just quickly wants a directory tree it's kinda confusing.
