### ISSUE TITLE
mkosi cleans inappropriate directory

### ISSUE THREAD

**Issue by webstrand** [systemd/mkosi#1835]
Systemd: 254.1-2
mkosi: 15.1

`mkosi clean` unexpectedly deleted the folder containing all of my configuration files.

### Steps to reproduce
```sh
mkdir -p /work/webdev

cat <<EOF > /work/webdev/mkosi.conf
[Output]
Format=directory
Output=webdev
EOF

cd /work
mkosi -C webdev clean

stat webdev # now missing
```

### Additional notes
The presence of `/work/webdev/mkosi.output` avoids this deletion. 

The presence of `/work/mkosi.output` does not avoid this deletion.

`-C` appears to be mis-documented

> mkosi switches to this directory before doing anything. 

but `mkosi` is clearly doing things in the directory it started from. Earlier a `tar` command was failing because of `mkosi`'s initial working directory.

**Comment by DaanDeMeyer** [comment]
Can you try the latest commit from main? This should be fixed already.

**Comment by webstrand** [comment]
Yep, already fixed in `main`. Should I prefer the development version over releases? I notice there seems to be a lot of breaking changes, it would be nice to get ahead of the cycle.
