### ISSUE TITLE
Using distro-provided secure boot shim

### ISSUE THREAD

**Issue by septatrix** [systemd/mkosi#1863]
Most (if not all) distributions supported by mkosi are capable of using a signed UEFI shim to enable secure boot usage. Is it possible to configure mkosi such that this shim is invoked?

This would make using this tools more useful for providing images to customers without requiring them to disable secure boot or manually enroll signing keys. With shim it would boot up even with secure boot enabled and then ask the user to trust the new keys whenever the signing key changes.

**Comment by septatrix** [comment]
If found a script in the Constellation repo which seems to [put shim before systemd-boot in the boot process](https://github.com/edgelesssys/constellation/blob/main/image/secure-boot/signed-shim.sh). Maybe this can be adjusted and incorporated into mkosi? I have not yet tried it though – maybe someone more knowledgeable in the generation of bootable images can say if this should work.

**Comment by behrmann** [comment]
I know that @DaanDeMeyer has done some work in that direction, this is why grub support was added back in #1797. Something like the thing linked above might already be achievable with a script.

**Comment by malt3** [comment]
I wrote the script in Constellation. The basic mechanism is this:

- The shim is placed in `/efi/EFI/BOOT/BOOTX64.EFI`
- `mmx64.efi` is placed under `/efi/EFI/BOOT/mmx64.efi`
- The next stage (`systemd-bootx64.efi`, grub or a UKI) is placed under `efi/EFI/BOOT/grubx64.efi` (This is where shim expects the next stage)

The implementation is pretty bad. It would be a lot cleaner to place files under `/efi` before repart runs.

**Comment by septatrix** [comment]
One aspect which came to my mind right now is that for these cases it would be good to have control over the UEFI variables. I.e. somehow tell mkosi to not load `/usr/share/OVMF/OVMF_VARS.fd` (it cannot be removed or overwritten with additional Qemu args) such that a custom file could be provided, or even better allow it to directly load `/usr/share/OVMF/OVMF_VARS.secboot.fd` if found which contains Microsoft's keys preloaded

**Comment by septatrix** [comment]
Steps which seem to be working:

1. Modified local mkosi installation to use the `OVMF_VARS.secboot.fd`
2. Generate local keypair using `mkosi genkey`
3. Convert the certificate to DER format `openssl x509 -in mkosi.crt -outform DER -out mkosi.crt.der`
4. Add `mkosi.finalize` script which puts everything in place
5. Generate image and boot it with qemu `mkosi qemu`
6. Shim will warn that authentication failed and prompt you to register your signing key.
7. Register the signing key and tell shim to reboot
8. Bootclt indicates that everything is working :tada:

```diff
--- .venv/lib/python3.11/site-packages/mkosi/qemu.py    2023-09-21 22:58:26.033742108 +0200
+++ /home/septatrix/Documents/programming/mkosi/mkosi/qemu.py   2023-09-22 01:15:19.766675584 +0200
@@ -101,7 +101,7 @@
 
 
 def find_ovmf_vars(config: MkosiConfig) -> Path:
-    OVMF_VARS_LOCATIONS = ["/usr/share/OVMF/OVMF_VARS.secboot.fd"]
+    OVMF_VARS_LOCATIONS = []
 
     if config.architecture == Architecture.x86_64:
         OVMF_VARS_LOCATIONS += ["/usr/share/ovmf/x64/OVMF_VARS.fd"]
```

```sh
#!/usr/bin/sh
# Finalize script

set -eux

cp "$BUILDROOT/usr/lib/shim/shimx64.efi.signed" "$BUILDROOT/efi/EFI/BOOT/BOOTX64.EFI"
cp "$BUILDROOT/usr/lib/shim/mmx64.efi.signed" "$BUILDROOT/efi/EFI/BOOT/mmx64.efi"
cp "$BUILDROOT/efi/EFI/systemd/systemd-bootx64.efi" "$BUILDROOT/efi/EFI/BOOT/grubx64.efi"
cp mkosi.crt.der "$BUILDROOT/efi/ENROLL_THIS_KEY.crt"
```

```
root@foobar:~# bootctl
System:
      Firmware: UEFI 2.70 (EDK II 1.00)
 Firmware Arch: x64
   Secure Boot: enabled (user)
  TPM2 Support: yes
  Boot into FW: supported

Current Boot Loader:
      Product: systemd-boot 252.12-1~deb12u1
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Load drop-in drivers
               ✓ Support Type #1 sort-key field
               ✓ Support @saved pseudo-entry
               ✓ Support Type #1 devicetree field
               ✓ Boot loader sets ESP information
         Stub: systemd-stub 252.12-1~deb12u1
     Features: ✓ Stub sets ESP information
               ✓ Picks up credentials from boot partition
               ✓ Picks up system extension images from boot partition
               ✓ Measures kernel+command line+sysexts
          ESP: /dev/disk/by-partuuid/a1b0caee-f57a-43d5-b84d-ad76cd3891de
         File: └─/EFI/BOOT/grubx64.efi

Random Seed:
 Passed to OS: no
 System Token: not set
       Exists: yes

Available Boot Loaders on ESP:
          ESP: /efi (/dev/disk/by-partuuid/a1b0caee-f57a-43d5-b84d-ad76cd3891de)
         File: ├─/EFI/systemd/systemd-bootx64.efi (systemd-boot 252.12-1~deb12u1)
               └─/EFI/BOOT/BOOTX64.EFI

No boot loaders listed in EFI Variables.

Boot Loader Entries:
        $BOOT: /efi (/dev/disk/by-partuuid/a1b0caee-f57a-43d5-b84d-ad76cd3891de)

Default Boot Loader Entry:
         type: Boot Loader Specification Type #2 (.efi)
        title: Debian GNU/Linux 12 (bookworm)
           id: mkosi-debian-6.1.0-12-amd64.efi
       source: /efi/EFI/Linux/mkosi-debian-6.1.0-12-amd64.efi
     sort-key: debian
      version: 12 (bookworm)
        linux: EFI/Linux/mkosi-debian-6.1.0-12-amd64.efi
      options: init=/usr/sbin/boot-maybe-install.sh pci=noaer
```

**Comment by DaanDeMeyer** [comment]
I'm pretty sure we won't want to implement this ourselves so we're probably waiting for https://github.com/systemd/systemd/issues/27234 to get resolved before we can do anything on this front.

**Comment by septatrix** [comment]
Regarding the finalize script I agree. It would be better if bootctl was capable of doing so, there is also an upstream discussion in the shim repo about discovering different bootloaders though sadly without any ETA.

Apart from that, however, I think two aspects can already be improved.

1. It should be possible to tell QEMU to load `OVMF_VARS.secboot.fd`. Currently this is only possible by patching mkosi. Passing them as separate `QemuArgs` does not seem to be able to override the previous definition.
2. Ideally, mkosi should be able to use keys in DER format. Otherwise two different formats of the same key would have to be stored in a vault and kept in sync (or only one stored but requiring every developer to convert it locally).

**Comment by septatrix** [comment]
> 1. It should be possible to tell QEMU to load `OVMF_VARS.secboot.fd`. Currently this is only possible by patching mkosi. Passing them as separate `QemuArgs` does not seem to be able to override the previous definition.

Maybe this could be added as an option to `QemuFirmware` introduced in v16? E.g. `QemuFirmware=OVMF-SecureBoot`

**Comment by DaanDeMeyer** [comment]
We have `ShimBootloader=` now, you can set to `signed` to install the distro secure boot shim.
