### ISSUE TITLE
systemd-boot package doesn't exist in Fedora

### ISSUE THREAD

**Issue by kerneis-anssi** [systemd/mkosi#1878]
The following line should be systemd-boot-unsigned I guess?

https://github.com/systemd/mkosi/blob/16c3f87c6ea117fd22a7b746df09b54d33c059de/docs/bootable.md?plain=1#L21

Cf. https://packages.fedoraproject.org/pkgs/systemd/systemd-boot-unsigned/

**Comment by DaanDeMeyer** [comment]
systemd-boot should be an alias to systemd-boot-unsigned. Can you give some more information? Fedora version at least might help here.

**Comment by kerneis-anssi** [comment]
Sorry, I have a non(-reliably)-reproducible bug where the `dnf install` step will fail with error 139 (target image: Fedora 38, host: Debian unstable). It seems to fail more often with `BuildPackages` than with `Packages`.

While trying to debug it it suddenly passed when I switched to systemd-boot-unsigned but that was a red-herring. I'll close this bug, and open a new one with the actual issue if I manage to get a minimal reproducible case.
