### ISSUE TITLE
using self-compiled packages or Fedora copr

### ISSUE THREAD

**Issue by fedelibre** [systemd/mkosi#189]
I'm currently using the postinst script to download a repository and build the binary of a software which is not packaged in Fedora. I don't like much this approach, as there's no cache and the download is always performed every time I run mkosi.

So I decided to write a spec and built an RPM package. How can I let mkosi use this local package?
Another option would be uploading the RPM to Fedora Copr. But I don't think mkosi can install packages from unofficial repositories, right?

**Comment by fsateler** [comment]
You can add the package to mkosi.extras. Or you could have it pre-installed there.

**Comment by fedelibre** [comment]
Having it preinstalled in mkosi.extra was the first choice I made. Then I preferred building the binary during the postinst, as I don't like adding binaries in my project repository.

When you say "add the package to mkosi.extras", it means that I should just copy the RPM file somewhere and then it's up to the user to install it?
It's not what I want.

I think I'll stay with the postinst script.

Installing a package from Copr would be cool.

**Comment by fedelibre** [comment]
This morining I woke up with the idea of downloading the .rpm file within `mkosi.extra/` ("gitignoring" .rpm files and using a Makefile to download the files needed) and then installing the .rpm in the mkosi.postinst.

But skeleton tree is way better. I'll wait for the pull request to be merged. Thanks @lucasdemarchi !
