### ISSUE TITLE
How to specify multiple architectures?

### ISSUE THREAD

**Issue by fwilhe2** [systemd/mkosi#1891]
Hi,

[the docs say](https://github.com/systemd/mkosi/blob/main/mkosi/resources/mkosi.md#distribution-section) "A number of architectures can be specified", but I don't seem to understand how this can be configured.

I tried:

`mkosi --architecture=x86-64,arm64`

This throws an error:

> mkosi: error: argument --architecture: invalid choice: 'x86-64,arm64' (choose from 'alpha', 'arc', 'arm', 'arm64', 'ia64', 'loongarch64', 'mips-le', 'mips64-le', 'parisc', 'ppc', 'ppc64', 'ppc64-le', 'riscv32', 'riscv64', 's390', 's390x', 'tilegx', 'x86', 'x86-64')

and

`mkosi --architecture=x86-64 --architecture=arm64`

This only builds the arm64 image.

I've tried to find examples and looking into the code, but I don't seem to be able to understand how I need to call mkosi to build two images in one call. Is this supported? What is the correct syntax?

Thanks.

**Comment by behrmann** [comment]
This can be achieved using presets and setting the architectures (and arch specific things like certain packages) in the preset files.

**Comment by fwilhe2** [comment]
Hi @behrmann, thanks for the quick reply.

It seems like in my case I don't need architecture specific packages.

Is there any actual example for how to do this? Seems a bit harder than it should be to me. I'd appreciate if the manpage was a bit more verbose for such things.
