### ISSUE TITLE
RFE: Add support for "none" distro

### ISSUE THREAD

**Issue by snickl** [systemd/mkosi#1929]
Basically #111 again, which was closed with "we have support for skeleton tarballs now so let's close this".

Which seems great except for that apparently mkosi still can't be invoked without a distro, something like _-d none_ or [NOP](https://github.com/systemd/mkosi/issues/111#issuecomment-335534321). Therefore the use case for using a rootfs that was pre-built with something like yocto or buildroot seems still unmet.

**Comment by DaanDeMeyer** [comment]
Happy to take PRs for this. I would implement this by implementing a DistributionInstaller subclass that just doesn't do anything and then leave it up to a mkosi.prepare script to initialize the rootfs by copying it to $BUILDROOT

**Comment by snickl** [comment]
Closed with #1932
