### ISSUE TITLE
Add $MKOSI_USER, $MKOSI_GROUP and $MKOSI_HOME

### ISSUE THREAD

**Issue by 4nd3r** [systemd/mkosi#1930]
In specific situations, I need to access the login name, primary group name, and the user's home directory (`$HOME`) within the postinst script. Right now, I have to pass these values through the command line and list them in `mkosi.conf`. However, having these values readily accessible by default would make things simpler for me and could be beneficial for others as well.

If someone more familiar with the code base thinks it's good idea, I'm willing to try and submit PR myself.

**Comment by DaanDeMeyer** [comment]
You can run `mkosi-as-caller id` in a script to get the necessary information. Exposing this information as environment variables seems a bit much, we generally don't want to leak this information into the build. Let's close the issue as the necessary information is available.
