### ISSUE TITLE
libosinfo metadata support

### ISSUE THREAD

**Issue by fedelibre** [systemd/mkosi#197]
[GNOME Boxes](https://wiki.gnome.org/action/show/Apps/Boxes) uses [libosinfo](https://libosinfo.org/) to search metadata and automatically identify what operating system an ISO image is for. This allows Boxes to name a new box with a sensible name, like `debian-9`. If a file is without metadata, the box will be named `boxes-unknown`.

This is also the name visible in virsh, e.g.:

    $ virsh list --all | grep unknown
     -     boxes-unknown-2                shut off

I've just made a test on an image I've built with mkosi and here's what I get:

    $ osinfo-detect my-file.raw 
    Error parsing media: Insufficient metadata on installation media

**Comment by poettering** [comment]
but where does osinfo pull that data from? why not just parse /usr/lib/os-release or so?

**Comment by fedelibre** [comment]
The manual of osinfo-detect says:

> By default "PATH" or "URI" will be interpreted as pointing to ISO media. To request examination of an install tree instead, the option "--type=tree" should be given.

I don't know where osinfo pulls the data from when using the default type (media), but look at this error message when using the tree type :

    $ osinfo-detect --type=tree my-tree-container/
    Error parsing installer tree: Failed to load .treeinfo file: Operation not supported

**Comment by lucaswerkmeister** [comment]
As far as I can tell from the documentation on `OsinfoLoader` (which is apparently not available online, you have to install the package), the database is loaded from “a set of XML documents”.

**Comment by poettering** [comment]
So, yeah, the way I understood libosinfo it's supposed to be a big database of OS image metadata, plus a way to match up with the images at hand. It would be kinda cool if it could deal with mkosi images, but afaics that needs to be added to libosinfo itself, and it's nothing we can add to mkosi.

Note that mkosi doesn't actually create any exotic images. It's just GPT images (using the GPT partition types from the discoverable partitions spec), and the images carry the typical OS metadata: /usr/lib/os-release, /etc/machine-id, /etc/machine-info and /etc/hostname. if libosinfo understands those it should have all it needs.

**Comment by zeenix** [comment]
what @poettering said. :)

**Comment by fedelibre** [comment]
I've opened a feature request here: https://bugzilla.redhat.com/show_bug.cgi?id=1513079

**Comment by berrange** [comment]
FYI, libosinfo currently detects ISO images by matching metadata in the ISO9660 headers. 

ie if you run 'isoinfo -d -i <ISOFILE>' it displays things like "Volume ID", "Publisher ID", etc. The libosinfo database files for each operating system we know, contain regexes that match against these header fields.

So if you're just creating custom ISO images off an existing well know OS, eg a custom spin of Fedora. The simplest approach is to just set the ISO header fields to match official media, such that they match existing rules libosinfo has for that OS.

If you're creating a custom ISO image that is of an OS that is not known to libosinfo at all, that pretty much requires adding extra data files to the osinfo database. This can be done by users / sysadmins locally if they want to override what's shipped by default.

**Comment by lucaswerkmeister** [comment]
Well, we’re creating images of well-known OSes (a limited set of supported distributions), but we don’t have an ISO output format – only raw GPT disc image, sub{directory,volume}, and tarball. Can libosinfo extract metadata from (some of) those formats?

**Comment by berrange** [comment]
Ah, I misinterpreted what it was doing. So libosinfo currently only tries to identify installation media (ISOs) and installation trees (ie network install locations). We've never attempted todo identification of built disk images. Libguestfs, however, *does* have code for inspecting guest disk images to identify the OS, and it works as Lennart suggest where by it reads key identifying files from inside the guest disk image.

**Comment by berrange** [comment]
IOW, the simplest approach right now is probably for GNOME Boxes to just use the libguestfs APIs to inspect the disk image.

**Comment by fedelibre** [comment]
I've opened [issue 790505 on GNOME Bugzilla](https://bugzilla.gnome.org/show_bug.cgi?id=790505)
