### ISSUE TITLE
--depth is ignored in local clones

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/mkosi#199]
I noticed this warning scroll past during an mkosi build:

> ‣ Copying in build script and sources...
> Cloning into '/var/tmp/mkosi-9ruhr8hg/root/root/src'...
> warning: --depth is ignored in local clones; use file:// instead.
> done.
> ‣ Copying in build script and sources complete.

I guess `copy_git_files` should rewrite the `src` argument to a `file://` URL? (And presumably then add `--local` because it’s no longer implied.)

CC @lucasdemarchi and #123.

**Comment by lucaswerkmeister** [comment]
> (And presumably then add --local because it’s no longer implied.)

Um, or perhaps I’m stupid – the warning says “local clones” :)

So I guess we choose a tradeoff? Either pass `--no-local` or drop the `--depth`?

**Comment by lucasdemarchi** [comment]
For local clones it's better just to clone the entire repo since it will share the storage. This is not true if it is traversing a mount point.... for getting rid of the warning we would need to try and check if the clone will be local to the filesystem or not.

**Comment by lucaswerkmeister** [comment]
I’m not sure I follow… in my case, the local source tree and the target directory were on different mount points. In this case, you’re saying the clone shouldn’t be treated as local, because the storage can’t be hardlinked anyways?

**Comment by poettering** [comment]
Since #232 got merged we don't use "git clone" for copying files anymore. Hence I figure we can close this one now.
