### ISSUE TITLE
Better cater to outputs for `systemd-sysupdate`

### ISSUE THREAD

**Issue by septatrix** [systemd/mkosi#2024]
When using systemd-sysupdate in an A/B style, the UKIs needs to know which partition to boot to. This can be achieved by setting the roothash or usrhash kernel command line option and labeling the partition fittingly. However, there is no way to model this in mkosi with the static `KernelCommandLine=` option. 
It is already possible to split the base system and united generation into two different presets/images and have one depend on the other though this is pretty much where I am stuck currently. Having mkosi better support this use case would allow one to pretty much implement everything from Lennarts "fitting everything together" post with mkosi.

There is also the problem that depending on the sysupdate.d setup the partition files generated when `SplitArtifacts=true` should include parts of the hash but that can be implemented with some rather trivial scripting. Bundling, signing and all the other steps for generating a UKI though are way harder to script.

**Comment by septatrix** [comment]
x-ref: https://github.com/systemd/systemd/issues/29722

**Comment by DaanDeMeyer** [comment]
@septatrix We automatically do the roothash/usrhash stuff in mkosi when required. This isn't documented but please check the sources

**Comment by septatrix** [comment]
Okay I found it. Is there any reason for not doing it for partitions without a hash, i.e. why use `finalize_roothash` instead of `finalize_root` which would also help to append the partition UUID for writeable root partitions?

**Comment by DaanDeMeyer** [comment]
@septatrix Because we generally want to rely on systemd-gpt-auto-generator instead of explicit `root=` on the kernel command line so we don't use it unless required.

**Comment by septatrix** [comment]
systemd-gpt-auto-generator however reaches its limits when finding the root partition belonging to a UKI if it is writeable. In those cases `roothash` cannot be used. Though I am aware that A/B style updates with a writeable root partition are likely not that widespread.

**Comment by septatrix** [comment]
If you do not plan to support that usecase please feel free to close this issue. I will likely manage with the small patch of replacing `finalize_roothash` with `finalize_root`

**Comment by septatrix** [comment]
> We automatically do the roothash/usrhash stuff in mkosi when required. This isn't documented but please check the sources.

I think I got most of this running as expected. One thing came up, however: sysupdate wishes for the partuuids to be included in the filename `SplitName=%U.%t`. Could mkosi maybe set this as a default or is that not possible? Currently I have simply set in inside the repart.d whiles which also works though having this be set by systemd would be a better OOTB experience.

**Comment by septatrix** [comment]
Or is this something which should be implemented in repart itself? E.g. if a partition definition has a `VerityMatchKey=...` set it defaults to `%U.%t` and otherwise to `%t`?

**Comment by septatrix** [comment]
Another thing I noticed and wasted way too much time on to figure out. The final filename of the split partitions depends on the name of the loopback device and the `SplitName=` configured in the `repart.d` definitions. This means that something like `SplitName=%U.%t` would result in `FoobarOS_1.0.0.3e3a(...some uuid).usr-x86-64-verity.raw`.
sysupdate however gets confused by the version number and subsequent UUID starting with a number. This means that artifacts have to be manually renamed. While this is not too hard, this also means that the generated `SHA256SUMS` file is essentially useless, including the automatic signing.

It would be great if the separator would instead be an underscore (to archive the same syntax as shown in the sysupdate man page `foobarOS_@v_@u.verity.xz`) though this seems to be hardcoded in repartd. Maybe mkosi could rename the files?

**Comment by septatrix** [comment]
> @septatrix Because we generally want to rely on systemd-gpt-auto-generator instead of explicit `root=` on the kernel command line so we don't use it unless required.

It has just come to my attention that Ubuntu [no longer ships with systemd-gpt-auto-generator](https://git.launchpad.net/~ubuntu-core-dev/ubuntu/+source/systemd/commit/?id=a366279a84730e92ed734710560ea833709f359d) since 253.5-1ubuntu5. I have [filed a bug upstream*](https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/2046459) though if they are unwilling to revert the change this will no longer work for Ubuntu.

*downstream? Upstream of mkosi but downstream of systemd/Debian :D

**Comment by DaanDeMeyer** [comment]
We're working with the ubuntu systemd maintainer to get it added back for the next LTS release.

**Comment by michaelbeaumont** [comment]
@DaanDeMeyer would you accept a feature that allows the user to choose to add an explicit `root`/`/usr` parameter? I.e. call `finalize_root` instead of `finalize_roothash`?

The only complication I see is if `Encrypt=yes` is set, I think that would need to be taken into account somehow, or duplicated in `mkosi.conf`, so we can set `cryptdevice` as well.

I don't see a way to rely on DDI in the case of A/B partitions if not using `dm-verity` partitions. Maybe "just use `dm-verity`" is the answer but then, `dm-verity` needs to be supported with `Encrypt=yes`. Which I believe is already on the systemd-repart TODO.

**Comment by mcassaniti** [comment]
There's a large post [here](https://github.com/systemd/mkosi/issues/1638#issuecomment-2116336263) covering UKI naming, but it also spans into other `systemd-sysupdate` details. While the output names should include the partition UUIDs, they do need to include the version as well.

**Comment by mcassaniti** [comment]
I have to retract my statement above. I mis-configured and had `SplitName = %U.%t` rather than `SplitName = %A.%U.%t` in my `repart.d` files which includes all the relevant details now (version, UUID and partition type).

**Comment by septatrix** [comment]
Another feature desirable for sysupdate would be to have the unit presets being applied to `/usr` instead of `/etc`. I opened discussion #2790 for that with more of an explanation

**Comment by DaanDeMeyer** [comment]
I don't think we're going to be changing these defaults to accomodate systemd-sysupdate so I'm going to close this issue. Instead, using https://github.com/systemd/particleos as an example of how to configure mkosi to generate outputs compatible with systemd-sysupdate seems like it will be sufficient.

mkosi is also gaining native support for systemd-sysupdate in https://github.com/systemd/mkosi/pull/3011.

**Comment by septatrix** [comment]
> I don't think we're going to be changing these defaults to accomodate systemd-sysupdate so I'm going to close this issue.

With `UnifiedKernelImageFormat=` implemented I agree that this is pretty much done on the mkosi side. The remaining things are settings where changing the default makes little sense (e.g. `SplitArtifacts=`) or shortcomings of other parts of the systemd ecosystem. I will link (those that I know of) here:

- https://github.com/systemd/systemd/issues/29722
  Some general points raised by Daan
- https://github.com/systemd/systemd/issues/30558
  `sd-repart` and `sd-sysupdate` use incompatible file naming conventions which necessitates stupid split names like `_%U.%t` where the underscore is necessary to stop `sd-sysupdate` from picking up the UUID is part of the version because normally `sd-repart` prepends the loopback name with a dot as a separator. This discrepancy should be fixed
- https://github.com/systemd/systemd/issues/33373
  Based on the original discussion in the repo: #2790
  Currently one has to manually watch out that adding new units or changing the default state (enabled/disabled) for them is correctly picked up which is currently not the case. Allowing to automatically ship that under `/usr` would fix that.

These, I think, would be the most important ones to facilitate easier sysupdate usage in combination with mkosi.

> Instead, using https://github.com/systemd/particleos as an example of how to configure mkosi to generate outputs compatible with systemd-sysupdate seems like it will be sufficient.

Is that intended to be a reference project showing best practices and what mkosi is capable of?
If that is the case I would have a few ideas:

1. Link the project in the readme or somewhere else. It is currently not easy to discover and I have not heard of it even though it seems to be almost a year (or has it only been public since recently?)
2. Add your GH action to build the image
3. Include some kind of installer. Currently mkosi is easy to use for VMs/nspawn or flashing directly to disk (e.g. SD card) but a PITA with intermediate media (e.g. flash install media to USB which is booted and used to install image to internal SSD/flash). Ideally [`systemd-installer-generator`](https://github.com/systemd/systemd/pull/27792) will be implemented some day but that is currently stalled and anything else is pretty hard to get correct. I had a few attempts but they all are quite complicated and integrate poorly with mkosi (especially since the subimage change) and have to work around some bugs by manually performing work which e.g. `sd-repart` should handle :/
  https://github.com/systemd/systemd/issues/32029
  https://github.com/systemd/systemd/issues/31381
