### ISSUE TITLE
Traceback at end of `mkosi` run

### ISSUE THREAD

**Issue by Winterhuman** [systemd/mkosi#2066]
Host distribution: Arch Linux
`uname`: Linux 6.6.1-arch1-1 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux
`mkosi` version: v18

# Description

After successfully running `mkosi`, as in it outputs everything as expected before the error, it sometimes exits with this traceback depending on the config (it's unclear what configuration changes cause this):

```
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mkosi/__main__.py", line 48, in main
    run_verb(args, presets)
  File "/usr/lib/python3.11/site-packages/mkosi/__init__.py", line 2514, in run_verb
    os.chown(p, uid, gid, follow_symlinks=False)
PermissionError: [Errno 1] Operation not permitted: '/home/user/Public/OSmaker/mkosi.output/.#TestOs.raw.lck'
```

I have no idea what information to provide debug wise, but, I'm happy to help debug this if needed.

**Comment by DaanDeMeyer** [comment]
Can you try with git main? I'm pretty sure we've already fixed it.

**Comment by Winterhuman** [comment]
Tried again with `bin/mkosi` after using the `git clone` method, and I wasn't able to reproduce the traceback. Closing issue, sorry about that
