### ISSUE TITLE
Revert to default settings from command line options

### ISSUE THREAD

**Issue by uningan** [systemd/mkosi#207]
I want to integrate mkosi with a CI pipeline so I need to ignore some customer settings from mkosi.default file

For instance: I need to output the artifacts to a fixed output (/tmp/output) to process there. But if customer has an fqdn output in Output setting then --output-dir is ignored.

Maybe something like this can make the work:
mkosi -C /tmp/input --output-dir=/tmp/output --output=""

Have any sense? Or maybe I must to sanitize the .default before run mkosi?

**Comment by poettering** [comment]
hmm i figure supporting --output="" would make sense to have. patches very welcome!
