### ISSUE TITLE
Using `-if` ignores `--force`, unlike `-fi`

### ISSUE THREAD

**Issue by Winterhuman** [systemd/mkosi#2075]
Host OS: Arch Linux
`uname`: Linux 6.6.1-arch1-1 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux
`mkosi`: v19

# Description

While `mkosi -fi` succeeds as expected, `mkosi -if` will fail as if `-f` wasn't passed:

```
~/mkosi/bin/mkosi -if
‣ Output path OUTPUT exists already. (Consider invocation with --force.)
```

**Comment by DaanDeMeyer** [comment]
This is rather hard to fix since python's argparse considers the f an argument to the -i option in this case.

**Comment by Winterhuman** [comment]
Could this be hacked around by handling single character arguments in a special way? For example: It's already read as `-i=f`, but then, you make the `f` "argument" be interpreted as implying `--force`.

**Comment by DaanDeMeyer** [comment]
@Winterhuman I don't think python's argparse lets us do that.
