### ISSUE TITLE
Fix `KernelModules*` options with `Bootable=no`

### ISSUE THREAD

**Issue by Winterhuman** [systemd/mkosi#2076]
Host OS: Arch Linux
`uname`: Linux 6.6.1-arch1-1 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux
`mkosi`: v19

# Description

After a discussion in [the mkosi Matrix room](https://matrix.to/#/#mkosi:matrix.org), it was found that `Bootable=no` unintentionally causes the `KernelModule*` options to be ignored, hence the previous issue description about those options not responding to any values.

# Old description

I've tried every pattern I can think of for `KernelModulesExclude` so it would exclude all modules by default, except those specified by `KernelModulesInclude`, however, nothing works (`*`, `.*`, `/.*`, `.*/.*`, `[^\n]+`, `/(.*?)`, etc).

As far as I understand, at least one of these patterns *should* work. Whatever the syntax is, I propose adding an "ALL" keyword (or whatever is most sensible to implement this) for matching all kernel modules. Unless I've missed a really obvious pattern, which is likely...

**Comment by behrmann** [comment]
Is `KernelModulesExclude=` the right thing for your use case or do you maybe need `KernelModulesInitrdExclude=`?

**Comment by Winterhuman** [comment]
I tried the Initrd and non-Initrd versions and it didn't work, though yes, I am using `Format=uki` and `MakeInitrd=no` similar to my previous issue. Here's the config:

```
[Distribution]
Distribution=arch
PackageManagerTrees=mkosi.pkgmgrtree

[Content]
MakeInitrd=no
Bootable=no
KernelCommandLine=
	systemd.volatile=overlay

Packages=
	base
	dracut
	linux
	linux-firmware
	util-linux
	systemd

RemoveFiles=
	/usr/share/man
        /usr/lib/libgfortran.so*
        /usr/lib/libgo.so*
        /usr/lib/libgomp.so*
        /usr/lib/libgphobos.so*
        /usr/lib/libobjc.so*

KernelModulesInitrdExclude=.*
KernelModulesInitrdInclude=
	arch/x86/crypto/aesni-intel.ko.zst
	# There's more modules than this in my config,
	# but, this should work as a demonstration.

[Output]
Format=uki
CompressOutput=zst
ImageId=ukios

[Host]
QemuMem=3G
QemuFirmware=uefi
```

**Comment by Winterhuman** [comment]
Okay, so it turns out removing `Bootable=no` from the config fixes the issue, which actually disables the kernel module stuff. From there `.*` works as expected
