### ISSUE TITLE
`CompressOutput=` should also apply to kernel EFI

### ISSUE THREAD

**Issue by septatrix** [systemd/mkosi#2085]
The compress output option is rather useful when one wants to push the artifacts directly to a server to be used with sysupdate or similar software. However, the efi file is for some reason not affected by this flag. This inconsistency leads to an additional step being necessary.

The same also holds true for the initrd and vmlinuz files though these are not used for sysupdate and are thus not relevant for me. For consistency it might also make sense to compress these too.

**Comment by septatrix** [comment]
Also is it possible to customize the output name and include (most importantly) the architecture?

**Comment by DaanDeMeyer** [comment]
It doesn't make sense to compress the UKI because it consists almost entirely out of compressed components already, so compressing it again gives little to no value.

**Comment by DaanDeMeyer** [comment]
Closing this as these files are not outer compressed and it doesn't make sense to do so or name them as if they were. Either sysupdate will have to be made more flexible or an intermediate step will be needed to make mkosi's output fit the model needed by sysupdate.
