### ISSUE TITLE
Separate enrollment of securebootkeys from `SecureBoot=`

### ISSUE THREAD

**Issue by Cornelicorn** [systemd/mkosi#2169]
I would like to enroll my own set of secureboot keys, containing the mkosi secure boot certificate instead of just the mkosi certificate while still signing the mkosi-built UKI during invocation of mkosi.

The goal is to have an image, which is updatable and will sign new UKIs with a key contained inside the image, but still use secureboot on the first boot with the UKI from mkosi. For this I need both secureboot certificates in the store and not just the one used by mkosi.

The easiest thing I could see would be to add an option `SecureBootAutoenroll=` which takes a bool or auto and replace the condition [here](https://github.com/systemd/mkosi/blob/a59ccdefd7f1b8d6cae88f28eb276cff00e770fe/mkosi/__init__.py#L810) with that option. `auto` would be the default and enable enrollment if `SecureBoot` is enabled.

**Comment by DaanDeMeyer** [comment]
Feel free to submit a PR. No need for `auto`, we'll just ignore `SecureBootAutoEnroll=` if `SecureBoot=` is disabled.
