### ISSUE TITLE
Wrong MKOSI_UID and MKOSI_GID values?

### ISSUE THREAD

**Issue by 4nd3r** [systemd/mkosi#2218]
Using main branch on Debian Sid. Running as regular user.

I get `MKOSI_UID=65436` and `MKOSI_GID=65436` in postinst and postinst.chroot scripts, but they should be 1000 and 100 respectively. No?

Also, there's no such uid nor gid in my system. What am I missing here?

**Comment by DaanDeMeyer** [comment]
We use user namespaces to do unprivileged image builds. These use uids from the uid range for your user in /etc/subuid. The uid in $MKOSI_UID is mapped to your user's uid on the host.

**Comment by 4nd3r** [comment]
OK, got it.
