### ISSUE TITLE
Revise etc/alternatives mounting

### ISSUE THREAD

**Issue by Cornelicorn** [systemd/mkosi#2247]
I just noticed an unforeseen problem with #2228: When using a toolstree, this can cause problems.

In my example, I had awk symlinked to `/etc/alternatives/awk`, which points to `gawk`. When I use the default tools tree, this breaks since `gawk` is not installed in there (mawk and nawk are, so there is something to provide awk after all). This again breaks validation of `/etc/apt/trusted.gpg.d`.

**Comment by DaanDeMeyer** [comment]
@Cornelicorn I fixed this in #2223 by using /etc/alternatives from the tools tree if one is provided, can you give that branch a try?

**Comment by Cornelicorn** [comment]
> @Cornelicorn I fixed this in #2223 by using /etc/alternatives from the tools tree if one is provided, can you give that branch a try?

Yep, that fixes it.
