### ISSUE TITLE
xz compression speed

### ISSUE THREAD

**Issue by alexlep** [systemd/mkosi#227]
Hi,

once _--xz_ flag is passed, **xz** command is launched to compress the image:
```
    with complete_step('Compressing image file'):
        f = tempfile.NamedTemporaryFile(prefix=".mkosi-", dir=os.path.dirname(args.output))
        run(["xz", "-c", raw.name], stdout=f, check=True)
```
But it uses only one core for compression:
```
root@sd-122375:~# time -p sh -c 'xz -c debian-stretch-latest.img > compressed.xz'
real 649.13
user 647.00
sys 1.69
```
I think it should be replaced, at least, with pxz:
```
root@sd-122375:~# time -p sh -c 'pxz -c debian-stretch-latest.img > compressed'
real 120.74
user 661.84
sys 3.36
```
Or **mkosi** should use **pxz** if it's available in the build environment. Otherwise **xz** should be taken and maybe some warning should be raised before compression.
Difference in sizes of resulting archives:
```
root@sd-122375:~# ls -altrh compressed*
-rw-r--r-- 1 root root 154M Jan 31 01:46 compressed
-rw-r--r-- 1 root root 153M Jan 31 01:58 compressed.xz
```

**Comment by lucaswerkmeister** [comment]
`pxz` isn’t even available in the official repositories on Arch, so `mkosi` definitely shouldn’t require it IMO, and the fallback to `xz` should, at most, print an unintrusive note about it (not a warning).
