### ISSUE TITLE
Debian-based distributions fail to build on non-debian systems since `v20`

### ISSUE THREAD

**Issue by msanft** [systemd/mkosi#2308]
Hey! Unfortunately, I'm still facing some issues when trying to fetch Ubuntu repositories in my image build.

I'm making the Ubuntu archive keyrings available in `/etc/apt/trusted.gpg.d` via `mkosi.skeleton`. When getting a shell into the image build, these files are present in the correct directory in the image. Now, with mkosi `v20`, the image build fails with the following:

```console
‣  Installing Ubuntu
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]            
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Err:1 http://archive.ubuntu.com/ubuntu jammy InRelease            
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Err:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Err:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Reading package lists... Done
W: GPG error: http://archive.ubuntu.com/ubuntu jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
E: The repository 'http://archive.ubuntu.com/ubuntu jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://archive.ubuntu.com/ubuntu jammy-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
E: The repository 'http://archive.ubuntu.com/ubuntu jammy-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://security.ubuntu.com/ubuntu jammy-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
E: The repository 'http://security.ubuntu.com/ubuntu jammy-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

while with mkosi `v19`, the build suceeds. While trying to debug, with mkosi `v20`, `apt-*` commands (i.e. `apt-config`, `apt-get`, ...) fail with `E: Unable to determine a suitable packaging system type`, which probably is caused by [this check](https://salsa.debian.org/apt-team/apt/-/blob/main/apt-pkg/deb/debsystem.cc#L321). 

When bisecting, I pinned the build failure down to [this commit](https://github.com/systemd/mkosi/commit/13d9dc64e9f4335a946fba268311952a3a431f03), however I'm not a 100% sure whether this introduced the actual bug, as the failure I see when building from it seems unrelated: `bwrap: execvp sh: No such file or directory`.

Do you have any advice on how to debug this further?

**Comment by DaanDeMeyer** [comment]
Can I have the full logs when mkosi is run with `--debug`?

**Comment by msanft** [comment]
> Can I have the full logs from v20 when mkosi is run with --debug?

Sure, I put them into [this gist](https://gist.github.com/msanft/e0bc2d7bb0ead536a41750e2c075ffff).

> Can you also check if this reproduces when running from mkosi git?

When running from main (`33421f2497d88e87567bcffc986252d07277f190`), I run into the same problem.

**Comment by DaanDeMeyer** [comment]
@msanft Can you try #2309? That should at least let you get a little further so we can figure out the real problem if it doesn't fix it completely.

**Comment by msanft** [comment]
Thanks @DaanDeMeyer. Unfortunately, that doesn't fix it yet. Still running into:
```console
sh-5.2# apt-config
E: Unable to determine a suitable packaging system type
```

[Full Debug Logs](https://gist.github.com/msanft/0b6d69c134374dd8d71a1904606e7001)

**Comment by DaanDeMeyer** [comment]
@msanft Your latest logs don't show "E: Unable to determine a suitable packaging system type"?

**Comment by msanft** [comment]
Sorry, should have clarified this. The logs are from running `mkosi --debug`, while the `E: Unable to determine a suitable packaging system type` error is shown when running `apt-*` commands in the `--debug-shell` of the build.

**Comment by DaanDeMeyer** [comment]
@msanft mkosi is failing because `RepositoryKeyCheck=` does not seem to be disabled so we don't add the corresponding apt options.

apt commands are failing because they need to be executed with a bunch of options and environment variables which you don't set when calling these. When running scripts we intercept apt to set these but we don't do that in the debug shell for these commands.

**Comment by msanft** [comment]
> apt commands are failing because they need to be executed with a bunch of options and environment variables which you don't set when calling these. When running scripts we intercept apt to set these but we don't do that in the debug shell for these commands.

Ah. Got it. Thanks a lot!

> mkosi is failing because RepositoryKeyCheck= does not seem to be disabled so we don't add the corresponding apt options.

This should not fail though, no matter what the option is set to, as the keys are available within `mkosi.skeleton/etc/apt/trusted.gpg.d`, right?

**Comment by DaanDeMeyer** [comment]
> This should not fail though, no matter what the option is set to, as the keys are available within mkosi.skeleton/etc/apt/trusted.gpg.d, right?

Using those directories is deprecated. mkosi picks up the keys from /usr/share/keyrings/ubuntu-archive-keyring.gpg

**Comment by msanft** [comment]
Thank you, and sorry for not picking this up earlier! With moving the keys to `mkosi.skeleton/usr/share/keyrings/ubuntu-archive-keyring.gpg`, it works on `main`. I assume your fix is not necessary, then. Still thanks a ton for your support here!
