### ISSUE TITLE
Proper way to create an unpriviledged user?

### ISSUE THREAD

**Issue by fwilhe2** [systemd/mkosi#2320]
Hi,

I'm wondering what the recommended way is to create an unprivileged user in my image? By default, only a root user is created as far as I can tell.

I see that [there is special handling for the `adduser` command](https://github.com/systemd/mkosi/blob/dc94177f3c57152770cb1c2316f971f6732d9525/mkosi/resources/mkosi.md?plain=1#L1947) which suggests that I should use that.

I've been using this in a `mkosi.postinst` script like so:

```bash
#!/bin/bash

useradd --user-group --create-home --shell=/usr/bin/bash --password='mypwd' user
```

which seems to work okay, but I'm wondering if this is the 'right'/idiomatic way to do it. I could not find more hints in the docs or example projects.

Might be related to #1930, but I'm not sure.

I'd appreciate a little docs snippet on that issue.

Thanks

**Comment by Vasu77df** [comment]
[sysusers.d ](https://www.freedesktop.org/software/systemd/man/latest/sysusers.d.html) is my recommendation to setup a unprivileged system user or groups. You can place a sysusers.d config file the `mkosi.extra` tree and in step 16 in the [mkosi execution workflow](https://github.com/systemd/mkosi/blob/main/mkosi/resources/mkosi.md#execution-flow) will setup the user for you. 

Note that this is a good declarative method to setup system users. If you want to setup a regular user with password but in a declarative method, You might be able to combine sysusers.d and systemd-firstboot to set the password on first boot, or you can setup the password for the user you create after the OS is booted.

**Comment by fwilhe2** [comment]
Thanks for sharing @Vasu77df, I think I came across sysusers before but I didn't remember it.

Yes I'm looking for ways to create a user for interactive usage. Not sure if it really needs to have a password. Essentially what I'm looking for is something that's similar to vagrant or lima-vm where either a default user with a known default password, or with no password exists.

**Comment by DaanDeMeyer** [comment]
In systemd git main @poettering added systemd-homed-firstboot.service which will prompt to create a regular user on first boot.

To make a regular user part of the image, `useradd` should be used. `sysusers` is intended for system users and doesn't properly set up regular users yet.

**Comment by DaanDeMeyer** [comment]
See the linked PR for a full snippet

**Comment by fwilhe2** [comment]
Thank you, that's the FAQ I was looking for :+1:
