### ISSUE TITLE
Hard to debug processes in sandbox

### ISSUE THREAD

**Issue by akihikodaki** [systemd/mkosi#2329]
Hi,

I'm trying mkosi for QEMU development and it does its job well.
One thing I found troubling though is that mkosi runs things in a sandbox. This makes debugging QEMU difficult in several ways:
- No core dumps are generated when processes abort.
- Requires some `nsenter` tricks to ptrace processes in the sandbox.
- Lacks access to files not used in normal execution.

An obvious option to fix this is to add an option to disable the sandbox.

**Comment by DaanDeMeyer** [comment]
@akihikodaki We already use a relaxed sandbox when we invoke qemu where access to most files is allowed. Which files are missing that you want to access in the sandbox?

**Comment by akihikodaki** [comment]
@DaanDeMeyer I was incorrectly assuming QEMU has a strict sandbox like other processes. Accessing external files for debugging should not be a problem, at least for QEMU.

**Comment by DaanDeMeyer** [comment]
@akihikodaki We also do not unshare the PID namespace (anymore) so ptrace should work out of the box? If not it'd be great if you could add more detail on why ptrace on the host doesn't work.

As for coredumps, AFAIK those should also just work. If they don't that's definitely something we need to fix.

**Comment by DaanDeMeyer** [comment]
@akihikodaki If I run `kill -s ABRT <qemu-pid>` followed by `coredumpctl -r`, I see a qemu coredump at the top of the list, so coredumps seem to work as well.

**Comment by DaanDeMeyer** [comment]
And doing `strace -p <qemu` seems to work without problems as well.

**Comment by DaanDeMeyer** [comment]
Let's close this as all reported issues seem to work as expected. Feel free to leave a comment if you have more questions.
