### ISSUE TITLE
mkosi unable to detect grub-mkimage binary name variation in fedora

### ISSUE THREAD

**Issue by nameOfUser0236** [systemd/mkosi#2332]
When building a fedora image with BIOS support, mkosi is unable to find the "grub-mkimage" binary do to it being named "grub**2**-mkimage"

> A BIOS bootable image with grub was requested but grub-mkimage was not found

https://github.com/systemd/mkosi/blob/9857f5b01a9f37cd1d002fe68098b8c24875e869/mkosi/__init__.py#L1108-L1113

**Comment by DaanDeMeyer** [comment]
@nameOfUser0236 

You might want to check the implementation of `find_grub_binary()` as well:

```
def find_grub_binary(binary: str, root: Path = Path("/")) -> Optional[Path]:
    assert "grub" in binary and "grub2" not in binary
    return find_binary(binary, binary.replace("grub", "grub2"), root=root)
```

So this should find `grub2-mkimage`. Please verify that it is installed somewhere that we can find it.

**Comment by DaanDeMeyer** [comment]
Note that the grub tools need to be installed on the host system, not in the image for us to find them.

**Comment by nameOfUser0236** [comment]
> Note that the grub tools need to be installed on the host system, not in the image for us to find them.

Thanks, using a Tools Tree fixed it.
