### ISSUE TITLE
mkosi removes required iwlwifi firmware files

### ISSUE THREAD

**Issue by swsnr** [systemd/mkosi#2334]
When filtering kernel modules with the following configuration:

```
KernelModulesExclude=.*
KernelModulesIncludeHost=true
KernelModulesInclude=
   iwlwifi
```

`mkosi` keeps the `iwlwifi` module and its firmware files, but still removes the `iwlwifi-*.pnvm.zst` files associated w/ the firmware files.  

I have no idea what these files are, and they don't appear in the firmware dependencies of `iwlwifi` (i.e. `modinfo iwlwifi` doesn't show them).  But `iwlwifi` needs them, and crashes when booting the generated image if those files aren't there.

I'm not sure it's possible to retain these files automatically given that they're not listed as firmware dependencies, but there doesn't seem to be any configuration option to exclude firmware files from the kernel module filter.

I'm currently working around this with

```
rsync -mar --include '*/' --include 'iwlwifi-*.pnvm.*' --exclude '*' \
            "${BUILDROOT}/usr/lib/firmware/" \
            "${BUILDROOT}/usr/lib/saved-firmware"
```

in `mkosi.prepare final`, and the reverse 

```
rsync -mar "${BUILDROOT}/usr/lib/saved-firmware/" \
            "${BUILDROOT}/usr/lib/firmware"
rm -rf "${BUILDROOT}/usr/lib/saved-firmware/"
```

in `mkosi.finalize`.

It'd be nice though if mkosi could retain these files automatically, or offer some customization option to retain certain firmware files.

That said, I'm fine with the workaround, so feel free to close this issue if it's out of scope for mkosi.

**Comment by DaanDeMeyer** [comment]
@swsnr I'm fine with adding a workaround for this, but can you please send an email to the linux-wireless mailing list asking for these dependencies to be added?

**Comment by swsnr** [comment]
@DaanDeMeyer Is this the linux-wireless mailinglist: <https://wireless.wiki.kernel.org/en/developers/mailinglists>?

Sorry if that's a stupid question, but I haven't had any contact w/ kernel development so far, so I don't the proper procedures here 🙂 

And should I CC' your github mail when writing to the mailing list?

**Comment by DaanDeMeyer** [comment]
@swsnr Yes, linux-wireless@vger.kernel.org is the address, feel free to cc me with my github email address.

**Comment by swsnr** [comment]
@DaanDeMeyer Done, though without subscription.  Let's see if it makes it past the spam filters…

**Comment by DaanDeMeyer** [comment]
Let's close this as upstream has confirmed the bug and will fix it upstream

**Comment by swsnr** [comment]
Just for the record, with kernel 6.9.7 `iwlwifi` now lists the missing files as firmware dependencies, so this appears to be fixed now.
