### ISSUE TITLE
`Transaction failed` when build fedora s390x image

### ISSUE THREAD

**Issue by lysliu** [systemd/mkosi#2343]
As @DaanDeMeyer in #2341 , I installed `qemu-user` and `qemu-user-binfmt`, but still got `Error: call to /usr/sbin/ldconfig failed.nError: call to /usr/sbin/iconvconfig failed.nError: call to /usr/sbin/ldconfig failed.n` 

### on `amd64` arch 
[x86_ubuntu.log](https://github.com/systemd/mkosi/files/14162574/x86_ubuntu.log)

when try to build fedora image by command `mkosi -d fedora --architecture s390x -f qemu`. 
I think the failures were caused missing some packages on `s390x` as the error log shows
```
Failed:
  apt-2.7.6-1.fc39.s390x                  ca-certificates-2023.2.60_v7.0.306-2.fc39.noarch      dbus-broker-35-2.fc39.s390x          gdb-14.1-2.fc39.s390x
  gettext-0.22-2.fc39.s390x               groff-base-1.23.0-3.fc39.s390x                        libutempter-1.2.1-10.fc39.s390x      mock-filesystem-5.4-1.fc39.noarch
  openssh-server-9.3p1-10.fc39.s390x      rpm-4.19.1-1.fc39.s390x                               tpm2-tss-4.0.1-6.fc39.s390x          xml-common-0.6.3-61.fc39.noarch

Error: Transaction failed
Error: call to /usr/sbin/ldconfig failed.nError: call to /usr/sbin/iconvconfig failed.nError: call to /usr/sbin/ldconfig failed.n‣ "env HOME=/ dnf --assumeyes --best --releasever=39 --installroot=/var/tmp/mkosi-workspacekczz1i5v/root --setopt=keepcache=1 --setopt=logdir=/var/log --setopt=cachedir=/var/cache/dnf --setopt=persistdir=/var/lib/dnf --setopt=install_weak_deps=0 --setopt=check_config_file_age=0 '--disableplugin=*' --enableplugin=builddep --setopt=metadata_expire=never --forcearch=s390x --config=/etc/dnf/dnf.conf --setopt=reposdir=/etc/yum.repos.d --setopt=varsdir=/etc/dnf/vars install amd-ucode-firmware apt archlinux-keyring attr autoconf automake bash btrfs-progs bubblewrap ca-certificates ca-certificates centos-packager coreutils cpio curl-minimal debian-keyring distribution-gpg-keys dnf dnf-plugins-core dnf5 dnf5-plugins dosfstools e2fsprogs erofs-utils fedora-packager fedora-packager-kerberos fedora-review gcc gdb gettext git iproute iputils kernel-core less libtool make mock mock-centos-sig-configs mock-core-configs mtools nano openssh-clients openssh-server openssl pacman perf pkgconf python3-cryptography qemu-kvm-core rpm-build rpminspect rpminspect-data-centos rpminspect-data-fedora shadow-utils socat squashfs-tools strace strace swtpm systemd systemd-container systemd-networkd systemd-resolved systemd-udev systemd-ukify tar tmux util-linux virtiofsd xfsprogs xz zstd zypper" returned non-zero exit code 1.
```
But when I tried this build command `mkosi -d fedora --architecture s390x -f qemu` 

### on `s390x` arch
[s390x_ubuntu.log](https://github.com/systemd/mkosi/files/14162613/s390x_ubuntu.log)

it does have all the missing packages.  That's very strange, why the build has dependency on the host environment? @DaanDeMeyer Could you share me with the environment which can passing the build `s390x` fedora image?
But with errors of `systemd-firstboot: not found`
```
‣   Applying presets…
Removed /var/tmp/mkosi-workspace234x3lvk/root/etc/systemd/system/systemd-homed.service.wants/systemd-homed-activate.service.
Created symlink /var/tmp/mkosi-workspace234x3lvk/root/etc/systemd/system/systemd-homed.service.wants/systemd-homed-activate.service → /lib/systemd/system/systemd-homed-activate.service.
‣   Applying first boot settings
systemd-firstboot: 1: exec: systemd-firstboot: not found
‣ "systemd-firstboot --root /var/tmp/mkosi-workspace234x3lvk/root --force --locale C.UTF-8" returned non-zero exit code 127.
```

**Comment by DaanDeMeyer** [comment]
@lysliu Please provide the full logs every time, you're excluding logs that would be valuable for debugging this issue.

**Comment by lysliu** [comment]
> @lysliu Please provide the full logs every time, you're excluding logs that would be valuable for debugging this issue.

@DaanDeMeyer , sorry,  I posted the full logs for the command both `x86` and `s390x` to the description in the issue.
Thank you for looking into this.

**Comment by DaanDeMeyer** [comment]
@lysliu So you have to install qemu-user-static, that's enough to make it work for me on x86 on ubuntu. For s390x you can try https://github.com/systemd/mkosi/pull/2344

**Comment by lysliu** [comment]
After I install `qemu-user-static`
the errors are the same both on `x86` and `s390x`, lack of `systemd-firstboot`
```
‣   Applying presets…
Removed /var/tmp/mkosi-workspace6sxgc9f6/root/etc/systemd/system/systemd-homed.service.wants/systemd-homed-activate.service.
Created symlink /var/tmp/mkosi-workspace6sxgc9f6/root/etc/systemd/system/systemd-homed.service.wants/systemd-homed-activate.service → /lib/systemd/system/systemd-homed-activate.service.
‣   Applying first boot settings
systemd-firstboot: 1: exec: systemd-firstboot: not found
‣ "systemd-firstboot --root /var/tmp/mkosi-workspace6sxgc9f6/root --force --locale C.UTF-8" returned non-zero exit code 127.
```
I think I really need a complete guide to build the s390x bootable fedora image.

**Comment by DaanDeMeyer** [comment]
@lysliu Please try #2344 which will fix the systemd-firstboot error.

**Comment by DaanDeMeyer** [comment]
Closing since the original issue has been fixed, please open a new issue for any other problems
