### ISSUE TITLE
mkosi v20.2 fails building ubuntu focal image

### ISSUE THREAD

**Issue by danielbisar** [systemd/mkosi#2346]
Host: Debian 12 (bookworm)
mkosi installed via git repo: tag v20.2

Target Distribution: ubuntu focal

See mkosi/resources/mkosi-initrd/mkosi.conf.d/10-debian-ubuntu.conf under Packages:
`^libtss2-esys-[0-9\.]+-0$
libtss2-rc0
libtss2-mu0`

These package cannot be installed, since they do not exist.

On Ubuntu focal the package is called: libtss2-esys0
https://packages.ubuntu.com/focal/libtss2-esys0

After commenting out the mentioned packages the image will get generated.

1. do i need these packages?
2. if yes: what are the correct package names for focal (libtss2-rc0 has no results)?

mkosi.conf
```[Distribution]
Distribution=ubuntu
Release=focal

[Output]
Format=disk
Output=image.raw

[Content]
Bootable=yes
Packages=linux-image-generic
         systemd 
         systemd-sysv
         udev
         dbus
RootPassword=root
WithDocs=yes
ToolsTree=default

[Partitions]
RootSize=2G

[Validation]
Checksum=yes
```

The log just says the packages mentioned cannot be installed, since they cannot be found.

**Comment by behrmann** [comment]
@danielbisar Can you have a look whether #2347 works for you?

**Comment by danielbisar** [comment]
Tested the changes and it worked!

**Comment by behrmann** [comment]
Great that it works for you :) Unfortunately the change makes our CI unhappy. With the given regex apt is unable to properly resolve the package there and what might be a solution (an `?or` apt search pattern) triggers a bug in our config parsing, since those contain commas and we use commas as separator for multiple packages, so this needs addressing, but I haven't found the time yet.

**Comment by danielbisar** [comment]
No worries; I think we can work with the patch for now. If I can support somehow let me know. 

I will leave this issue open, until your changes are merged, so you can track better when it was solved in master?!
