### ISSUE TITLE
[Meta] declare a policy about adding new distributions

### ISSUE THREAD

**Issue by r-darwish** [systemd/mkosi#236]
Before people start creating issues asking to support their favorite distribution, I think that mkosi should declare its policy regarding new distributions support.

The policy should state in which terms (if any) you will be willing to support a new distributions.

**Comment by poettering** [comment]
yeah, it's a difficult question where to draw the line. And I figure when adding this we should also open the door for smaller distros to hook things up to mkosi too, by adding some form of drop-in logic, where additional distros could be added by dropping in some minimal file that does the minimal core bits to hook things up...
