### ISSUE TITLE
Error booting directory with qemu

### ISSUE THREAD

**Issue by septatrix** [systemd/mkosi#2371]
When booting a debian bootstrap image with `mkosi qemu` the sysroot.mount unit fails. Performing the same with an output of type disk boots as expected.

Some logs which look suspicious:

```txt
# dmesg
virtio-fs: tag <root> not found
# weirdly enough, calling `mount -t virtiofs root /sysroot` in the emergency shell succeeds

# journalctl -u sysroot.mount
Feb 10 19:42:25 localhost mount[98]: mount: /sysroot: wrong fs type, bad option, bad superblock on root, missing codepage or helper program, or other error.
Feb 10 19:42:25 localhost mount[98]:        dmesg(1) may have more information after failed mount system call.
```

**Comment by DaanDeMeyer** [comment]
@septatrix Debian stable or testing? If stable, try with testing

**Comment by bluca** [comment]
That was only backported to v254-stable and not any further, so it does not

**Comment by DaanDeMeyer** [comment]
@septatrix My educated guess is that you're running Debian stable which can't boot from virtiofs without the patch I linked.

@bluca Any chance we could backport that patch to Debian stable? Don't bother if it's too much effort.

**Comment by bluca** [comment]
If it was skipped below v254-stable it's because it didn't apply cleanly when cherry-picking I imagine, I can check in the next round

**Comment by septatrix** [comment]
> @septatrix Debian stable or testing? If stable, try with testing. Also, please get me the output of `systemctl --version` in the emergency shell.

Bookworm as I said, so stable. Not at my machine right now but I can provide the version number later. If it is due to the systemd version I could enable bookworm-backports and see if that resolves it (or I guess a hacky approach of having sysroot.mount wait for a `Type=oneshot`, `Exec start=sleep 5` might also work for the time)

**Comment by DaanDeMeyer** [comment]
@septatrix No need for the version, bluca already mentioned that the patch is missing in stable. Anyway I'm closing this as the bug is already fixed in systemd

**Comment by DaanDeMeyer** [comment]
@septatrix See https://github.com/systemd/systemd-stable/pull/366 for the backport
