### ISSUE TITLE
output files invisible to match section

### ISSUE THREAD

**Issue by CosmicToast** [systemd/mkosi#2379]
I'm building a kernel (multiple kernel builds for multiple architectures) using mkosi in Format=directory.
I then want to use the data out of this in other build targets, but also use that kernel with `QemuKernel=`.
To this end, I have a drop-in that looks like so:
```ini
[Match]
PathExists=%O/kernel/boot/linux-%a

[Host]
QemuKernel=%O/kernel/boot/linux-%a
```
This never triggers.
If I comment out `PathExists=`, then qemu will boot as expected, but obviously mkosi will refuse to run without an mkosi-built image already being built.

Here's an example minimal setup to reproduce:
```ini
# mkosi.conf
[Distribution]
Distribution=fedora
Release=39

[Content]
Bootable=no
```

```ini
# mkosi.conf.d/qemu.conf
[Match]
PathExists=%O/a/akernel

[Host]
QemuKernel=%O/a/akernel
```

```sh
# ensure output directory exists
mkdir mkosi.output

# build the image
mkosi

# booting via qemu fails for unrelated reasons, this is expected
mkosi qemu

# let's trigger the condition
mkdir mkosi.output/a
touch mkosi.output/a/akernel

# booting via qemu fails for the same reason as before
mkosi qemu

# edit mkosi.conf.d/qemu.conf to comment out the PathExists condition
# we now get the expected error!
mkosi qemu
# => File is smaller than DOS magic (got 0 of 2 bytes)
# => ‣ "bootctl kernel-identify /tmp/t/mkosi.output/a/akernel" returned non-zero exit code 1.
```

I'm running this on fedora 39 with mkosi 20.1, but based on the NEWS file it doesn't seem like this was recently changed.

**Comment by behrmann** [comment]
This is because we only check matches at config parsing time. This means, that this can only match things, that exist at that point in time. The use case, though, is understandable and we should probably add a way to do this.

**Comment by CosmicToast** [comment]
Thanks!

This is still a bit confusing to me though, since it will fail even after the initial build.
I.e I can test the existence of the file before calling `mkosi`, but it will continue to act as though it doesn't exist.

**Comment by DaanDeMeyer** [comment]
@CosmicToast Fix waiting in https://github.com/systemd/mkosi/pull/2381

**Comment by CosmicToast** [comment]
Can confirm this fix works for me. Thanks :)
