### ISSUE TITLE
Should `amd-ucode-firmware` (fedora) only be used for x86-64?

### ISSUE THREAD

**Issue by septatrix** [systemd/mkosi#2391]
I am a bit confused currently while I was looking to include microcode packages in my image. In the configuration contained in this repo there is usually a match section to only install microcode on x86-64 with the exception of the above package under Fedora. Now the package does have the following description (emphasis mine):

> Microcode updates for AMD CPUs, **ARM** SEV amd TEE.

However, I do guess that this is only a type as [the contained files](https://packages.fedoraproject.org/pkgs/linux-firmware/amd-ucode-firmware/fedora-40.html#files) are all about AMD. And while there is ARM TEE, there is not such thing as ARM SEV whereas AMD SEV and AMD TEE both exist.

**Comment by DaanDeMeyer** [comment]
Next time feel free to do a PR instead of making an issue for trivial stuff such as this
