### ISSUE TITLE
bwrap: "No such file or directory", when installing local package from `@commandline` with dnf5

### ISSUE THREAD

**Issue by septatrix** [systemd/mkosi#2397]
When I install a package mounted via `BuildSources=` I get the following error message.

```
bwrap: Can't find source path /home/septatrix/.cache/mkosi/fedora~38~x86-64/cache/libdnf5/@commandline-f1fcf1ce45c07955/packages: No such file or directory
bwrap: Can't find source path /home/septatrix/.cache/mkosi/fedora~38~x86-64/cache/libdnf5/@commandline-f1fcf1ce45c07955/packages: No such file or directory
‣ "/work/prepare build" returned non-zero exit code 1.
```

I also noticed that the docs say that one can use `PackageDirectories=` though the approach using `BuildSources=` is also still documented. Is that still supposed to work or was the `PackageDirectories=` method supposed to replace the old one which was forgotten to be removed from the docs?

**Comment by DaanDeMeyer** [comment]
Please provide a full reproducer

**Comment by septatrix** [comment]
The following `mkosi.local.conf` on top of the this repo's default config reproduces the issue (with a fedora host):

```ini
[Content]
BuildSources=prebuild:prebuild
# Package downloaded from https://kojipkgs.fedoraproject.org/packages/nodejs-pnpm/8.12.0/1.fc39/noarch/pnpm-8.12.0-1.fc39.noarch.rpm
Packages=prebuild/pnpm-8.12.0-1.fc39.noarch.rpm
```
