### ISSUE TITLE
PackageManagerTrees=/etc/yum.d/repos/foo.repo:/etc/yum.d/repos/foo.repo fails with a permission error

### ISSUE THREAD

**Issue by jgouly** [systemd/mkosi#2429]
`--repository` allows you to select more repositories, but you may want more than from the predefined list (in dnf.py for example).

For some images I'm building I want mesa from the asahi copr (https://download.copr.fedorainfracloud.org/results/@asahi/mesa/fedora-$releasever-$basearch/) which I can do with `PackageManagerTrees=`.

Note that `PackageManagerTrees=/etc/yum.d/repos/foo.repo:/etc/yum.d/repos/foo.repo` currently doesn't work due to a permission error, so you have to copy foo.repo to the current dir.

**Comment by DaanDeMeyer** [comment]
@jgouly Which permission error do you get, please include the full stacktrace
