### ISSUE TITLE
Add ToolsTreeRepositores / ToolsTreePackageManagerTrees

### ISSUE THREAD

**Issue by jgouly** [systemd/mkosi#2430]
For an image I'm building, I want to include the Asahi Mesa library in the ToolsTree so that I can run QEMU images with GL acceleration.

However there's currently no way to add extra repos to the ToolsTree.

I locally have the below hack which passes PackageManagerTrees to the ToolsTree build also:
```
diff --git a/mkosi/__init__.py b/mkosi/__init__.py
index 74e20fe3..3800fd16 100644
--- a/mkosi/__init__.py
+++ b/mkosi/__init__.py
@@ -3593,6 +3593,7 @@ def finalize_default_tools(args: Args, config: Config, *, resources: Path) -> Co
         *(["--package-cache-dir", str(config.package_cache_dir)] if config.package_cache_dir else []),
         "--incremental", str(config.incremental),
         "--acl", str(config.acl),
+        *([f"--package-manager-tree={package.source}:{package.target}" for package in config.package_manager_trees]),
         *([f"--package={package}" for package in config.tools_tree_packages]),
         "--output", f"{config.tools_tree_distribution}-tools",
         *(["--source-date-epoch", str(config.source_date_epoch)] if config.source_date_epoch is not None else []),
```

**Comment by septatrix** [comment]
Maybe mkosi could allow for custom tools tree similar to initrds. Ship definitions for one which works for most and otherwise make dependencies/images for work them

**Comment by DaanDeMeyer** [comment]
> Maybe mkosi could allow for custom tools tree similar to initrds. Ship definitions for one which works for most and otherwise make dependencies/images for work them

Maybe read the documentation for the ToolsTree option ;)
