### ISSUE TITLE
Issues booting debian images on real hardware

### ISSUE THREAD

**Issue by wbw455** [systemd/mkosi#2433]
Hello, 
Sorry for asking such a trivial question but I have spent the entire day without getting this to work. I have been using the older mkosi versions 12/13 to build bootable images on actual hardware. 
I'm trying out the latest 20.02 but I cannot get it to boot properly. Here is a paste bin with my settings, thankful for any pointers on what I'm doing wrong.

Here is a paste bin with my settings:

https://pastebin.com/A7CDXC9b

Here is the build log using --debug option

[build.log](https://github.com/systemd/mkosi/files/14437967/build.log)

Thanks,

**Comment by behrmann** [comment]
How did you install mkosi and how are you using it? Asking because bootctl complains
```
statfs("/sys/fs/cgroup/") failed: No such file or directory
Failed to detect cgroup namespace: No such file or directory
Found container virtualization none.
```

**Comment by wbw455** [comment]
> How did you install mkosi and how are you using it? Asking because bootctl complains
> 
> ```
> statfs("/sys/fs/cgroup/") failed: No such file or directory
> Failed to detect cgroup namespace: No such file or directory
> Found container virtualization none.
> ```

I'm running on Ubuntu 22.04 which does not support mkosi 20.02 so I downloaded the git repo and ran it from the bin/mkosi script.

**Comment by DaanDeMeyer** [comment]
@wbw455 

```
root@default:~# ls /boot/EFI/Linux/
debian-6.1.0-18-amd64.efi
```

The unified kernel image is generated by mkosi as expected so as far as we're concerned it is bootable. It also boots fine when booting the image in qemu with `mkosi qemu`. You're going to have to provide more information on what is going wrong when trying to boot the image on real hardware.

**Comment by DaanDeMeyer** [comment]
@wbw455 Ping?

**Comment by wbw455** [comment]
Hello,

Sorry for the late reply. I did manage to get Ubuntu (I initially had issues with both Debian and Ubuntu) booting by removing my custom mkosi.repart and updating the config file with the following:

```
[Distribution]
Distribution=ubuntu
Release=jammy
Architecture=x86-64

[Output]
Format=disk
Output=test
CacheDirectory=mkosi.cache


[Content]
Bootable=yes
Bootloader=systemd-boot
Packages=
    linux-image-generic
    systemd
    systemd-sysv
    udev
    dbus
    linux-firmware
    intel-microcode
    
KernelCommandLine= console=ttyS0 

InitrdPackages=
    linux-image-generic
    udev

[Host]
ToolsTree=default
```
I will have to looking why my mkosi.repart configuration caused the system to be even recognized in UEFI. I will update you once I have sucessfully booted Debian as well as understod the mkosi.repart config better.

**Comment by wbw455** [comment]
Hello,

In the first scenario, where I built the image without a custom mkosi.repart directory, I just needed to add a console to the command line.

In the other scenario I needed to make some adjustments to my configuration file:


 ``` 
[Partition]
Type=esp
Format=vfat
CopyFiles=/efi:/
CopyFiles=/boot:/
SizeMinBytes=512M
SizeMaxBytes=512M
 ``` 
 ``` 
Initially I had it set as 256M and when i re-built it I saw:
 ``` 
Populating vfat filesystem.
Successfully populated vfat filesystem.
mkfs.fat 4.2 (2021-01-31)
WARNING: Number of clusters for 32 bit FAT is less then suggested minimum.
/var/tmp/repart-p0c5u6 successfully formatted as vfat (label "ESP", uuid ebe7ca67)
 ``` 
Once I increased it to 512M I had no warnings and it boots properly. So no bug just some miss configurations from my side.

You can close this case and thanks for the support!
