### ISSUE TITLE
`mkosi qemu jammy.raw` fails with `BdsDxe: failed to load Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x4,0x0)/Scsi(0x0,0x0): Not Found`

### ISSUE THREAD

**Issue by paulmenzel** [systemd/mkosi#2436]
In a Debian trixie/testing VM with *mkosi* 20.2-1, building a Ubuntu 22.04 VM, it fails to run by default:

    $ sudo mkosi -d ubuntu -r jammy -m http://ftp.gwdg.de/ubuntu/ --output=ubuntu-jammy.raw
    […]
    $ ls -lh ubuntu-jammy.raw*
    lrwxrwxrwx 1 build build   20 Feb 29 16:17 ubuntu-jammy.raw -> ubuntu-jammy.raw.raw
    -rw-r--r-- 1 build build 133M Feb 29 16:17 ubuntu-jammy.raw.raw
    $ file ubuntu-jammy.raw.raw
    ubuntu-jammy.raw.raw: DOS/MBR boot sector; partition 1 : ID=0xee, start-CHS (0x0,0,2), end-CHS (0x3ff,255,63), startsector 1, 271095 sectors, extended partition table (last)

But running this image fails

    $ mkosi qemu ubuntu-jammy.raw
    WARNING: Image format was not specified for 'ubuntu-jammy.raw' and probing guessed raw.
             Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
             Specify the 'raw' format explicitly to remove the restrictions.
    
    BdsDxe: failed to load Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x4,0x0)/Scsi(0x0,0x0): Not Found
    BdsDxe: No bootable option or device was found.
    BdsDxe: Press any key to enter the Boot Manager Menu.

Pressing a key it shows

    BdsDxe: loading Boot0000 "UiApp" from Fv(7CB8BDC9-F8EB-4F34-AAEA-3EE4AF6516A1)/FvFile(462CAA21-7614-4503-836E-8AB6F4662331)
    BdsDxe: starting Boot0000 "UiApp" from Fv(7CB8BDC9-F8EB-4F34-AAEA-3EE4AF6516A1)/FvFile(462CAA21-7614-4503-836E-8AB6F4662331)

and then the EDK2 menu. Entering the *Boot Manager*:

    ┌───────────────────────────────────────────────────┐
    │                                Boot Manager       │
    └───────────────────────────────────────────────────┘
 
                                                             Device Path :
       Boot Manager Menu                                     PciRoot(0x0)/Pci(0x4,0
                                                             x0)/Scsi(0x0,0x0)
       UEFI QEMU QEMU HARDDISK
       UEFI QEMU HARDDISK QM00001
       UEFI PXEv4 (MAC:525400123456)
       UEFI PXEv4 (MAC:525400123456) 2
       UEFI PXEv6 (MAC:525400123456)
       UEFI HTTPv4 (MAC:525400123456)
       UEFI HTTPv6 (MAC:525400123456)
 
       Use the <↑> and <↓> keys to choose a boot option,
       the <Enter> key to select a boot option, and the
       <Esc> key to exit the Boot Manager Menu.

The QEMU processes below are run:

    $ ps aux | grep qem
    build       9121  0.2  0.0 108956 27904 pts/0    Sl   18:16   0:01 /usr/bin/python3 /usr/bin/mkosi qemu ubuntu-jammy.raw
    build       9164  0.0  0.0   3376  1536 pts/0    S+   18:16   0:00 bwrap --ro-bind /usr /usr --die-with-parent --proc /proc --setenv SYSTEMD_OFFLINE 1 --bind /tmp /tmp --bind /sys /sys --bind /run /run --dev-bind /dev /dev --bind /etc /etc --bind /opt /opt --bind /srv /srv --bind /media /media --bind /mnt /mnt --bind /var /var --bind /home/build /home/build --symlink usr/bin /bin --symlink usr/sbin /sbin --symlink usr/lib /lib --symlink usr/lib64 /lib64 --setenv PATH :/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games --ro-bind /etc/alternatives /etc/alternatives sh -c exec $0 "$@" qemu-system-x86_64 -machine type=q35,smm=on -smp 1 -m 2G -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0,id=rng-device0 -nic user,model=virtio-net-pci -accel kvm -device vhost-vsock-pci,guest-cid=2358200178,vhostfd=4 -cpu max -nographic -nodefaults -chardev stdio,mux=on,id=console,signal=off -serial chardev:console -mon console -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE_4M.secboot.fd -drive file=/tmp/mkosi-ovmf-varssa6x4o54,if=pflash,format=raw -global ICH9-LPC.disable_s3=1 -global driver=cfi.pflash01,property=secure,value=on -smbios type=11,value=io.systemd.credential.binary:agetty.autologin=cm9vdA== -smbios type=11,value=io.systemd.credential.binary:login.noauth=eWVz -smbios type=11,value=io.systemd.credential.binary:firstboot.timezone=RXVyb3BlL1ZpZW5uYQ== -smbios type=11,value=io.systemd.credential.binary:firstboot.locale=Qy5VVEYtOA== -device virtio-scsi-pci,id=scsi -smbios type=11,value=io.systemd.stub.kernel-cmdline-extra=systemd.wants=network.target module_blacklist=vmw_vmci systemd.tty.term.ttyS0=screen systemd.tty.columns.ttyS0=104 systemd.tty.rows.ttyS0=55 ip=enc0:any ip=enp0s1:any ip=enp0s2:any ip=host0:any ip=none loglevel=4 SYSTEMD_SULOGIN_FORCE=1 systemd.tty.term.console=screen systemd.tty.columns.console=104 systemd.tty.rows.console=55 console=ttyS0 -drive if=none,id=mkosi,file=/home/build/image.raw,format=raw -device scsi-hd,drive=mkosi,bootindex=1 -smbios type=11,value=io.systemd.credential:vmm.notify_socket=vsock-stream:2:1390837830 ubuntu-jammy.raw
    build       9165 28.5  0.3 2644364 106992 pts/0  Sl+  18:16   2:17 qemu-system-x86_64 -machine type=q35,smm=on -smp 1 -m 2G -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0,id=rng-device0 -nic user,model=virtio-net-pci -accel kvm -device vhost-vsock-pci,guest-cid=2358200178,vhostfd=4 -cpu max -nographic -nodefaults -chardev stdio,mux=on,id=console,signal=off -serial chardev:console -mon console -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE_4M.secboot.fd -drive file=/tmp/mkosi-ovmf-varssa6x4o54,if=pflash,format=raw -global ICH9-LPC.disable_s3=1 -global driver=cfi.pflash01,property=secure,value=on -smbios type=11,value=io.systemd.credential.binary:agetty.autologin=cm9vdA== -smbios type=11,value=io.systemd.credential.binary:login.noauth=eWVz -smbios type=11,value=io.systemd.credential.binary:firstboot.timezone=RXVyb3BlL1ZpZW5uYQ== -smbios type=11,value=io.systemd.credential.binary:firstboot.locale=Qy5VVEYtOA== -device virtio-scsi-pci,id=scsi -smbios type=11,value=io.systemd.stub.kernel-cmdline-extra=systemd.wants=network.target module_blacklist=vmw_vmci systemd.tty.term.ttyS0=screen systemd.tty.columns.ttyS0=104 systemd.tty.rows.ttyS0=55 ip=enc0:any ip=enp0s1:any ip=enp0s2:any ip=host0:any ip=none loglevel=4 SYSTEMD_SULOGIN_FORCE=1 systemd.tty.term.console=screen systemd.tty.columns.console=104 systemd.tty.rows.console=55 console=ttyS0 -drive if=none,id=mkosi,file=/home/build/image.raw,format=raw -device scsi-hd,drive=mkosi,bootindex=1 -smbios type=11,value=io.systemd.credential:vmm.notify_socket=vsock-stream:2:1390837830 ubuntu-jammy.raw

Trying to run it myself, I also failed to correctly set up OVMF:

    $ qemu-system-x86_64 -M q35 -m 2G -enable-kvm -cpu host -smp cpus=2 -device virtio-rng-pci -net nic,model=virtio-net-pci -net user,hostfwd=tcp::22225-:22 -drive if=virtio,file=ubuntu-jammy.raw.raw -vga none -nographic -global driver=cfi.pflash01,property=secure,value=on -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE_4M.secboot.fd -drive file=/tmp/mkosi-ovmf-varssa6x4o54,if=pflash,format=raw
    […]
    BdsDxe: failed to load Boot0001 "UEFI Misc Device" from PciRoot(0x0)/Pci(0x3,0x0): Not Found

**Comment by DaanDeMeyer** [comment]
We don't build bootable images by default. You need to add --bootable yes and install the required packages.

**Comment by paulmenzel** [comment]
Thank you. Let’s see if it boots after issue https://github.com/systemd/mkosi/issues/2437 is resolved.
