### ISSUE TITLE
mkosi: before doing anything let's check if all deps are installed

### ISSUE THREAD

**Issue by fabiand** [systemd/mkosi#247]
```
$ sudo docker run --rm --name mkosi --privileged -it mkosi
…
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 3614, in <module>
    main()
  File "/usr/bin/mkosi", line 3604, in main
    build_stuff(args)
  File "/usr/bin/mkosi", line 3447, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=False, for_cache=True)
  File "/usr/bin/mkosi", line 3289, in build_image
    raw = create_image(args, workspace.name, for_cache)
  File "/usr/bin/mkosi", line 402, in create_image
    disable_cow(f.name)
  File "/usr/bin/mkosi", line 335, in disable_cow
    run(["chattr", "+C", path], stdout=DEVNULL, stderr=DEVNULL, check=False)
  File "/usr/lib64/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chattr': 'chattr'
```

**Comment by fabiand** [comment]
Yep, that fixes it.

But I think it should be fixed in the packaging.
This makes me wonder if I should have filed this bug on Fedora ...

**Comment by poettering** [comment]
Yeah, that should have been posted against fedora.

That said, it might make sense to add a concept to mkosi to look for everything it needs before starting to do anything, just to make things easier. will rename the bug like that

**Comment by keszybz** [comment]
`chattr` is executed with `check=False`, so `mkosi` should just ignore the failure and continue. Do you still see this with current master?

**Comment by keszybz** [comment]
https://src.fedoraproject.org/rpms/mkosi/c/ea929b4e596adac8a7531a73946ebcb09f787e5e

**Comment by DaanDeMeyer** [comment]
We don't yet check if all dependencies are installed, but we do show a much better error now if something isn't installed, which should be sufficient so let's close this. Please comment if you don't think this is sufficient
