### ISSUE TITLE
Erofs partition cannot be created (xattrs)

### ISSUE THREAD

**Issue by gdonval** [systemd/mkosi#2485]
Setup
=====

`mkosi.conf`

```
[Output]
Output=disk_file
Format=disk

[Distribution]
Distribution=ubuntu
Release=jammy
Repositories=main restricted universe multiverse

[Content]
CleanPackageMetadata=no
WithDocs=no
Packages=systemd
         systemd-sysv
         libpam-systemd
         udev
         dbus
```

---

`mkosi.repart/10-usr.conf`

```
[Partition]
Type=usr
Label=usr
SplitName=usr_%a
Format=erofs
CopyFiles=/usr:/
Minimize=yes
```

Result
======

`$ mkosi -f`

```
[...]
‣  Generating disk image
Pre-populating erofs filesystem of partition 10-usr.conf twice to calculate minimal partition size
Populating erofs filesystem.
Successfully populated erofs filesystem.
mkfs.erofs 1.7.1
<E> erofs: failed to build shared xattrs: [Error 61] No data available
<E> erofs: 	Could not format the device : [Error 61] No data available

(mkfs) failed with exit status 1.
‣ "setpgid --foreground -- systemd-repart --empty=allow --size=auto --dry-run=no --json=pretty --no-pager --offline=yes --seed b2094c34-1d27-45aa-a254-20292f3ea43f /home/gdonval/.cache/mkosi/mkosi-workspacedu64ewkx/staging/disk_0.1.raw --root /home/gdonval/.cache/mkosi/mkosi-workspacedu64ewkx/root --empty=create --private-key /home/gdonval/Documents/Work/RVMI/CustomOS/ubuntu_nixon/mkosi.key --certificate /home/gdonval/Documents/Work/RVMI/CustomOS/ubuntu_nixon/mkosi.crt --defer-partitions esp,xbootldr --definitions /home/gdonval/Documents/Work/RVMI/CustomOS/ubuntu_nixon/mkosi.images/disk/mkosi.repart" returned non-zero exit code 1.
```

Note
====

`mkfs.erofs` does not seem to support the full extent of `xattrs` as defined in recent `btrfs`.

In the same dir, if I run

```
$ mkfs.erofs mkosi.repart.erofs.img mkosi.repart

mkfs.erofs 1.7.1
<E> erofs: failed to build shared xattrs: [Error 61] No data available
<E> erofs: 	Could not format the device : [Error 61] No data available
```

i.e. same error.

And the only way to achieve anything at all is by using

```
$ mkfs.erofs -x-1 mkosi.repart.erofs.img mkosi.repart
```

which disables xattrs altogether and is probably **not** something we actually want to do in the general case.

I wanted to open a bug request with them but everything is done by email so I can't cross reference.

**Comment by hsiangkao** [comment]
hi, thanks for the feedback! please see my reply:
https://lore.kernel.org/r/57655d61-6ba7-4188-a96f-898cfadd7176@linux.alibaba.com

**Comment by gdonval** [comment]
Thanks for your help! I believe the new `mkfs.erofs` version will issue warnings instead of errors and would therefore solve the problem here.

As `mkosi` uses `systemd-repart` exclusively to generate new images and there is no 1st-class support for `mkfs` customization, there is little it can do to workaround the problem. `erofs` in `mkosi` will remain broken on certain systems.

**Comment by gdonval** [comment]
So having a `MkfsOptions=` option is not fine but abusing environment is?
And if I want to, say, use `mkosi` to use `mkosi` to generate `sysext` on the fly without the problem reported here, I need to remember unsetting the variable first?

The many problems with env vars are subtle and the fact Docker users abuses them is not an excuse.
