### ISSUE TITLE
Add `VARIANT_ID` in mkosi.postinst to indicate a image usage

### ISSUE THREAD

**Issue by lysliu** [systemd/mkosi#2500]
We want to Add `VARIANT_ID` in mkosi.postinst to indicate a image usage, e.g. `Server`, `Workstation`, `Production` or `Debug`
and add it to `/etc/os-release`
from https://github.com/systemd/mkosi/blob/main/mkosi/__init__.py#L639-L652
the mkosi.postinst script only accept the variables in the dict, 
```
        DISTRIBUTION=str(context.config.distribution),
        RELEASE=context.config.release,
        ARCHITECTURE=str(context.config.architecture),
        BUILDROOT=str(context.root),
        OUTPUTDIR="/work/out",
        CHROOT_OUTPUTDIR="/work/out",
        SCRIPT="/work/postinst",
        CHROOT_SCRIPT="/work/postinst",
        SRCDIR="/work/src",
        CHROOT_SRCDIR="/work/src",
        PACKAGEDIR="/work/packages",
        MKOSI_UID=str(INVOKING_USER.uid),
        MKOSI_GID=str(INVOKING_USER.gid),
        MKOSI_CONFIG="/work/config.json",
```
So it's required to Add `VARIANT_ID` in the dict.

**Comment by DaanDeMeyer** [comment]
@lysliu We already have `--profile` to select a different mkosi profile when building an image. Would it be OK if we used that as the variant ID instead of adding a new section? Please read the `Profile=` section in the docs for more information.

**Comment by lysliu** [comment]
> @lysliu We already have `--profile` to select a different mkosi profile when building an image. Would it be OK if we used that as the variant ID instead of adding a new section? Please read the `Profile=` section in the docs for more information.
I set the profile as below,  but still cannot be used in `mkosi.postinst`, could you provide a example for this?

```
/work/postinst: line 13: VARIANT_ID: unbound variable
‣ "/work/postinst final" returned non-zero exit code 1.
root@c83851v1:~/cloud-api-adaptor/podvm-mkosi# more mkosi.conf | grep Profile
Profile=profile.conf
root@c83851v1:~/cloud-api-adaptor/podvm-mkosi# more mkosi.profiles/profile.conf
[Profile]
VARIANT_ID=debug
```

**Comment by DaanDeMeyer** [comment]
@lysliu A profile is not a section. Quoting the profile documentation:

> `Profile=`, `--profile=`
> : Select the given profile. A profile is a configuration file or
>   directory in the `mkosi.profiles/` directory. When selected, this
>   configuration file or directory is included after parsing the
>   `mkosi.conf` file, but before any `mkosi.conf.d/*.conf` drop in
>   configuration.

So what you'd do is the following:

```
$ tee mkosi.profiles/server.conf <<EOF
[Content]
Environment=VARIANT_ID=Server
EOF
$ mkosi --profile server ...
```

That way `$VARIANT_ID` will be set to `Server` in all your scripts when you pass `--profile server` to mkosi.

**Comment by DaanDeMeyer** [comment]
Let's close this as an alternative solution has been provided
