### ISSUE TITLE
Ubuntu 22.04 Build permissions issues

### ISSUE THREAD

**Issue by shady786** [systemd/mkosi#2504]
I am trying to build a image but it gets hung up trying to mount after syncing package manager meta:

Syncing package manager metadata for development image
mount: /usr: must be superuser to use mount.
       dmesg(1) may have more information after failed mount system call.
mount: /usr: must be superuser to use mount.
       dmesg(1) may have more information after failed mount system call.
‣ "env APT_CONFIG=/etc/apt.conf DEBIAN_FRONTEND=noninteractive DEBCONF_INTERACTIVE_SEEN=true INITRD=No apt-get -o APT::Architecture=amd64 -o APT::Architectures=amd64 -o APT::Install-Recommends=false -o APT::Immediate-Configure=off -o APT::Get::Assume-Yes=true -o APT::Get::AutomaticRemove=true -o APT::Get::Allow-Change-Held-Packages=true -o APT::Get::Allow-Remove-Essential=true -o APT::Sandbox::User=root -o Dir::Cache=/var/cache/apt -o Dir::State=/var/lib/apt -o Dir::Log=/var/log/apt -o Dir::State::Status=/home/runner/.cache/mkosi/mkosi-workspacemw5z8v3j/root/var/lib/dpkg/status -o Dir::Log=/home/runner/.cache/mkosi/mkosi-workspacemw5z8v3j -o Dir::Bin::DPkg=/usr/bin/dpkg -o Debug::NoLocking=true -o DPkg::Options::=--root=/home/runner/.cache/mkosi/mkosi-workspacemw5z8v3j/root -o DPkg::Options::=--force-unsafe-io -o DPkg::Options::=--force-architecture -o DPkg::Options::=--force-depends -o DPkg::Options::=--no-debsig -o DPkg::Use-Pty=false -o DPkg::Install::Recursive::Minimum=1000 -o pkgCacheGen::ForceEssential=, update" returned non-zero exit code 32.
‣  (Fixing ownership of package manager cache directory)

Should I not be running the build using sudo or could this be a bug ?

**Comment by DaanDeMeyer** [comment]
@shady786 Fixed in git main already
