### ISSUE TITLE
run mkosi containers in Windows/Mac hosts?

### ISSUE THREAD

**Issue by fedelibre** [systemd/mkosi#251]
How can I run, in a Windows or Mac OS X host, a container generated by mkosi?
Is it possible at all?

**Comment by lucaswerkmeister** [comment]
A bootable image can probably run under VirtualBox or other virtualization software, I assume. A non-bootable image *might* perhaps run under Windows Subsystem for Linux, somehow? But I have no idea if that implements all the necessary technologies (mainly namespaces).

**Comment by fedelibre** [comment]
I'm trying to avoid virtualization software like VirtualBox. I used the word container as opposed to traditional images which run only under VirtualBox and similar.

Windows Subsystem for Linux cannot run a non-bootable image yet, see [issue 994 of WSL](https://github.com/Microsoft/WSL/issues/994).

Other options?

**Comment by poettering** [comment]
I am not sure there's anything actionable from our side here. We do provide you with a way to run these things in a VM. And to run them on WSL the work needs to be done by the Windows folks to support something like nspawn (i.e. cgroups and stuff), and as long as they don't do that we are stuck...

Anyway, will close this here, as there's nothing we can do on this from our side. Hope this makes sense. Sorry.
