### ISSUE TITLE
Allow for variables in Configuration

### ISSUE THREAD

**Issue by killermoehre** [systemd/mkosi#2519]
Hi,

so I use profiles to build images. So far so good. The profiles include all the files in `mkosi.conf.d`, which have the proper `[Match]` to distinguish among all the different distributions and version.

Now I want to reduce the number of boilerplate files by using something like

```ini
[Match]
Distribution={distribution}
Release={release}

[Output]
Output={distribution}-{release}

[Content]
ExtraTrees=mkosi.extra.d/{distribution}-{release}:/
```

where those parameters are either provided by the profile or the CLI parameters.

Maybe this is already possible and I just don't understand the documentation. In general IMHO this is a worthwhile feature.

**Comment by behrmann** [comment]
The "Specifiers" section in the man page should satisfy your needs.

**Comment by DaanDeMeyer** [comment]
Closing because specifiers already provide this functionality
