### ISSUE TITLE
systemd-tmpfiles-clean.service removes files while an image is created

### ISSUE THREAD

**Issue by michaelolbrich** [systemd/mkosi#252]
mkosi failed for me because part of the OS tree was deleted while creating the image:
The files created in /var/tmp/mkosi-* are older than 30 days. systemd-tmpfiles-clean.service started while I created the image and deleted most of the OS tree.

It seems to me, that /var/tmp is a bad choice for the temporary directory.

**Comment by poettering** [comment]
Fix waiting in #319
