### ISSUE TITLE
root directory of Debian buster tar images is world writable

### ISSUE THREAD

**Issue by michaelolbrich** [systemd/mkosi#253]
For tar and directory images (I've not tested any others) the permissions of the root directory may be world writable, depending on the distribution.
Debian stretch/buster/sid: 0777
Debian jessie: 0755
Fedora 27: 0555
For Debian buster, this is caused by setting the umask to 0000. I'm not sure why this is needed.
I guess we need to fix the permissions at the end. What is the correct mode here anyways?

**Comment by poettering** [comment]
Fix waiting in #311
