### ISSUE TITLE
[RFE for the future] Support for debos? 

### ISSUE THREAD

**Issue by q2dg** [systemd/mkosi#255]
It seems interesting as a replacement to debootstrap: https://www.collabora.com/news-and-blog/blog/2018/06/27/introducing-debos/ Let's see how evolves....

**Comment by lucaswerkmeister** [comment]
Hm, to me the blog post reads more like `debos` is an image generation tool more similar to `mkosi` than to `debootstrap`. I’m not sure what `mkosi` would gain from using `debos` over `debootstrap`.

**Comment by q2dg** [comment]
Closed due to lack of interest
