### ISSUE TITLE
`ExtraTrees=` via `InitrdInclude=` incorrectly resolved

### ISSUE THREAD

**Issue by septatrix** [systemd/mkosi#2579]
When using `ExtraTrees=` fom a *file* which is included via `InitrdInclude=` which itself was set in the config file of an image the paths are incorrectly resolved. More specifically they seem to be resolved relative to the project root instead of the config file (or the image root).

I would have expected that paths are resolved relative to the included config file. This is also the case when including a directory which contains a `mkosi.conf` file.

I have not yet had the time to check if this also happens with a normal include, without the image step, or with attributes which resolve paths.

**Comment by DaanDeMeyer** [comment]
This is expected behavior, we only change directory when parsing a directory containing a mkosi.conf file. If we're parsing a regular file, we do not change directory.

**Comment by DaanDeMeyer** [comment]
https://github.com/systemd/mkosi/pull/2583 should give you a way to specify that you wants paths to be interpreted relative to the parent directory of the config file.
