### ISSUE TITLE
/var/lib/dpkg/available does not exist and causes errors when installing packages using apt in image

### ISSUE THREAD

**Issue by koberbe** [systemd/mkosi#2610]
### mkosi commit the issue has been seen with

v22

### Used host distribution

Debian 12 (backports enabled)

### Used target distribution

Ubuntu 20.04

### Linux kernel version used

6.1.0-18-amd64

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

mkosi does not create /var/lib/dpkg/available which is used by the old tool dselect. This caused errors when using piuparts to test Debian packages. The error occurs when piuparts installs the package to be tested into a chroot environment.

We have already found a workaround by running the following command in a prepare script:
```bash
dpkg --update-avail
```

I'm wondering if this command should be part of the mkosi build process.

### Used mkosi config

```ini
[Output]
Format=tar
CompressOutput=false

[Host]
QemuSwtpm=False
# setup qemu to exit on kernel panic
# https://unix.stackexchange.com/questions/443017/can-i-make-qemu-exit-with-failure-on-kernel-panic
QemuArgs=-no-reboot
KernelCommandLineExtra=panic=-1

[Content]
Bootable=false
WithDocs=false
PackageDirectories=../extra_packages/

[Packages]
WithNetwork=true

[Distribution]
Architecture=x86-64
Distribution=ubuntu
Release=focal
Repositories=main,universe

@Mirror=http://my-package-mirror.local/ubuntu

[Content]
Packages=apt
         apt-transport-https
         sudo
         ca-certificates
         ca-custom
         gpg
SkeletonTrees=../../../../data/rootfs
```

### mkosi output

```sh
piuparts output:

Preconfiguring packages ...
  dpkg: error: failed to open package info file '/var/lib/dpkg/available' for reading: No such file or directory
  Fetched 497 MB in 11s (44.2 MB/s)
  E: Sub-process dpkg --set-selections returned an error code (2)
  E: Couldn't record the approved state changes as dpkg selection states
```

**Comment by DaanDeMeyer** [comment]
@koberbe Please test the linked PR
