### ISSUE TITLE
`RuntimeSize=XG` does not result in image file of size X G

### ISSUE THREAD

**Issue by paulmenzel** [systemd/mkosi#2614]
### mkosi commit the issue has been seen with

88c54bab

### Used host distribution

Debian sid/unstable

### Used target distribution

Debian sid/unstable

### Linux kernel version used

6.7.9-cloud-amd64

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

Despite `RuntimeSize=20G` the resulting image is only 3.7 GB.

```
$ ls -lh mkosi.output/debian-sid-mkosi*
lrwxrwxrwx 1 100000 100000   20 Apr 10 13:10 mkosi.output/debian-sid-mkosi -> debian-sid-mkosi.raw
-rw-rw-r-- 1 build  build   89M Apr 10 13:10 mkosi.output/debian-sid-mkosi.efi
-rw-rw-r-- 1 build  build   73M Apr 10 13:10 mkosi.output/debian-sid-mkosi.initrd
-rw-rw-r-- 1 build  build  3.7G Apr 10 13:10 mkosi.output/debian-sid-mkosi.raw
-rw-rw-r-- 1 build  build   16M Apr 10 13:10 mkosi.output/debian-sid-mkosi.vmlinuz
```

### Used mkosi config

```ini
[Distribution]
#Repositories=main,universe

[Content]
Packages=dbus
#         linux-image-kvm
         systemd
         udev

[Host]
RuntimeSize=20G
```

### mkosi output

```sh
$ mkosi -d debian -r sid -t disk -o debian-sid-mkosi --debug
‣ Including configuration file /home/build/src/mkosi/mkosi.local.conf
‣ Including configuration file /home/build/src/mkosi/mkosi.conf
‣ Including configuration file /home/build/src/mkosi/mkosi.conf.d/15-bootable.conf
‣ Including configuration file /home/build/src/mkosi/mkosi.conf.d/15-x86-64.conf
‣ Including configuration file /home/build/src/mkosi/mkosi.conf.d/20-debian/mkosi.conf
‣ Including configuration file /home/build/src/mkosi/mkosi.conf.d/20-debian/mkosi.conf.d/20-x86-64.conf
[…]
```

[mkosi-debug-log.txt](https://github.com/systemd/mkosi/files/14931745/mkosi-debug-log.txt)

**Comment by paulmenzel** [comment]
I edited the issue description and attached the log file.

**Comment by DaanDeMeyer** [comment]
From the documentation:

```
`RuntimeSize=`, `--runtime-size=`

If specified, disk images are grown to the specified size before
  they're booted with systemd-nspawn or qemu.
```

You're not booting the image, so `RuntimeSize=` is not applied. Use mkosi.repart/ to assign partition with custom sizes. If you need more help, join the matrix channel linked in the readme.

**Comment by paulmenzel** [comment]
I see. In that case, “disk images are grown to the specified size before they're booted” is ambiguous to me. For me, it would help, if it was made clear, that this always means mkosi is used to boot the image.

**Comment by DaanDeMeyer** [comment]
https://github.com/systemd/mkosi/pull/2615
