### ISSUE TITLE
Link to mkosi.systemd.io is HTTP and HTTPS is not enforced

### ISSUE THREAD

**Issue by klausenbusk** [systemd/mkosi#2626]
I just noticed that the "about link" to mkosi.systemd.io on the repository front page is a HTTP link and that no redirecting from HTTP to HTTPS is implemented. That is a bit odd in the year of 2024.

For the systemd repository the link is HTTPS and HTTP requests are redirected to HTTPS.

**Comment by DaanDeMeyer** [comment]
Should be fixed now.

**Comment by klausenbusk** [comment]
The about link is still a HTTP link :)
