### ISSUE TITLE
Clamp mtime to `$SOURCE_DATE_EPOCH`

### ISSUE THREAD

**Issue by septatrix** [systemd/mkosi#2635]
### Discussed in https://github.com/systemd/mkosi/discussions/2571

<div type='discussions-op-text'>

<sup>Originally posted by **septatrix** March 30, 2024</sup>

TL;DR: Current implementation of `SourceDateEpoch=` is very drastic as the mtime of every file is updated.

</div>

An alternative suggested in the discussion is to clamp the mtime of files newer than `SourceDateEpoch=` instead of setting it for all files. This is way less invasive and also the approach used by adopted by Fedora: https://fedoraproject.org/wiki/Changes/ReproducibleBuildsClampMtimes

**Comment by keszybz** [comment]
Yeah. In hindsight, this is a very specific implementation choice. Simple people want to just reset the times, but for most uses this is too much, because the timestamps of files installed from packages are correct and reproducible and we don't want to get rid of them.
