### ISSUE TITLE
Ubuntu builds don't use the specified Mirror= for security patches

### ISSUE THREAD

**Issue by robleady** [systemd/mkosi#2640]
### mkosi commit the issue has been seen with

fa89e17c

### Used host distribution

Debian Unstable

### Used target distribution

Ubuntu 22.04

### Linux kernel version used

6.6.15-amd64

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

When building an Ubuntu image and specifying a Mirror, that mirror is used for the `<dist>` and `<dist>-updates` repositories, but not for the `<dist>-security` repository, which always uses `security.ubuntu.com`

That appears to be deliberate, looking at [ubuntu.py](https://github.com/systemd/mkosi/blob/fa89e17ccb4acef1972ceb29b3da804de1946bc4/mkosi/distributions/ubuntu.py#L70) however the rationale that `Security updates repos are never mirrored` appears to be incorrect, as the security repos are all present on [archive.ubuntu.com](http://archive.ubuntu.com/ubuntu)

For testing I've been using a mirror based on [snapshot.ubuntu.com](http://snapshot.ubuntu.com)

### Used mkosi config

```ini
[Output]
Format=disk
Output=ubuntu-test
ManifestFormat=json

[Distribution]
Distribution=ubuntu
Repositories=main,universe
Release=jammy
Mirror=http://snapshot.ubuntu.com/ubuntu/20231201T000000Z
Architecture=x86-64

[Content]
Packages=
    bash
    coreutils
    util-linux
    systemd
    systemd-sysv
    udev
    dbus
    linux-generic-hwe-22.04

Bootable=yes
Bootloader=systemd-boot
Autologin=yes
WithDocs=no
```

### mkosi output

```sh
$ mkosi --debug build
‣ Including configuration file /home/robl/mkosi-testing/mkosi.conf
‣ Acquiring lock on /tmp/mkosi-uidmap-lock_lb4gk4w
‣ Acquired lock on /tmp/mkosi-uidmap-lock_lb4gk4w
‣ + flock --exclusive --close /tmp/mkosi-uidmap-lock_lb4gk4w newuidmap 1885299 0 100000 65436 65436 1000 1 65437 165437 99
‣ + flock --exclusive --close /tmp/mkosi-uidmap-lock_lb4gk4w newgidmap 1885299 0 100000 65436 65436 1000 1 65437 165437 99
‣ + stat --file-system --format %T /home/robl/.cache/mkosi/mkosi-workspacel80kdh37
‣ Syncing package manager metadata for default image
‣ Acquiring lock on /home/robl/.cache/mkosi/ubuntu~jammy~x86-64/cache/apt
‣ Acquired lock on /home/robl/.cache/mkosi/ubuntu~jammy~x86-64/cache/apt
‣ Acquiring lock on /home/robl/.cache/mkosi/ubuntu~jammy~x86-64/lib/apt
‣ Acquired lock on /home/robl/.cache/mkosi/ubuntu~jammy~x86-64/lib/apt
‣ + apt-get -o APT::Architecture=amd64 -o APT::Architectures=amd64 -o APT::Install-Recommends=false -o APT::Immediate-Configure=off -o APT::Get::Assume-Yes=true -o APT::Get::AutomaticRemove=true -o APT::Get::Allow-Change-Held-Packages=true -o APT::Get::Allow-Remove-Essential=true -o APT::Sandbox::User=root -o Dir::Cache=/var/cache/apt -o Dir::State=/var/lib/apt -o Dir::Log=/var/log/apt -o Dir::State::Status=/buildroot/var/lib/dpkg/status -o Dir::Bin::DPkg=/usr/bin/dpkg -o Debug::NoLocking=true -o DPkg::Options::=--root=/buildroot -o DPkg::Options::=--force-unsafe-io -o DPkg::Options::=--force-architecture -o DPkg::Options::=--force-depends -o DPkg::Options::=--no-debsig -o DPkg::Use-Pty=false -o DPkg::Install::Recursive::Minimum=1000 -o pkgCacheGen::ForceEssential=, -o 'DPkg::Options::=--path-exclude=/usr/share/doc/*' -o 'DPkg::Options::=--path-include=/usr/share/doc/*/copyright' -o 'DPkg::Options::=--path-exclude=/usr/share/man/*' -o 'DPkg::Options::=--path-exclude=/usr/share/groff/*' -o 'DPkg::Options::=--path-exclude=/usr/share/info/*' update
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:1 https://snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy InRelease [270 kB]
Get:2 https://snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy-updates InRelease [119 kB]
Get:4 http://security.ubuntu.com/ubuntu jammy-security/main Sources [259 kB]
Get:5 https://snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy/main Sources [1340 kB]
Get:6 http://security.ubuntu.com/ubuntu jammy-security/universe Sources [182 kB]
Get:7 https://snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy/universe Sources [17.8 MB]
Get:8 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1346 kB]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/main Translation-en [237 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [852 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/universe Translation-en [163 kB]
Get:12 https://snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy/main amd64 Packages [1395 kB]
Get:13 https://snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy/main Translation-en [510 kB]
Get:14 https://snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy/universe amd64 Packages [14.1 MB]
Get:15 https://snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy/universe Translation-en [5652 kB]
Get:16 https://snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy-updates/universe Sources [289 kB]
Get:17 https://snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy-updates/main Sources [456 kB]
Get:18 https://snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy-updates/main amd64 Packages [1211 kB]
Get:19 https://snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy-updates/main Translation-en [253 kB]
Get:20 https://snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy-updates/universe amd64 Packages [1010 kB]
Get:21 https://snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy-updates/universe Translation-en [224 kB]
Fetched 47.8 MB in 8s (5768 kB/s)
Reading package lists... Done

<remaining output snipped>
```

**Comment by DaanDeMeyer** [comment]
@bluca

**Comment by bluca** [comment]
https://www.debian.org/mirror/ftpmirror#what

> The debian-security/ archives contain the security updates released by the Debian security team. While it sounds interesting to everyone, we do not recommend to our users to use mirrors to obtain security updates and instead ask them to directly download them from our distributed security.debian.org service. We recommend debian-security not be mirrored.

**Comment by DaanDeMeyer** [comment]
https://wiki.ubuntu.com/SecurityTeam/FAQ

> While packages are copied from security to updates frequently, it is recommended that systems always have the security pocket enabled, and use security.ubuntu.com for this pocket. For all other pockets feel free to use archive.ubuntu.com or an [archive mirror](https://launchpad.net/ubuntu/+archivemirrors). This combination will ensure you are able to download important updates immediately while taking advantage of the mirror network or archive.ubuntu.com for all other downloads. Ubuntu systems are configured in this manner by default.

So I'm not sure what to do here. I think your best bet is to provide your own sources file like follows:

```
[Distribution]
PackageManagerTrees=<path-to-sources>:/etc/apt/sources.list.d/mkosi.sources
```

**Comment by robleady** [comment]
For **Debian** that would be true. Indeed, you won't find any of the `-security` feeds on [deb.debian.org/debian/dists](http://deb.debian.org/debian/dists)

However, Canonical appear to taking a different approach with **Ubuntu**, and do provide the `-security` feeds alongside the others.
Mirror services do mirror the security feeds. For example: [https://www.mirrorservice.org/sites/archive.ubuntu.com/ubuntu/dists/](https://www.mirrorservice.org/sites/archive.ubuntu.com/ubuntu/dists/)

**Comment by DaanDeMeyer** [comment]
@robleady See my earlier reply, ubuntu also recommends using security.ubuntu.com for security updates and to not use the mirror network.

**Comment by robleady** [comment]
OK - I'd missed that FAQ on the Ubuntu site.
I had looked at the `PackageManagerTrees=` option, but couldn't make sense of the documentation.
I'll do some more testing...

**Comment by robleady** [comment]
Using `PackageManagerTrees=` seems to do the trick. Well actually I ended up using `SkeletonTrees=custom.sources:/etc/apt/sources.list.d/mkosi.sources` as I wanted the repository information to be in the final image.
However, I also get a default `jammy.sources` being written to `/etc/apt/sources.list.d` alongside my custom `mkosi.sources` in the final image. Is there an option to prevent this being written?

**Comment by DaanDeMeyer** [comment]
@robleady There is no option to prevent this from being written. I'd suggest removing it in a postinst script.

**Comment by DaanDeMeyer** [comment]
Let's close this as there's no clear solution here
