### ISSUE TITLE
Unbootable system with XBOOTLDR partition and UKIs?!

### ISSUE THREAD

**Issue by JM1** [systemd/mkosi#2738]
### mkosi commit the issue has been seen with

main

### Used host distribution

Debian 12 (Bookworm) on the host, Debian Sid in the tools tree.

### Used target distribution

Debian Sid

### Linux kernel version used

6.8.11-amd64

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

Suppose mkosi should create a disk image with systemd-boot, UKIs and three partitions:
* EFI system partition for `/efi`
* XBOOTLDR partition for `/boot`
* root partition for `/`

Using [this mkosi.repart configuration](https://github.com/JM1/mkosi-issue-xbootldr-uki/tree/main/mkosi.repart), `mkosi build` will create a disk image that will not boot. `systemd-boot` will not be able to find the UKI at the ESP. I have uploaded a reproducer at [JM1/mkosi-issue-xbootldr-uki](https://github.com/JM1/mkosi-issue-xbootldr-uki) to better illustrate the problem.

The disk will have three partitions:

```
$> losetup --find --show -P mkosi.output/image.raw

$> sgdisk  --print /dev/loop0
Disk /dev/loop0: 20973608 sectors, 10.0 GiB
Sector size (logical/physical): 512/512 bytes
Disk identifier (GUID): 94F1B98E-61F9-428E-A180-421874475669
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 33
First usable sector is 2048, last usable sector is 20973574
Partitions will be aligned on 2048-sector boundaries
Total free space is 7 sectors (3.5 KiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048         2099199   1024.0 MiB  EF00  esp
   2         2099200         4196351   1024.0 MiB  EA00  xbootldr
   3         4196352        20973567   8.0 GiB     8304  root-x86-64
```

For Debian Sid, the ESP contains the following:
```
./EFI
./EFI/systemd
./EFI/systemd/systemd-bootx64.efi
./EFI/BOOT
./EFI/BOOT/BOOTX64.EFI
./EFI/BOOT/grubx64.EFI
./EFI/BOOT/mmx64.efi
./loader
./loader/loader.conf
./loader/random-seed
```

XBOOTLDR contains the following:
```
./System.map-6.8.11-amd64
./config-6.8.11-amd64
./vmlinuz-6.8.11-amd64
./loader
./loader/entries
./loader/entries.srel
./EFI
./EFI/Linux
./EFI/Linux/debian-6.8.11-amd64.efi
```

The last file, `./EFI/Linux/debian-6.8.11-amd64.efi` is supposed to be stored at ESP.

## Workarounds

One dirty workaround is to copy all files from `/boot` to `/efi`, e.g. by adding `CopyFiles=/boot:/` to [mkosi.repart/00-esp.conf](mkosi.repart/00-esp.conf) as suggested [here](https://github.com/systemd/mkosi/commit/efbca7d01307a319f270ab65c30871ac31b43e4a).

However, a cleaner solution would be to install the UKI to `/efi` instead of `/boot`:
```
diff --git a/mkosi/__init__.py b/mkosi/__init__.py
index 5b49a82f..b41d36f1 100644
--- a/mkosi/__init__.py
+++ b/mkosi/__init__.py
@@ -2314,9 +2314,9 @@ def install_uki(context: Context, kver: str, kimg: Path, token: str, partitions:
     else:
         if roothash:
             _, _, h = roothash.partition("=")
-            boot_binary = context.root / f"boot/EFI/Linux/{token}-{kver}-{h}{boot_count}.efi"
+            boot_binary = context.root / f"efi/EFI/Linux/{token}-{kver}-{h}{boot_count}.efi"
         else:
-            boot_binary = context.root / f"boot/EFI/Linux/{token}-{kver}{boot_count}.efi"
+            boot_binary = context.root / f"efi/EFI/Linux/{token}-{kver}{boot_count}.efi"
 
     # Make sure the parent directory where we'll be writing the UKI exists.
     with umask(~0o700):
```

**NOTE:** Will this patch affect other build formats?!?

After applying the patch and rebuilding the image for Debian Sid, the ESP contains the following:
```
./EFI
./EFI/systemd
./EFI/systemd/systemd-bootx64.efi
./EFI/BOOT
./EFI/BOOT/BOOTX64.EFI
./EFI/BOOT/grubx64.EFI
./EFI/BOOT/mmx64.efi
./EFI/Linux
./EFI/Linux/debian-6.8.11-amd64.efi
./loader
./loader/loader.conf
./loader/random-seed
```

XBOOTLDR will contain the following:
```
./System.map-6.8.11-amd64
./config-6.8.11-amd64
./vmlinuz-6.8.11-amd64
./loader
./loader/entries
./loader/entries.srel
./EFI
./EFI/Linux
```

Afterwards, the image can be booted with `mkosi qemu`.

What do you think? 🤔

**Comment by DaanDeMeyer** [comment]
@JM1 Your XBOOTLDR partition is btrfs. Your UEFI firmware will only have a filesystem driver for vfat. XBOOTLDR should really always be vfat, otherwise there's a very good chance your bootloader can't read anything from it. Unless you use grub which reimplements all filesystems and is riddled with CVEs and bugs because of it.

**Comment by JM1** [comment]
Oooh! Changing `XBOOTLDR` from `btrfs` to `vfat` indeed fixes the boot issue. Now systemd-boot is able to find the UKI in QEMU. It looks like I misunderstood the purpose of XBOOTLDR. Having read the [boot loader spec](https://uapi-group.org/specifications/specs/boot_loader_specification/) again, it makes sense now. 

Now I am wondering though how we could get rid of the non-UKI files on XBOOTLDR (or ESP when XBOOTLDR does not exist), in particular:

```
./System.map-6.8.11-amd64
./config-6.8.11-amd64
./vmlinuz-6.8.11-amd64
```

They are not needed with UKIs, arent they? 

This is a different question from the initial report though, so i will close this. Thank you for the fast response :+1: ☺️

**Comment by JM1** [comment]
Well, the solution to my last question was easy: Change [mkosi.repart/10-xbootldr.conf](https://github.com/JM1/mkosi-issue-xbootldr-uki/blob/main/mkosi.repart/10-xbootldr.conf) to:

```
[Partition]
Type=xbootldr
Format=vfat
CopyFiles=/boot/loader:/loader
CopyFiles=/boot/EFI:/EFI
SizeMinBytes=1G
SizeMaxBytes=1G
```

Done.

**Comment by DaanDeMeyer** [comment]
`RemoveFiles=` is also an option
