### ISSUE TITLE
How to run mkosi inside chroot

### ISSUE THREAD

**Issue by asrinuva** [systemd/mkosi#2786]
### mkosi commit the issue has been seen with

main

### Used host distribution

debian 13

### Used target distribution

chroot

### Linux kernel version used

 6.5.0-35-generic #35~22.04.1-Ubuntu

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

Hi everyone,

                   My intention is to create standalone initrd via yocto recipe, created the recipe to chroot into the rootfs and installed the necessary packages and the calling mkosi to generate image/initrd

In the first time it says that "KeyError: 'getpwuid(): uid not found: 1000" this one gone after adding user with UID 1000 in chroot.
then i invoke the mkosi with the minimal configuration but still it says the below error:
No configuration found
‣ (Make sure you're running mkosi from a directory with configuration files)
‣ + tput cnorm
‣ + tput smam
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mkosi/run.py", line 55, in uncaught_exception_handler
    yield
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mkosi/__main__.py", line 38, in main
    run_verb(args, images, resources=resources)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 4098, in run_verb
    die("No configuration found",
  File "/usr/lib/python3/dist-packages/mkosi/log.py", line 31, in die
    sys.exit(1)
SystemExit: 1

Any help would be appreciated

### Used mkosi config

```ini
mkosi.conf file used in root directory:

[Output]
Format=cpio

[Content]
Packages=systemd
         udev
         kmod
```

### mkosi output

```sh
root@srinu-Precision-Tower-3430:/# ls
bin   dev  home        initrd.img.old  lib64       media       mnt  proc  run   srv  tmp  var      vmlinuz.old
boot  etc  initrd.img  lib             lost+found  mkosi.conf  opt  root  sbin  sys  usr  vmlinuz
root@srinu-Precision-Tower-3430:/# mkosi --debug
‣ Including configuration file /mkosi.conf
‣ Including configuration file /mkosi.conf
‣ No configuration found
‣ (Make sure you're running mkosi from a directory with configuration files)
‣ + tput cnorm
‣ + tput smam
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mkosi/run.py", line 55, in uncaught_exception_handler
    yield
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mkosi/__main__.py", line 38, in main
    run_verb(args, images, resources=resources)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 4098, in run_verb
    die("No configuration found",
  File "/usr/lib/python3/dist-packages/mkosi/log.py", line 31, in die
    sys.exit(1)
SystemExit: 1
root@srinu-Precision-Tower-3430:/#
```

**Comment by asrinuva** [comment]
Thanks! for the quick reply 
Hmm, Sorry for the confusion, my host system is trixie, but am generating rootfs by using container with ISAR build system, here i created ROOTFS for trixie version of debian.

I try to invoke mkosi manually once i entered to the chroot of root file system, in this chroot i installed the required packages like mkosi and more additional packages.

this is my os-release info:

srinu@srinu-Precision-Tower-3430:~/srinu_workspace/ISAR_MKOSI/build/tmp/work/debian-trixie-amd64/isar-image-base-qemuamd64/1.0-r0/rootfs$ cat etc/os-release PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
BUILD_ID="v0.10-104-g2c76d889-dirty"
VARIANT="Isar target filesystem"
VARIANT_VERSION="1.0"

Here my intention is to write a recipe that will generate standalone initrd using mkosi tool, but here all the recipes running in chroot.

Is there is any possibility to invoke the mkosi in chroot environment or what is the way to generate initrd via MKOSI using yocto like buildsystem


Many thanks,
Srinu

**Comment by asrinuva** [comment]
@DaanDeMeyer we need one more help, As you suggested the MKOSI can be invoked other than / directory but still this works on booted system (f.e: debian trixie)

But what i am trying is something try to invoke the MKOSI in chroot environment, here i manually created <user>/.cache/mkosi/<distro>/apt/.. folder due to MKOSI says that these folders not able to found, and moreover i have empty /proc folder because it's not booted environment.

Are we able to invoke MKOSI utility without booted environment?, 
I am trying to create standalone initrd before image generation in the build system

**Comment by behrmann** [comment]
At lot of the tools we use don't like `/proc` being empty, i.e. they require a booted system. 

The being said, looking at the the output you posted below, you are running an older version of mkosi. Can you try with current main?

Also, why exactly do you want to run this in a non-running system via chroot? Why not simply run it unprivileged? I gather this is a limitation of the build system?

**Comment by DaanDeMeyer** [comment]
We don't need a booted system, but we do need /proc mounted, it cannot be empty.

**Comment by asrinuva** [comment]
> At lot of the tools we use don't like `/proc` being empty, i.e. they require a booted system.
> 
> The being said, looking at the the output you posted below, you are running an older version of mkosi. Can you try with current main?
> 
Hmm, Here i installed the latest debian trixie mkosi package and using that

> Also, why exactly do you want to run this in a non-running system via chroot? Why not simply run it unprivileged? I gather this is a limitation of the build system?

I want to install some custom packages which is generated by the build system and it's available in chroot (installed via IMAGE_INSTALL) , once i entered into chroot i can able to install the upstream packages as well as my custom packages for initrd generation, but this chroot is not full rootfs like our booted system.

Suppose if i create the initrd via standalone script from the host system (debian trixie running), my worry is to how to build the custom packages and add into the initrd without build system

**Comment by asrinuva** [comment]
> We don't need a booted system, but we do need /proc mounted, it cannot be empty.

Thanks , let me try, can you please suggest what other folders should mount from the host system, because in my chroot there is no user under home directory, for testing purpose just i created manually .cache/mkosi/<distro> under /home/<user> directory

**Comment by behrmann** [comment]
> I want to install some custom packages which is generated by the build system and it's available in chroot (installed via IMAGE_INSTALL) , once i entered into chroot i can able to install the upstream packages as well as my custom packages for initrd generation, but this chroot is not full rootfs like our booted system.

Building the packages and then using them in a separate step, when running mkosi, might safe you some hassle.

**Comment by asrinuva** [comment]
Hi @DaanDeMeyer @behrmann ,

Now i have enough information in chroot to invoke the MKOSI command to generate the image, but still i could see few issue, here is my logs, please have a look.

`+ schroot -r -c isar-mahanadi-71d97ab2-3b76-4f53-b12a-a23ca24233b6-1812972-09a261f7-2c10-4fc2-bc52-7e217efe29ef -p -d /home/mahanadi/mkosi -- sh -c mkos     i --debug
1080 ‣ Including configuration file /home/mahanadi/mkosi/mkosi.conf
1081 ‣ Acquiring lock on /tmp/mkosi-uidmap-lock-4_75dw8c
1082 ‣ Acquired lock on /tmp/mkosi-uidmap-lock-4_75dw8c
1083 ‣ + flock --exclusive --close /tmp/mkosi-uidmap-lock-4_75dw8c newuidmap 1814129 0 100000 65436 65436 1000 1 65437 165437 99
1084 ‣ + flock --exclusive --close /tmp/mkosi-uidmap-lock-4_75dw8c newgidmap 1814129 0 100000 65436 65436 1000 1 65437 165437 99
1085 Traceback (most recent call last):
1086   File "/usr/lib/python3/dist-packages/mkosi/run.py", line 60, in uncaught_exception_handler
1087     yield
1088   File "/usr/lib/python3/dist-packages/mkosi/run.py", line 101, in fork_and_wait
1089     target(*args, **kwargs)
1090   File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 4443, in run_clean
1091     become_root()
1092   File "/usr/lib/python3/dist-packages/mkosi/user.py", line 195, in become_root
1093     unshare(CLONE_NEWUSER)
1094   File "/usr/lib/python3/dist-packages/mkosi/user.py", line 138, in unshare
1095     raise OSError(e, os.strerror(e))
1096 PermissionError: [Errno 1] Operation not permitted
1097 WARNING: exit code 1 from a shell command.
1098 + bb_sh_exit_handler
1099 + ret=1
1100 + [ 1 != 0 ]
1101 + echo WARNING: exit code 1 from a shell command.
1102 + exit 1`

Any help would be appreciated

**Comment by DaanDeMeyer** [comment]
@asrinuva Since you're trying to execute mkosi in this weird environment, it's up to you to figure out why it's not working. We expect to be able to unshare a user namespace. If that's not allowed, you'll need to figure out why your environment does not allow that.

**Comment by asrinuva** [comment]
Thanks let me check
