### ISSUE TITLE
Unable to build bootable Ubuntu Noble disk image (Package 'libtss2-mu0' has no installation candidate)

### ISSUE THREAD

**Issue by marekl** [systemd/mkosi#2857]
### mkosi commit the issue has been seen with

v23.1 (75b115aecf6c1011c3360bda4fc1c62250f66998) and main (4681dd733a925cd048d0301af26221bce0c95eed)
Using the zipapp built from the specified commits.

### Used host distribution

Ubuntu 24.04 (Noble)

### Used target distribution

Ubuntu 24.04 (Noble)

### Linux kernel version used

6.8.0-38-generic

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

When building an Ubuntu image with the `linux-image-generic` package specified the mkosi build fails with trying to install a non-existent package:  
`E: Package 'libtss2-mu0' has no installation candidate`

Seems to be a possible recurrence of https://github.com/systemd/mkosi/issues/2346?

### Used mkosi config

```ini
[Distribution]
Distribution=ubuntu
Release=noble

[Output]
Format=disk

[Content]
Bootable=yes
Bootloader=systemd-boot
Packages=linux-image-generic,systemd-boot
```

### mkosi output

Full log (too long for comment): https://gist.github.com/marekl/a4c32db0187948b4ac3ef85357271f58

Relevant error:
```sh
Package libtss2-mu0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libtss2-mu-4.0.1-0t64

E: Package 'libtss2-mu0' has no installation candidate
‣ "env APT_CONFIG=/var/tmp/mkosi-workspacevmscijrr/apt.conf DEBIAN_FRONTEND=noninteractive DEBCONF_INTERACTIVE_SEEN=true INITRD=No apt-get -o APT::Architecture=amd64 -o APT::Architectures=amd64 -o APT::Install-Recommends=false -o APT::Immediate-Configure=off -o APT::Get::Assume-Yes=true -o APT::Get::AutomaticRemove=true -o APT::Get::Allow-Change-Held-Packages=true -o APT::Get::Allow-Remove-Essential=true -o APT::Sandbox::User=root -o Dir::Cache=/var/cache/apt -o Dir::State=/var/lib/apt -o Dir::State::Status=/var/tmp/mkosi-workspacevmscijrr/root/var/lib/dpkg/status -o Dir::Log=/var/tmp/mkosi-workspacevmscijrr -o Dir::Bin::DPkg=/usr/bin/dpkg -o Debug::NoLocking=true -o DPkg::Options::=--root=/var/tmp/mkosi-workspacevmscijrr/root -o DPkg::Options::=--force-unsafe-io -o DPkg::Options::=--force-architecture -o DPkg::Options::=--force-depends -o DPkg::Options::=--no-debsig -o DPkg::Use-Pty=false -o DPkg::Install::Recursive::Minimum=1000 -o pkgCacheGen::ForceEssential=, -o 'DPkg::Options::=--path-exclude=/usr/share/doc/*' -o 'DPkg::Options::=--path-include=/usr/share/doc/*/copyright' -o 'DPkg::Options::=--path-exclude=/usr/share/man/*' -o 'DPkg::Options::=--path-exclude=/usr/share/groff/*' -o 'DPkg::Options::=--path-exclude=/usr/share/info/*' install '^libtss2-esys-[0-9\.]+-0$' bash dmsetup e2fsprogs kmod less libfido2-1 libtss2-mu0 libtss2-rc0 libtss2-tcti-device0 lvm2 p11-kit systemd udev util-linux" returned non-zero exit code 100.
```

**Comment by DaanDeMeyer** [comment]
My initial attempts at reproducing this from Fedora are coming up empty, even with a ubuntu noble tools tree.

**Comment by DaanDeMeyer** [comment]
Cannot reproduce in a Ubuntu Noble virtual machine either :(

**Comment by marekl** [comment]
> Cannot reproduce in a Ubuntu Noble virtual machine either :(

@DaanDeMeyer My apologies, upon further investigation I realized that I was running the build as `root` which did not have the updated `zipapp` binaries on the path and was instead defaulting to mkosi `v20.2` which ships with Ubuntu 24.04. Actually running the build with `v23.1` resolves the issue for me.

Not a bug in `mkosi`. Thank your for your assistance.
