### ISSUE TITLE
`PackageManagerTree=` in image directory no longer falls back to `mkosi.skeleton/`

### ISSUE THREAD

**Issue by septatrix** [systemd/mkosi#2874]
### mkosi commit the issue has been seen with

main

### Used host distribution

Fedora 40

### Used target distribution

Fedora 40

### Linux kernel version used

6.9.8-200.fc40.x86_64

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

My previously working build started to fail due to dnf not finding a match for packages from additional repos.
Checking with `mkosi summary` it reports `Package Manager Trees: none` instead of `.../mkosi.images/system/mkosi.skeleton` like it did previously.

Moving the skeleton tree to the main image, or moving it to `mkosi.pkgmngr/` results in it being correctly picked up.

**Comment by DaanDeMeyer** [comment]
@septatrix I think this is fallout from the config parsing rework. Package manager trees are a univeral property so they're explicitly passed to the subimages which causes the default one to not be picked up even if there are none in the main image. I recommend either of the solutions you already came up with or explicitly configuring `PackageManagerTrees=` in the subimage which should also make it get picked up.

**Comment by septatrix** [comment]
Maybe universal options should not be explicitly passed to subimages if they are none (unless explicitly set to none)? At the very least the current behavior contradicts what is written in the docs.

For the time being I moved it to `mkosi.pkgmngr`
