### ISSUE TITLE
Environment in mkosi.configure script

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#2894]
### Discussed in https://github.com/systemd/mkosi/discussions/2893

<div type='discussions-op-text'>

<sup>Originally posted by **ragazenta** July 22, 2024</sup>
Hello, I haven't followed `mkosi` for a while and it seems there are some big changes.

Previously I set up `mkosi.configure` script to do some `sed` replacement with some environment variables. I defined the variables in `mkosi.env`. With `mkosi` from latest git main, it doesn't work anymore, the variables are now blank.

Is there any alternatives to do this?

Thanks.</div>

@ragazenta Can you provide a config that reproduces the issue? This should still work

**Comment by ragazenta** [comment]
Ah I see, previously I put `mkosi.env` in main directory, the `mkosi.configure` script is in the sub-image directory (`mkosi.images/base`). I need to move the `mkosi.env`.

Previous setup
```shell
.
├── mkosi.conf
├── mkosi.crt
├── mkosi.env
├── mkosi.images
│   ├── base
│   │   ├── mkosi.conf
│   │   └── mkosi.configure
│   ├── initrd
│   │   ├── mkosi.conf
│   │   └── mkosi.extra
│   └── system
│       ├── mkosi.conf
│       ├── mkosi.extra
│       ├── mkosi.postinst
│       ├── mkosi.postinst.chroot
│       └── mkosi.skeleton
```

**Comment by DaanDeMeyer** [comment]
@ragazenta Please see the description of https://github.com/systemd/mkosi/pull/2847. You'll should move your `system` image to the top level configuration as well to accomodate the latest changes in mkosi.

**Comment by DaanDeMeyer** [comment]
Let's close this as the original issue was resolved. Feel free to open another discussion if you have more questions on how to adapt your config to the latest changes
