### ISSUE TITLE
Cannot use sub-images to generate disk images with different sector sizes

### ISSUE THREAD

**Issue by mcassaniti** [systemd/mkosi#2939]
With the change in v24 to building multiple images, the option `SectorSize=` cannot be changed between sub-images. It makes sense to build images for different devices that support different sector sizes with the most common being 512 bytes and 4096 bytes. The sub-images can share a base directory image that contains everything required and then the output images are only interested in generating disk images.

You cannot use a disk image with 512 byte sector sizes on an NVMe drive that expects 4096 byte sector sizes and vice versa. You also cannot just convert the image and expect the verity hashes to work properly, so you really do need multiple images with almost the same content.

**Comment by mcassaniti** [comment]
My particular use case is to build a rescue image for a USB stick using sector size of 512 bytes, and a desktop image with a sector size of 4096 bytes. Both use a common base image. Naturally there's more packages in the desktop image too, but the base image has a lot of common packages.

**Comment by DaanDeMeyer** [comment]
OK in that case, we can fix this with the same solution as #2938

**Comment by mcassaniti** [comment]
> OK in that case, we can fix this with the same solution as #2938

Brilliant. Always grateful.
