### ISSUE TITLE
reproducible UKI for Arch Linux (possibly other distros)

### ISSUE THREAD

**Issue by jelly** [systemd/mkosi#2957]
### mkosi commit the issue has been seen with

main

### Used host distribution

Arch Linux

### Used target distribution

Arch Linux

### Linux kernel version used

6.9.7

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

I noticed the UKI isn't reproducible, the cause is `/var/cache/ldconfig/aux-cache` generated by glibc is unreproducible, this is a known issue but not sure how trivial it is to fix upstream. This ends up in the initrd which makes the whole UKI not reproducible:

In `build_image` I hacked up:
```
        fixup_vmlinuz_location(context)

        # drop ldconfig
        os.remove(context.root / "var/cache/ldconfig/aux-cache")
```

This makes the UKI reproducible, but as this function also calls 

```
        remove_files(context)
```

I suspected that I could use: `--remove-files /var/cache/ldconfig/aux-cache` in my reproducer in the CLI, but this does not seem to remove the file.

Full invocation:

```
mkosi -d arch -p systemd -p linux -p base -p grub -p openssh -p sudo -p reflector -p btrfs-progs -p udev --source-date-epoch 1662046009 --format directory -o foo -m https://archive.archlinux.org/repos/2024/06/30/ --force --remove-files /var/cache/ldconfig/aux-cache
```

This is just to make a `foo` dir and then I run it again with `bar` as dir and `diffoscope the output.

**Comment by jelly** [comment]
So for Arch, I'd be happy to just add /var/cache/ldconfig/aux-cache to RemoveFiles in the config, but I believe `--remote-files` should also work, unless I am mistaken in how the arguments are specified.

**Comment by DaanDeMeyer** [comment]
@jelly `--remove-files` is not propagated to the default initrd image build (you might want to remove files in the main image without removing them in the initrd). Instead, we can just remove the file by default in the initrd, see linked PR.

**Comment by jelly** [comment]
> @jelly `--remove-files` is not propagated to the default initrd image build (you might want to remove files in the main image without removing them in the initrd). Instead, we can just remove the file by default in the initrd, see linked PR.

Right, that was indeed my issue, I suppose I should have been more clear about that. Thanks for the PR, removing it would also help out [here](https://github.com/edgelesssys/reproducible-mkosi/blob/main/mkosi.images/initrd/mkosi.conf.d/fedora.conf#L13)

Interestingly not needed for Ubuntu https://github.com/edgelesssys/reproducible-mkosi/blob/main/mkosi.images/initrd/mkosi.conf.d/ubuntu.conf

**Comment by aafeijoo-suse** [comment]
I came across this issue today using openSUSE Tumbleweed, and 173dc51c8013b24c5bbcb9379c87d1bff83ed78a also fixed the reproducible build for me. Thanks!
