### ISSUE TITLE
error detecting Azure Linux host (`os-release`'s `"azurelinux"` != `mkosi`'s `"azure"`)

### ISSUE THREAD

**Issue by reubeno** [systemd/mkosi#2988]
### mkosi commit the issue has been seen with

main

### Used host distribution

Azure Linux 3.0

### Used target distribution

Azure Linux 3.0

### Linux kernel version used

kernel-6.6.47.1-1.azl3

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

`mkosi` knows about Azure Linux 3.0 now, thanks to #2833 🎉, but uses `azure` as the moniker instead of the `azurelinux` moniker that Azure Linux 3.0+ uses in `os-release`, e.g.:

```
NAME="Microsoft Azure Linux"
VERSION="3.0.20240824"
ID=azurelinux
VERSION_ID="3.0"
PRETTY_NAME="Microsoft Azure Linux 3.0"
```

This appears to result in the host not being correctly detected, and then things start failing thereafter (see error output below).

A naive `s/azure/azurelinux/g` in `mkosi` gets past this issue (well, at least far enough to hit a different one 🙂 ). I'm happy to submit a PR but wanted to check in with y'all first as to how you'd envision resolving this. (Would you instead prefer to keep the distribution enum and conf-file value as-is and instead add an indirection/alias?)

### mkosi output

```sh
‣ Distribution of your host can't be detected or isn't a supported target. Defaulting to Distribution=custom.
‣ Distribution of your host can't be detected or isn't a supported target. Defaulting to Distribution=custom.
‣ Syncing package manager metadata for default image
‣ Building default image
‣  Installing Custom
Traceback (most recent call last):
  File "/home/reubeno/mkosi/mkosi/run.py", line 63, in uncaught_exception_handler
    yield
  File "/home/reubeno/mkosi/mkosi/run.py", line 104, in fork_and_wait
    target(*args, **kwargs)
  File "/home/reubeno/mkosi/mkosi/__init__.py", line 4676, in run_build
    build_image(
  File "/home/reubeno/mkosi/mkosi/__init__.py", line 3906, in build_image
    install_distribution(context)
  File "/home/reubeno/mkosi/mkosi/__init__.py", line 174, in install_distribution
    (context.root / "etc/machine-id").write_text("uninitialized\n")
  File "/usr/lib/python3.12/pathlib.py", line 1047, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/reubeno/.cache/mkosi/mkosi-workspace-_7wu37qc/root/etc/machine-id'
```

**Comment by DaanDeMeyer** [comment]
I took the liberty to prepare a fix myself. See the attached PR
