### ISSUE TITLE
run_workspace_command runs in a private network, breaking apt-get

### ISSUE THREAD

**Issue by fsateler** [systemd/mkosi#30]
Commit 305b6e45 introduced `run_workspace_command`. This function sets `--private-network`, and thus breaks the `apt-get` command in `install_debian_or_ubuntu`. 

I wonder why is it important to set --private-network? Or should the function have an optional parameter specifying whether the network should be private?

**Comment by fsateler** [comment]
cc @keszybz

**Comment by keszybz** [comment]
Yeah, that's of course an error. `run_workspace_command` is now used 4 times, and only 1 requires network, so an optional parameter would be a good solution.

**Comment by fsateler** [comment]
Fix at #31
