### ISSUE TITLE
PXE-boot root-fs

### ISSUE THREAD

**Issue by NicolasT** [systemd/mkosi#302]
Hello,

Has anyone ever tried (or, ideally, succeeded) to use `mkosi` to build a root-fs image which can be used with a kernel and a `dracut`-based `initrd` and passed in using the `dracut` `root=live:...` feature, for PXE booting? Ideally with `verity` support and such :smile:

Or is `mkosi` not supposed to be used for such purposes?

Thanks.

**Comment by poettering** [comment]
I have no experience with PXE, and what requirements are made on images supplied that way.

That said: do you intend to deploy the whole generated image via PXE? or just kernel+initrd? If the latter, how do you intend to reference the image? nbd? iscsi? or even nfs?

I figure it might be worth adding explicit PXE support for this in some way, i.e. generate a PXE image with kernel+initrd in addition to the main OS image. But this really needs a champion to do the work...

(besides building the PXE image, this would probably also need some generator that detects its run in a PXE environment and then sets up nbd/iscsi/... to reference the host image)

**Comment by NicolasT** [comment]
There are many ways, of course: one could likely take a `directory` build of `mkosi`, put it on an NFS server, have a kernel image and a corresponding `initrd` (e.g. created with `dracut`) and take it from there.

Basically, PXE allows you to load some first image (e.g. `pxelinux` or chainload to an `ipxe` image), which then take it from there. In the `pxelinux` case, you may then load a kernel and `initrd` from a TFTP server, or when using iPXE from a HTTP server or whatnot.

Anyway, the whole PXE part of my question is a bit of a red herring, sorry. I'm more specifically looking for a way to build an FS image which can be booted using Dracut's 'livenet' feature. Here's how it works: in the kernel cmdline you specify `root=live:http://host/root.img`, then when the Dracut init script runs, it will download this image file using HTTP after setting up the network (or using one of the other supported protocols), `losetup` the image, create a writable overlay (using dm-snapshot or overlayfs) when the image is SquashFS, then pivot root and launch the image init system (i.e. `systemd`).

Currently one can build such SquashFS image using Lorax and `livemedia-creator` using `--make-pxe-live`. This image requires a somewhat specific file structure with an embedded image, though with newer versions of Dracut this is no longer the case, I believe.

When not using SquashFS, as far as I could see (though admitted didn't test yet) all one needs is a plain image of e.g. an `ext4` filesystem which can act as a root-FS.

So, as a first step, things may work out by adding support to `mkosi` to build an `ext4` image *without* emulating a full block device including a GPT table, EFI and root partitions,...

In a later stage, supporting creation of a SquashFS image adhering to the Dracut requirements could make sense.

Finally, for `verity` (eventually): right now there's no support in Dracut for this, however, there are some third-party modules to add support. The way these work, given the lack of a partitions, is by appending the `verity` data to the `ext4` filesystem, then at boot time figure out the length of the root FS in the image, and tell the DM layer to find the `verity` data at that offset.

**Comment by NicolasT** [comment]
Basically, what the output should conform to, is that given a Dracut `initrd` which has `livenet` support (and some other modules enabled), a corresponding kernel image, and the output of `mkosi` served on some HTTP server, then (from memory) `qemu-system-x86_64 -kernel vmlinuz -initrd initramfs -append "ro root=live:http://host/mkosi-output.img"` should work (assuming networking is set up etc.)

**Comment by poettering** [comment]
> Anyway, the whole PXE part of my question is a bit of a red herring, sorry. I'm more specifically looking for a way to build an FS image which can be booted using Dracut's 'livenet' feature. Here's how it works: in the kernel cmdline you specify `root=live:http://host/root.img`, then when the Dracut init script runs, it will download this image file using HTTP after setting up the network (or using one of the other supported protocols), `losetup` the image, create a writable overlay (using dm-snapshot or overlayfs) when the image is SquashFS, then pivot root and launch the image init system (i.e. `systemd`).

Where does dracut put the downloaded image? RAM?

**Comment by poettering** [comment]
So, if dracut sets up everything including the overlayfs, then it also needs to be dracut that does the verity stuff in the middle. But yeah, it should totally be possible to do this, but I have no idea how smart dracut is when it comes to dm-verity though.

That said, I think it would make sense to teach systemd itself the root overlayfs magic a bit, after all it contains the generator that that process root= and automatic root discovery, and a concept like this is kinda useful in all cases, not just PXE I guess.

Does dracut insist on partition-table-less images though? if not, then mkosi should be mostly ready for your usecase (except that it also needs to output the unified kernel as artifact, so that you can use that as PXE payload, currently it only generates that as part of the image itself, so you'd have to extract it from there...)

**Comment by NicolasT** [comment]
> Where does dracut put the downloaded image? RAM?

Exactly.

For details, see https://github.com/dracutdevs/dracut/blob/master/modules.d/90livenet/livenetroot.sh and the `dmsquash-live-root` script.

**Comment by poettering** [comment]
> Agree. Do you suggest to get rid of Dracut and have a systemd-based initrd only?

Well, what dracut gives you is two things:

1. a tool that can generate them, picking all the various bits and pieces from the host that are necessary
2. a set of scripts doing LVM, DM, RAID, … and all that other weird stuff

systemd is not going to give you either of that. That said, what systemd probably should offer is a some really generic stuff, and I'd count overlayfs root support into that. People have previously asked for support for something like that in nspawn, and I figure when we support that for nspawn containers we should support that for the host too. (I mean, generally we try to keep what we support for nspawn in sync with what we support for the host fs: verity, luks, auto discovery, it's all there)

**Comment by poettering** [comment]
oh, and btw, I completely forgot: there's now support for creating naked squashfs images too. use `plain_squashfs` for that.

That said, those images are currently not bootable. I figure to make this work for you, we'd have to add a mode where mkosi can build an fs image for you and a detached, unified kernel/initrd image. That shouldn't be too hard I guess.

**Comment by NicolasT** [comment]
I experimented with `plain_squashfs` before, but no success. I may need to try some more though.

One of the issues may be that CentOS7 (the OS I want to deploy) `initrd`s aren't able to handle plain SquashFS images of a root FS, but require the image-in-image layout. Not sure though.

**Comment by poettering** [comment]
btw, just to mention: verity kinda means having two partitions: one with the verity data and one with the actual file system. hence if you want to do verity you can't do naked images really.

**Comment by NicolasT** [comment]
So, some success :) I got a `plain_squashfs` image to boot to prompt using a variant of the `qemu` command line above. Currently it's quite an ugly setup using a CentOS 7 image built by `mkosi`, combined with a Fedora 29 kernel and a custom-built Dracut initrd matching that kernel.

The trick was using a new-enough Dracut version (i.e. 049, not 048) which contains https://github.com/dracutdevs/dracut/commit/789668deb3e6f8584ffab964d2204ddcb75f0a06 and as such supports 'plain' filesystems inside the SquashFS without another embedded image.

**Comment by NicolasT** [comment]
> btw, just to mention: verity kinda means having two partitions: one with the verity data and one with the actual file system. hence if you want to do verity you can't do naked images really.

`veritysetup` has a `--hash-offset` option, so, if one creates a fixed-size `ext4` filesystem in some raw image, then creates the `verity` hashes and concatenates these to the existing image taking proper alignment into account (without the need for any actual partitions), things can work out: the raw image file can be used as a root FS as-is, the `ext4` FS knows its proper size so it won't care about whatever data is appended to it 'in the same device', and `veritysetup` should be called with the appropriate `hash-offset` which can be calculated from the `ext4` metadata.

This is exactly what https://github.com/hatlocker/dracut-verity/blob/master/10verity/verity-generator does using https://github.com/hatlocker/dracut-verity/blob/master/e2size.c (originally developed by the CoreOS people).

Anyway, for the PXE scenario, `verity` may be overkill anyway: similar to how Dracut supports validating the checksum of a boot ISO file, one could add support to validate the checksum (or even signature?) of the root image after download, based on a hash passed on the kernel command-line, similar to `verity`.

**Comment by poettering** [comment]
> `veritysetup` has a `--hash-offset` option, so, if one creates a fixed-size `ext4` filesystem in some raw image, then creates the `verity` hashes and concatenates these to the existing image taking proper alignment into account (without the need for any actual partitions), things can work out: the raw image file can be used as a root FS as-is, the `ext4` FS knows its proper size so it won't care about whatever data is appended to it 'in the same device', and `veritysetup` should be called with the appropriate `hash-offset` which can be calculated from the `ext4` metadata.

Well, great, so you are now using the partition concept but not a partition table, where's the benefit of that?

the verity support in systemd is really about making these things full automatic, fully discoverable: a gpt partition with two partitions and the data and verity partition are bound together by their uuids which are both derived from the root level hash. It doesn't get simpler than that. Moreover, pretty much everything understands GPT, so why even bother with avoiding it?

**Comment by poettering** [comment]
> Anyway, for the PXE scenario, `verity` may be overkill anyway: similar to how Dracut supports validating the checksum of a boot ISO file, one could add support to validate the checksum (or even signature?) of the root image after download, based on a hash passed on the kernel command-line, similar to `verity`.

Well, this is only works if you are fine with paying the verification penalty up-front.

**Comment by lzap** [comment]
@NicolasT hey is there any chance you could share steps to build a live PXE image today? I am assuming the required patch is in both Fedora and CentOS8 and I'd be interested in trying this out.

Or perhaps, are there any new features in mkosi that would make PXE boot ready images easier to generate?

**Comment by ajf** [comment]
@lzap - been a while, but I managed to boot a mkosi image with iPXE on an EFI machine, hope it helps.  I'm probably missing a bunch of stuff around what mkosi is doing, but it's a start, and I'm still integrating it with our build system.

Add dracut-live:
```
diff --git a/mkosi/__init__.py b/mkosi/__init__.py
index f95696b..917a028 100644
--- a/mkosi/__init__.py
+++ b/mkosi/__init__.py
@@ -1631,6 +1631,7 @@ def configure_dracut(args: CommandLineArguments, packages: Set[str], root: Path)
     )

     dracut_dir.joinpath("30-mkosi-qemu.conf").write_text('add_dracutmodules+=" qemu "\n')
+    dracut_dir.joinpath("31-live.conf").write_text('add_dracutmodules+=" livenet "\n')

     with dracut_dir.joinpath("30-mkosi-systemd-extras.conf").open("w") as f:
         for extra in DRACUT_SYSTEMD_EXTRAS:
```

Build the image:
```
sudo python3 -m mkosi -d debian -b --hostname mkosi-preexec -p cloud-init -p file -p dracut-live --password password --format gpt_squashfs --split-artifacts
```
(node the `-p dracut-live` and `--split-artifacts` options here)

Your unified kernel will be `image.efi` and the root filesystem will be `image.root`, copy these somewhere accessible from the iPXE client.

From iPXE:
```
chain http://server/image.efi root=live:http://server/image.root
```

I haven't figured anything else out yet, it'd be great if i could figure out how to get dracut to do something with the image.raw directly, which I'd imagine is how to get most of the other stuff mkosi does like verity and luks and stuff.

```
image.raw: DOS/MBR boot sector; partition 1 : ID=0xee, start-CHS (0x0,0,2), end-CHS (0x3ff,255,63), startsector 1, 989439 sectors, extended partition table (last)
```

Anyway, hope that helps and super interested if you get more of the mkosi experience working properly.
