### ISSUE TITLE
pkcs11 urls can't be entered into mkosi.conf

### ISSUE THREAD

**Issue by pwicks86** [systemd/mkosi#3050]
### mkosi commit the issue has been seen with

main

### Used host distribution

Ubuntu

### Used target distribution

Ubuntu

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

pkcs11 urls may have `;` characters in them, which the parsing of mkosi.conf does not handle correctly. If left unquoted, then the parser assumes anything after the first `;` on a line is a comment and strips it from the `SecureBootKey` value. If quoted, then there seems to be a bug in the way the command is generated for `sbsign`. For example, if I have this in mkosi.conf:

```
[Validation]
SecureBoot=yes
SecureBootKey="pkcs11:object=sb-key;type=private"
SecureBootCertificate=../cert.pem
SecureBootKeySource=engine:pkcs11
```

then mkosi tries to call sbsign like this:

```
‣ + sbsign --cert /work/home/pwicks/Projects/test/os/cert.pem --output /work/var/tmp/mkosi-workspace-48oqwus4/root/usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed --engine pkcs11 --key '"pkcs11:object=sb-key' /work/var/tmp/mkosi-workspace-48oqwus4/root/usr/lib/systemd/boot/efi/systemd-bootx64.efi
````

This fails as sbsign does not recognize the url format due to the incorrect quoting applied to it.

Entering the urls as command-line args works though.

### Used mkosi config

```ini
[Validation]
SecureBoot=yes
SecureBootKey="pkcs11:object=sb-key;type=private"
SecureBootCertificate=../cert.pem
SecureBootKeySource=engine:pkcs11
```

### mkosi output

```sh
‣ + sbsign --cert /work/home/pwicks/Projects/test/os/cert.pem --output /work/var/tmp/mkosi-workspace-48oqwus4/root/usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed --engine pkcs11 --key '"pkcs11:object=sb-key' /work/var/tmp/mkosi-workspace-48oqwus4/root/usr/lib/systemd/boot/efi/systemd-bootx64.efi
```

**Comment by DaanDeMeyer** [comment]
We don't consider ';' as a comment anymore on git main
