### ISSUE TITLE
Can't pass pkcs11 url to sbsign (still)

### ISSUE THREAD

**Issue by pwicks86** [systemd/mkosi#3051]
### mkosi commit the issue has been seen with

main

### Used host distribution

Ubuntu

### Used target distribution

Ubuntu

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

Same issue as #3033, which was mostly fixed by #3034, but I think there's a small typo there, https://github.com/systemd/mkosi/commit/d372eff718454eb34177f452b0bebd8836b97928#diff-6dd01168bec0ccfd7768e60d92f625169f00097fc407541abda3055841a29fb0R523 shouldn't have the call to workdir. I can also submit a PR for this if that's helpful.

**Comment by DaanDeMeyer** [comment]
@pwicks86 Send a PR please I can't see where we're still doing it wrong
