### ISSUE TITLE
[systemd spawn issue]

### ISSUE THREAD

**Issue by ferrar12121987** [systemd/mkosi#3071]
### mkosi commit the issue has been seen with

main

### Used host distribution

Debian 12

### Used target distribution

Debian bookworm

### Linux kernel version used

6.1.0-23-cloud-amd64

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

Hey, Apologies I am just getting familiar with the tool if there is introduction tutorials etc I can watch please let me know, however I am following https://0pointer.net/blog/mkosi-a-tool-for-generating-os-images.html . I attempted to test the image a got the output below:

```
admin@ip-172-31-36-241:~/test_mkosi/mkosi-for-ubuntu$ ls
README.md  debian-tools  image  image.raw  kiwi  mkosi  mkosi.default  mkosi.extra  mkosi.postinst
admin@ip-172-31-36-241:~/test_mkosi/mkosi-for-ubuntu$ mkosi --version
mkosi 25~devel
admin@ip-172-31-36-241:~/test_mkosi/mkosi-for-ubuntu$ sudo systemd-nspawn -bi image.raw
Spawning container image on /home/admin/test_mkosi/mkosi-for-ubuntu/image.raw.
Press ^] three times within 1s to kill container.
execv(/usr/lib/systemd/systemd, /lib/systemd/systemd, /sbin/init) failed: No such file or directory
Container image failed with error code 1.
admin@ip-172-31-36-241:~/test_mkosi/mkosi-for-ubuntu$ 
```

Any advice would be appreciated.

Kind regards

### Used mkosi config

```ini
# This is the main configuration file.

[Distribution]
Distribution=debian

Release=bookworm
Architecture=x86-64


[Output]
Format=gpt_ext4
Bootable=yes
Hostname=thegrid

[Partitions]
RootSize=5G

[Packages]
# The packages to appear in the final image
Packages=nano less tmux ssh dnsutils curl

# let mkosi.postinst access the internet
# (needed because we are updating and installing packages there)
WithNetwork=yes

[Validation]
# root password
Password=mementomori
```

### mkosi output

```sh
I cannot get the full debug from the build.
```

**Comment by DaanDeMeyer** [comment]
@ferrar12121987 That blog post is from years ago and doesn't apply anymore, please follow https://0pointer.net/blog/a-re-introduction-to-mkosi-a-tool-for-generating-os-images.html instead
