### ISSUE TITLE
mkosi.finalize hookup appears borked

### ISSUE THREAD

**Issue by poettering** [systemd/mkosi#310]
run_finalize_script() is currently called with verb="build" after the incremental build image is created and then a second time with verb="final" after the development image is created. This looks wrong. I am sure it should not be called during the incremental image generation at all, but instead only in the later real development/final image generation.

@keszybz could you look into this plz?

(Note that build_image() is called four times currently: 1. to generate incremental devel image, 2. to generate incremental final image. 3. to generate real devel image off incremental one, 4. to generate real final image off incremental one, and afaics the hookups are done between the wrong stages of this)

**Comment by dellgreen** [comment]
Could these be related? #316

**Comment by mmorvai** [comment]
I think you were right. It was done between the wrong stages. But the hookup also has to move inside build_image() to be able to manipulate the contents of the final image.
