### ISSUE TITLE
Empty directories remain under `.../kernel/drivers/firmware/`

### ISSUE THREAD

**Issue by Winterhuman** [systemd/mkosi#3124]
### mkosi commit the issue has been seen with

26673f65e17ae099bb0cf65928fe70c93b8a6a37 (v24.3)

### Used host distribution

Arch Linux

### Used target distribution

Arch Linux

### Linux kernel version used

6.11.2-arch1-1

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

`/usr/lib/modules/*/kernel/drivers/firmware/{cirrus,efi,google}/` are left as empty directories after their modules are removed. The behaviour doesn't change regardless of `-fi` or `-ffi` (the `--debug` logs are from running `mkosi -fi --debug`).

### Used mkosi config

```ini
[Distribution]
Distribution=arch

[Content]
Packages=
	base
	linux

KernelModulesExclude=
	drivers/firmware

[Output]
Format=uki
ImageId=debug
PackageCacheDirectory=mkosi.pkgcache
```

### mkosi output

```sh
Pasting the log returned: "There was an error creating your issue: body is too long, body is too long (maximum is 65536 characters)."

https://gist.github.com/Winterhuman/03b4f1c4e54577454995b1be7645feed
```

**Comment by DaanDeMeyer** [comment]
That probably means it's a dependency of some other module?

**Comment by Winterhuman** [comment]
Yeah, the module's inclusion is definitely unrelated to the empty directories being left; I should of figured that. I'll modify the report to focus on the actual bug.
