### ISSUE TITLE
mkosi-initrd config file has no effect

### ISSUE THREAD

**Issue by MoltenArmor** [systemd/mkosi#3127]
### mkosi commit the issue has been seen with

main

### Used host distribution

Debian testing

### Used target distribution

Centos

### Linux kernel version used

5.14.0-516.el9.aarch64

### CPU architectures issue was seen on

aarch64

### Unexpected behaviour you saw

When building a centos image, this configuration file: `mkosi-initrd/mkosi.conf.d/10-centos/20-epel-packages.conf` has no effect.

```
# mkosi/resources/mkosi-initrd/mkosi.conf.d/10-centos/20-epel-packages.conf
# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Repositories=epel

[Content]
Packages=
        # provides fsck.erofs
        erofs-utils
```

However, renaming it to `mkosi-initrd/mkosi.conf.d/10-centos/mkosi.conf` fixes this problem.

I wonder if this was done on purpose or by mistake?

### Used mkosi config

```ini
[Build]
CacheDirectory=mkosi.cache
Incremental=yes

[Output]
OutputDirectory=mkosi.output
Format=disk

[Distribution]
Distribution=centos
Release=9
# Enable epel in order to meet the condition in [Match] section
Repositories=epel

[Content]
KernelModulesInitrdInclude=default
Bootable=yes
Packages=kernel-core
```

### mkosi output

This initrd is built before renaming `20-epel-packages.conf` to `mkosi.conf`:
```sh
root@debian-test:~/test/mkosi.output# ls -l image.initrd.1/bin/ | grep -F 'erofs'
root@debian-test:~/test/mkosi.output#
```

This initrd is built after renaming `20-epel-packages.conf` to `mkosi.conf`:
```
root@debian-test:~/test/mkosi.output# ls -l image.initrd.2/bin/ | grep -F 'erofs'
-rwxr-xr-x 1 root root   69560 Oct 16 05:18 dump.erofs
-rwxr-xr-x 1 root root   69624 Oct 16 05:18 fsck.erofs
-rwxr-xr-x 1 root root  203024 Oct 16 05:18 mkfs.erofs
```

### Other questions
By the way, I wonder how to enable `Repositories=epel` when using `mkosi-initrd`? It seems there is no related option by now.

**Comment by aafeijoo-suse** [comment]
Check #3128

**Comment by MoltenArmor** [comment]
> Check #3128

Nice resolution, but it seems that 10-epel.conf needs to be updated every time a new RHEL version is released. Just for curiosity, is there any way to implement logic similar to `Release>9` in the config file?

**Comment by aafeijoo-suse** [comment]
> > Check #3128
> 
> Nice resolution, but it seems that 10-epel.conf needs to be updated every time a new RHEL version is released. Just for curiosity, is there any way to implement logic similar to `Release>9` in the config file?

I don't think so, `Release=` can also be non-numeric. FTR see the previous enablement: https://github.com/systemd/mkosi/commit/3d9a5cb055798ac54e3edc84bf250675467c33ce

**Comment by MoltenArmor** [comment]
> > > Check #3128
> > 
> > 
> > Nice resolution, but it seems that 10-epel.conf needs to be updated every time a new RHEL version is released. Just for curiosity, is there any way to implement logic similar to `Release>9` in the config file?
> 
> I don't think so, `Release=` can also be non-numeric. FTR see the previous enablement: [3d9a5cb](https://github.com/systemd/mkosi/commit/3d9a5cb055798ac54e3edc84bf250675467c33ce)

Thanks☺️.
