### ISSUE TITLE
sysext image: allow to code architecture in image name

### ISSUE THREAD

**Issue by thkukuk** [systemd/mkosi#3143]
### mkosi commit the issue has been seen with

main

### Used host distribution

openSUSE Tumbleweed

### Used target distribution

openSUSE Tumbleweed

### Linux kernel version used

6.11.5-1-default

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

Since we support several architectures, we need to build sysext images for all Architectures. To make it easier to use always the correct image without loopback mounting it to look at the config file, it's common practice to code the architecture in the filename. 

I haven't found a way to do this with mkiso in the configuration files. So I "misused" mkiso.postoutput to rename the image. But if I do that, mkiso will stop with a python backtrace, since it does not find the image name. So I have to additional create a symlink to the original image name without architecture. Which creates later problems.

Is there a way to create images with the architecture in the name?
Currently mkiso.output looks like:
```
strace_2.3 -> strace_2.3.raw
strace_2.3.raw -> strace-2.3.x86-64.raw
strace-2.3.x86-64.raw
```

I only need the last file, `strace-2.3.x86-64.raw`

**Comment by behrmann** [comment]
Can you use `Output=` with the `%a` specifier foryour needs?

**Comment by thkukuk** [comment]
Thanks, it wasn't clear for me from the description, that this is possible.
