### ISSUE TITLE
Nested conf is ignored

### ISSUE THREAD

**Issue by 4nd3r** [systemd/mkosi#3155]
I want to use nested configurations.

With **v24.3** `mkosi --profile x summary` says:
```
Extra Trees: .../mkosi.extra
             .../mkosi.conf.d/debian/mkosi.extra
             .../mkosi.conf.d/debian/mkosi.conf.d/bookworm/mkosi.extra
```

With **main**:
```
Extra Trees: .../mkosi.extra
             .../mkosi.conf.d/debian/mkosi.extra
```

Profile `x` is:
```
[Distribution]
Distribution=debian
Release=bookworm
```

`.../mkosi.conf.d/debian/mkosi.conf`:
```
[Match]
Distribution=debian
```

`.../mkosi.conf.d/debian/mkosi.conf.d/bookworm/mkosi.conf`:
```
[Match]
Release=bookworm
```

f2a9d0f5b668a96c39dbbd0ddb1cce33a955ca73 is the first bad commit.

I'm doing it wrong?

**Comment by DaanDeMeyer** [comment]
@4nd3r Profiles are now parsed last instead of first, so your config file with `[Match]` is getting parsed before the profile config file.

If you want to set the distribution and release based on the profile, put a config file in mkosi.conf.d that matches on the profile and set the distribution and release in there. For example:

```
mkosi.conf.d/10-x.conf

[Match]
Profile=x

[Distribution]
Distribution=debian
Release=bookworm
```

**Comment by 4nd3r** [comment]
Thank you for explaining. This isn't too obvious. At first I had `mkosi.conf.d/x.conf`, which didn't work, because this is how alphabet works, I guess.

Basically, profiles like this are quite unnecessary, as I can define everything in `mkosi.conf.d/10-x.conf` (or `mkosi.conf.d/10-dev/...`) and only need an empty `mkosi.profiles/x.conf` for `mkosi` to recognize the profile as existing. So it makes sense to do matching with `ImageId` and drop profiles. Or am I missing something?

**Comment by 4nd3r** [comment]
Got it, thanks, got my enlightenment.
