### ISSUE TITLE
RFE: Support for bsd's as an distro options

### ISSUE THREAD

**Issue by johannbg** [systemd/mkosi#318]
Just throwing the ball out there 
It would be nice if bsd would be installable from mkosi something along the line of...
 mkosi -t raw_gpt --bootable -d freebsd 

Perhaps better generic alternative would be the ability to create images and use ISO images as installation source? then probably support for Windows ( Nano Server Server Core? ), OS - X ( server ) *BSD, Solaris and the entire fragmented Linux ecosystem ( ca 500 distro's ) could be support on the fly ( just download the vendor ISO image and use that as an installation source )  

And on the generic notes there is a question if mkosi can create and or nspawn can run the least hyped microsoft feature, it's containers [¹] 

1. https://blogs.technet.microsoft.com/virtualization/2018/06/27/insider-preview-windows-container-image/

**Comment by johannbg** [comment]
Here is an example how you can create iso/kvm image for FreeBSD [1] via shell scripts. 
1. https://github.com/joyent/freebsd-kvm-image-builder

**Comment by poettering** [comment]
Sorry, but this cannot work. mkosi is not the right tool for that. It's ultimately just a fancy wrapper around dnf/debootstrap and friends and systemd-nspawn, that's all. But nspawn means containers, and containers means kernel between host and the payload that is being built is shared. And if the kernel is shared this means Linux on the host and Linux in the generated payload. Sorry.

There might be tools using VM virtualization or so to build images, but mkosi is really not that, it's clearly focussed on nspawn, and it's technically simply not feasible to run freebsd as a linux container, sorry!

Hope that makes some sense?

**Comment by johannbg** [comment]
Hmm I was expecting somekind of rejection based on potential ( BSD ) license clash ( hense the proposed loopback mounted iso approach or something ) not you contradicting your own blog post which reads "mkosi — A Tool for Generating OS Images" not "mkosi — A Tool for Generating Linux OS Images" or  "mkosi — A Tool for Generating Linux containers" so based on the original title and what mkosi stands for "Make Operating System Image, and is a tool for precisely that: generating an OS tree or --> image that can be booted.<---" it made very much sense and expect it to be extended to be able to build other OS images ( but leave out the container and os-tree part ) such as Windows,OS-X and BSD, rescue images, firmware images etc. for deployment/development stand point.  

If it was never your intent to make other OS images you should have named and advertised the project differently so perhaps a rename is in order to prevent future feature request in this regard?

**Comment by poettering** [comment]
Well, I figure we have to agree to disagree about what an OS is. To me that's more than a kernel, and that's what mkosi generates. But yes, some people consider OS to be synonymous to kernel. But dunno... Not sure this really a discussion worth having...
