### ISSUE TITLE
RFE: Add fedora dynamic gpg key querying

### ISSUE THREAD

**Issue by kragniz** [systemd/mkosi#320]
It's been a while since the last release, and the current latest release is failing to build fedora images:

```
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 3605, in <module>
    main()
  File "/usr/bin/mkosi", line 3595, in main
    build_stuff(args)
  File "/usr/bin/mkosi", line 3448, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=True)
  File "/usr/bin/mkosi", line 3303, in build_image
    install_distribution(args, workspace.name, run_build_script, cached)
  File "/usr/bin/mkosi", line 1536, in install_distribution
    install[args.distribution](args, workspace, run_build_script)
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/bin/mkosi", line 1060, in install_fedora
    gpg_key = "https://getfedora.org/static/%s.txt" % FEDORA_KEYS_MAP[args.release]
KeyError: '29'
```

It'd be great to get a fresh tag so distros can update.

**Comment by johannbg** [comment]
Can you be somewhat more specific how you are using mkosi and on what platform.
I'm building Fedora 29 left and right using Fedora 29 as the buildsystem and mkosi-4-3.fc29.noarch to generate those images. 

The error there seems to be mkosi having problem fetching gpg key for fedora which can be a) problem with firewall b) the naming of the keys in that url or c) the infrastructure hosting this has re-generated new keys. )

**Comment by kragniz** [comment]
I'm on arch linux using this package build: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mkosi

I just switched to git master instead.

**Comment by johannbg** [comment]
Let's ping @keszybz this is outdated Should contain

FEDORA_KEYS_MAP = { 
     '23': '34EC9CBA', 
     '24': '81B46521', 
     '25': 'FDB19C98', 
     '26': '64DAB85D', 
     '27': 'F5282EE4', 
     '28': '9DB62FB1', 
     '29': '429476B4',
     '30': 'CFC659B9',     
} 

IOT should probably be there as well not sure how that would be handle thou

DBBDCF7C is for "IOT 2019"

There must be a better way to handle this other than having to manually update/maintain this list every time downstream makes new releases and or might roll different keys and what not...

**Comment by q2dg** [comment]
It seems @keszybz hasn't been pinged :-(

**Comment by johannbg** [comment]
@q2dg the upstream Fedora keys are correct ( with the exception of the missing IOT ) one but this approach ( and other none scalable design defects that mkosi suffer from ) probably needs re-factoring/re-thinking. 

As things stand now ( regarding this issue ) and have been implemented, Mkosi would need to tie it's release cycle to downstream distributions so everytime Fedora,OpenSuse,Debian etc, go EOL or produce new releases then mkosi would need to be released with updated release keys, number names etc and the EOL-ed ones be removed in the process. 

@poettering  @keszybz how have you envisioned this going forward? Is upstream supposed to handle this or do you expect downstream to do it?

**Comment by keszybz** [comment]
I don't have a good solution for this. One option would be to query this live, e.g. from https://getfedora.org/keys/, if the required key is not found in the map. Otherwise, I think it should be OK to keep updating mkosi with the new keys as time goes on.

**Comment by johannbg** [comment]
@keszybz now that FC30 is released upstream needs to a) release new upstream release of mkosi which contains only the relevant non EOL Fedora release as in ( the older keys should be removed so users dont use EOL release )

FEDORA_KEYS_MAP = {
'29': '429476B4',
'30': 'CFC659B9',
'31': '3C3359C4',
}

And b) as a downstream maintainer you need to build that new mkosi release for all supported release as in F29,F30,F31 ( 5.1 has not been built for F29 ) and all the other primary distros ( Arch/Debian/OpenSuse ) need to build a new mkosi release as well. 

Then there is always the security issue if downstream has for whatever reason revoke the keys, then upstream has to pay attention to it and react by releasing a new release and push it to down streams shipping mkosi o_O 

Perhaps better to just parse a directory which contains distribution file, in which downstream then maintains ( /etc/mkosi/distributions.d/fedora ? ) as opposed to have distribution and their release hard coded in mkosi code? 

Why are you so reluctant to completely remove distribution from the mkosi code and put it in parsable downstream maintainable file instead, what's the argument against such approach?

**Comment by keszybz** [comment]
We want to support building of distributions on other distributions. So relying on the keys being provided by the distribution is problematic, and it's much nicer to keep the list of keys internally or query them dynamically from the web, so that the requirements on the host are minimized.

> Why  are you so reluctant to completely remove distribution from the mkosi  code and put it in parsable downstream maintainable file instead, what's  the argument against such approach?

Because then each distribution would have to be aware of all other distributions. Even if that'd work, it's much more work for everybody involved. I also wouldn't worry about key revocation, it's not something that happens for distribution keys.

I think we want to keep current scheme, which has the advantage that it is quick, simple, and requires no network access, and supplement it with some dynamic querying of keys as a fallback.

**Comment by johannbg** [comment]
Mkosi is not a standalone application that can support building distributions on other distributions like for example if we stick with primary distributions ( defined by distinct package manager ) not their derivatives (  upstream should only support which results in maybe 7 distinct distribution to support as opposed to 500 )

On Arch
Arch support requires - arch-install-scripts
Debian support requires - debootstrap, debian-archive-keyring
Fedora support requires - DNF
OpenSuse support requires - zypper-git
to be Installed

Then swap names of same components in the other distro's where relevant to support each other. 

In addition to the above upstream using mkosi for testing deployment on various distribution have to deal with the needless deviation between them on the core/baseOS level as well as between various application stacks, CA paths, different packagenames etc. so *always* relies on downstream dependencies backing it up so a single .extra directory, .postinst etc cant work. 
Personally I have never heard of having hard coded dependencies outside a project being a good thing but let's put that religious topic aside, why is it a bad thing to move atleast the releases out from from the mkosi code itself and into a directory which can contain distribution configuration files, distribution release files and distribution directories ( mkosi.extra ) for scalability and for your argument sake it would be kept and maintained here upstream? Why is that a bad thing?

**Comment by DaanDeMeyer** [comment]
Let's keep this fedora only. I don't think we can easily solve this for arch, ubuntu and debian since they're keyring package based. mageia and openmandriva don't have their keys online and opensuse and centos already seems to dynamically import gpg keys. I'm not sure about photon and clear but those are niche enough that we can wait for separate issues to be created for them.
