### ISSUE TITLE
Cleaning default initrd unintentionally deletes other data

### ISSUE THREAD

**Issue by slarew** [systemd/mkosi#3237]
As of e3d80a7a326968551e68047660740f1b91cc465d, the call to `run_clean(args, finalize_default_initrd(...))` is deleting a directory, named `initrd`, in my project. I bisected recent changes to this commit and line. The directory layout of my project looks like:
```
os                                                                                                                                                                                         
├── initrd                                                                                                                                                                                 
│   ├── mkosi.conf                                                                                                                                                                         
├── installer                                                                                                                                                                              
│   └── mkosi.conf                                                                                                                                                                         
└── mkosi.conf
```
The build flow is: build the custom `os/initrd/mkosi.conf` image first, then I build the top level image `os/mkosi.conf` which uses that custom initrd, then I build the `os/installer/mkosi.conf` image.

At the start of the `os/mkosi.conf` image build, `mkosi -f` finds the `initrd` project directy and mistakenly deletes it. (Fortunately I had committed all my changes so I didn't lose any files from my `initrd` directory).

_Originally posted by @slarew in https://github.com/systemd/mkosi/pull/3233#discussion_r1861363758_

**Comment by DaanDeMeyer** [comment]
@slarew You definitely want to use a separate output directory configured with `OutputDirectory=`. But we should still avoid this I guess.
