### ISSUE TITLE
History=yes breaks post-build verbs when using subimages

### ISSUE THREAD

**Issue by hundeboll** [systemd/mkosi#3238]
### mkosi commit the issue has been seen with

5103ebb13061

### Used host distribution

Arch + Fedora

### Used target distribution

Arch + CentOS

### Linux kernel version used

6.6.63-1-lts

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

In a setup with a main image that depends on a subimage (i.e. `mkosi.images/base`), `mkosi qemu` fails with an error about the subimage not being found.

Removing `History=yes` from the main image configuration makes it work again. 

Our subimage use case is a directory formatted base image used both when creating a bootable disk image (in the main config), and when creating system extension images (in other subimages).

I've created a minimal reproducer:
```
.
├── mkosi.conf
└── mkosi.images
    └── base
        └── mkosi.conf
```

The base subimage is rather basic:
```ini
[Output]
Format=directory
```

### Used mkosi config

```ini
[Config]
Dependencies=base

[Build]
History=yes

[Output]
Format=disk
```

### mkosi output

```sh
‣ Loading configuration file mkosi.conf
‣ No image found with name base
‣ + tput cnorm
‣ + tput smam
Traceback (most recent call last):
  File "mkosi/mkosi/run.py", line 62, in uncaught_exception_handler
    yield
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "mkosi/mkosi/__main__.py", line 36, in main
    run_verb(args, images, resources=resources)
  File "mkosi/__init__.py", line 4728, in run_verb
    images = resolve_deps(images[:-1], last.dependencies) + [last]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mkosi/config.py", line 3919, in resolve_deps
    die(f"No image found with name {missing}")
  File "mkosi/log.py", line 40, in die
    sys.exit(1)
SystemExit: 1
```

**Comment by hundeboll** [comment]
From looking around in the code, the issue seems to history is stored for the main image only, and when loading the history, the parsing of subimages is skipped.

**Comment by behrmann** [comment]
Can you say a bit more about your reproducer, because I get 
```
$ mkosi qemu
‣ No image found with name base
```
after running `mkosi build`, which to be fair is also not ideal, but is not a crash.

**Comment by hundeboll** [comment]
I assume you did run `mkosi build` first?

Here's what doesn't work in the reproducer (where history is enabled):
```sh
mkosi clean
mkosi build
mkosi qemu
```

But it works with history disabled:
```sh
mkosi clean
mkosi --history=no build
mkosi qemu
```

I would expect history to take subimages into account.

**Comment by hundeboll** [comment]
Thanks for fixing this so promptly!
