### ISSUE TITLE
Cannot build image for the first time if `QemuKernel` is set

### ISSUE THREAD

**Issue by g-arjones** [systemd/mkosi#3249]
### mkosi commit the issue has been seen with

main

### Used host distribution

Ubuntu 22.04

### Used target distribution

Ubuntu 24.04

### Linux kernel version used

6.5.0-35-generic

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

`mkosi build` fails because the kernel image does not exist

### Used mkosi config

```ini
[Host]
QemuKernel=image.vmlinuz

[Distribution]
Distribution=ubuntu
Release=noble
```

### mkosi output

```sh
‣ image.vmlinuz does not exist
```

**Comment by DaanDeMeyer** [comment]
If you want to boot with the kernel image produced by mkosi itself, just use `QemuFirmware=linux`, no point in using  `QemuKernel=` for that
