### ISSUE TITLE
Missing --no-clean option

### ISSUE THREAD

**Issue by marc-hb** [systemd/mkosi#3283]
### mkosi commit the issue has been seen with

v24.3

### Used host distribution

Fedora 40

### Used target distribution

Fedora 40

### Linux kernel version used

 6.8.9-100.fc38.x86_6

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

Everything always gets cleaned up unless the script fails.

I just root-caused a time-consuming mkosi configuration issue[*] where some kernel files did not land in the expected partition. Probably the main reason this was so time-consuming: `mkosi` very aggressively deletes all workspaces and other temporary files, leaving nothing behind for forensics. I tried `--debug-workspace` and every other --debug option I could find but as the script did not fail, there was still nothing left behind. I eventually managed to gather some useful clues thanks to an infinite `while; rsync -a ...` loop racing with mkosi itself. Pretty ridiculous!

Consider the gigabytes involved, the default cleanup behavior makes complete sense, But it should be easier to override for when things go wrong.

[*] https://github.com/pmem/run_qemu/issues/88

### Used mkosi config

```ini
Irrelevant
```

### mkosi output

```sh
None: that's the problem. All workspaces get cleaned up.
```

**Comment by DaanDeMeyer** [comment]
@marc-hb Note that you can just add `bash` to a mkosi script to get a shell in the script if it doesn't fail. Would that also help with debugging this?

**Comment by marc-hb** [comment]
That sounds useful when... you already know where to look! I mean: if you already have a good idea of which mkosi step does what and when. I have been getting there but this learning takes time; building a full operating system is not the simplest thing! In this particular case, I just wanted to follow which files were copied where and by whom and I didn't care exactly when. 

I will likely try this trick in the future (is it documented already?) but I think there would still be value in some `--clean-nothing` option.

**Comment by DaanDeMeyer** [comment]
@marc-hb If we change `--debug-workspace` to work regardless of whether something failed or not, would that be sufficient?

**Comment by marc-hb** [comment]
> @marc-hb If we change --debug-workspace to work regardless of whether something failed or not, would that be sufficient?

Most likely yes!

Shooting myself in the foot: it would fill up the disks of people and bots who are using it unconditionally. https://xkcd.com/1172/
