### ISSUE TITLE
Rocky8 Linux has been mistakenly removed support

### ISSUE THREAD

**Issue by Avimitin** [systemd/mkosi#3301]
### mkosi commit the issue has been seen with

https://github.com/systemd/mkosi/commit/e9ae161ef71cca531d19404a6365e61c7ed7fc43

### Used host distribution

NixOS 24.11

### Used target distribution

Rocky 8

### Linux kernel version used

6.6.11-1-lts

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

After updating to mkosi 24.3, building rocky8 image is no more supported. However according to Rocky Linux release information, rocky8 EOL is at 2029 (https://wiki.rockylinux.org/rocky/version/). I think the setup code in rocky.py might need to override the default CentOS version assertion.

Related code:
* rocky.py: https://github.com/systemd/mkosi/blob/main/mkosi/distributions/rocky.py 
* centos.py: https://github.com/systemd/mkosi/blob/1201463acd871d136bb68edbe13808ad8bd133ad/mkosi/distributions/centos.py#L66

### mkosi output

```sh
> Rocky Linux Stream 8 or earlier variants are not supported
```

**Comment by DaanDeMeyer** [comment]
This is what ntentional, it's not because rocky linux provides long term support beyond CentOS Stream that we're willing to support it for that long in mkosi. We support derivatives of CentOS Stream for as long as CentOS Stream itself is supported. And since CentOS Stream 8 is eol we removed support for it and all its derivatives.

**Comment by Avimitin** [comment]
Rocky is the de facto distro that most of commercial tools select to replace CentOS and related distro. IMHO, it's not good to remove its support: 

see
- https://www.synopsys.com/support/licensing-installation-computeplatforms/compute-platforms/compute-platforms-roadmap.html
- https://www.cadence.com/en_US/home/support/computing-platform-support/support-road-map-2022x-2025x.html
- https://calibre.mentorcloudservices.com/docs/Calibre_OS_Roadmap.htm

**Comment by DaanDeMeyer** [comment]
Yourself or someone from Rocky Linux is welcome to fork mkosi and maintain support there or propose a plan to have this support upstream without myself being stuck maintaining it. I'm not interested in doing this work myself and I don't see anyone stepping up to do it either so I'll tentatively close this issue as not planned.
