### ISSUE TITLE
Cannot use profiles from sub images

### ISSUE THREAD

**Issue by g-arjones** [systemd/mkosi#3307]
### mkosi commit the issue has been seen with

main

### Used host distribution

Ubuntu 24.04

### Used target distribution

Ubuntu 24.04

### Linux kernel version used

6.5.0-35-generic

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

After `mkosi --profile=container-runtime build`

```
‣ Profile 'container-runtime' not found in mkosi.profiles/
```

The `container-runtime` profile is defined in a sub image

### Used mkosi config

```ini
# mkosi.conf
[Build]
Incremental=yes
ToolsTree=default
ToolsTreeDistribution=ubuntu
ToolsTreeRelease=noble

[Distribution]
Repositories=universe
Distribution=ubuntu
Release=noble
Architecture=x86-64

[Config]
Profiles=container-runtime
Dependencies=base_os
MinimumVersion=25~devel

[Content]
BaseTrees=%O/base_os
Packages=
    linux-image-generic

[Output]
SplitArtifacts=yes
Format=disk

# mkosi.images/base_os/mkosi.conf
[Content]
CleanPackageMetadata=no
Packages=
    ubuntu-server

# mkosi.images/base_os/mkosi.profiles/container-runtime/mkosi.conf
[Content]
Packages=
    docker.io
    docker-compose-v2
```

### mkosi output

```sh
‣ Profile 'container-runtime' not found in mkosi.profiles/
```

**Comment by g-arjones** [comment]
I considered working around this by using matchers but that didn't pan out either. Thoughts?

**Comment by g-arjones** [comment]
Creating an empty `mkosi.profiles/container-runtime` in the default image works. Is this intentional?

**Comment by MoltenArmor** [comment]
> Creating an empty `mkosi.profiles/container-runtime` in the default image works with a matcher in a `mkosi.conf.d/container-runtime/mkosi.conf` but not if `mkosi.conf` is in the sub image's `mkosi.profiles` dir. Is this intentional? That's odd because [the documentation mentions that `Profiles` is universal.](mkosi/mkosi/config.py)

As said in [mkosi.1](https://github.com/systemd/mkosi/blob/main/mkosi/resources/man/mkosi.1.md):

> When images are defined, mkosi will first read the main image configuration (configuration outside of the mkosi.images/ directory), followed by the image specific configuration. Several "universal" settings apply to the main image and all its subimages and cannot be configured separately in subimages. The following settings are universal and cannot be configured in subimages:
> ......
> `Profiles=`

**Comment by MoltenArmor** [comment]
> Creating an empty `mkosi.profiles/container-runtime` in the default image works with a matcher in a `mkosi.conf.d/container-runtime/mkosi.conf` but not if `mkosi.conf` is in the sub image's `mkosi.profiles` dir. Is this intentional? That's odd because [the documentation mentions that `Profiles` is universal.](mkosi/mkosi/config.py)

"Universal" means `Profiles=` can not be used in subimages.

**Comment by g-arjones** [comment]
> "universal" settings apply to the main image and all its subimages

What does this mean exactly?

**Comment by MoltenArmor** [comment]
> > "universal" settings apply to the main image and all its subimages
> 
> What does this mean exactly?
> 
> How does `Profile` apply to sub images?

That's to say, when you set a profile through command line, like:
```
mkosi --profile container-runtime
```
or through configuraion file, like:
```
Profiles=container-runtime
```
Those configuration lines in the `container-runtime` profile is applied to all images, including the main image and ALL THOSE SUBIMAGES.

In your example, this means, these configuration lines:
```
Packages=
    docker.io
    docker-compose-v2
```
will be exactly the same as they are in both `mkosi.conf` and `mkosi.images/base_os/mkosi.conf`. And that's why `mkosi.profiles/` directory must be in the project's root directory.

This is my understanding, might be wrong.

**Comment by DaanDeMeyer** [comment]
*Universal* means that `Profiles=` can not be changed in subimages. The profile to use is determined early on before parsing subimages and cannot be changed afterwards anymore. The only profiles that are selectable are the ones in the top level `mkosi.profiles/`. Subimages still have access to the profiles to use in `[Match]` but can't define their own profiles in `mkosi.profiles/`.

I'm not opposed to be able to define profile specific stuff for subimages in an subimage specific `mkosi.profiles` directory though, but that doesn't work yet today.

**Comment by g-arjones** [comment]
> Universal means that Profiles= can not be changed in subimages.

That was my understanding.

> I'm not opposed to be able to define profile specific stuff for subimages in an subimage specific mkosi.profiles directory though, but that doesn't work yet today.

Exactly my use case.
