### ISSUE TITLE
mkosi fails to build using directory or tar formats

### ISSUE THREAD

**Issue by abogani** [systemd/mkosi#333]
mkosi.default:
[Distribution]
Distribution=ubuntu
Release=bionic

[Output]
Format=tar

Executing `sudo ./mkosi --force` on Ubuntu 18.04 I obtain:
‣ Removing output files...
‣ Removing output files complete.
DISTRIBUTION:
          Distribution: ubuntu
               Release: bionic
                Mirror: http://archive.ubuntu.com/ubuntu

OUTPUT:
         Output Format: tar
                Output: /home/alessio/WIP/netboot/image.tar.xz
       Output Checksum: n/a
      Output Signature: n/a
           Output Bmap: n/a
Output nspawn Settings: n/a
           Incremental: no
             Read-only: no
        FS Compression: no
        XZ Compression: yes
            Encryption: no
                Verity: no

PACKAGES:
              Packages: none
         Package Cache: none
           Extra Trees: none
        Skeleton Trees: none
          Build Script: none
         Build Sources: /home/alessio/WIP/netboot
  Source File Transfer: none
       Build Directory: none
        Build Packages: none
    Postinstall Script: none
       Finalize Script: none
  Scripts with network: no
       nspawn Settings: none

HOST CONFIGURATION:
    Extra search paths: none
‣ Detaching namespace...
‣ Detaching namespace complete.
‣ Setting up package cache...
‣ Setting up package cache /home/alessio/WIP/netboot/.mkosi-ezg4gjay complete.
‣ Setting up temporary workspace.
‣ Temporary workspace in /var/tmp/mkosi-cv_wmj72 is now set up.
‣ Mounting image...
Traceback (most recent call last):
  File "./mkosi", line 4540, in <module>
    main()
  File "./mkosi", line 4536, in main
    run_verb(args)
  File "./mkosi", line 4508, in run_verb
    build_stuff(args)
  File "./mkosi", line 4333, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, do_run_build_script=False, cleanup=True)
  File "./mkosi", line 4147, in build_image
    with mount_image(args, workspace.name, loopdev, encrypted_root, encrypted_home, encrypted_srv):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "./mkosi", line 961, in mount_image
    if args.xbootldr_partno is not None:
AttributeError: 'CommandLineArguments' object has no attribute 'xbootldr_partno'
Traceback (most recent call last):
  File "/usr/lib/python3.6/weakref.py", line 624, in _exitfunc
    f()
  File "/usr/lib/python3.6/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/lib/python3.6/tempfile.py", line 938, in _cleanup
    _rmtree(name)
  File "/usr/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.6/shutil.py", line 422, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 420, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: 'root'

**Comment by abogani** [comment]
Commit 316562061b24664581dc2f19e69c024fe7141f41 introduces the bug

**Comment by behrmann** [comment]
So the problem is that `args.xbootldr_partno` is never set when the output format is `tar` or `directory` before `mount_image` is called. 

`args.xbootlodr_partno` is set by `determine_partition_table`, which is called by `create_image` and `reuse_cache_image`. Both are called by `build_image` before the first call to `mount_image`, but return right away because neither `tar` nor `directory` is `True` for `.is_disk` or `.is_disk_rw`.
