### ISSUE TITLE
Arch distribution supports borked 

### ISSUE THREAD

**Issue by johannbg** [systemd/mkosi#342]
I was testing the Arch support which seems to be borked since installing fails with what looks like key trust issues downstream but that makes no sense for "fresh install" o_O ( I have no idea how the Arch community has manage to screw this up )

error: <component>: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust

Are people doing some magic workarounds and I did not get that memo or is literally nobody testing if distribution ( and their releases ) that are integrated here upstream actually work? ( which means perhaps test cases should be written for existing distro and providing it made as an requirement for pull request for new distributions to be added )

**Comment by lucasdemarchi** [comment]
> iterally nobody testing if distribution ( and their releases ) that are integrated here upstream actually work?

Arch doesn't really have releases, so it may break from one day to the other.

Last time I fixed a issue like you are mentioning was in
https://github.com/systemd/mkosi/pull/327 and the "fix" was to trust all signatures.

**Comment by johannbg** [comment]
@lucasdemarchi  your changes there are confirmed working ( that fix is not available in FC30 ) @keszybz can you back port his fix to FC30, from the looks of the arch linux community will never get this right so it's best to just set TrustAll
