### ISSUE TITLE
Bootable images are currently not supported on Ubuntu.

### ISSUE THREAD

**Issue by johannbg** [systemd/mkosi#343]
Here's another weird one.  

Works fine for Debian but fails when you swap out Debian with Ubuntu with "Bootable images are currently not supported on Ubuntu." How can it not be supported when Ubuntu is downstream of Debian o_O 

And how come Ubuntu got added upstream if it is not ( or cant be ) properly supported?

**Comment by lucasdemarchi** [comment]
> Works fine for Debian but fails when you swap out Debian with Ubuntu with "Bootable images are currently not supported on Ubuntu." How can it not be supported when Ubuntu is downstream of Debian o_O

because nobody tested generating bootable ubuntu images? If it's working for you, a patch to fix it would be a oneliner.

> And how come Ubuntu got added upstream if it is not ( or cant be ) properly supported?

Bootable images are not the only use for mkosi. People are also generating directory or tar images, too. And those don't need to be booted and serve as a chroot on steroids.

**Comment by johannbg** [comment]
> > Works fine for Debian but fails when you swap out Debian with Ubuntu with "Bootable images are currently not supported on Ubuntu." How can it not be supported when Ubuntu is downstream of Debian o_O
> 
> because nobody tested generating bootable ubuntu images? 

Right we need to start testing this....

> 
> > And how come Ubuntu got added upstream if it is not ( or cant be ) properly supported?
> 
> Bootable images are not the only use for mkosi. People are also generating directory or tar images, too. > And those don't need to be booted and serve as a chroot on steroids.

Right but the default upstream behaviour should be the same for all distributions ( bootable image ), People will then just change it to fit the environment. 

And the above just points to a lack of coherent policy regarding distro implementation here upstream.

**Comment by johannbg** [comment]
Closing more of an policy decision than an issue.
