### ISSUE TITLE
mkosi -d bug or feature :)

### ISSUE THREAD

**Issue by johannbg** [systemd/mkosi#344]
This is either a bug or a feature request. 

Basically my expectation when running mkosi -d <distribution> is that it would try to search for existing mkosi.<distribution> file if it existed and use that instead of directly use some built in default) 

I propose if this is not a bug but a feature that 

mkosi -d searches for existing distribution files in relevant paths before using hard coded defaults..
.mkosi/mkosi.<distribution>
.mkosi.files/mkosi.<distribution>
.mkosi.distribution/<distribution>
.mkosi.arch
.mkosi.fedora
.mkosi.opensuse
....

mkosi/mkosi.<distribution>
mkos.files/mkosi.<distribution>
mkosi.distribution/<distribution>
mkosi.arch
mkosi.debian
mkosi.fedora
mkosi.opensuse

Alternative would be to keep distribution specific files in distribution related directories which could scale pretty nicely which would use everything in those distribution directories when using mkosi -d like.. 

mkosi.arch/
mkosi.debian/
mkosi.fedora/
mkosi.opensuse/
....

With each directory having files and sub directory's along the lines of
mkosi.fedora/default
mkosi.fedora/postinst
mkosi.fedora/extra/
mkosi.fedora/build/
mkosi.fedora/cache/
mkosi.fedora/extra/
mkosi.fedora/output

For multiple release support within a single distribution probably the cleanest way would be to implement additional release directory 

mkosi.fedora/releases/30/default
mkosi.fedora/releases/30/postinst
mkosi.fedora/releases/30/extra/
mkosi.fedora/releases/30/build/
mkosi.fedora/releases/30/cache/
mkosi.fedora/releases/30/output/

**Comment by afreof** [comment]
Hi Jóhann,
As far as I understand, your proposal, it should not be that hard to be implemented. You might want to extend the function `parse_args_file_group` around line 3377 in the mkosi.py file.

This function searches for files in mkosi.default.d folder and for the mkosi.default file. Finally the variable `argv_post_parsed` is a list of file names prefixed with an @. Example:
`'@/home/foo/mkosi.default', '@/home/foo/mkosi.default.d/bar.conf']`

If you would extend the function to create a list such as `['@/home/foo/mkosi.default', '@/home/foo/mkosi.default.d/bar.conf', '@/home/foo/mkosi.default.d/distro/fedora.conf', '@/home/foo/mkosi.default.d/distro/fedora/30.conf']` you will get what you want.

Note: The "@" means file name in comparison to "--" which means command line parameter to the parser.

The parser is smart enough to handle the priorities of these files. In the example above the file 30.conf will override settings from the file fedora.conf and so on.

**Comment by johannbg** [comment]
@afreof I'm not sure if it would be smart to have priorities of those files since distributions usually have incremental release numbers so it's probably best to have one-to-one relationship between the release number or name to file names. 

There also needs to be some policy in place that decides which and how distribution gets accepted upstream given that there are ca 200 systemd linux based distributions as well as policy about their supported releases upstream ( as in should EOL releases be included ) before the current things are implemented right?

There are couple of options here ( anyone feel free to chime in more or comment ) 

1. 
Limit distribution support to only the parent distributions in the Linux family tree not their derivatives as in Arch,Debian,Fedora Opensuse and remove the other distributions ( Centos,Clear,Mageia,Ubuntu ) and we cover all those with proper test cases in all ways mkosi could be use ( which means probably 10 cases per distribution times supported release in systemd ) has the least file/directory footprint. 

2. 
Restrict inclusion to the following that the distribution needs to have yum/dnf, debootstrap, pacstrap,zypper,systemd 233+, Python 3.5+ included in their distribution repositories, let's put an arbitrary number and say that's like 50 of the 200 systemd based distribution contain those requirements, which means 500 test cases for a single supported release of those 50 distributions needed to be supported here upstream to ensure that included distributions works anywhere. 

3. 
Any one of the 4 package manager + systemd 233+, Python 3.5+ ( this will result in added reports against upstream since it might be that the missing packages and managers are not packaged universally on all distributions ) 

4. 
No limitation other than systemd 233+, Python 3.5+ and *any* of those what 40 packaging solution that exist in the linux eco system.

On top of that there things like if this should not be de-associated with the systemd project ( mkosi has nothing to do with systemd development ) and into it's own repository on github along with a mailinglist and or something like groups.io etc for discussion.

Technically this is something should be hashed out on mailinglist or at hackfest or something ( I probably could arrange summer house beer and bbq to host such event for people would just have to fly to Iceland ;) ) but it's not like there is any other place to discuss these topics. ( the current status of the projects and where it should be going etc )

**Comment by johannbg** [comment]
Given there has not been any significant increase or decrease in releases wanting to be added to mkosi, I'm closing this issue. If and then when mkosi gains any traction and the limitation I was trying to point out will be hit this issue could get revisited/reopened.
