### ISSUE TITLE
UEFI / Grub as an option

### ISSUE THREAD

**Issue by h0ru5** [systemd/mkosi#348]
to integrate well with some management tools supplied for GRUB only, we need to boot using Grub/UEFI. Currently, mkosi only supports sd-boot/UEFI or GRUB/BIOS, so my plan is generating UEFI with GRUB as package and then adapting the image manually

without having looked deeper, would it be low-hanging to do a GRUB/UEFI variant?
(as sd-boot only supports UEFI, the other way around would not be relevant)

**Comment by keszybz** [comment]
We dropped support for grub2 in #1152 because it was too much effort to support. Sorry.

**Comment by behrmann** [comment]
You can get a plain bios partition, though, which we don't touch. You can probably hack together support for whatever bootloader by using some postinst or finalize script.
