### ISSUE TITLE
Examples? How do use mkosi to make a CentOS rootfs.tar file for use with WSL

### ISSUE THREAD

**Issue by devlocalca** [systemd/mkosi#349]
Is there a page with examples on how to use mkosi to create rootfs.tar files that can be used with WSL --import?

I have tried numerous things to create a rootfs.tar for CentOS 7.1905 with no luck, and searching around, cannot find good documentation, examples on how to do this.

It would be nice to know the dnf command as well, to create at a lower level if needed.

**Comment by DaanDeMeyer** [comment]
Sorry, I don't think we're going to be able to help with this. We'd be happy to take improvements that make this work for you but figuring out what's necessary to make this work is up to you.

Closing this issue, you can make new issues if you figure out what exactly mkosi's missing to make this work.

**Comment by nilskattenbeck-bosch** [comment]
For Ubuntu you could take a look at [their manifest files](https://cloud-images.ubuntu.com/wsl/jammy/current/) online which should contain the list of packages to get WSL properly running. I do not think they have any special structure in general, just a rootfs which likely some integration packages for better interop.

**Comment by BrunoVernay** [comment]
For information, here is a mkosi.conf file that creates an image that can be imported in WSL.
`$ wsl --import fedodo41 C:\Users\toto\MyWSL\fedodo41  \\wsl.localhost\fedodo\home\myname\mkosi-project\work\image.tar.zst
$ wsl -d fedodo41
`
I created the package list using: https://pagure.io/fedora-kickstarts/blob/main/f/fedora-container-base.ks 
```
[Distribution]
Distribution=fedora
Release=41
Architecture=x86-64

[Output]
Format=tar

[Content]
Bootable=no

# hashed:
RootPassword=toto

# From https://pagure.io/fedora-kickstarts/blob/main/f/fedora-container-common.ks 
Packages=fedora-release-container
  bash,sudo
  coreutils,util-linux-core
  glibc-minimal-langpack
  rootfiles,tzdata
  rpm,dnf5,dnf5-plugins
  tar,vim-minimal
  # Extra packages:
  openssl,shadow-utils,zsh,openssh

Locale=en_US.UTF-8
Keymap=us
Timezone=Europe/Paris

[Build]
# https://github.com/systemd/mkosi/blob/main/mkosi/resources/man/mkosi.1.md#build-section
Incremental=yes
```
