### ISSUE TITLE
Unable to create bootable Ubuntu image.

### ISSUE THREAD

**Issue by cedws** [systemd/mkosi#359]
Using the following mkosi recipe:
```
[Distribution]
Distribution=ubuntu
Release=bionic

[Output]
Format=gpt_ext4
Bootable=yes
BootProtocols=bios

[Partitions]
RootSize=2G

[Validation]
Password=root
```

Expected behaviour:
A bootable raw Ubuntu image is created.

Actual behaviour:
This output is produced and the image is not created: https://gist.github.com/cedws/4bd11af26cd27ad322ff1e34c851158d

**Comment by DaanDeMeyer** [comment]
nspawn fix waiting in https://github.com/systemd/systemd/pull/16645. I'll add a workaround in mkosi as well since it'll take a while before the nspawn fix is widely available.
