### ISSUE TITLE
Use chown + uidmapped mounts to avoid root owned files on the host

### ISSUE THREAD

**Issue by purpleidea** [systemd/mkosi#366]
It's required to run `mkosi` as root. Unfortunately, this means that output in `mkosi.output` and `mkosi.cache` is owned by root at the end and this is a mess. It would be best to have it `chown` on exit.

It also seems to cause some things in my `.git/` to be `root` probably because it runs `git` commands as root!

This can break git in a dangerous way if you run a command that expects to be able to write one of those files.

Perhaps it could look at env `SUDO_USER` and fix things accordingly, and/or drop permissions before running git.

Thanks!

**Comment by lucasdemarchi** [comment]
The only git commands are commands to read the tree depending on the option you set to copy the src.

We already chown the end result like you describe. See https://github.com/systemd/mkosi/blob/76e8d6118cdfad899a46401c8c6aa961a1434cd4/mkosi#L2909

**Comment by purpleidea** [comment]
@lucasdemarchi ! Ah, I will test again shortly with git master, and close if the issue is gone. I am currently using the packaged version in F29 which perhaps doesn't have this patch yet. Thanks for the info!

**Comment by purpleidea** [comment]
After testing with git master and reading the source, I can confirm the bug is valid. In particular the `mkosi.builddir` and `mkosi.cache` directories don't get `chown`-ed, so the stuff in there is now `root` owned, but in your $HOME directory. :/

**Comment by poettering** [comment]
But the mkosi.builddir/mkosi.cache thing being root owned, is that so bad? I mean, unlike the output files these are only read/written by mkosi which after all runs privileged...

We could of couse rechown those dirs after running, but I am not sure that would be worth it? it would just be slow, no?

**Comment by purpleidea** [comment]
@poettering I have a `make.sh` script to poke at the things like this:

https://github.com/purpleidea/mgmt/blob/0fa3d6c462bd5dd34fee4b80cd5f9aaaf9a4c2c9/misc/mkosi/make.sh#L50

Unfortunately it means I've got a `sudo` that happens after a long mkosi operation. So I either have to have a very long sudo timeout (but who knows how long) or have to run a sudo hack to run `sudo -v` every few minutes to keep it active. (gross)

Otherwise I might miss this sudo prompt and nuke the script by sudo timeout.

So including this `chown` in the already long running operation would be a good idea IMO. If there's some use case that wants to keep the files chown-ed as root, then it could be gated by a flag, but I think it should be the default.

**Comment by poettering** [comment]
sure, send a patch... but if figure this should chown the dir before starting the operation to root, and then back to the calling user after its done

**Comment by DaanDeMeyer** [comment]
Isn't this fixed by using a finalize script that runs in the host as part of the mkosi run?

**Comment by DaanDeMeyer** [comment]
With a few chowns (I think we already do most of these) and some uidmapped bind mounts once nspawn supports them, we should be able to avoid any root owned files on the host

**Comment by DaanDeMeyer** [comment]
We recently merged support to run mkosi without root, and all the files generated should now be removable by the user; so let's close this

**Comment by purpleidea** [comment]
@DaanDeMeyer 

Awesome, thanks!

From your recent commit message:

> systemd-nspawn cannot run as an unprivileged user yet

I've been waiting for this for a while, and your `yet` gives me hope. Any idea if this is on the cards? So we could have an equivalent --user version of nspawn? Cheers!

**Comment by DaanDeMeyer** [comment]
@brauner was going to implement it at some point, don't know when exactly
