### ISSUE TITLE
Has mkosi future having buildah instead?

### ISSUE THREAD

**Issue by q2dg** [systemd/mkosi#370]
Hello. Now systemd-nspawn has the capacity of running OCI containers ("à la podman"), I was wondering if there is any use case where a container's rootfs built by mkosi could provide any extra advantage/functionality against a container's rootfs build by buildah.
Thanks!

**Comment by poettering** [comment]
buildah is purely a container builder. mkosi otoh can build verity enabled bare metal and VM images with boot loader and whatnot. It's very different stuff. Yes, you can run OCI images with nspawn too, but the overlap of image types mkosi and buildah can build is currently the empt set. Maybe mkosi eventually can build OCI too, but I doubt that buildah will ever supprt building raw disk images with boot loader, verity, secureboot and so on

**Comment by q2dg** [comment]
Thanks for your so clear explanation
