### ISSUE TITLE
Adopt /etc/kernel/entry-token once all distros have sufficiently new bootctl/kernel-install

### ISSUE THREAD

**Issue by lucasdemarchi** [systemd/mkosi#376]
I have the following problem when generating bootable Fedora images:

- A directory /efi/\<fake-machine-id\> is leftover in the image
- /etc/machine-id is wiped so a new one is created on first boot
- kernel-install fails to install new kernels when the dir /efi/\<machine-id\> doesn't exist

I use kernel-install in the final image to install additional kernels for testing. I don't know exactly where to fix this current behavior. My current approach is to always remove the fake-machine-id dir and add a new one, but there should be a better way.

Related question: could we have a toggle to avoid using a unified kernel? For my use cases having a bootloader conf entry with separate initrd and kernel image would be better.

**Comment by DaanDeMeyer** [comment]
Might be interested in this PR: https://github.com/systemd/systemd/pull/16687

**Comment by DaanDeMeyer** [comment]
We should be able to fix this with the new /etc/kernel/entry-token support that was added to bootctl and kernel-install. It might just take a while until we have sufficiently new systemd in all distros to be able to depend on it.

We already have an option to not use unified kernel images.

**Comment by DaanDeMeyer** [comment]
We don't create an entry-token directory at all anymore, so let's close this
