### ISSUE TITLE
Conflicting initrd with Ubuntu

### ISSUE THREAD

**Issue by jardinimf** [systemd/mkosi#393]
System: Ubuntu Eoan
MkOSI version installed: mkosi/eoan,eoan,now 5-1 all

-- Begin of mkosi.default --
```
[Distribution]
Distribution=ubuntu
Release=xenial
Mirror=http://br.archive.ubuntu.com/ubuntu

[Output]
Format=raw_gpt
Output=xenial.img
Bootable=yes
BootProtocols=uefi
Hostname=TestDisk

[Packages]
Packages=nano

[Partitions]
RootSize=2G
ESPSize=128M
```
-- End of mkosi.default --

Mkosi script target to use **dracut** but Ubuntu linux-image expect to use **initramfs-tools**
Adding **initramfs-tools** to _Packages_ cause mutual exclusion conflict (dracut vs initramfs-tools)

**Comment by fernandolobato** [comment]
I hit this under a different context. I don't think its mkosi issue though:

Package linux-initramfs-tool is a virtual package provided by:
  initramfs-tools 0.130ubuntu3.9
  tiny-initramfs 0.1-5
  dracut 047-2
You should explicitly select one to install.

Its the way things are referenced.

**Comment by DaanDeMeyer** [comment]
Using dracut almost everywhere has its own advantages from a complexity and cross-distro consistency standpoint. Does it matter all that much if we use dracut instead of initramfs-tools as long as it is automatically invoked when new kernels are installed to regenerate the initramfs?

**Comment by matspetter** [comment]
Running on host Ubuntu18.04 with mkosi from master as of today 201123 

I think I have a similar problem connected to this. I'm also trying to build against xenial but at the end it says it cannot find update-initramfs. See part of build log.

:
Setting up kbd (1.15.5-1ubuntu4) ...
Setting up console-setup-linux (1.108ubuntu15) ...
update-alternatives: using /etc/console-setup/vtrgb to provide /etc/vtrgb (vtrgb) in auto mode
Setting up linux-image-4.4.0-21-generic (4.4.0-21.37) ...
Running depmod.
**sh: 1: /usr/sbin/update-initramfs: not found**
Failed to create initrd image.
dpkg: error processing package linux-image-4.4.0-21-generic (--configure):
:


mkosi.default:
[Distribution]
Distribution=ubuntu
Release=xenial

[Output]
Bootable=yes
Format=gpt_ext4

**Comment by behrmann** [comment]
@matspetter When did it last work for you and with what version of mkosi and what Ubuntu target? The last change to mkosi was more than a month ago, so something on the Ubuntu side must have changed.

**Comment by matspetter** [comment]
this is actually the very first time I try to use this tool so unfortunately I cannot tell. mkosi version is from master today and target is ubuntu/xenial.

**Comment by matspetter** [comment]
I tried it now on a host computer with ubunu20.04/focal and with mkosi ver 5 targeting xenial and it gives the same problem:
/usr/sbin/update-initramfs: not found

**Comment by DaanDeMeyer** [comment]
Switching away from dracut is not something that we're going to do as it simplifies things substantially to use the same initrd generator everywhere.

If you're having trouble generating an image, please open a new issue for that with all the necessary information to reproduce the issue.
