### ISSUE TITLE
Use tar instead of shutil.unpack_archive()

### ISSUE THREAD

**Issue by quasicomputational** [systemd/mkosi#404]
`ExtraTrees` is copied over and unpacked before `PostInstallationScript` is run. This is problematic if you want to add users/group and have them own objects in the filesystem.

Even though `mkosi` will try to respect user/group names in an archive, it simply can't because they haven't been added to `/etc/(passwd|group)` at extraction time.

A solution is to use numeric UIDs/GIDs, but that's horrible. We can do better.

Another solution is to hack around `ExtraTrees`: copy over a tarball to be extracted by `PostInstallationScript`, after the users/groups have been added. But this is imperative and is defeating the point of `ExtraTrees` - and, I suspect, forcing `PostInstallationScript` to be used in many situations where it's not otherwise necessary.

One more solution that works today is to let `ExtraTrees` copy the trees over, and then to mass-`chown` in `PostInstallationScript`, but this is basically just a fragile version of the previous solution, spreading a single file's configuration across two locations.

It would be much nicer if there was a declarative way to create users/groups before `ExtraTrees` is extracted. `systemd-sysusers` already has a nice declarative configuration, and a `--root` option meaning it already plays nice with bootstrapping an image.

Users & groups are something of a special case - not having them set up in time really vitiates `ExtraTrees`, and there's already a declarative solution lying around - so I think this would pull its weight compared to, e.g., adding another hook to run arbitrary code before `ExtraTrees` is extracted.

So, my proposal, `mkosi.default` grows a new `SystemUsers=` field, pointing to a `sysusers` file (or multiple files). After distribution installation but before `ExtraFiles` is extracted, the host's `systemd-sysusers` is run on those files. (There's not even any need to copy the files into the mounted image, which is nice if utterly minor; perhaps someone somewhere will get excited over shaving 2 kB off their images...)

**Comment by DaanDeMeyer** [comment]
I would add `SysusersDirectory=` or so and a corresponding path `mkosi.sysusers` containing sysusers definition files and we'd run this during the build before copying extra trees. Makes total sense to add this, would love to see a patch for this

**Comment by DaanDeMeyer** [comment]
Actually, this should already be possible by just putting some sysusers files in mkosi.skeleton/. The only thing missing is to make sure we take these users into account when unpacking archives by using `tar` with `bwrap()` instead of `shutil.unpack_archive()`

**Comment by DaanDeMeyer** [comment]
So we now use tar everywhere, so if you put your sysusers files in a skeleton tree, systemd-sysusers will create them when it is invoked as part of package installation and the users will be ready to be used by the time we unpack the extra trees archives.
