### ISSUE TITLE
centos8 - install_unified_kernel not supported

### ISSUE THREAD

**Issue by jpcurrey** [systemd/mkosi#407]
Creating centos8 images I noticed that the image wasn't bootable, a key difference between centos 8 and fedora was that install_unified_kernel didnt support centos
changing the following line on 2867 fixed my problem
`
def install_unified_kernel(args, workspace, run_build_script, for_cache, root_hash):
...
   if args.distribution not in (Distribution.fedora, Distribution.centos, Distribution.mageia):
        return
...
`
there maybe a preferred work around for centos that I missed but as centos 8 is now released this should now be supported in centos 8.

**Comment by DaanDeMeyer** [comment]
Should be fixed in git master
