### ISSUE TITLE
Ubuntu: failure at install_unified_kernel from 531f52d

### ISSUE THREAD

**Issue by alessandrogambino** [systemd/mkosi#410]
Hello,

Could be already known or work-in-progress as it is quite recent, by the way commit 531f52d4815cd4465ce3be82835ea0edbf005272 introduce some regression on Ubuntu.
Command and stacktrace in attachment. Previous commit (22dc19b4cc9f5bcfee3c45426a579755cf77bef) conclude the command successfully.

[stack.txt](https://github.com/systemd/mkosi/files/4403885/stack.txt)

Regards

**Comment by fernandolobato** [comment]
For ubuntu 18.04 you will need to add usrmerge to the list of packages. Maybe this should be installed by default. I will send another PR.

**Comment by fernandolobato** [comment]
The fix has been merge, closing this issue.

**Comment by fernandolobato** [comment]
@alessandrogambino , The fix can be merge, you can now check.

**Comment by DaanDeMeyer** [comment]
Let's close this one as a fix was merged.
