### ISSUE TITLE
Support incremental mode for all output formats

### ISSUE THREAD

**Issue by mmorvai** [systemd/mkosi#433]
It seems that a cached image is saved for gpt_ext4, gpt_xfs, gpt_btrfs and gpt_squashfs (is_disk()). 

So actually incremental mode seems to work only with gpt_ext4, gpt_xfs, gpt_btrfs and gpt_squashfs as output format. Or am I wrong? If not, is there a reason for that? 

It would be great if the incremental mode also worked for the formats directory, tar, plain_squashfs, gpt_squashfs and subvolume.

**Comment by mmorvai** [comment]
PR #583 adds support for directory, tar and plain_squashfs.

The support for generated images (minimized and gpt_squashfs) is still missing.

**Comment by DaanDeMeyer** [comment]
We support incremental mode for everything now
