### ISSUE TITLE
How to specify package repositories for ubuntu images?

### ISSUE THREAD

**Issue by krystofl** [systemd/mkosi#435]
Hi,

I'm trying to build an image from Ubuntu 18.04 that includes the latest available package versions as well as Docker.

I can't figure out how to use the `Repositories=` option properly for ubuntu packages. The option wants urls, but the format for ubuntu repositories is like `deb http://archive.ubuntu.com/ubuntu bionic-updates main universe`

I can get the results I want after booting up the image with
```
add-apt-repository "deb http://archive.ubuntu.com/ubuntu bionic-updates main universe"
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
```
and then updating the package lists and installing the packages I want.

After digging at this for hours, I realized it may not be possible because of a [Debootstrap limitation](https://askubuntu.com/a/849749), so I thought about doing it in `mkosi.postinst`. However, that script does not seem to be able to access the internet (is that normal? can I change this?).

**How can I install packages for ubuntu images from arbitrary package repositories (such as the two listed above)?**

**Comment by dellgreen** [comment]
The documentation is inaccurate with respects ubuntu is should be in the following format in your mkosi.default file if using file based configuration
```

Repositories=
    multiverse
    main
    universe
    restricted

```

**Comment by dellgreen** [comment]
mkosi adds its own /etc/apt/sources.list during the build which will clobber any you try to add vie mkosi.skeleton, but you can add your own to replace it in mkosi.extra/etc/apt/sources.list and then use mkosi.posinst as you mention to install whatever you wish. You will need to add the following to your mkosi.default file

```
[Packages]
WithNetwork=yes
```

**Comment by krystofl** [comment]
Thanks @dellgreen! 

Adding entries to the Repositories did not work for me, but by adding `WithNetwork=yes` and adding code to `mkosi.postinst` I got everything I needed done.
