### ISSUE TITLE
"firmware-atheros" network debian package issue while building a minimal OS

### ISSUE THREAD

**Issue by SashankGit** [systemd/mkosi#445]
Hello Peeps,

Here am experimenting on including **firmware-atheros** network driver package of Debian flavor of OS. Here goes the command

$ sudo mkosi -d debian -r buster -f -b -t gpt_ext4 --checksum --password password --package=vim,curl,git,firmware-atheros,linux-image-amd64 -o image.raw 

Error on screen: subprocess.CalledProcessError:.... returned non-zero exit status 100.

Let me know what would be the issue when am trying to include the **firmware-atheros** package? is it in-compatible? or anything else I should include for resolving this conflict?

**Comment by DaanDeMeyer** [comment]
Try adding the `--repositories=main,non-free` option. By default, only the main repository is enabled.

**Comment by SashankGit** [comment]
Yes it did work, Thanks and pls close the issue

**Comment by SashankGit** [comment]
May I know, how to create a user account and password while generating this image?

Since the default options, it considers username: root password: password!

How do I create a user account?

**Comment by DaanDeMeyer** [comment]
Creating user accounts is not explicitly supported in mkosi itself. You could use a post install script to add the user yourself using the usual `useradd` command, same way you'd do it for any other linux system.

**Comment by DaanDeMeyer** [comment]
Let's close this. You can open another issue if you have other questions.
