### ISSUE TITLE
RFE: utilize (or allow utilizing) the Arch Linux mirrorlist

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/mkosi#467]
When bootstraping the Arch Linux image I sometimes end up with:
```
error: failed retrieving file 'libutil-linux-2.36-1-x86_64.pkg.tar.zst' from mirrors.kernel.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
```

This could, probably, be avoided (to some degree) by utilizing the [Arch Linux mirrorlist](https://www.archlinux.org/mirrorlist/?country=all) as right now there's only the kernel.org mirror enabled by default. There's the `--mirror` option, but that supports just a single mirror. Also, other distros already have a fallback to their respective mirrorlists (like [Fedora](https://github.com/systemd/mkosi/blob/4ac0cd84e3cc4161d1bff3fd32ba03766a602da6/mkosi#L1708), [CentOS](https://github.com/systemd/mkosi/blob/4ac0cd84e3cc4161d1bff3fd32ba03766a602da6/mkosi#L1926), or [Mageia](https://github.com/systemd/mkosi/blob/4ac0cd84e3cc4161d1bff3fd32ba03766a602da6/mkosi#L1760)).

Right now, I could think of two ways how to do it:

1) Pick a several mirrors at random and enable them
This would make the behavior somewhat consistent with the other supported distributions, which already have a mirrorlist fallback. It could be done either statically (pick several mirrors from the mirrorlist and hardcode them), or automatically (fetch the mirrorlist before the bootstrap and generate a custom mirrorlist with randomly enabled mirrors) but that would make the Arch-related code bit more complex (not counting the new possible point-of-failure).

2) Expose a new option (like `--mirrorlist`) and let the user pass their own mirrorlist
This would be more flexible, since users could choose the closest/best mirrors to them.

**Comment by behrmann** [comment]
Option 1 does sound a bit magical, although I think that automatically fetching it from https://www.archlinux.org/mirrorlist/ would be fine, if there were a way to reliably determine which country to use, without calling out to e.g. geoclue. 

I think in the long run a `--mirrorlist` option would be more helpful as an alternative to the `--mirror` option.

**Comment by DaanDeMeyer** [comment]
How about we use this: https://www.archlinux.org/mirrorlist/?country=all&protocol=http&protocol=https&ip_version=4&use_mirror_status=on?

Not sure if we just want to be using any random mirror that happens to have the highest score though.

**Comment by behrmann** [comment]
This would be as possibility, but I can see some downsides. The list is random and uses servers worldwide, so the mirrors could be just anywhere, this might make things hard to reproduce, because not all mirrors might have the same state and might have wildly different latencies between different invocations of mkosi (that's why I wondered about reliably determining which country to use). 

I guess `--mirrorlist` would also be better in way of reproducibility
