### ISSUE TITLE
RFE: Socket-activated devserver

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#480]
We should support a command that sets up the necessary machinery to use the mkosi build image as a devserver. The idea is that you build the image, tell mkosi you want it to be a devserver and are able to ssh into it to work on the project. As a bonus, we could use socket-activation to start up the devserver only when a user actually wants to use it.

A first version could simply add ssh and systemd to the build image so it can be booted with ssh access and add an extra command that installs the necessary systemd files to make it socket activatable. We'd probably want an option to boot either with qemu or nspawn when socket activating to allow running integration tests and whatnot in the build image (when a container is not isolated enough (e.g /dev is needed) or we're doing kernel stuff)

(ssh access would be specifically to make it work with VSCode's remote ssh extension and to have the option of socket activation)

**Comment by johannbg** [comment]
What's the end goal here which is not covered by running the image as a vm with sshd running or container with sshd running? Why would would you suddenly want turn an image generation tool into a "dev server"

**Comment by DaanDeMeyer** [comment]
Closing this, the right fix is vscode adding nspawn support. When we have that we can look into adding an option to persist the build image so that vscode can run itself.
