### ISSUE TITLE
partition size is rounded down instead of up..  Also image_size is sometimes too small because sfdisk 2.26 realigns partition offsets silently

### ISSUE THREAD

**Issue by arianvp** [systemd/mkosi#493]
https://github.com/systemd/mkosi/blob/e18478f3150a41259e04278a7e5519f6174ddb9e/mkosi#L615

dividing by `512` rounds down; which sounds wrong to me.  

Say you'd have a partition of size  `1512` . This will then allocate `2` blocks whilst we should allocate `3`

Instead we should do:
`(args.esp_size + 511) // 512` 

to get the correct size

**Comment by arianvp** [comment]
Seems I was wrong. Sorry

**Comment by arianvp** [comment]
I see there's already some utility functions for this. but they're not used everywhere

**Comment by arianvp** [comment]
I also think since sfdisk 2.26, the calculation of `image_size` here is incorrect:
https://github.com/systemd/mkosi/blob/e18478f3150a41259e04278a7e5519f6174ddb9e/mkosi#L572

from the manpage:
>        sfdisk  (since  version 2.26) aligns the start and end of partitions to block-device I/O limits when relative sizes
>        are specified, when the default values are used or when multiplicative suffixes (e.g. MiB) are used for sizes.   It
>        is  possible  that  partition  size will be optimized (reduced or enlarged) due to alignment if the start offset is
>        specified exactly in sectors and partition size relative or by multiplicative suffixes.

The proposed fix is that the `sfdisk` lines must _both_ contain the `size=` and the `offset=` parameter. If `offset=`  is **not** explicitly provided, sfdisk is free to reshuffle the partitions, and `sfdisk` crashes because the image is truncated to a too small size (without a useful error message)


Reproducer:

```
reserved=4096
espSize=14944
rootSize=71176
veritySize=576
fullSize=$(($reserved + $espSize + $rootSize + $veritySize))
echo $fullSize
truncate --size $(( $fullSize * 512 )) out.img

sfdisk out.img <<EOF
label: gpt
size=$espSize
size=$rootSize
size=$veritySize
EOF
```

This just fails without any error message silently:
```
$ sfdisk out.img <<EOF
> label: gpt
> size=$espSize
> size=$rootSize
> size=$veritySize
> EOF
Checking that no-one is using this disk right now ... OK

Disk out.img: 44.3 MiB, 46485504 bytes, 90792 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

>>> Script header accepted.
>>> Created a new GPT disklabel (GUID: CACF3CA1-DBC0-BE42-A006-12E9D8B9A516).
out.img1: Created a new partition 1 of type 'Linux filesystem' and of size 7.3 MiB.
out.img2: Created a new partition 2 of type 'Linux filesystem' and of size 34.8 MiB.
out.img3: Created a new partition 3 of type 'Linux filesystem' and of size 288 KiB.
out.img4: Done.

New situation:
Disklabel type: gpt
Disk identifier: CACF3CA1-DBC0-BE42-A006-12E9D8B9A516

Device     Start   End Sectors  Size Type
out.img1    2048 16991   14944  7.3M Linux filesystem
out.img2   18432 89607   71176 34.8M Linux filesystem
out.img3   18432 19007     576  288K Linux filesystem

$ echo $?
1
```

**Comment by arianvp** [comment]
Rereading the `sfdisk` manpage; I honestly think this is a bug in `sfdisk`; not `mkosi`.  it shouldn't be realigning sectors when not using relative sizes or size specifiers

**Comment by DaanDeMeyer** [comment]
PRs appreciated!

If you post a mkosi reproduce command I might take a look myself.

**Comment by arianvp** [comment]
Yeh the way I reproduced this is that I was stealing the way mkosi does partitioning to write my own bash script :')  I'll have to un-reverse-engineer my stuff to make a reproducer with `mkosi` directly.

**Comment by DaanDeMeyer** [comment]
Let's close this until a reproducer is available. Will happily take a look once that's available

**Comment by arianvp** [comment]
No problem. Once I start playing with mkosi again I'll have a look at this
again. Just haven't had the time. Fine with closing it if you want to keep
the backlog clean of unactionable things.
