### ISSUE TITLE
Include man page in Python package

### ISSUE THREAD

**Issue by behrmann** [systemd/mkosi#497]
When building the man page with
```
pandoc -t man -o mkosi.1 mkosi.md
```
the output looks rather unpleasing:
```
mkosi  ‐  Build  Legacy‐Free  OS  Images mkosi [options...] build
mkosi [options...] clean mkosi [options...]  summary  mkosi  [op‐
tions...]  shell [command line...]  mkosi [options...] boot [com‐
mand line...]  mkosi [options...] qemu mkosi is a tool for easily
building  legacy‐free OS images.  It’s a fancy wrapper around dnf
‐‐installroot, debootstrap, pacstrap and zypper that may generate
disk  images  with a number of bells and whistles.  The following
output formats are supported: Raw GPT disk image,  with  ext4  as
[...]
```

We should fix that and maybe generate the man page automatically via a commit hook, so that the man page can be included (and installed) when doing a pip install.

**Comment by behrmann** [comment]
This was tested with pandoc 2.9.2.1 on Arch.

**Comment by behrmann** [comment]
That was easy. Adding `-s` fixes it, see jgm/pandoc#6521.

**Comment by DaanDeMeyer** [comment]
Can we not just generate the man page on demand when installing?

**Comment by behrmann** [comment]
Not with pandoc, that's not guaranteed to be installed and it's also a rather heavy dependency just for a man page.

**Comment by DaanDeMeyer** [comment]
Commit hooks seems a bit heavy for the amount of contributors we have. I think we can get by if we just include the man page in the repo and tell devs to regenerate it if they update mkosi.md.

**Comment by DaanDeMeyer** [comment]
I do remember when first installing mkosi from the AUR on Arch that I was extremely annoyed that I had to install more than 200 haskell dependencies to get the docs so I get where you're coming from.

**Comment by cvlc12** [comment]
This is closed as completed, but the AUR package still needs to pull in 220+ haskell packages. It is a problem with the PKGBUILD or is this expected? Thanks
