### ISSUE TITLE
RFE: Support ISO image output format

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#520]
mkosi should support building bootable ISO images that can be copied directly onto a USB stick and booted.

**Comment by poettering** [comment]
hmm, why is an ISO necessay for that? 

firmware should boot fine of USB sticks with GPT/ESP or MBR without any ISO.

ISO is only really necessary for CDs afaik

**Comment by lucasdemarchi** [comment]
I've been using images generated by mkosi on USB drives for a long time. I don't think a iso is needed: it makes it a pain to update the image when you want to just change something before deploying.

**Comment by DaanDeMeyer** [comment]
So you just dd the image onto the USB? I had no idea that was possible.

**Comment by lucasdemarchi** [comment]
Yes. We may also consider integrating the systemd-repart... Today I actually run this after the dd: https://github.com/lucasdemarchi/toolbox/blob/master/mkosi-resize  (but ideally repart would make this obsolete)

**Comment by DaanDeMeyer** [comment]
I'm not sure yet if mkosi would have to do anything special to make that work. Isn't it sufficient to include a set of repart files in the mkosi generated image? I'm thinking you'd generate an image with mkosi, include the repart config with the image, flash the image onto the usb with `dd ... conv=sparse` and when you boot the USB on a laptop or so, you run systemd-repart on the actual hard drive of the laptop to completely configure it from top to bottom based on whats in the usb.

So instead of taking a default distribution ISO, you'd completely set up your own thing with mkosi just the way you like it and then you can trivially install the resulting image on whatever block device you want with repart taking care of resizing the partitions and copying everything over.

**Comment by poettering** [comment]
> Yes. We may also consider integrating the systemd-repart... Today I actually run this after the dd: https://github.com/lucasdemarchi/toolbox/blob/master/mkosi-resize (but ideally repart would make this obsolete)

Actually, we might even want to use systemd-repart instead of fdisk when building the image. It's great as a tool that combines file systems or file trees into a GPT image.

**Comment by poettering** [comment]
> I'm not sure yet if mkosi would have to do anything special to make that work. Isn't it sufficient to include a set of repart files in the mkosi generated image? I'm thinking you'd generate an image with mkosi, include the repart config with the image, flash the image onto the usb with `dd ... conv=sparse` and when you boot the USB on a laptop or so, you run systemd-repart on the actual hard drive of the laptop to completely configure it from top to bottom based on whats in the usb.

Yes, all that's necessary should be that mkosi.extra/ contains the repart definitions and then everything should just work, as we trun on repart automatically in systemd if it has definition files around
