### ISSUE TITLE
Move to Python 3.7 (and only use dataclasses?)

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#529]
I'm looking at cleaning up the argument parsing a bit and it turns out Python dataclasses would be extremely useful to allow us to define a dataclass which we can automatically turn into an argument parser.

The biggest problem is that CentOS 8 only has Python 3.6. There is a backport of dataclasses available for Python 3.6 that would have to be installed on CentOS 8 for mkosi to keep working there . @mrc0mmand would that work for you if CentOS CI would ever move to mkosi? I found this: https://cbs.centos.org/koji/buildinfo?buildID=29591 which seems to do something similar already.

So this seems like it should work as long as we only use dataclasses from Python 3.7 and nothing else.

**Comment by behrmann** [comment]
This is something I thought about a few times as well, but haven't acted on because of Centos 8.

Preferably I'd like to split up the somewhat monolithic `args` into a few chunks per topic, as well, although I haven't given it too much thought, which those would be.

**Comment by mrc0mmand** [comment]
After a quick peek there's both python3.6 and python3.8 in the CentOS 8 AppStream repository, so I guess moving to python3.7 shouldn't be much of an issue from the CentOS 8 point of view.

```
Available Packages
Name         : python36
Version      : 3.6.8
Release      : 2.module_el8.1.0+245+c39af44f
Arch         : x86_64
Size         : 19 k
Source       : python36-3.6.8-2.module_el8.1.0+245+c39af44f.src.rpm
Repo         : AppStream
...

Name         : python38
Version      : 3.8.0
Release      : 6.module_el8.2.0+317+61fa6e7d
Arch         : x86_64
Size         : 76 k
Source       : python38-3.8.0-6.module_el8.2.0+317+61fa6e7d.src.rpm
Repo         : AppStream
...
```

**Comment by poettering** [comment]
I guess we can close this now that #788 has been merged.
