### ISSUE TITLE
bin/mkosi uses /usr/bin/bash

### ISSUE THREAD

**Issue by mtdcr** [systemd/mkosi#532]
After installing mkosi-6 with `pip install git+https://github.com/systemd/mkosi.git` and trying to run it, I get `/usr/bin/bash: bad interpreter: No such file or directory`. I propose using `/bin/bash` or `/usr/bin/env bash` for wider compatibility. Or better yet, remove unneeded bashisms (change `[[` to `[`, `]]` to `]`, `== false` to `= "false"`, remove `declare PREPEND_PYTHONPATH`) and use `/bin/sh`.

You can also replace `] && [` with `-a` to reduce the number of forks.

**Comment by behrmann** [comment]
The reason I used bash is that shell scripts are terrible and portable shell scripts are even worse. Requiring bash at least has known semantics (e.g. `&&` is coalescing for which `-a` has no guarantees as far as I know). I'm also of the strong opinion that every system where mkosi will be used will have bash installed.
