### ISSUE TITLE
Missing security updates in images created with debootstrap

### ISSUE THREAD

**Issue by mtdcr** [systemd/mkosi#534]
Unfortunately, debootstrap doesn't include security updates (or updates from point releases) in /etc/apt/sources.list.

In mkosi, this can get worked around in a mkosi.prepare script, but it's a time-consuming process and requires parsing /etc/apt/sources.list and /etc/os-release to pick the correct mirrors and componentes (in mkosi: repositories).

It would be nice if mkosi could handle this.

In the past I used [mmdebstrap](https://gitlab.mister-muffin.de/josch/mmdebstrap) to create Debian-based root filesystems. It's a drop-in replacement for debootstrap, which solves this problem by using apt to set up the whole system. You might consider supporting it, at least as an alternative, if present.

**Comment by DaanDeMeyer** [comment]
Sure, we can put this behind an option If it's not too much of a much of a maintenance burden. It doesn't seem like adding this would require too many changes though. PRs are welcome.

**Comment by keszybz** [comment]
I'm not even sure if it needs to be an option. I think we could do it unconditionally for Debian (and Ubuntu?).

**Comment by mtdcr** [comment]
I gave it a first try yesterday: https://github.com/systemd/mkosi/compare/master...mtdcr:345a32c5b678fd34bb16b455fd8a9de8708d7681

Issues noticed so far:
- Versions below 0.7.0 can't install into a non-empty root. Version 0.7.1 is available in Debian bullseye, but not in any version of Ubuntu.
- It deletes all installed .deb files unconditionally, so the cache doesn't work.
- It uses system keyrings, which means creating an Ubuntu image from Debian requires prior installation of `ubuntu-keyring`, for example.

**Comment by DaanDeMeyer** [comment]
- >Versions below 0.7.0 can't install into a non-empty root. Version 0.7.1 is available in Debian bullseye, but not in any version of Ubuntu.

mkosi uses empty roots AFAIK but I might be wrong here.

- >It deletes all installed .deb files unconditionally, so the cache doesn't work as intended (cf. upstream issue).

Without caching support I wouldn't enable this unconditionally. The caching is pretty important as it saves a large amount of time on rebuilds.

- > It uses system keyrings, which means creating an Ubuntu image from Debian requires prior installation of ubuntu-keyring, for example.

The system keyring thing is expected, on Arch I have to install the debian and ubuntu keyrings as well to generate debian/ubuntu images.

- > It only works on systems shipping apt-get, so it's not going to replace debootstrap on non-Debian systems.

There's actually an AUR package for apt but I agree that having to install that would be a degradation in user experience.

I'm kinda torn on using this unconditionally. I'm fine with making it opt-in though so users explicitly opt-in to using this. It's probably a good idea to have a testing period regardless before we switch the default to something else than debootstrap.

**Comment by behrmann** [comment]
> In mkosi, this can get worked around in a mkosi.prepare script, but it's a time-consuming process and requires parsing /etc/apt/sources.list and /etc/os-release to pick the correct mirrors and componentes (in mkosi: repositories).

I'm not quite sure I follow. It's definitely sensible to add an `/etc/apt/sources.list`, but we know a mirror (the one we are bootstrapping from) and we know the suite we are installing and the names for repositories are well-known. Shouldn't it be as easy as dropping a file containing
```
deb {mirror} {args.release} main contrib non-free
```
and not require parsing anything?

Possibly, if `args.release` is not sid, a few more lines for `{args.release}-updates`, `{args.release}/updates` and possibly `{args.release}-backports`?

**Comment by mtdcr** [comment]
> mkosi uses empty roots AFAIK but I might be wrong here.

Since 0.7.0 it's possible to pass `--skip check/empty` to it.

**Comment by mtdcr** [comment]
> I'm not quite sure I follow. It's definitely sensible to add an `/etc/apt/sources.list`, but we know a mirror (the one we are bootstrapping from) and we know the suite we are installing and the names for repositories are well-known. Shouldn't it be as easy as dropping a file containing
> 
> ```
> deb {mirror} {args.release} main contrib non-free
> ```
> 
> and not require parsing anything?
> 
> Possibly, if `args.release` is not sid, a few more lines for `{args.release}-updates`, `{args.release}/updates` and possibly `{args.release}-backports`?

At which point in mkosi's execution flow would you recommend injecting a sources.list? Do you propose letting mkosi handle it?

What I'm looking for is a solution that works for many different configurations without having to provide redundant information (all the parameters are already known from mkosi.default or the command-line, so it shouldn't be needed to craft a custom sources.list manually), which is why I preferred parsing in a mkosi.prepare script shared by many configurations as a workaround.

Anyway, the most important thing is that whatever solution is preferred, **it should not require an invocation of `apt-get update && apt-get upgrade`**, which is the time consuming part of the problem, and there's no usable hook between the invocation of `debootstrap` (which generates the sources.list) and `apt-get install`.

If I'm missing the obvious, I'd appreciate a kind pointer.

**Comment by behrmann** [comment]
I guess the right point to set a sources.list (and call `apt-get update` and `apt-get upgrade`) is between the call to `debootstrap` and our first call to `apt-get`. Somewhere around like 2150. One could either clobber the debootstrap supplied sources.list or move it out of the way temporarily.

Running `apt-get update` and `apt-get upgrade` also shouldn't take all too long, since the bootstrap is minbase anyway. 

I'd prefer to stay within upstream debootstrap land instead of using a tool that is quite dated in current stable (without a newer version in backports) and that would introduce a second code path for bootstrapping Debian-based systems, if your problem can be solved within those constraints. Maybe I'm misunderstanding your problem, though.

**Comment by behrmann** [comment]
I just bootstrapped a system via
```bash
debootstrap --variant=minbase buster ./buster-chroot/ http://deb.debian.org/debian
```
and added 
```
deb http://deb.debian.org/debian buster-updates main
```
in addition to the generated line 
```
deb http://deb.debian.org/debian buster main
```

The following `apt upgrade` was a noop:
```
root@hostname:/# apt update
Hit:1 http://deb.debian.org/debian buster InRelease
Get:2 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:3 http://deb.debian.org/debian buster/main Translation-en [5968 kB]
Get:4 http://deb.debian.org/debian buster-updates/main amd64 Packages [7868 B]
Get:5 http://deb.debian.org/debian buster-updates/main Translation-en [5672 B]
Fetched 6033 kB in 2s (3556 kB/s)                                     
Reading package lists... Done
Building dependency tree... Done
All packages are up to date.
root@hostname:/# apt upgrade
Reading package lists... Done
Building dependency tree... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Am I missing something? I fail to see where the packages are not current. Sorry if I'm being dense.

**Comment by mtdcr** [comment]
> I guess the right point to set a sources.list (and call apt-get update and apt-get upgrade) is between the call to debootstrap and our first call to apt-get.

Here's an excerpt from mmdebstrap, where it determines the URL of a security mirror.
```perl
    my $mirror    = 'http://deb.debian.org/debian';
    my $secmirror = 'http://security.debian.org/debian-security';
    if (any { $_ eq $suite } @ubuntustable) {
        if (any { $_ eq $arch } ('amd64', 'i386')) {
            $mirror    = 'http://archive.ubuntu.com/ubuntu';
            $secmirror = 'http://security.ubuntu.com/ubuntu';
        } else {
            $mirror    = 'http://ports.ubuntu.com/ubuntu-ports';
            $secmirror = 'http://ports.ubuntu.com/ubuntu-ports';
        }
    ...
```
Would you like to include such information in mkosi?

**Comment by mtdcr** [comment]
> Am I missing something? I fail to see where the packages are not current. Sorry if I'm being dense.

I was wrong assuming that $suite-updates would be used for point releases. It's the replacement for the former volatile repository: https://www.debian.org/News/2011/20110215

However, you forgot to add the security repository. There may or may not be security updates for packages in minbase, but we can't know in advance. Security updates for minbase will generally be rare and small. I'm more concerned about missing security updates in other packages.

**Comment by behrmann** [comment]
It would probably make sense to add the security repository, but it's not extremely crucial. If my understanding is correct, it is meant to push security fixes in between the regular sync intervals of regular mirrors, which is at most four hours (I think most sync via some push notification). The contents of this repository change irregularly, but when they come, they're usually gone just as quickly. 

So, yes, it would probably be an improvement to patch these repositories into sources.list, but generally the regular mirrors should be current enough for bootstrapping and afterwards the update cycles of the deployed machine will probably be longer than the sync cycle of the mirror, if the machines are updated at all (instead of redeployed).

**Comment by mtdcr** [comment]
> If my understanding is correct, it is meant to push security fixes in between the regular sync intervals of regular mirrors, which is at most four hours (I think most sync via some push notification). The contents of this repository change irregularly, but when they come, they're usually gone just as quickly.

No, that's wrong. Even though security tarballs might get synced into the regular archive early, it doesn't mean they're going to end up in its package index before a new point release every few months.

Here's an overview of recent security advisories for the buster release, starting September 18th: https://www.debian.org/security/#DSAS

The latest [point release 10.6](https://www.debian.org/News/2020/20200926) appeared on September 26th, but does not include any of the fixes listed on that page.

Let's take mediawiki as an example:
```sh
$ apt-cache policy mediawiki
mediawiki:
  Installed: (none)
  Candidate: 1:1.31.10-1~deb10u1
  Version table:
     1:1.35.0-1~bpo10+1 100
        100 http://deb.debian.org/debian buster-backports/main amd64 Packages
        100 http://deb.debian.org/debian buster-backports/main i386 Packages
     1:1.31.10-1~deb10u1 500
        500 http://deb.debian.org/debian-security buster/updates/main amd64 Packages
        500 http://deb.debian.org/debian-security buster/updates/main i386 Packages
     1:1.31.7-1~deb10u1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        500 http://deb.debian.org/debian buster/main i386 Packages
```
You can find version 1:1.31.10-1~deb10u1 on both http://deb.debian.org/debian/pool/main/m/mediawiki/ and http://security.debian.org/debian-security/pool/main/m/mediawiki/, but it gets referenced from the package lists of debian-security only.

**Comment by behrmann** [comment]
Thank you for the clarification. The point remains, though, that dropping a single line for the security repositories into `sources.list` and running `apt update` and `apt upgrade` should be sufficient.

**Comment by adrelanos** [comment]
mmdebstrap is amazing. Please add an option for it.

Caching can be done using apt-cacher-ng.
(apt-cacher-ng works with both, debootstrap and mmdebstrap.)
The speed gains of mmdebstrap over debootstrap are amazing.
Also security of mmdebstrap is better since it supports valid-until (since it uses APT) and since it can bootstrap from multiple repositories (regular and security) at the same time.

> Thank you for the clarification. The point remains, though, that dropping a single line for the security repositories into `sources.list` and running `apt update` and `apt upgrade` should be sufficient.

No, sometimes APT itself is vulnerable. In these cases, mmdebstrap is the only secure way to bootstrap the patched APT from the security repository. Thereby skipping to ever install the vulnerable APT from the non-security (regular) repository. By installing a vulnerable APT from the regular repository first, then running apt update and apt upgrade, one is exposed during times where APT didn't yet migrate from security repository to regular repository.

//cc @josch (creator of mmdebstrap)

(Words are my own. Not affiliated with mmdebstrap.)

**Comment by keszybz** [comment]
> Thank you for the clarification. The point remains, though, that dropping a single line for the security repositories into `sources.list` and running `apt update` and `apt upgrade` should be sufficient.

I agree. Somebody who uses Debian or Ubuntu should add this… It should be a few lines of code at most.
(We might or might not add support for mmdebstrap later on, but since it seems unlikely we'll get rid of support for debootstrap, we need to fix this issue here too.)

**Comment by jakob-tsd** [comment]
FYI: You probably want to use /usr/share/doc/apt/examples/debian.sources instead of generating the urls by hand.

**Comment by daandemeyer** [comment]
> FYI: You probably want to use /usr/share/doc/apt/examples/debian.sources instead of generating the urls by hand.

Generating by hand is a lot more flexible than using preshipped files. We can plug in our own mirrors, set up use of snapshots via the debian or ubuntu archive and much more all of which is not possible when using preexisting files.

**Comment by josch** [comment]
> FYI: You probably want to use /usr/share/doc/apt/examples/debian.sources instead of generating the urls by hand.

No. Debian Policy §12.6 "Examples" says:

> Any examples (configurations, source files, whatever), should be installed in a directory /usr/share/doc/package/examples. These files should not be referenced by any program: they’re there for the benefit of the system administrator and users as documentation only.

https://www.debian.org/doc/debian-policy/ch-docs.html#examples

The correct fix for "apt sources are generated manually" is to improve the `distro-info-data` package and add this information in a machine-readable format. @julian-klode is working on that.
