### ISSUE TITLE
Support providiing extra repositories from config files

### ISSUE THREAD

**Issue by markwellis** [systemd/mkosi#536]
I can no longer use extra repos with fedora, I get an error they don't exist.

Looks like it's because `install_fedora` calls `setup_dnf` here https://github.com/systemd/mkosi/blob/master/mkosi/__init__.py#L1881-L1884 but only with 2 predefined repos.

When `invoke_dnf` is ran here https://github.com/systemd/mkosi/blob/master/mkosi/__init__.py#L1893 with the extra repos, they're not in `temp.root` as created by setup_dnf.

**Comment by DaanDeMeyer** [comment]
PRs appreciated! Unfortunately, --repositories is a bit of a mess with different meanings per distro.

**Comment by DaanDeMeyer** [comment]
Could you provide some more information on how you were passing these extra repos to mkosi? An example to reproduce would be great!

**Comment by markwellis** [comment]
mkosi.default
```
[Distribution]
Distribution=fedora
Release=33

Repositories=
     fedora
     updates
     rpmfusion-nonfree
     rpmfusion-nonfree-updates

[Output]
Format=directory
Output=out

[Packages]
Packages=
    unrar
```

**Comment by DaanDeMeyer** [comment]
I can't seem to figure out how this worked before. Is there an associated url for these repositories?

**Comment by markwellis** [comment]
If I remember correctly, they came from the host. Because that's fedora, and the repos were inherited and the ones listed here were not removed

**Comment by DaanDeMeyer** [comment]
So what behavior do you want here? The idea is to make mkosi as independent from the host it's running on as we can. To configure these repositories, I'd need a url to configure in dnf's repo file (and preferably a url for the gpg key as well). Without those, I'm not sure how to support this.

**Comment by markwellis** [comment]
Makes sense. I'd be happy to add those to my config. I just after a way of adding repos via the config file so that I can install packages from there. If that means it needs a directory full or .repo files, or a bunch of config with names, urls, pgp keys etc, that's also fine.

**Comment by DaanDeMeyer** [comment]
Allowing custom repo files sounds like it would be a good addition. No cycles to work on that atm unfortunately but will be happy to review a PR.
