### ISSUE TITLE
Streamline setting up SSH access to QEMU vm

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#593]
While --qemu-headless is a perfect solution to work interactively with a vm launched from a user's terminal, the serial connection can't be "multiplexed" to allow usage by other tools. More specifically, it's currently not possible to give VSCode access to a shell in the virtual machine. With SSH access to a remote host, VSCode makes remote debugging possible without having to install any tools on the local host. See https://code.visualstudio.com/docs/cpp/pipe-transport.

The most obvious way to give other tools access to shells in the VM is to setup SSH in the final image. Currently, this requires installing and enabling SSH in the final image and either modifying sshd_config to allow root login with a password or setup an ssh key and copy it to the final image. Logging in with a password is annoying as it requires entering the password every time so the second solution seems more attractive.

This seems like something we could automate in mkosi though. We could add an --ssh option that takes care of installing ssh, enabling sshd and generating an SSH key on the host which is copied to the final image. The password for the SSH key would be the root password provided to mkosi.

This would allow users to specify the --ssh option, boot the QEMU vm and immediately have SSH access to it while only having to enter the root password once if ssh-agent is setup correctly.

**Comment by bluca** [comment]
This is a great feature and the PR is shaping up good!

But isn't the network config still missing? As far as I can see, when I build and boot a qemu Debian image with --network-veth, I just get an unconfigured interface. It doesn't work out of the box.

Shouldn't we boot qemu with user network mode enabled, and then start networkd/resolved in the image? Something like:

```
qemu-system-x86_64 <...> -device virtio-net-pci,netdev=network0,mac="<some random generated mac>" -netdev user,id=network0
```

(given it's qemu-emulated it doesn't require root privileges to set up on the host)

Then enabling resolved/networkd, dropping a .network file which matches en* e* and sets DHCP, and symlink /etc/resolve.conf to /run/systemd/resolve/resolve.conf.

**Comment by DaanDeMeyer** [comment]
Yes! That's what I'm working on now. Arch has networkd enabled by default in the mkosi image but when adding this to CI, I noticed that Ubuntu (and the rest of the distro as well probably) don't. I'm working on fixing that now.
