### ISSUE TITLE
mkosi should do nothing if executed in a directory without configuration

### ISSUE THREAD

**Issue by keszybz** [systemd/mkosi#609]
When executed in any parameters, `mkosi` will attempt to do a build, possibly creating a mess. The build is unlikely to succeed with the defaults anyway. I think this is just bad from user POV: programs should do state-changing operations by default like this.

I'm opening this to start discussion... I'd be happy to do a PR if there's agreement.

**Comment by johannbg** [comment]
makes sense...

**Comment by DaanDeMeyer** [comment]
A big thing is that mkosi can currently be used completely from the command line though. How would you detect no config was passed?

I agree that this isn't ideal though. I've ran into this problem a few times myself.

**Comment by behrmann** [comment]
I think we could detect this in `load_args` after `find_secure_boot`, i.e. after looking for all config files, by comparing `args` at that point to an artificially empty one coming fresh out of `parse_args`. At that point one could error out (or better yet, print the summary first) and ask the user to run with `--force` if the current config is really what they desire.

**Comment by keszybz** [comment]
> A big thing is that mkosi can currently be used completely from the command line though.

I think only the case of completely empty commandline should be treated as special. If some parameters are passed, I'd treat that as "the user knows what they are doing".

> or better yet, print the summary first

Yeah, something like:
```
This program expects configuration in the current directory or some command-line parameters.
Use 'mkosi --help' or specify at 'mkosi build' to build with the built-in defaults.
```
?

**Comment by poettering** [comment]
I think i agree that it probably doesn't make sense to build stuff without config.

this was modelled after "make", which also works without Makefile. But admittedly it's a pretty useless feature. At least I could never make that generate anything useful to me. So maybe not have it in mkosi either.

**Comment by keszybz** [comment]
```console
$ make
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by DaanDeMeyer** [comment]
> ```console
> $ make
> make: *** No targets specified and no makefile found.  Stop.
> ```
> 

Yeah, I think it makes sense for mkosi to do the same.
