### ISSUE TITLE
Copy of mkosi.nspawn file is broken

### ISSUE THREAD

**Issue by afreof** [systemd/mkosi#610]
The mkosi.spawn file gets copied only in "--incremental" mode. Without --incremental command line argument mkosi creates just an empty target nspawn file.

**Comment by DaanDeMeyer** [comment]
I cannot reproduce this. Can you give a list of commands to reproduce this issue?

**Comment by DaanDeMeyer** [comment]
I think we fixed this by flushing the file, please report back if you still encounter this on the latest commit.
