### ISSUE TITLE
Allow different development and final image sizes

### ISSUE THREAD

**Issue by bcbnz** [systemd/mkosi#611]
Some of my images require building some large packages during the development phase, but only a small subset of those build artefacts are copied to the final image. Making `RootSize` large enough to accommodate the build means the final image is much larger than its contents require. Could another option, maybe something like `FinalRootSize`, which defaults to `RootSize` if not given be added to allow different image sizes for the two steps?

**Comment by DaanDeMeyer** [comment]
Development images don't have a size limit anymore since they're just regular directories on disk now
