### ISSUE TITLE
RFE: way to also output generated partitions + kernels separately, too

### ISSUE THREAD

**Issue by poettering** [systemd/mkosi#625]
Right now mkosi builds a combined disk image containing multiple partitions + the signed kernels.

I am currently toying with some very simple tools for upadating images sanely after they have been booted. Idea is to support an A/B scheme, i.e. something along these lines:

1. Build minimal mkosi images, consisting of just one root partition + one verity partition + one EFI partition
2. At first boot, use `systemd-repart` to add in another (initially empty) root partition of the same size, plus another verity partition plus encrypted/TPM'ed/… /var and /home partitions.
3. At update download just the new root partition + verity partition + signed kernel, stream them into the empty partitions and the ESP + reboot, done.

What's missing for this is that mkosi spits out not only the combined partitioned image, but also the root partition + verity partition as separate files, as well as the signed kernel it puts into the ESP.

With that in place fresh installs would use the full disk image, but updates would download the three files separately, and put them in the right places, and reboot.

(Implementation would probably easy to implement (I mean it just means to dd/cp out the raw partitions/kernels into new files). Question though is whether we should maybe swap the whole order of partitioning around in mkosi. i.e. instead of setting up the partition table first, and mount the file systems directly from it, operate the other way: generate all file systems as separate files, and as last step combine them all in a GPT partition table.)

**Comment by behrmann** [comment]
As a short note: This scheme can currently not be implemented for Debian (and I guess Ubuntu), since Debian doesn't build `systemd-repartd` and likely won't ship it before the [bookworm](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=976959) release, maybe ~2023.

**Comment by DaanDeMeyer** [comment]
A separate kernel would also allow us to provide a qemu fast path using the `-kernel` option. That could shave another 2 seconds of qemu boot times.
