### ISSUE TITLE
RFE: add simple version concept

### ISSUE THREAD

**Issue by poettering** [systemd/mkosi#626]
In light of #625 I'd like to generate images with versioning. For me, versioning means primarily three things:

1. The output files should contain the version somewhere in their name. i.e. instead of generating foo.raw we should generate foo-4.76.5.raw in case version 4.76.5 of the image is built, and that for the whole shebang of generated files (except for SHA256SUMS of course, since that name needs to be fixed)
2. The images themselves should incorporate the version in the /usr/lib/os-release file, and possibly other files. This probably means that mkosi.build should probably know the current version so that it can generate/patch these files.
3. The unified kernel images, need to integrate the number too. sd-boot after all will use the version to order its entries in the menu, and pick the newest.

Here's my implementation idea:

1. Introduce `mkosi.version` that contains the version to generate
2. If this file exists, mkosi reads it and passes it as $VERSION into `mkosi.build`. If the file doesn't exist, everything happens as it always did. (the `mkosi.build` scripts would then patch /usr/lib/os-release with this info)
3. In the Output= stanza we should probably introduce some super basic variable expansion. Initially maybe just say that `%v` when used in Output= would be replaced by the version from `mkosi.version`. Thus if you specify `Output=foobar-%v.raw` you get what is needed.
4. Maybe have a new verb "mkosi bump" or so, which reads mkosi.build, identifies the last numeric component of it, increments it by one, writes it again. It should just do this trivial operation I guess, i.e. not bother with major/minor semantics or so. If people want more complex version bumps they can edit trivially hand.
5. Maybe add an option to mkosi.defaults called `AutoBump=yes`. If set after each *successful* build the equivalent of `mkosi bump` would be run.

With all that in place one could run `mkosi build` and it would generate a new version that would be immediately deployable, including for updates.

(Hmm, maybe changes to the unified kernel generation are probably not needed at all, as long as it picks up any updated /usr/lib/os-release file, which it already does)

**Comment by DaanDeMeyer** [comment]
> If this file exists, mkosi reads it and passes it as $VERSION into mkosi.build. If the file doesn't exist, everything happens as it always did. (the mkosi.build scripts would then patch /usr/lib/os-release with this info)

I don't see why this should be done by mkosi.build. Can't mkosi just do this itself? or is the os-release format distro specific? The rest looks good to me.

**Comment by poettering** [comment]
> I don't see why this should be done by mkosi.build. Can't mkosi just do this itself? or is the os-release format distro specific? The rest looks good to me.

I was thinking that various distros have their own os-release-like stuff. i.e. fedora as /etc/redhat-release. And we certainly don't want to edit that, but leave this to people in their own scripts.

There's also the question whether VERSION/VERSION_ID is the right thing to patch or BUILD_ID, i.e. wether the image actually follows verisoning or more a rolling distro of quick rebuilds. i.e. it depends on the project how to update stuff.

**Comment by poettering** [comment]
another usecase: let's say i build an image on top of fedora 33. so i might want generate VERSION_ID on the 33 somehow, but maybe use a different counting myself. i.e. the script might want to write 33.<version> into VERSION_ID as long as fedora 33 is used, and so on.

**Comment by poettering** [comment]
Thinking more about this: I figure, once we have the versioning stuff we also need "mkosi gc" sooner or later, plus an AutoGarbageCollect= option, that will remove old versions from the mkosi.output/ tree. So that the `mkosi.output/` directory won't run full without bounds. In fact, we should enable that GC logic by default, and limit it to keep the last 5 versions or so, by default.

(Hmm, and the SHA256SUMS generation/signing should probably then include the prior versions already found in `mkosi.output/`, so that people can rsync tht tree onto their http server and evreything is properly congruent)
