### ISSUE TITLE
RFE: support building images with only /usr/ hierarchy, but no root dir

### ISSUE THREAD

**Issue by poettering** [systemd/mkosi#634]
I'd like to see a mode supported where mkosi prepares things as it usually does, but instead of putting the whole rootfs into the image actually just puts the /usr part of it in the image, and dropping everything else.

usecase: in systemd we nowadays support setting up /etc and /var and everything else to the minimum necessary if they are not populated. Thus, an image like this could either:

1. mount a tmpfs as root, so that every boot comes up with a freshly initialized /etc and /var (kernel cmdline option `root=tmpfs usr=/dev/by-…`
2. on first boot, from the initrd generate a root partition, for example via a simple `systemd-repart` drop-in, so that that a basic root fs is freshly initialized on first boot, but persists from that point on. (users could then do factory reset, by removing the root partition again, which `systemd-repart` already implements, too)

(`root=tmpfs` is not yet supported by systemd, but i do intend to change that soon)

**Comment by poettering** [comment]
A bit more background on my usecase for tall of this: i eventually want to come to a state where I can use `mkosi` to build images that consist of just:

1. an ESP
2. a read-only /usr/ file system partition
3. a verity partition for /usr/

And then at first boot I want to use `systemd-repart` to add in:
1. A second version of the /usr/ partition, so that A/B updates can work
2. Similar, a second version of the verity partition for /usr.
3. An encrypted root partition, with keys in TPM
4. A /home partition unencrypted, but with dm-integrity based on an HMAC, with keys in TPM (so that the file system is effectively read-only outside of the local system. This partition should then contain `systemd-homed` encrypted home volumes. This scheme avoids double encryption (as `systemd-homed` encrypts anyway), and people can sitll extract their encrypted volumes easily if the system breaks.
5. An encrypted swap partition, with keys in TPM

**Comment by DaanDeMeyer** [comment]
Any thoughts on how to handle non-system users in this scheme? Where do the systemd-homed volumes come from? I really want to setup a little Linux home router based on the scheme you described here eventually where every update comes from running mkosi which is then deployed via casync. I assume we'd add an option to mkosi to initialize regular users as well (optionally with systemd-homed encryption)?

**Comment by poettering** [comment]
> Any thoughts on how to handle non-system users in this scheme? Where do the systemd-homed volumes come from? I really want to setup a little Linux home router based on the scheme you described here eventually where every update comes from running mkosi which is then deployed via casync. I assume we'd add an option to mkosi to initialize regular users as well (optionally with systemd-homed encryption)? My motivation is that I'd need some kind of admin user to avoid having an unlocked root account on the box.

we could add to systemd-firstboot or so a thing that adds a human user, would that work?

**Comment by componentscience** [comment]
On Arch systems the required base package installs many files and directories into /etc and /var. Does the UsrOnly setting move them somewhere in /usr so that they can be moved back or linked on first boot? If so, exactly where?

**Comment by daandemeyer** [comment]
> On Arch systems the required base package installs many files and directories into /etc and /var. Does the UsrOnly setting move them somewhere in /usr so that they can be moved back or linked on first boot? If so, exactly where?

This setting is long gone. These days the equivalent is achieved via repart definition files in mkosi.repart. And no we do not move /etc or /var anywhere, that's up to the user.
