### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#639]
systemd did the same so we should follow suit: https://github.com/systemd/systemd/issues/16834

I'll probably do this tomorrow unless there are any objections.

Instructions to fix local checkouts:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by behrmann** [comment]
I agree and this should hurt nobody. Also, this is where it's going and git will change the default for new repos in March and we're all about modern defaults. :)

**Comment by DaanDeMeyer** [comment]
master branch has been renamed to main

**Comment by behrmann** [comment]
I just noticed, that systemd has a big banner announcing that mater was renamed to main, can we have something like that, too?

**Comment by DaanDeMeyer** [comment]
Can you tell me where systemd has that banner? I haven't noticed anything.

**Comment by behrmann** [comment]
![screenshotsystemd](https://user-images.githubusercontent.com/1044766/105841617-319d5780-5fd5-11eb-93fc-0fd47583f6af.png)

**Comment by DaanDeMeyer** [comment]
Github also shows detailed migration instructions to anyone that visit's the repository. That should be more than enough guidance I think.

**Comment by behrmann** [comment]
Ah, interesting. I somehow did not see *that*.

**Comment by DaanDeMeyer** [comment]
Should show this for visitors: https://github.com/github/renaming/blob/main/rename-default-branch-dialog.png
