### ISSUE TITLE
RFE: Include `systemd-volatile-root` (generator and service) in `initrd`

### ISSUE THREAD

**Issue by NicolasT** [systemd/mkosi#674]
Currently `/usr/lib/systemd/systemd-volatile-root` and `/usr/lib/systemd/system/systemd-volatile-root.service` are not included in the generated `initramfs`. As a result, booting a readonly `gpt_*` image (e.g., `gpt_ext4` created with `--readonly`, or a `gpt_squashfs` image) with `systemd.volatile=yes` added to the kernel command-line fails.

Adding these two files to `DRACUT_SYSYTEMD_EXTRAS` fixes this, at least for CentOS 8 images.

**Comment by DaanDeMeyer** [comment]
This is fine, feel free to make a PR
