### ISSUE TITLE
RFE: AlpineLinux support

### ISSUE THREAD

**Issue by Edu4rdSHL** [systemd/mkosi#677]
Hello, would be awesome to have Alpine Linux support in `mkosi`, they're well-known for being lightweight and other things.

After taking a look, they've an [alpine-make-rootfs](https://github.com/alpinelinux/alpine-make-rootfs) script that is able to automatically package the rootfs in several formats, for example to get a minimal TAR container ready to import with `machinectl` we just need to use:

```
┌─[✗]─[ SecHackLabs /tmp/tmp.L1y954VIV3/apk-tools-2.10.4 ]
└──╼ $ sudo ./alpine-make-rootfs alpine.tar.gz

> Installing system
fetch https://nl.alpinelinux.org/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz
fetch https://nl.alpinelinux.org/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
(1/6) Installing musl (1.2.2-r0)
(2/6) Installing busybox (1.32.1-r3)
Executing busybox-1.32.1-r3.post-install
(3/6) Installing alpine-baselayout (3.2.0-r8)
Executing alpine-baselayout-3.2.0-r8.pre-install
var/cache/misc/alpine-baselayout-3.2.0-r8.pre-install: line 3: can't create /dev/null: Permission denied
Executing alpine-baselayout-3.2.0-r8.post-install
(4/6) Installing busybox-suid (1.32.1-r3)
(5/6) Installing scanelf (1.2.8-r0)
(6/6) Installing musl-utils (1.2.2-r0)
Executing busybox-1.32.1-r3.trigger
OK: 2 MiB in 6 packages
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'

> Cleaning-up rootfs

> Creating rootfs archive
-rw-r--r-- 1 edu4rdshl wheel 970748 Mar 16 22:10 alpine.tar.gz
┌─[✗]─[ SecHackLabs /tmp/tmp.L1y954VIV3/apk-tools-2.10.4 ]
└──╼ $ sudo machinectl import-tar ./alpine.tar.gz alpinelinux
Enqueued transfer job 1. Press C-c to continue download in background.
Importing '/tmp/tmp.L1y954VIV3/apk-tools-2.10.4/alpine.tar.gz', saving as 'alpinelinux'.
Imported 1%.
Operation completed successfully.
Exiting.
┌─[ SecHackLabs /tmp/tmp.L1y954VIV3/apk-tools-2.10.4 ]
└──╼ $ sudo systemd-nspawn -D /var/lib/machines/alpinelinux
Spawning container alpinelinux on /home/edu4rdshl/machines/alpinelinux.
Press ^] three times within 1s to kill container.
alpinelinux:~# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.2
PRETTY_NAME="Alpine Linux v3.13"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
alpinelinux:~# 
```
and the compressed container size is just 948K in this case.

**Comment by poettering** [comment]
does alpine support systemd?

**Comment by Edu4rdSHL** [comment]
It doesn't.

**Comment by behrmann** [comment]
Sorry to hear that. mkosi is a somewhat focussed tool and only supports systemd, but we can take this up again once alpine does support systemd.

**Comment by Edu4rdSHL** [comment]
I doubt that Alpine will support systemd but feel free to close or keep this issue open.

**Comment by DaanDeMeyer** [comment]
I don't see us supporting this unfortunately. We're already dealing with tons of issues as is due to amount of different configurations we support, adding support for a distro that doesn't use systemd seems a bit too much.

(While we can do images without systemd these days with BasePackages, I'd still like for all distros we support to be able to boot using systemd, which wouldn't be possible using alpine).

**Comment by 9001** [comment]
Just chiming in to say I've been working on [alpine-service-mode](https://github.com/9001/asm) which overlaps with a handful of mkosi's usecases. But beware -- it's shellscripts all the way down, and fairly hacky :grin: 

Currently it supports building with qemu (non-root) and/or using podman (as root). And UKI is supported, producing a measured secureboot-signed EFI image which is also bios-bootable, but DDI was not on the to-do list until now.

I first heard of mkosi earlier today thanks to FedoraMagazine. Looking forward to becoming more familiar with it at some point :-)

**Comment by DaanDeMeyer** [comment]
We could probably support alpine these days, it would just not be as well integrated as the distos using systemd. Happy to review PRs to add alpine support.

**Comment by 9001** [comment]
oh awesome! if nobody else picks it up by then I might give it a go some time next year :>
