### ISSUE TITLE
mkosi-2

### ISSUE THREAD

**Issue by keszybz** [systemd/mkosi#68]
I think it'd be about time for a new release... Just a few PRs and bugs outstanding.

**Comment by poettering** [comment]
sounds good to me!

**Comment by vbatts** [comment]
yes please. looking forward to the `--with-networking` flag :-)

**Comment by poettering** [comment]
I tagged v2 right now. Closing.

**Comment by fsateler** [comment]
Version in the program and setup.py is still 1...

**Comment by poettering** [comment]
ah, my bad... hmm, and now? shall i tag v3 with that fixed?

**Comment by poettering** [comment]
and i figure there's no nice way to pick up the version automatically from the newest git tag, eh?

**Comment by AsciiWolf** [comment]
@poettering What about v2.1?

**Comment by lucaswerkmeister** [comment]
> and i figure there's no nice way to pick up the version automatically from the newest git tag, eh?

Well, in principle `setup.py` could do that, right? Not sure if it would be a good idea… (I wouldn’t mind a v3 either FWIW, won’t hurt to have a faster release cycle ;) )

Also, just FYI, I fixed the oversight in the `mkosi` AUR PKGBUILD but the `mkosi-git` package will continue to report version 1 until we push *some* version bump to master.

> What about v2.1?

It looks like systemd and mkosi prefer single-component version numbers, though I don’t know if that rule is set in stone.

**Comment by poettering** [comment]
OK, I rolled v3 now, which is the same as v2, but with the version numbers properly adjusted.

I added a small script for doing releases now, that patches the files and tags the git repo accordingly, so that doing releases is simpler now.
