### ISSUE TITLE
Ensure synchronization between `mkosi qemu` and `mkosi ssh`

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/mkosi#684]
Hello!

In my recent struggles I came across an issue I can't wrap my head around. I'd like to use `mkosi` in a scripted environment (CentOS CI), so for this purpose I run `mkosi qemu` via `systemd-run` (since that ensures `mkosi` doesn't leave the `qemu` process behind when terminated via `SIGTERM`) and then run a couple of arbitrary commands via `mkosi ssh`:

```bash
MKOSI_UNIT="mkosi-build-image-$RANDOM.service"
systemd-run --unit "$MKOSI_UNIT" -p WorkingDirectory="$PWD" -- mkosi "${MKOSI_ARGS[@]}" qemu
systemctl --no-pager -l status "$MKOSI_UNIT"

mkosi "${MKOSI_ARGS[@]}" ssh -o BatchMode=yes "echo 'hello world'"
```

This, however, poses a problem - `mkosi ssh` will fail with `Error: Container/VM interface not found`, since `systemd-run` returns immediately without waiting for `mkosi` to configure the veth interface and spawn the `qemu` process.

Fine, let's "fix" this (I apologize beforehand for the following code):

```bash
MKOSI_UNIT="mkosi-build-image-$RANDOM.service"
systemd-run --unit "$MKOSI_UNIT" \
            -p WorkingDirectory="$PWD" \
            -p ExecStartPost="/bin/bash -c \"while ! /bin/systemd-cgls --unit $MKOSI_UNIT | grep -E '[0-9]+ qemu-kvm '; do sleep 1; done\"" \
            -- mkosi "${MKOSI_ARGS[@]}" qemu
systemctl --no-pager -l status "$MKOSI_UNIT"

mkosi "${MKOSI_ARGS[@]}" ssh -o BatchMode=yes "echo 'hello world'"
```

With this *work of art* `systemd-run` waits until the `qemu-kvm` process pops up in the service's cgroup and then returns. But that's still not enough, since the networking may not be up, causing `mkosi ssh` to fail with `Error: Container/VM address not found`.

Originally I thought about using `mkosi -o ConnectionAttempts=60 ssh` but that doesn't apply in this case either, since the error is thrown by `mkosi`. My current *solution* is to call `mkosi ssh` in a loop for a minute and then eventually give up, but that's not very pretty.

Is there anything else I might have overlooked which would make the `mkosi qemu` and `mkosi ssh` synchronization easier/nicer? For example, Vagrant takes care of waiting for the SSH session during provisioning, so I can simply call `vagrant up; vagrant ssh -c "echo 'hello world'"` without any additional hassle. Something similar in `mkosi` would be definitely welcome.

**Comment by DaanDeMeyer** [comment]
See https://github.com/systemd/mkosi/pull/594 for the absolute mess I got into making sure mkosi ssh waits for the IP address before trying to connect. We can just extend that code to poll for the interface as well. Polling isn't ideal of course but I still need to find some time to figure out how to do netlink properly from Python.

**Comment by mrc0mmand** [comment]
I wonder if it would be enough to just introduce a new option, let's say `--ssh-timeout=`, which would loop for a while in this particular part:

https://github.com/systemd/mkosi/blob/fe30ff39af93aecff2a6dbe48dd5497971cebe3b/mkosi/__init__.py#L6664-L6666

something like:

```python
    timeout = args.ssh_timeout or -1
    dev = None
    address = None

    while timeout > 0:
        stime = time.time()
        # Some exception handling shenanigans
        ....
            dev, address = find_address(args)
        ...
        timeout = timeout - (time.time() - stime)
    else:
        if dev is None or address is None:
            dev, address = find_address(args)
```

(don't look into the code too much, I'm still processing my first coffee...)

This should be fairly easy to implement without having to resort to handling the more low-level stuff.

**Comment by behrmann** [comment]
I think this could be hooked more easily into `find_address` around [here](https://github.com/systemd/mkosi/blob/fe30ff39af93aecff2a6dbe48dd5497971cebe3b/mkosi/__init__.py#L6642), where it already loops with a timeout. :)

**Comment by mrc0mmand** [comment]
> I think this could be hooked more easily into `find_address` around [here](https://github.com/systemd/mkosi/blob/fe30ff39af93aecff2a6dbe48dd5497971cebe3b/mkosi/__init__.py#L6642), where it already loops with a timeout. :)

That would work too, I guess, but it wouldn't cover the scenario where `mkosi qemu` and `mkosi ssh` are run in quick succession, and the veth interface is not yet configured (so the `interface_exists()` [calls](https://github.com/systemd/mkosi/blob/fe30ff39af93aecff2a6dbe48dd5497971cebe3b/mkosi/__init__.py#L6627-L6632) would fail).

**Comment by DaanDeMeyer** [comment]
But can't we just put that logic in a polling retry loop for X seconds?

**Comment by mrc0mmand** [comment]
> But can't we just put that specific logic in a polling retry loop for X seconds just like the IP polling part of that function?

Ah, that should work, I guess!
