### ISSUE TITLE
Add more emojis to the output

### ISSUE THREAD

**Issue by poettering** [systemd/mkosi#703]
I think we are missing a big opportunity by not outputting enough emojis in our build-time logs. At the very least, we should show a piece of cake or so on success.

I mean, something must be wrong with our priorities!

**Comment by keszybz** [comment]
This is an important feature. Mkosi has been reworked to use more systemd tools (systemd-repart, systemd-firstboot, etc.), so we can move the development of this to systemd ;]]]]
