### ISSUE TITLE
Support building as non-root using kernel 5.12 UID mappings

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#716]
Once support lands in systemd-nspawn, we should support running the mkosi build as a non-root user. The biggest advantage I see here is that we can solve the annoyance where files created in directories that are mounted into the build image are owned by root in the host filesystem. With the 5.12 mapping feature, we can make sure all these files are owned by the user running mkosi instead.

**Comment by behrmann** [comment]
Don't we still need root to mount the loopback device to build in?

**Comment by DaanDeMeyer** [comment]
Ah yeah, the title is misleading, I meant non-root the inside the build container.
