### ISSUE TITLE
Idea: add .packages file similar to what kiwi-ng generates

### ISSUE THREAD

**Issue by keszybz** [systemd/mkosi#748]
Kiwi-ng has this nice property that it generates sidecar files that provide metadata about the generated image, see https://osinside.github.io/kiwi/image_types_and_results.html#image-results.

In particular I think the following are interesting:
- `<image-name>.<arch>-<version>.packages`: a sorted list of the packages that are included into the image. In fact this is normalized dump of the package manager database. It follows the following cvs format where each line is represented by: `<name>|<epoch>|<version>|<release>|<arch>|<disturl>|<license>`.
  The format is somewhat clunky, but it works. It could be useful to generate the same for compatibility. Or we could generate a json file.
- `*.changelog`: a concatenated changelog of rpms in the image.

Such metadata makes it easier to figure out "what changed" between image builds. In particular, when packages are pulled through transitive deps it can be very helpful.

**Comment by behrmann** [comment]
That a good idea. If I remember correctly @poettering mentioned this idea already in some comment thinking about more reproducible images. I guess this format is as good as any.

**Comment by poettering** [comment]
i think we should not just have this "manifest" as output, but as input as well, to make things more reproducible, as @behrmann suggested.

See #700.
