### ISSUE TITLE
Do unified kernel image generation (i.e. objcopy invocation) without dracut

### ISSUE THREAD

**Issue by poettering** [systemd/mkosi#752]
I think the objcopy line for combining the kernel image with the initrd and the kernel cmdline is probably something we should do on the host instead of inside the build environment.

Right now, we rely on dracut invoking objcopy for us. However, I think that is less than ideal:

1. It means we strictly have to use dracut for initrds, but I think we should add support for other options (right, @keszybz ;-))
2. objcopy needs to be installed in the final image, so that dracut can install it, objcopy means binutils which is pretty clearly a development package, and it kinda sucks that it's kind the only tool we need to install in the final image too, just because of this. If mkosi instead of dracut combines the initrd + kernel via objcopy this means we can do this host side, and thus require no deps inside the container for it.
3. this would allow us to move building of initrds from the 2nd phase of build to the 1st phase in more cases. Currently it was done in phase 2 in particular when verity was used, because in that case the top hash of the verity image must be included in the kernel cmdline embedded into the image and that is only known at the end of the 2nd phase. But given that this hash actually is only needed for the objcopy invocation and not already for the initrd generation, we can do building of the initrds in phase 1. This also means we no longer would have to install dracut at all in the 2nd phase of the boot.
4. It might make sense to support upstream distro pre-generated initrds one day, i.e. where the cpio is already complete, and we then just need to combine it with a kernel cmdline and sign it afterwards. in this mode we'd not need dracut at all anymore, and the objcopy step we do ourselves would suffice entirely.

**Comment by brpatel12** [comment]
Hi @poettering - until this get's added to mkosi, is there a suggested workaround to use objcopy directly (as opposed to dracut)?

**Comment by behrmann** [comment]
You could probably do that in a build or finalise script - dracut would still be run - but you could do your own thing on top.

**Comment by keszybz** [comment]
Fixed by 683268367374e7c1c659af38b575ab0ad0c1088b.
