### ISSUE TITLE
gitignore logic doesn't grok git submodules

### ISSUE THREAD

**Issue by doverride** [systemd/mkosi#76]
1. theres a typo that breaks postinst:

-- arg.postinst_script = value
++ args.postinst_script = value

2. the git ls-files does not work with submodules (--recurse-submodules doesnt work with --others):

-- c = subprocess.run(['git', 'ls-files', '-z', '--others', '--cached',
++ c = subprocess.run(['git', 'ls-files', '-z', '--recurse-submodules', '--cached',

**Comment by lucaswerkmeister** [comment]
Re 1: #77

Re 2: well, apparently we would lose some functionality with that… until git supports other modes with `git ls-files --recurse-submodules`, perhaps you could specify `--use-git-files=no`?

**Comment by doverride** [comment]
Re 2: havent tried --user-git-files=no, i might try it one of these day's and yes you'd lose --other with --recurse-submodule. was not expecting you to accept my hack, just saying though.

**Comment by doverride** [comment]
maybe git ls-files is not the right tools for the job, maybe some other solution is possible?
either way. i am good, just giving a heads-up

**Comment by poettering** [comment]
I changed the title of the issue given that only the git submodules issue remains

**Comment by keszybz** [comment]
I looks like the proper place to fix this would be git itself... C.f. the meson issues with `dist` target — same problem, same solution.

**Comment by doverride** [comment]
This issue seems to have been fixed with `copy_git_files()`
