### ISSUE TITLE
Specifiy release versions

### ISSUE THREAD

**Issue by brpatel12** [systemd/mkosi#767]
Hi, I'm trying to download a specific version `efitools`.
- I generated a `.raw` file with `sudo mkosi` and launched it via `qemu`.
- Ran `sign-efi-sig-list --verison` which output `1.8.1`.
- The [repo](https://git.kernel.org/pub/scm/linux/kernel/git/jejb/efitools.git) says the latest version is `1.9.2`.
- Running `apt-cache policy efitools` on my desktop yields:
```
efitools:
  Installed: 1.9.2-1
```

Is there a way to specify version number in `mkosi.default` or elsewhere? Any tips as to why I'm getting an old version?
```
$ mkosi --version
mkosi 5
```

#mkosi.default
```
[Distribution]
Distribution=ubuntu
Release=focal
Repositories=main,universe,restricted

[Output]
Bootable=yes
BootProtocols=uefi
Hostname=test
Output=test.raw
OutputDirectory=output

[Packages]
WithDocs=true
WithNetwork=yes
Packages=
        efitools=1.9.2
        efibootmgr

[Partitions]
RootSize=5G
HostSize=2G

[Validation]
Password=dummy
```
```
E: Version '1.9.2' for 'efitools' was not found
```

**Comment by brpatel12** [comment]
Tried this with `mkosi 10` as well.

**Comment by behrmann** [comment]
The problem is
```
[Distribution]
Distribution=ubuntu
Release=focal
```
where [1.8.1](https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/efitools_1.8.1-0ubuntu2_amd64.deb.html) seems to be the packaged version. You need to go for a newer Ubuntu release (or different distro) if you want newer packages. :)

**Comment by behrmann** [comment]
>     * I saw from a closed bug that LUKS support was added with a passphrase. Is there support for using a keyfile?

Don't think so, if it's not in the docs, but patches welcome! :)

>     * I cannot add `nvidia-driver-470` to `Packages=`, keeps saying not found. Any tips here?

Have a look on your Ubuntu machine with `apt-cache policy` from which repository apt wants to take that package. Might be that it's a repository that we don't include, if that's the case you will have to add the `.list` file for that repo to `/etc/apt/sources.list.d` in the image.

**Comment by brpatel12** [comment]
Gotcha. Sorry if this is answered elsewhere, but what is the `.list` file 

```
  Version table:
     470.57.02-0ubuntu1 600
        600 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     470.57.02-0ubuntu0.20.04.1 500
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages
     470.42.01-0ubuntu1 600
        600 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
```

**Comment by behrmann** [comment]
`/etc/apt/sources.list` is where all the repositories are listed, that apt searched. It also looks for additional files `/etc/apt/sources.list.d/*.list` to complement this. This is were admins can add further repositories by adding files with the appropriate config.

The output above tells me, that the drivers are, as I could have guess, since they are non-free, in the repo `focal-updates/restricted` (and the top-priority repo is an nVidia one, that doesn't even seem to belong to Canonical). Neither of which we add, you will have to do that yourself. 

If your question is answered I'd be much obliged if you closed the issue. :)

**Comment by brpatel12** [comment]
One more followup! This suggestion is for _after_ mkosi builds the `.raw` file or would this be part of that build process?

**Comment by brpatel12** [comment]
@behrmann I closed the ticket, but still would like to know if it's possible to add that to the image as part of the build, or it it has to be done after installation.Thanks!

**Comment by behrmann** [comment]
Sorry, forgot to answer here. You can add the files during the build, since you want apt to see it, `--skeleton-tree` is probably what you want. If not, you could also do it via a script during the build phase.
