### ISSUE TITLE
Mkosi no respecting command line arguments after the `build` verb in release >=10 but the build verb is mandatory as well

### ISSUE THREAD

**Issue by Edu4rdSHL** [systemd/mkosi#771]
Hello, I'm having the issue mentioned with the latest mkosi release, I have the `Output=` directive set in my `.default` file but mkosi doesn't respect it and instead creates a `image.${format}` file in my current dir.

How to reproduce:

1. Download any template from [mkosi-definitions](https://github.com/nspawn/mkosi-definitions), I will use [archlinux-tar.default](https://github.com/nspawn/mkosi-definitions/blob/master/archlinux-tar.default)
2. Run: `/usr/bin/mkosi build  --default archlinux-tar.default  --force --postinst-script=archlinux.postinst --cache=archlinux.cache`
3. mkosi will create the image file in the current dir instead of the path specified in the `Output=` directive.

Regards,
Ed

**Comment by iam-TJ** [comment]
Your link "archlinux-tar.default" actually points to "bionic-tar.default" but that is incidental.

There is no ConfigFile `Output` key; there is `OutputDirectory` though:

https://github.com/systemd/mkosi/blob/80c8f985aceb99e1ad0500eb302fe0d4bad7a38e/mkosi/__init__.py#L4474

`mkosi::process_settings()` did handle `Output` up to v5 but was removed (https://github.com/systemd/mkosi/pull/330/commits/a45d911f742cd3954a6fc2f8a61e93bc250be368) for v6 in April 2019.
https://github.com/systemd/mkosi/blob/03ef94705d9098f3328a7653b372887fa828fbac/mkosi#L3324

**Comment by Edu4rdSHL** [comment]
Hey, @iam-TJ, thanks for your answer. According to `man mkosi` there's an `Output=` key inside the `[Output]` section, I have tried setting `OutputDirectory=/srv/www/nspawn.org/public/storage/archlinux/archlinux/tar/` in the `.default` file but the result was exactly the same, the artifacts are created in my current dir instead of the specified one.

**Comment by Edu4rdSHL** [comment]
Any comments about it? @DaanDeMeyer @keszybz @poettering

**Comment by DaanDeMeyer** [comment]
Ignoring all arguments after the "build" verb is intentional, the "qemu", "shell" and "boot" verbs work the same. Any arguments passed after "build" are passed to the build script.
