### ISSUE TITLE
No space left on device when installing multiple ubuntu packages

### ISSUE THREAD

**Issue by nandra** [systemd/mkosi#775]
Hello,

I'm building mkosi image with mutliple ubuntu packages added on top. During image creation I'm getting:
```
Unpacking libconsole-bridge-dev:amd64 (0.4.0+dfsg-2) ...
dpkg: error processing archive /tmp/apt-dpkg-install-FDpfAf/536-libconsole-bridge-dev_0.4.0+dfsg-2_amd64.deb (--unpack):
 cannot copy extracted data for './usr/include/console_bridge/console.h' to '/usr/include/console_bridge/console.h.dpkg-new': failed to write (No space left on device)
tar: ./triggers: Cannot write: No space left on device
tar: Exiting with failure status due to previous errors
```

When I decrese number of packages image is build. Is there any setting I can use to increase memory footprint in mkosi? Thanks.

**Comment by poettering** [comment]
Use the `RootSize=` setting in mkosi.default or `--root-size=` on the command line to increase the rootfs size.
