### ISSUE TITLE
rename UseSystemRepositories= → UseHostRepositories=?

### ISSUE THREAD

**Issue by poettering** [systemd/mkosi#808]
For my reasoning, see:

https://github.com/systemd/mkosi/pull/732#issuecomment-917148152

But maybe I totally misunderstand what the option is supposed to do. if it does something else than I assume, then it should really get better docs though.

**Comment by ray-sit** [comment]
No, you are right, the term Host is more accurate. I can see how System can be misleading as it is too broad. Added the PR to rename it.

**Comment by poettering** [comment]
CLosing as #810 has been merged.
