### ISSUE TITLE
RFC: Rocky Linux Support

### ISSUE THREAD

**Issue by dellgreen** [systemd/mkosi#811]
Has anyone tested building Rocky Linux at all?
Would it be a matter of targeting a Centos8 build and swapping out the repos at an early stage of the build?
Or would it be better to add  proper support?

https://rockylinux.org/

**Comment by keszybz** [comment]
Proper support please. It should be a matter of having a different set of repos, but otherwise sharing all of the other code.

**Comment by dellgreen** [comment]
Ok working on it now, if all goes well, then I'll add a separate ticket to add Alma Linux as it should follow the same principal.
