### ISSUE TITLE
Enable sticky bit on /tmp on Ubuntu

### ISSUE THREAD

**Issue by lights0123** [systemd/mkosi#838]
This is required for many graphical things, e.g. GDM. Ubuntu doesn't use tmpfs on /tmp by default, so it requires the sticky bit to be set on the actual folder in the image—which mkosi doesn't do. tmpfs can be enabled with `systemctl enable /usr/share/systemd/tmp.mount`, but that's not the Ubuntu standard method.

**Comment by poettering** [comment]
tmpfiles.d adjusts this automatically on boot if needed. Doesn't that work for you?

If we can be sure that the directory is overmounted I think it would make sense to give it access mode 0400 actually, to ensure noone writes there before /tmp is mounted, but if we cannot be sure of that we should probably make it world writable + sticky.
