### ISSUE TITLE
Merged-usr not supported under Ubuntu

### ISSUE THREAD

**Issue by AsciiWolf** [systemd/mkosi#84]
Ubuntu version of Debootstrap does not support the _--merged-usr_ flag.

`E: unrecognized or invalid option --merged-usr`

**Comment by keszybz** [comment]
This option was added in debootstrap-1.0.83, September 2016. Ubuntu has 1.0.81. Shouldn't they just upgrade?

**Comment by keszybz** [comment]
https://bugs.launchpad.net/ubuntu/+source/debootstrap/+bug/1685873

**Comment by AsciiWolf** [comment]
It looks like the issue was [fixed](http://changelogs.ubuntu.com/changelogs/pool/main/d/debootstrap/debootstrap_1.0.90ubuntu1/changelog) in Ubuntu 17.10.
