### ISSUE TITLE
Support custom partitions and partition order

### ISSUE THREAD

**Issue by trittsv** [systemd/mkosi#866]
### Add custom partitions 

I have to following mkosi file.
```
[Distribution]
Distribution=ubuntu
Release=focal

[Output]
KernelCommandLine: systemd.volatile=overlay
ReadOnly=yes

[Partitions]
RootSize=8G
SwapSize=1G
```
This creates an image which mounts root as "Read-Only" with a Ram-Overlay.
The result is a hardend system which is powerfailure safe, no files can be corrupted.
All file changes are gone after a reboot.

#### Problem:

You may want to store some persistent data anyway on a separate partition.
Some examples:
- User settings like language which should survive a reboot
- Touch driver calibration files which should survive a reboot
- etc...

#### Solution

A custom partition which is mounted as "rw" where the applications can store some persistent data.
But currently there is no mechanism to do this with mkosi.

I think it would be a great enhancement for mkosi when i could simple add some custom partitions on the fly like the partitions for Root, Srv, Swap, etc via a simple configuration entry in a mkosi file.

Sadfully systemd-repart is not available on all distributions like ubuntu which could solve this problem too.

#### Implementation

Implementation suggestion by @poettering :
Simple mechanism for adding in additional sfdisk lines via some drop-in file "mkosi.sfdisk".

**Comment by behrmann** [comment]
Well, the canonical solution would be systemd-repart and its lack in Debian and its derivatives is quite problematic in that regard, since we can't add the same logic mkosi and adding some crutch to work around repart missing will be only that. 

The [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=976959) to package repart in Debian has been open for a while and depends on the resolution of the gnutls vs openssl. Something about that was on the systemd mailing list recently, but I have to reread it to remember what if anything was decided there. 

I do think that getting repart into Debian (and that flowing into Ubuntu) would be the best solution for this problem. Alas, I don't think it will be fast. 

This just as my two cents, I'd be happy to hear about different perspectives to this problem.

**Comment by behrmann** [comment]
From a non-mkosi workaround angle: You can also add partitions to the image after mkosi is done with it and you could probably do that in a finalise script.

**Comment by trittsv** [comment]
So far i did not tried to create a partition in the "mkosi.postinst" file because i dont understand yet how mkosi handles partitions in general.
For example there are no entries in `/etc/fstab` for the swap and root partition which confuses me.
But may you can give me the crucial hint?

**Comment by trittsv** [comment]
@behrmann another perspective on this problem:
The name of the section "[Partitions]" in mkosi.default is a little bit misleading, it suggests (for non-pro mkosi users) that this is a place where partitions can be handled generally.
But it seems that this is only a place where partitions for system folders can be created/configured.

**Comment by behrmann** [comment]
> So far i did not tried to create a partition in the "mkosi.postinst" file because i dont understand yet how mkosi handles partitions in general. 

I was actually thinking about `FinalizeScript=` (or `mkosi.finalize`).

> For example there are no entries in `/etc/fstab` for the swap and root partition which confuses me. But may you can give me the crucial hint?

systemd can find these on its own via the [discoverable partitions scheme](https://systemd.io/DISCOVERABLE_PARTITIONS/).

**Comment by behrmann** [comment]
In good news [systemd-repart doesn't require openssl](https://github.com/systemd/systemd/blob/main/NEWS#L696) starting with systemd v250. I think this was the main blocker for its inclusion in Debian, so we can hope that Debian enables repart going forward, shortly after which it would end up in Ubuntu.

**Comment by DaanDeMeyer** [comment]
Custom partitions are supported via systemd-repart, so let's close this issue
