### ISSUE TITLE
Support mkosi integration tests

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#876]
In the beginning of January, we'll have an intern starting who will be working on improving mkosi's testing infra. The primary goal is to have more tests in general, which will help catch regressions and help us map out what currently works and what doesn't work.

To make writing mkosi integration tests a productive and pleasant experience, I figure we should at least make the following easy:

- Allow easily building customized images for a test
- Boot the test's image in shell, boot, or qemu mode
- Provide easy ways to make assertions from either the outside or inside perspective of the booted image
- Properly clean up everything when the test is done

## Provide easy ways to make assertions from either the outside or the inside perspective of the booted image

I'll start with a dump of all the possible ways I could think of this working

### Run tests exclusively outside the booted image with SSH/serial access to the booted image

Practically, this would mean all of our assertions would go over SSH, which would mean we'd mostly make use of unix commands over SSH to retrieve information on the running image. SSH also allows us to use `busctl` to run D-Bus commands inside the container and get their output. 

### Allow running tests "inside" the booted image by moving namespaces

When using containers (shell/boot verbs), it should theoretically be possible to move the test process initially running outside the container into the namespaces of the container image (except pid/user). This means we could have the test set everything up and then move the test into the container namespaces, after which it should theoretically be able to interact with the container image as if the test was running inside the container image. I'm not all too sure how the Python interpreter would deal with the filesystem being replaced from under its feet though, especially when the python versions mismatch between the host and the container image. On top of that, this solution wouldn't work from VMs.

### Run the entire test in the container image

Using SSH or pexpect, we could run the test script inside the container image and run it using the Python interpreter installed into the test image. This requires making the test files available in the test image but we already support this using --source-transfer-final. We'd then need a little glue similar to the current boot test script using pexpect that builds the image, waits for it to boot and when a prompt becomes available, runs the given command, raises an exception if it returns a non-zero exit code and shuts down the image.

## Proposed solution

A combination of solution 1 and 3 seems the most promising. Tests that don't need to run inside the image would be able to run on the host using SSH access while those tests that do need internal access get copied into the test image and executed over SSH or pexpect.

We should abstract common boilerplate as a subclass of unittest.TestCase or a pytest fixture. This subclass/fixture would take care of building the image and shutting it down, doing cleanup after the test finishes. For each custom test image, we'd have a separate directory containing the test(s) and all the mkosi files required to build the test image. To speed up building images, we should have a shared base image which will be cached. All custom test images will then be built from this cached base image. Some modifications might be needed to allow building from a shared cached image (optionally concurrently). 

To support running tests inside a booted image, we could need some unittest/pytest magic that checks for a custom prefix in the test name indicating it should run inside the booted image. Another option would be to use a decorator. All such tests would be executed using pexpect/SSH in the booted image. Optionally, we could try to use the moving namespaces solution if we're working with a container to allow for better error reporting. If we're working with a VM, we'd run the test method over SSH and fail the test on a non-zero exit status.

We should also expose a config option to allow running tests without any setup so that when debugging, developers can start the mkosi image manually and run tests manually inside the booted image. 

Depending on how much code we end up with that can be reused, we could consider properly exposing the testing stuff so that we can reuse it in systemd as well.

We'll also need to decide whether we want to stick with pytest or use unittest instead. pytest has the pytest-xdist plugging to support running tests concurrently which could be handy. On the other hand, pytest supports running unittest style tests so we might want to avoid choosing and write tests in unittest style so they can be used with either test runner.

This turned into a bit of a brain dump. I'll probably add more information to this later and improve formatting but this seems like a decent start. Any comments on the design or concerns about stuff I forgot to consider would be greatly appreciated.

**Comment by bluca** [comment]
For complex unit tests I'd suggest adopting an existing test framework rather than reinventing, there's plenty available

**Comment by DaanDeMeyer** [comment]
> For complex unit tests I'd suggest adopting an existing test framework rather than reinventing, there's plenty available

I mentioned using either python's unittest or just sticking to pytest which is already used in mkosi. Is that what you hand in mind when you say test framework?

**Comment by bluca** [comment]
There are higher level tools which allow to avoid reimplementing things like pattern matching over ssh with pexpect, like the robot test framework and others

**Comment by DaanDeMeyer** [comment]
> There are higher level tools which allow to avoid reimplementing things like pattern matching over ssh with pexpect, like the robot test framework and others

I'd only consider pexpect + pattern matching a fallback if we have no other option though, e.g. for bootloader stuff. I assume that for systemd itself a lot of testing would happen over D-Bus (or varlink) or by calling the corresponding CLI program and checking the status code or output if it's simple or if there's a --json switch. A lot of D-Bus calls can be executed remotely over SSH so we don't necessarily need direct access to the image. And with D-Bus replies we wouldn't need pattern matching either to check the results.

**Comment by DaanDeMeyer** [comment]
We have this implemented now. See mkosi/machine.py and test/test_machine.py for more information

**Comment by gsegatti** [comment]
Not sure anyone's gonna see this since the issue is closed. But are we using the `machine.py` for testing anywhere? Curious because I remember @DaanDeMeyer mentioning it could be used in systemd.

**Comment by behrmann** [comment]
Yes, in `test/test_machine`, which is run by the `integration-test` workflow.

**Comment by DaanDeMeyer** [comment]
We don't use it in systemd yet, needs a bit more work for that to be possible
