### ISSUE TITLE
overlay absolute path failure

### ISSUE THREAD

**Issue by vbatts** [systemd/mkosi#88]
on this line https://github.com/systemd/mkosi/blob/master/mkosi#L2452

`+/root/src::/root/src` fail with `Overlay path +/root/src is not absolute.`

Produced when running `sudo mkosi --with-network -t raw_squashfs`
on a fedora-25 box (systemd-nspawn 231)

**Comment by poettering** [comment]
@vbatts yeah, that needs a newer systemd version...

**Comment by vbatts** [comment]
bugger. I'm seeing this 5th paragraph in systemd-nspawn.1 man page. Bummer
to depend on not compatible new behavior.

**Comment by poettering** [comment]
So, the feature is kinda important, and only available in v233, and the dep is documented. I agree it's annoying, but I don#t see how to solve this otherwise...

Closing this hence. Sorry!
