### ISSUE TITLE
ubuntu: build kernel with different config

### ISSUE THREAD

**Issue by Ismael-98** [systemd/mkosi#888]
# Build Kernel With Different Config

Hello all,

My team is currently generating an OS image using Mkosi that has secure boot enabled and with an immutable root-fs. When building the image, there is a mkosi.postinst binary that we run that polishes up the image before the root-fs is sealed.

My team now wants to add support for a driver that is not part of the in-tree kernel modules. In order to support this new driver, we are thinking of signing out-of-tree modules, and we will have the public key baked into the kernel. 

## The Issue
The issue that we are running into is that the kernel that is compiled does not include our public key in it's builtin_trusted_keys keyring, even after we've modified the `/usr/src/linux-headers-<kversion>-generic/.config` file so that the `CONFIG_SYSTEM_TRUSTED_KEYS` value is set to the public key certificate we want to be part of the system keyring. 

## Question
My question is, what tools/configurations are available so that we can make changes to the kernel configuration file, and those changes will be honored by the compiled kernel? The main change we want to make is change one value in the configuration file.

**Comment by behrmann** [comment]
I'm not entirely sure I understand your problem, so just to make sure:
- You add your key to the kernel sources
- You rebuild the kernel
- You rebuild the initrd
- You seal your rootfs

but your key is missing from the kernel keyring afterwards?

**Comment by Ismael-98** [comment]
Hi behrmann,

Thank you for getting back to me!

The steps that you listed is what I'm trying to do, but I haven't had any luck so far in accomplishing that. What I've done so far is include the key in the root-fs before the kernel is built by mkosi. But I've only been able to modify the kernel configuration file in the mkosi.postinst script that my team runs. However, it seems that by the time we modify the kernel config, the kernel has already been built, so it does get built with the right configuration that would allow us to add the key to the kernel keyring.

The main issue for us is then, how can we modify the kernel configuration file, so that when mkosi builds the kernel, the configuration we want is used instead of the default one? Would we have to modify the kernel using a script that get's called before mkosi builds the kernel? If so, is that already an option that is available (a flag or something like that)?

I guess ideally the flow that I'm trying to describe is like this:

1. Call Mkosi so that it fetches the kernel sources
2. Run script that adds the key to the kernel sources and updates kernel config.
3. Mkosi builds the kernel and initrd
4. Mkosi continues it's normal flow.

**Comment by behrmann** [comment]
Just to clarify: mkosi generally doesn't build the kernel by itself, but installs the distro package. The only place where this might be different (I don't remember the code from the top of my head) is Gentoo, but even that uses a binary cache if I remember correctly. If you need the kernel build, you need to add a build script that does that.

**Comment by Ismael-98** [comment]
Oh that makes sense. I have one last question. Do you know of any limitations that would prevent us from running the kernel build logic inside the mkosi.postinst script we already have in place? So the following logic would be added:

1. Change the config for the kernel
2. Rebuild the kernel
3. Sign the new kernel (we need to do this step because our OS images have secureboot enabled).
4. And replace the kernel that comes with the distro package with the new kernel.

Do you see any issues with us adding that logic to our mkosi.postinst script, or would that logic have to be added in a different script (e.g the mkosi.build script)?

**Comment by behrmann** [comment]
> Do you see any issues with us adding that logic to our mkosi.postinst script, or would that logic have to be added in a different script (e.g the mkosi.build script)?

No, not really. I think that should work. Depending on what your initrd is, remember to regenerate that.

**Comment by Ismael-98** [comment]
Thank you so much for your help.

 I just had one last question that just came up. Since we want to have secure boot enabled for the OS image we created, do you know if we have to sign the new kernel and initrd with the secure boot private key ourselves, or would that be handled by MKOSI. For clarification, I just wanted to know if MKOSI signs the kernel and the initrd as soon as the distribution is installed (i.e before the mkosi.postinst script is run). Or does MKOSI sign the kernel and everything else during the Finalize stage (i.e. when the mkosi.finalize script is run).

**Comment by behrmann** [comment]
mkosi signs all `.efi` binaries add the end. Have a look at the function `secure_boot_sign` in `__init__.py`.

**Comment by Ismael-98** [comment]
Great!!! Thank you so much in helping me work through this problem! I will close this issue.
