### ISSUE TITLE
mkosi misdetects kvm availability

### ISSUE THREAD

**Issue by vt-alt** [systemd/mkosi#914]
We had [accidental boot failures](https://github.com/lkrg-org/lkrg/issues/132#issuecomment-1048134856) on GA for `mkosi qemu` [like this](https://github.com/lkrg-org/lkrg/runs/5259672421?check_suite_focus=true):
```
‣ Running command:
‣ qemu-system-x86_64 -machine type=q35,accel=kvm,smm=off -smp 2 -m 1G -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0,id=rng-device0 -cpu host -nographic -nodefaults -serial mon:stdio -vga virtio -drive if=none,id=hd,file=/home/runner/work/lkrg/lkrg/image.raw,format=raw -device virtio-scsi-pci,id=scsi -device scsi-hd,drive=hd,bootindex=1 -no-reboot

7lSeaBIOS (version 1.13.0-1ubuntu1.1)
Booting from Hard Disk...
[    0.0KVM: entry failed, hardware error 0xffffffff
...
Error: Process completed with exit code 1.
```
This is because mkosi tries to boot with KVM but [GA does not have KVM support](https://github.com/actions/virtual-environments/issues?q=kvm). In turn this is because mkosi misdetects availability of KVM just by presence of `/dev/kvm` like this:
```
mkosi (main)$ git grep -e has_kvm -e accel
mkosi/__init__.py:    has_kvm = os.path.exists("/dev/kvm")
mkosi/__init__.py:    accel = "kvm" if has_kvm else "tcg"
mkosi/__init__.py:        f"type=q35,accel={accel},smm={'on' if fw_supports_sb else 'off'}",
mkosi/__init__.py:    if has_kvm:
```
I suggest better detection mechanism — open `/dev/kvm` for reading and if it fails there is no KVM support.

**Comment by behrmann** [comment]
Thanks for the detailed bug report!

Will this be as simple as this
```python
try:
    with open("/dev/kvm"):
        has_kvm = True
except:
    has_kvm = False
```
or is something else necessary?

**Comment by vt-alt** [comment]
Looks good!
