### ISSUE TITLE
Environment variables missing for postinst script. 

### ISSUE THREAD

**Issue by Cornelicorn** [systemd/mkosi#937]
According to the [docs](https://github.com/systemd/mkosi/blob/main/mkosi.md) the environment variables should be also passed to the `postinst` script. However, if I try to do this in a simple test setup, the environment variables are not set.

This is my `mkosi.default`
```
[Distribution]
Distribution=arch
Mirror=https://mirror.fra10.de.leaseweb.net/archlinux/

[Output]
Format=directory
Output=env-test

[Packages]
Packages=
    bash

[Content]
Environment=
    TEST1=abc
```
and `mkosi.{prepare,postinst}` are:
```
#!/bin/bash

echo $TEST1
```

In the output I just get
```
‣  Mounting Package Cache
‣  Running prepare script…
abc
‣  Unmounting Package Cache
‣  Mounting Package Cache
‣  Running postinstall script…

‣  Unmounting Package Cache
```

A `printenv` also does not show the `TEST1` variable during `postinst`.

I also don't see that the environment variables are actually passed on in [run_postinst_script](https://github.com/systemd/mkosi/blob/main/mkosi/__init__.py#L3353#L3383) like they are in [run_prepare_script](https://github.com/systemd/mkosi/blob/main/mkosi/__init__.py#L3343) or [run_build_script](https://github.com/systemd/mkosi/blob/main/mkosi/__init__.py#L7190).

**Comment by Cornelicorn** [comment]
I installed mkosi from master as a zipapp.

**Comment by behrmann** [comment]
You are right, the calls to `run_workspace_command` in `run_prepare_script` and `run_postinst_script` are missing the `env` parameters. Cann you have a look whether #938 addresses your issue?

**Comment by Cornelicorn** [comment]
> You are right, the calls to `run_workspace_command` in `run_prepare_script` and `run_postinst_script` are missing the `env` parameters. Cann you have a look whether #938 addresses your issue?

Yes, this is working :+1:
`run_prepare_script` was not missing the environment variables though, they are included from `nspawn_params = nspawn_params_for_build_sources(args, SourceFileTransfer.mount)` in [L3343](https://github.com/systemd/mkosi/blob/main/mkosi/__init__.py#L3343).

**Comment by behrmann** [comment]
Ah, yeah, misread your description, pushed an updated version just for postinst.

**Comment by Cornelicorn** [comment]
`0de60ba361efd39da000e6243eac0cd560299e44` is also working
