### ISSUE TITLE
bmap file is being created after compression

### ISSUE THREAD

**Issue by gsalvatella** [systemd/mkosi#950]
Using `--bmap` and `--compress-output=xz` flags together, I was expecting the `.bmap` file to be created on the raw image and the compression to take place thereafter. Instead I get the following output:
```
‣ Compressing output file /home/user/images/.mkosi-v92rp6c8...
‣ Creating BMAP file...
bmaptool: WARNING: all 330.8 MiB are mapped, no holes in '/home/user/images/.mkosi-jy908gzc'
bmaptool: WARNING: was the image handled incorrectly and holes were expanded?
```
When using `bmaptool copy` I then get an error
```
bmaptool: ERROR: checksum mismatch for blocks range 0-84687: calculated 4c4cb38c90709a58fb4696e2c87663bc2644009100da275a6f492017e9524b8f, should be 7a22c8bf1bf56316b5adfdbabbcf4b5f62a9ab6544b1065bf0ad7b8c1b27e28a (image file image.raw.xz)
```
Is there a reason for this? Should I be creating the raw image first without compression and compress it manually afterwards?

```shell
mkosi --version
mkosi 10
```

**Comment by gsalvatella** [comment]
The bmap file must be created before compression since bmap needs to know where the "holes" of the image are. After compression the holes are gone and bmap complains with the "no holes found" warning.

>  Does this work if you don't have mkosi compress the output image?

Yes, the `--bmap` flag works fine. The compression step should simply come thereafter.

**Comment by behrmann** [comment]
> Be aware if you are running on a ZFS partition, you need to set a ZFS property, instructions are in the docs.

Just out of morbid curiosity about the world of out of tree modules: what would the proper incantations be?

**Comment by dellgreen** [comment]
> > Be aware if you are running on a ZFS partition, you need to set a ZFS property, instructions are in the docs.
> 
> Just out of morbid curiosity about the world of out of tree modules: what would the proper incantations be?

I added the incantations here:

https://github.com/intel/bmap-tools#zfs-file-system

:)

**Comment by behrmann** [comment]
Closing thanks to #994
