### ISSUE TITLE
chattr on xfs

### ISSUE THREAD

**Issue by vbatts** [systemd/mkosi#96]
trying to build casync, on fedora 25 host.

`mkosi build` fails due to
`chattr +C /home/vbatts/src/github.com/systemd/casync/.mkosi-kbs2v8b4` returns non-zero.
And swallows a message like `chattr: Operation not supported while setting flags on /home/vbatts/src/github.com/systemd/casync/.mkosi-kbs2v8b4`

systemd version: 231
mkosi version: mkosi-1-1.fc25.noarch

**Comment by poettering** [comment]
hmm, the current code in mkosi explicity sets check=False when invoking the chattr binary...

**Comment by sebix** [comment]
I can confirm that it works on XFS now (bot on Fedora, but on tumbleweed)

**Comment by fsateler** [comment]
Yes this was fixed by https://github.com/systemd/mkosi/pull/38

**Comment by vbatts** [comment]
cool thanks!
