### ISSUE TITLE
New release (13)

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#965]
I've gotten a few requests for a new release so I figure it's time to release mkosi 13. Do we have anything that needs to happen before we can do a new release?

**Comment by behrmann** [comment]
I don't think there's anything super pressing, but  landing #946 and #958 would be nice for the release. Also #907 and #926 were basically ready, no?

**Comment by coling** [comment]
I've just submitted #993 which is a fairly major blocker for using mkosi on a Fedora 36 host as far as I can tell.

**Comment by gsalvatella** [comment]
https://github.com/systemd/mkosi/issues/950 seems to be a bug to me. Can you confirm?

**Comment by malt3** [comment]
Would love to get #999 in. Very simple fix to get verity auto configuration working again.

**Comment by brpatel12** [comment]
#990 as well if possible!

**Comment by DaanDeMeyer** [comment]
Aside from what's already mentioned, I'd like for all my open PRs to go in the next release as well.

**Comment by DaanDeMeyer** [comment]
Everything I wanted in is now merged so from my end we're good to go.
