### ISSUE TITLE
don't patch nsswitch on Arch guest

### ISSUE THREAD

**Issue by gdamjan** [systemd/mkosi#97]
Arch already comes with nss_resolve enabled
https://git.archlinux.org/svntogit/packages.git/tree/trunk/nsswitch.conf?h=packages/filesystem

the patching in 
https://github.com/systemd/mkosi/blob/master/mkosi#L678
results in `hosts: files mymachines resolve [!UNAVAIL=return] resolve myhostname`

Ideally it should not patch nsswitch if resolve is already enabled.

**Comment by poettering** [comment]
Patch would be very welcome for this
