### ISSUE TITLE
[question] qemu integration tests

### ISSUE THREAD

**Issue by nlacombe42** [systemd/mkosi#991]
i have been playing with the codebase a bit.
but i don't know much about python so i might be making errors that seems obvious to people who know python (keep that in mind).

i am trying to create an integration test that uses qemu.

i added `super().__init_subclass__(["qemu"])` to the existing `MkosiMachineTestCase` class :
```diff
diff --git a/tests/test_machine.py b/tests/test_machine.py
index 6555bc9..909f6ad 100644
--- a/tests/test_machine.py
+++ b/tests/test_machine.py
@@ -16,6 +16,7 @@ pytestmark = [
 class MkosiMachineTestCase(MkosiMachineTest):
     @classmethod
     def setUpClass(cls) -> None:
+        super().__init_subclass__(["qemu"])
         super().setUpClass()
 
         if cls.machine.args.distribution == Distribution.centos_epel and cls.machine.args.verb == Verb.qemu and not cls.machine.args.qemu_kvm:
```

and then ran `sudo pytest -s ./tests/test_machine.py`
but when the test starts qemu it eventually prints the error you can see below.
it keeps printing that error for a while (i killed the process after waiting for ~10s).

i was wondering if i was doing anything wrong or how i could fix this so that i can try to write integration tests that uses qemu.

```
Arch Linux 5.18.0-arch1-1 (ttyS0)

archlinux login: root (automatic login)

Last login: Sun May 29 11:34:38 on tty1
[root@archlinux ~]# ‣ Warning: --netdev requires systemd-networkd to be running to initialize the host interface of the virtual link ('systemctl enable --now systemd-networkd')
‣ Error: Container/VM interface ve-test-infinit/vt-test-infinit not found
‣ Error: Container/VM interface ve-test-infinit/vt-test-infinit not found
‣ Error: Container/VM interface ve-test-infinit/vt-test-infinit not found
^C
```

**Comment by behrmann** [comment]
Not an expert on the integration tests, @DaanDeMeyer is much more qualified to answer that.

The specific warning message though should be pretty much on point though, you are using `--netdev` and that requires networkd to be running, so the virtual ethernet devices can be created.

**Comment by nlacombe42** [comment]
oh i didn't understand that `systemctl enable --now systemd-networkd` needs to be ran on the host system.
and i still can't figure out where `--netdev` is used, but i guess the integration tests must use it.

after running `systemctl enable --now systemd-networkd` on my host system, the integration test in `MkosiMachineTestCase` passes.
although now `test_after_shutdown()` fails.
