### ISSUE TITLE
Empty rpmdb after building older RPM distro on Fedora 36 host

### ISSUE THREAD

**Issue by coling** [systemd/mkosi#993]
I've tried latest git 92e021d on a Fedora 36 host and the rpm db changes are causing me grief building older rpm-based distros.

While the install is fine, if you have to add additional DNF repos to install further packages in the prepare script, the system doesn't know what is installed as the host's rpm has put the the sqlite rpmdb in /usr/lib/sysimage/rpm/ which the container's rpm doesn't parse or look for.

I've seen d3d0fbd4 and 0497f2bf before it which rebuild the rpm db inside the container but as they don't know what's actually installed, this results in an empty database which is fairly useless for further installs in the prepare script.

I've not found a specific bug for this, but wondering if I'm missing something here. If this can be fixed and released in Fedora 36, it would certainly help.

Current workaround is is to only use ```Packages=dnf``` in the mkosi.default then do ```dnf --releasever=8 install dnf ...``` in the container. This will reinstall dnf and deps inside the container and mean the rpmdb is properly populated for the container distro. This is pretty rubbish workaround as no caching is used for packages which means everything needs to be downloaded again etc which is far from ideal.

Are there any other better workarounds/fixes?

**Comment by behrmann** [comment]
Just to make sure I understand the problem properly: This is an upstream RPM problem and doesn't work with any mkosi version on Fedora 36 properly and the recent touch ups around rpm on our side are insufficient?

**Comment by coling** [comment]
> Just to make sure I understand the problem properly: This is an upstream RPM problem and doesn't work with any mkosi version on Fedora 36 properly and the recent touch ups around rpm on our side are insufficient?

Certainly as far as I can tell, this is a correct statement.

Installing a very basic container using mkosi from git on a Fedora 36 host and the following mkosi.default:
````
[Distribution]
Distribution=rocky_epel
Release=8
Architecture=x86_64

[Packages]
Packages=rpm,dnf

[Output]
Format=directory
Output=ostree
````

When entering that container via ```systemd-nspawn -D ostree``` running ```rpm -qa``` gives no results i.e. the rpm database is blank.

The rpm version on rocky/centos 8 does link with sqlite as a backend but not sure it will look in /usr/lib/sysimage/rpm/ for the files, so the ```rpm --rebuilddb``` that is issued in d3d0fbd and 0497f2b will only serve to initialise a blank rpmdb AFAICT.

This also means dnf can't seem to know what release it's running under either:

```
[root@ostree ~]# dnf install dnf
Unable to detect release version (use '--releasever' to specify release version)
Rocky Linux $releasever - AppStream             2.3 kB/s | 5.7 kB     00:02    
Errors during downloading metadata for repository 'appstream':
  - Status code: 404 for https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=AppStream-$releasever (IP: 199.232.54.132)
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: Status code: 404 for https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=AppStream-$releasever (IP: 199.232.54.132)
```

Using ```--releasever 8``` does fix this up and we can initialise things properly.

**Comment by coling** [comment]
I think I've found a work around (for rocky/centos etc. 8 at least):

```
[root@ostree ~]# rm -rf /var/lib/rpm/*
[root@ostree ~]# cp /usr/lib/sysimage/rpm/* /var/lib/rpm/
[root@ostree ~]# rpm --rebuilddb
warning: Found SQLITE rpmdb.sqlite database while attempting bdb backend: using sqlite backend.
[root@ostree ~]# rpm -qa
gpg-pubkey-2f86d6a1-5cf7cefb
...
```

So I will work on a patch for mkosi to try and detect this format and run those fix up commands prior to the rebuild db.

**Comment by coling** [comment]
Hmm, there is a fundamental chicken+egg issue here I think.

As I noted in #934 I don't think it's right to migrate the rpmdb in invoke_dnf() as this will break remove_packages() invocation (and manifest.record_packages()) which is run later using the host's rpm.

So we could clean this all up after the manifest is written, but then this means we cannot have a nice migrated rpm db when we are running our prepare script to install additional repos/modules etc.

Of course if we could do more to specify repos/modules as part of the initial install packages phase, this would negate the need to do any package management during prepare, but it's still probably necessary in some edge cases.

So I don't really know what's best here. Something is always going to break!

I think for now with my use case, I'll do the file move + --rebuilddb myself in the prepare script, knowing that I do not write a manifest nor define any packages to remove and I should be OK for my uses cases. Sadly this isn't really an upstream fix, nor do I know what such a fix would look like (other than my suggestion to build a minimal initial+native arch container to install the package manager and then run it from there rather than the host machine - but I'm sure that will come with it's own version compatibility headaches.

**Comment by coling** [comment]
For completeness, this is the snippet I put in my (final) mkosi.prepare:

```
if [ -f /usr/bin/rpm -a -d /usr/lib/sysimage/rpm ]; then
  echo "Migrating Fedora 36+ RPM DB to correct location"
  rm -f /var/lib/rpm/*
  cp /usr/lib/sysimage/rpm/rpmdb* /var/lib/rpm/
  rpm --rebuilddb --define "_db_backend bdb" || exit 1
  rm -rf /usr/lib/sysimage/rpm
fi
```

**Comment by coling** [comment]
> The "proper" solution here is likely to copy mock which first installs dnf/rpm in an intermediate bootstrap chroot and use those to install all the other packages (credits to @keszybz for the suggestion). So we'd use host dnf to install only dnf in a separate chroot, and then use `run_workspace_command()` to run dnf in the chroot and bind mount the final chroot directory, cache dirs and other stuff in there.

Yeah that's what I was thinking (what I tried to describe above). Probably a bit too much work for me to look at just now (certainly in the short term, I'm afraid)

**Comment by keszybz** [comment]
Please test the work-around proposed in #1004.
